### ISSUE TITLE
Generated code would not compile because of "Object" naming conflict

### ISSUE THREAD

**Issue by ivstas** [apollographql/apollo-kotlin#1173]
Code generation produces not-compiling code if server GraphQL schema has a type called `Object`.

This is a piece of generated code that fails to compile:
```java
public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], objects, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Object) item).marshaller());
              }
            }
          });
        }
      };
    }
```

The line that has the issue is `for (Object item : items) {`. Problem is that `Object` here is supposed to be `java.lang.Object`, but because I have a `public static class Object` generated within the same file (which takes precedence), I got a compile error.

I know it's kind of short-sighted solution to name your type `Object`, but it is the schema I've been provided to work with.

The simpliest solution is probably to explicitly use `java.lang.Object` in code-generation.

**Comment by sav007** [comment]
Well, right interesting. As a workaround try to use aliases in your query to resolve this issue.
