### ISSUE TITLE
Enqueue never finishes if dispatcher fails

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-kotlin#1373]
https://github.com/apollographql/apollo-android/blob/a1cd963f632e2a5d333b9d34e90107b9b5e6733f/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloCall.java#L125-L146

Given that the second half of the function is not caught, any exception at that time will mean that the callback never finishes.

As an example, I added an interceptor within the http client that will throw an exception. The result is correctly logged, but the respective unit test never finishes.

Perhaps try wrapping everything within a try catch, or introduce a way to provide a reasonable timeout?

**Comment by sav007** [comment]
Hm, not sure if this is a right approach to `throw an exception` in the interceptor rather than just return an error response. What I agree with is we should probably catch errors for user provided interceptors, as we can't rely on bad behaviour :)

**Comment by martinbonnin** [comment]
I'm going to close this issue as it's pretty old now and everything has changed since then. @AllanWang please let us know if you want us to reopen.
