### ISSUE TITLE
On the fly code generation

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-kotlin#1692]
I'm not sure if incremental compilation is the right term for this. Basically, whenever I make an edit to a query/mutation, I'd like for Apollo to automatically detect this change and recompile so I don't have to rebuild manually to access my new generated query. SQLDelight does this really well when modifying SQL queries.

Edit: I'm talking more about on the fly code generation while editing

**Comment by martinbonnin** [comment]
There are ~2 things~ 3 things:

1. Incremental compilation: it is the process of compiling a partial subset of files. If you have query1.sql and query2.sql and you only modify query1.sql, we could optimize and not recompile query2.sql.
2. Up-to-date checks: if you change query1.sql, the plugin should detect the input files have changed and recompile the generated sources. This happens at compile time, not when editing and should already work.
3. On the fly generation. This is generating files at editing time and I think this is what you are thinking about. SQL delight did it here: https://github.com/cashapp/sqldelight/commit/a55f80a0056b3eff3affa91c1bd0bb3db0dcaa9b. It is significant work but would be nice indeed.

**Comment by sav007** [comment]
>  I'd like for Apollo to automatically detect this change and recompile so I don't have to rebuild manually to access my new generated query

Current versions (@martinbonnin pls correct me if I'm wrong) of gradle plugins (including incubating) must behave as you described. Whenever you touched: schema.json or any graphql file, UP-TO-DATE must be false and models should be re-generated. 

If you don't see than this is a bug, could you please confirm?

**Comment by AOrobator** [comment]
I'm using the current version (1.2.0) and I don't see this behavior

**Comment by martinbonnin** [comment]
@AOrobator can you confirm you're talking about up-to-date checks (happens at compile time and ahould be working already, we have tests for that) or on-the-fly generation (happens at editing time, this is more work)

**Comment by AOrobator** [comment]
On the fly generation, happens at editing time

**Comment by tasomaniac** [comment]
I believe this is done thanks to the IntelliJ plugin. This also allows going back and forth between usages and `query` files using `Command + Click`. If I'm not mistaken, this concept is called `Light Class` in IntelliJ. It is a way to create fake classes/references on the fly to make the IDE happy.

**Comment by martinbonnin** [comment]
The newly released IntelliJ Plugin generates models on the fly. See the [blog post](https://apollographql.quip.com/0ZFDAELI6T7Z/Blog-Post-The-Apollo-Kotlin-IDE-plugin) for more details. Closing this issue.
