### ISSUE TITLE
Split Gradle Plugin in 2 artifacts, api & implementation

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#1697]
* `apollo-gradle-plugin-api` will contain the "public" gradle model part.
* `apollo-gradle-plugin` will contain the implementation. It will depend on `apollo-gradle-plugin-api`

This will ensure that consumers of the plugin will not depend on implementation details that can change.

**Comment by tasomaniac** [comment]
Is this still valid for the incubating plugin?

**Comment by martinbonnin** [comment]
Yes, the incubating plugin has different package names (`com.apollographql.gradle.api` and `com.apollographql.gradle.internal` respectively) but not different maven artifacts. 

The idea would be to ship 2 different maven artifacts so that developers building on-top of the plugin would not pull the internal dependencies by mistake. 

This ticket is very low priority as the impact isn't huge. Also I think java/gradle is moving towards more capable packages and metadata (https://blog.gradle.org/gradle-metadata-1.0) so we maybe that could be used as well.

**Comment by martinbonnin** [comment]
Closing as stale. Will reopen if needed
