### ISSUE TITLE
New codegen does not auto-box single enum parameters

### ISSUE THREAD

**Issue by gshcherb** [apollographql/apollo-kotlin#1731]
If parameter for a node is a list of enums old codegen allowed to specify a single enum in query. New codegen requires you to specify array explicitly.

was: 
```
   tags(include:DEFAULT) {
       ...
   }
```

now:
```
   tags(include:[DEFAULT]) {
       ...
   }
```
Error message for this case is a bit misleading: 

> Can't parse `Array` value, expected array

**Comment by cjbrooks12** [comment]
I'm getting an issue that I think is related, when the value is a single object. The following is a valid query when handled by Hasura, but cannot be parsed by Apollo.

```graphql
mutation CreateGame($teamId: Int, $gameName: String, $schema: jsonb, $config: jsonb) {
    insert_games(objects: [
        {
            team_id: $teamId,
            game_name: $gameName,
            config: $config,
            schema: $schema,
            game_revisions: {data: {}} # <-- this line is causing the Apollo codegen error
        }
    ]) {
        returning {
            game_id
            game_name
            game_revisions {
                revision_id
            }
        }
    }
}
```

That query is for a [Hasura nested insert](https://docs.hasura.io/1.0/graphql/manual/mutations/multiple-mutations.html#insert-an-object-and-a-nested-object-in-the-same-mutation), and cannot simply be wrapped in an array. If the `game_revisions` object is wrapped in an array, Apollo codegen will accept it, but then Hasura will not.

**Comment by devnet-io** [comment]
Any update on this?

**Comment by martinbonnin** [comment]
@devnet-io not really sorry, this fell out of my radar. Can you try with `2.5.3`? If that still fail provide a sample query and the corresponding exception?

**Comment by devnet-io** [comment]
@martinbonnin thanks, it turns out this was actually user error. I was able to adjust my mutation to fix the issue.

For reference, here's an updated version of the Hasura mutation posted above that should work. Its possible the op does not have their relationships setup correctly if Hasura wont accept this.

```graphql
mutation CreateGame($teamId: Int, $gameName: String, $schema: jsonb, $config: jsonb) {
    insert_games(objects: [
        {
            team_id: $teamId,
            game_name: $gameName,
            config: $config,
            schema: $schema,
            game_revisions: {data: [{foo: "bar"}]} # <-- Ensure that data is an array, not an object
        }
    ]) {
        returning {
            game_id
            game_name
            game_revisions {
                revision_id
            }
        }
    }
}
```

**Comment by martinbonnin** [comment]
Thanks for the update! @cjbrooks12, @gshcherb, do you still have the issue? Anything I can do here?

**Comment by martinbonnin** [comment]
Hi 👋 This one should be fixed with https://github.com/apollographql/apollo-android/pull/3337. Can you try version [3.0.0-rc01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) and let us know how that worked?
