### ISSUE TITLE
subscription events should be picked up by client event listener

### ISSUE THREAD

**Issue by simonmarshall** [apollographql/apollo-kotlin#2009]
**Is your feature request related to a problem? Please describe.**
I tried to look into #1864, since I also have that issue.  I figured putting an EventListener on the OkHttpClient would help.  However, it doesn't get called for subscription events.  It does get called for, eg, mutation events.

**Describe the solution you'd like**
If I build an OkHttpClient like this:
```
  final OkHttpClient okHttpClient = new OkHttpClient.Builder()
    .eventListener(new TestEventListener())
    .build();
  client = ApolloClient.builder()
    .serverUrl(API_URL)
    .okHttpClient(okHttpClient)
    .subscriptionTransportFactory(new WebSocketSubscriptionTransport.Factory(SUB_URL, okHttpClient))
    .build();
```
then I would like the `TestEventListener` to be invoked for subscription events, not just, eg, mutation events.

**Comment by martinbonnin** [comment]
Hi 👋 Apollo Android 3 significantly reworked the WebSocket code, can you try the [release candidate](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) and let us know if you still have the issue?

**Comment by martinbonnin** [comment]
I'm going to close this one as I'm not sure how to move forward. @simonmarshall if you can't update to 3.x, let us know the reason and we'll work on those!
