### ISSUE TITLE
Bug: Updating cache in apollo store no longer updates query watcher

### ISSUE THREAD

**Issue by hedvigoscar** [apollographql/apollo-kotlin#2145]
**Summary**
Since version 1.4.0, writing data to the cache, query watchers no longer appear to fire.

**Description**
Example code (AGPL 3.0):

```kotlin
class PayinStatusRepository(
    private val apolloClientWrapper: ApolloClientWrapper
) {
    private val payinStatusQuery = PayinStatusQuery()

    fun payinStatus() = apolloClientWrapper
        .apolloClient
        .query(payinStatusQuery)
        .watcher()
        .toFlow()

    suspend fun refreshPayinStatus() {
        val response = apolloClientWrapper
            .apolloClient
            .query(payinStatusQuery)
            .responseFetcher(ApolloResponseFetchers.NETWORK_ONLY)
            .toDeferred()
            .await()

        response.data()?.let { data ->
            val cachedData = apolloClientWrapper
                .apolloClient
                .apolloStore()
                .read(payinStatusQuery)
                .execute()

            val newData = cachedData.copy(payinMethodStatus = data.payinMethodStatus)
            apolloClientWrapper
                .apolloClient
                .apolloStore()
                .writeAndPublish(payinStatusQuery, newData)
                .execute()
        }
    }
}
```

where `apolloClientWrapper` holds an instance of `ApolloClient`.

In version 1.3.3 (last known working version), when performing `.writeAndPublish(payinStatusQuery, newData).execute()`, the watcher fires and sends the new data out on the `Flow`. In `1.4.0` and up, this no longer occurs.

**Version**
Last known working version is 1.3.3.
Issue exists in 1.4.0-1.4.4.

**Comment by martinbonnin** [comment]
Hi 👋 Sorry for the huuuuuge delay...Are you still having this issue? If yes, any chance you can try on a [recent version](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) and let us know how that went?

**Comment by hedvigoscar** [comment]
I'm not entirely sure about reproduction for this one anymore, but given that we are running 2.5.9 currently, I'm going to assume that it is actually working now. 🙂
