### ISSUE TITLE
ApolloResponseFetchers.NETWORK_ONLY does not disable storing response to cache

### ISSUE THREAD

**Issue by hameno** [apollographql/apollo-kotlin#2421]
**Summary**
We have a very big query that we do not want to cache. ApolloResponseFetchers.NETWORK_ONLY does still store the response into cache

**Version**
2.2.2

**Description**
We have a very big query that we do not want to cache. It is so big, that they cache key does not fit into a cursor window:

```
W/CursorWindow: Window is full: requested allocation 2214191 bytes, free space 2096227 bytes, window size 2097152 bytes
E/SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT key, record FROM records WHERE key=?1
```

How can we disable the store into cache for certain queries?

**Comment by hameno** [comment]
Maybe it's only a question? I wasn't sure about the type of this issue.

**Comment by hameno** [comment]
On iOS there is a CachePolicy.fetchIgnoringCacheCompletely. This seems to be what I need.

**Comment by martinbonnin** [comment]
You can use [`ApolloCacheHeaders.DO_NOT_STORE`](https://github.com/apollographql/apollo-android/blob/ba9d69fcaa98632c1424969f6e3a8438cf903e2c/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo/cache/ApolloCacheHeaders.kt#L12) to bypass the cache write.

**Comment by hameno** [comment]
Thanks, I assume I set the value to "true"?

**Comment by martinbonnin** [comment]
Looking [at the code](https://github.com/apollographql/apollo-android/blob/7261de18d3f11879f74ae268dca935c886913191/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/NormalizedCache.kt#L79) looks like any value (even `null` 🤔 ) will work. That should definitely be improved/documented.

**Comment by hameno** [comment]
If I see it correctly, even with this Header it calculates the cache keys which seems to be unnecessary work.

**Comment by martinbonnin** [comment]
Yep, having a more "global" way to disable the cache would be nice.

**Comment by hameno** [comment]
Yes, for now I'm gonna work around this issue by having a second ApolloClient without any caching configured and switching between those when needed.

**Comment by martinbonnin** [comment]
Closing this issue as 3.x now has `MutableExecutionOptions.doNotStore(true)`. It can be set both at the `ApolloClient` level or individual query level:

```kotlin
// Default to not storing data in the cache
ApolloClient.Builder()
  .serverUrl("https://...")
  .doNotStore(true)
  .build()

// Override the default for a single query
apolloClient.query(myQuery).doNotStore(true).execute()
```
