### ISSUE TITLE
[Multiplatform] Add NSURLSession and Multipath TCP support

### ISSUE THREAD

**Issue by likuai2010** [apollographql/apollo-kotlin#2442]
**Question.**
apollo Multiplatform When to support NSURLSession。
I have one that needs to use MutiPath TCP

**Comment by martinbonnin** [comment]
This is not supported at the moment but you can implement your own `NetworkTransport` based on `NSURLSession`, like [`ApolloHttpNetworkTransport`](https://github.com/apollographql/apollo-android/blob/1465640c4bd8920a3755d0df62b09e6ae568c262/apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt#L57) does for NSURLConnection

**Comment by BoD** [comment]
Closing for now as this didn't get more traction after a few years. Don't hesitate to re-open if you need this.
