### ISSUE TITLE
HMPP support (hierarchical projects structure) 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#2630]
Kotlin `1.4.0` introduced [HMPP](https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#try-the-hierarchical-project-structure). Investigate how to enable it.

**Comment by martinbonnin** [comment]
Fixed with https://github.com/apollographql/apollo-kotlin/pull/4033

**Comment by BoD** [comment]
Available in v3.3.0.
