### ISSUE TITLE
Java codegen doesn't support inline fragments inside named fragments 

### ISSUE THREAD

**Issue by dominolog** [apollographql/apollo-kotlin#2748]
**Question.**
I have problems with accessing my fragment's data after migration to Apollo 2.X Android. Previously the fragments were resolving correctly but now I cannot access specific types (example type is NotificationData and child classes).

```


fragment NotificationDetails on IRecord {

    id
    created_at

    ...on INotification {
        message
        category
        is_read
        is_resolved

    }

    ...on NewMatchesInJoinedAlbumNotification {
        album_membership {
            id
                root_album_membership_group(root_groups_only: true) {
                id
            }
            entitled_matched_photos(slice: { offset: 0, limit: 1}) {
                records {
                    ...PhotoData
                }
            }
        }
        identities {
            id
            current_face {
                photo {
                    ...PhotoData
                }
            }
        }
    }

    ... on UsersJoinedAlbumNotification {
        album_membership {
            ...AlbumMembershipDataLite
        }
        account {
            current_selfie_face {
                photo {
                    ...PhotoData
                }
            }
        }
    }

    ... on InboundAlbumShareNotification {
        album_share {
            ...AlbumShareDetails
            album_membership {
                ...AlbumMembershipDataLite
            }
        }
    }

    ... on AlbumShareAcceptedNotification {
        album_share {
            ...AlbumShareDetails
            album_membership {
                ...AlbumMembershipDataLite
            }

        }
    }
    ... on AlbumFolderShareAcceptedNotification {
        album_folder_share {
            ...AlbumFolderShareDetails
        }

    }
    ... on InboundAlbumFolderShareNotification {
        album_folder_share {
            ...AlbumFolderShareDetails
        }

    }

    ... on AlbumFolderShare {
        ...AlbumFolderShareDetails

    }

    ... on AlbumShare {
        ...AlbumShareDetails

    }

    ... on NewPhotosPublishedNotification {
        album {
            ...ProAlbumDataLite
        }
    }
    ... on NewPhotosToReviewNotification {
        album {
            ...ProAlbumDataLite
        }
    }
}


fragment AlbumShareDetails on AlbumShare {
    id
    status
    receiver_account {
        ...UserDataLite
    }
    sender_account {
        ...UserDataLite
    }
    album {
        name
        cover_photo {
            ...PhotoData
        }
        root_album_folder {

            id
        }
    }
}
fragment AlbumFolderShareDetails on AlbumFolderShare {
    id
    status1 : status
    receiver_account {
        ...UserDataLite
    }
    sender_account {
        ...UserDataLite
    }
    album_folder {
        id
        name
        cover_photos(slice: { limit: 1, offset: 0}) {
            records {
                ...PhotoData
            }
        }
    }
}



```

**Comment by martinbonnin** [comment]
Hi @dominolog 👋 ! Thanks for sending this! Can you give some more details? 

* What version are you using?
* Are you using java or kotlin models?
* Can you share the exception stacktrace? 
* Or is the problem that the fragment is not being generated?
* If you could give an example of the code that creates the problem, that'll help a ton. 

Thanks!

**Comment by dominolog** [comment]
1. I am using Apollo plugin version **2.1.0**
2. The model is generated into Java classes
3. There is no stack trace, the generated code just does not have the specific child classes accessible.
4. Yes - the problem is that fragments are not properly generated.
5. The attached graphql fragment in the issue description demonstrates the problem.

**Comment by martinbonnin** [comment]
Thanks for the quick follow up! So `AlbumFolderShareDetails` would be generated but not `NotificationDetails` for an example? 

Also,  is there a particular reason you use `2.1` and not `2.4.2` ?

**Comment by martinbonnin** [comment]
Hi @dominolog , have you been able to resolve the above?

**Comment by dominolog** [comment]
No. Still having issues. I tested with 2.4.2 but still same problem. What can I do more to help you investigate the issue?

**Comment by martinbonnin** [comment]
Can you share your schema.json and graphql files ? Either here or at martin at apollographql.com ?

**Comment by dominolog** [comment]
For instance below fragment is always resolved into `AsINotification`

`fragment NotificationDetails on IRecord {

    ...on IRecord {
        id
        created_at
    }
    ...on INotification {
        message
        category
        is_read
        is_resolved

    }

    ...on NewMatchesInJoinedAlbumNotification {
        album_membership {
            id
                root_album_membership_group(root_groups_only: true) {
                id
            }
            entitled_matched_photos(slice: { offset: 0, limit: 1}) {
                records {
                    ...PhotoData
                }
            }
        }
        identities {
            id
            current_face {
                photo {
                    ...PhotoData
                }
            }
        }
    }

    ... on UsersJoinedAlbumNotification {
        album_membership {
            ...AlbumMembershipDataLite
        }
        account {
            current_selfie_face {
                photo {
                    ...PhotoData
                }
            }
        }
    }

    ... on InboundAlbumShareNotification {
        album_share {
            ...AlbumShareDetails
            album_membership {
                ...AlbumMembershipDataLite
            }
        }
    }

    ... on AlbumShareAcceptedNotification {
        album_share {
            ...AlbumShareDetails
            album_membership {
                ...AlbumMembershipDataLite
            }

        }
    }
    ... on AlbumFolderShareAcceptedNotification {
        album_folder_share {
            ...AlbumFolderShareDetails
        }

    }
    ... on InboundAlbumFolderShareNotification {
        album_folder_share {
            ...AlbumFolderShareDetails
        }

    }

    ... on AlbumFolderShare {
        ...AlbumFolderShareDetails

    }

    ... on AlbumShare {
        ...AlbumShareDetails

    }

    ... on NewPhotosPublishedNotification {
        album {
            ...ProAlbumDataLite
        }
    }
    ... on NewPhotosToReviewNotification {
        album {
            ...ProAlbumDataLite
        }
    }
}`

**Comment by martinbonnin** [comment]
Hi @dominolog ! Did you manage to solve your problem? I'm not sure how to move forward. What specific classes would you expect?

**Comment by martinbonnin** [comment]
@dominolog and I investigated offline and it boils down to Java codegen and these schema/queries:

schema:
```graphql
type Query {
  animal: Animal
}

interface Animal {
    species: String!
}

type Cat implements Animal {
    name: String!
    mustache: String!
}
```

query:
```graphql
query GetAnimal {
  animal {
    ...animalDetails
  }
}
fragment animalDetails on Animal {
  ... on Animal {
    species
  }
  ... on Cat {
    name
  }
}
```

**Comment by martinbonnin** [comment]
This is working as of `3.8.4`
