### ISSUE TITLE
Unable to handle incorrect deprecated field marking in version 2.4.5

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-kotlin#2778]
**Summary**
We have been using Android Apollo version 1.2.2 for a while , bumping version to 2.4.5 produces issue where deprecated field is not handled correectly.

**Version**
2.4.5

**Description**

We have fragment like this which gets parsed fine in version 1.2.2

```
"""
Attachable entities in a widget."
@deprecated Widget: To get widget details use query Widget#newWidgetDetails instead.
"""
union WidgetAttachment = File | ImageFile | VideoFile | WebImage | WebLink | WebVideo | Message

```

But if I change fragment to be defined as follows everything works 

```
"""
Attachable entities in a some widget details. @deprecated(reason: 'Widget: To get widget details use query Widget#newWidgetDetails instead').
"""
union WidgetAttachment = File | ImageFile | VideoFile | WebImage | WebLink | WebVideo | Message
```

Seems like with version 2.4.5 we need some specific format to parse deprecated comment?

The error I get while compiling code is

***warning: [dep-ann] deprecated item is not annotated with @Deprecated***

Note, I have tried to use following directives in apollo sections of my gradle without any effect.

```
apollo {
    warnOnDeprecatedUsages.set(false) // true by default
    failOnWarnings.set(false) // true by default
}
```

**Comment by snijsure** [comment]
I am not 100% sure if this is a bug, if someone can provide pointer to formal GQL schema grammer I would check.

**Comment by martinbonnin** [comment]
Hi! Thanks for sending this! You can find the GraphQL grammar there: https://spec.graphql.org/draft/#UnionTypeDefinition

In this case, it looks like our SDL parser doesn't like the quote embedded in the first description. 

In all cases, I'm surprised this has ever worked. Directives and deprecated annotations should be put outside the description:

Something like:

```
"""
Attachable entities in a widget.
"""
union WidgetAttachment @deprecated(reason = "Widget: To get widget details use query Widget#newWidgetDetails instead.") = File | ImageFile | VideoFile | WebImage | WebLink | WebVideo | Message
```

Also double checking, 1.2.2 was using the npm codegen, I'm not 100% sure how it was finding the schema but on 2.4.5, you should name your SDL schema `schema.sdl` for it to be parsed as SDL

**Comment by martinbonnin** [comment]
This should work fine in latest versions, closing.
