### ISSUE TITLE
Cache and connection restore for Subscription

### ISSUE THREAD

**Issue by akelix** [apollographql/apollo-kotlin#2823]
**Summary**
Client does no recieve data from subscriptions flow.

**Version**
2.4.1

**Description**
Client has cached data.
If application starts without internet connection, data from cache will not be used.
After connection restore, subscription keeps inactive.

There are few problems:
First problem lives [here](https://github.com/apollographql/apollo-android/blob/8a160f57845cb9c5d009660017a11820be3f7a5c/apollo-coroutines-support/src/main/kotlin/com/apollographql/apollo/coroutines/CoroutinesExtensions.kt#L168)

Cached data emitted [here](https://github.com/apollographql/apollo-android/blob/8a160f57845cb9c5d009660017a11820be3f7a5c/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloSubscriptionCall.java#L69)

As a result, channel closed before cached data is emitted.
My temporary solution [here](https://pastebin.com/m6qcKRkN). Rewrite `toFlow` extension.

Second problem with connection restore.
Client have to handle errors inside [flow](https://www.apollographql.com/docs/android/tutorial/11-subscriptions/#handle-errors)
Because if you ignore exception, connection will not be restored.

**Comment by danielehrhardt** [comment]
Same Issue here

**Comment by martinbonnin** [comment]
Hi y'all 👋 Version [4.0.0-beta.6](https://github.com/apollographql/apollo-kotlin/releases/tag/v4.0.0-beta.6) has experimental websockets that make it a lot easier to handle these situations. Please try it out and leave a comment if the issue is still there (which shouldn't be the case)
