### ISSUE TITLE
Enable sharing of schema.json in published android maven packages

### ISSUE THREAD

**Issue by chrisr-ifit** [apollographql/apollo-kotlin#3042]
**Is your feature request related to a problem? Please describe.**
Ideally we would like to be able to share our schema.json and other apollo metadata across our maven published android libraries.

**Describe the solution you'd like**
Currently using the apolloMetadata configuration such as:
```
implementation "com.example.mypublishedlibrary:0.0.1"
apolloMetadata "com.example.mypublishedlibrary:0.0.1"
```
With a local or remote maven published android library results in the following error:
```
Execution failed for task ':app:generateDebugServiceApolloSources'.
> Failed to calculate the value of task ':app:generateDebugServiceApolloSources' property 'generateMetadata'.
   > Could not resolve all files for configuration ':app:apolloDebugServiceConsumer'.
      > Could not resolve com.example.mypublishedlibrary:0.0.1.
        Required by:
            project :app
         > No matching variant of com.example.mypublishedlibrary was found. The consumer was configured to find a usage of 'apollo-metadata' of a component, as well as attribute 'com.apollographql.variant' with value 'debug', attribute 'com.apollographql.service' with value 'service' but:
             - Variant 'compile' capability com.example.mypublishedlibrary:
                 - Incompatible because this component declares an API of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
             - Variant 'enforced-platform-compile' capability com.example.mypublishedlibrary-derived-enforced-platform:0.0.1:
                 - Incompatible because this component declares an API of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
             - Variant 'enforced-platform-runtime' capability com.example.mypublishedlibrary-derived-enforced-platform:0.0.1:
                 - Incompatible because this component declares a runtime of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
             - Variant 'platform-compile' capability com.example.mypublishedlibrary-derived-platform:0.0.1:
                 - Incompatible because this component declares an API of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
             - Variant 'platform-runtime' capability com.example.mypublishedlibrary-derived-platform:0.0.1:
                 - Incompatible because this component declares a runtime of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
             - Variant 'runtime' capability com.example.mypublishedlibrary:0.0.1:
                 - Incompatible because this component declares a runtime of a component and the consumer needed a usage of 'apollo-metadata' of a component
                 - Other compatible attributes:
                     - Doesn't say anything about com.apollographql.service (required 'service')
                     - Doesn't say anything about com.apollographql.variant (required 'debug')
```
Using the module directly such as:
```
implementation project(":mylibrary")
apolloMetadata project(":mylibrary")
```
Works as intended with the exact same code.

Is there a way get apolloMetadata working with a maven published android library? Is there a recommended maven publishing configuration that allows for this use case?

We do have an alternative solution using gradle tasks to copy and delete the schema.json from the published dependency during build when generating apollo sources. Ideally we would like to use apolloMetadata if possible! Thank you!

**Comment by martinbonnin** [comment]
Hi 👋  

Indeed, Apollo metadata publication isn't handled at the moment. Doing so will open a whole new class of interesting questions such as binary compatibility, matching schemas, Gradle variant selection, etc... 

> We do have an alternative solution using gradle tasks to copy and delete the schema.json from the published dependency during build when generating apollo sources.

Interesting, does that mean you actually publish a `apollo-metadata.jar` where you get the schema from ? Is that repository public by any chance ? Maybe adding support for publication could be added without changing too many things if we enforce the same plugin versions everywhere...

**Comment by chrisr-ifit** [comment]
Hello 👋 

> Interesting, does that mean you actually publish a apollo-metadata.jar

We're not currently doing this but instead are including the `schema.json` in the published artifact by adding the graphql directory to the resources source set.
```
sourceSets {
    main.resources.srcDirs += 'src/main/graphql/com/example/mypublishedlibrary'
}
```

Then in the consumer build gradle we pull in the schema during any ApolloSources task:
```
task copySchema(type: Copy) {
    from { getSchemaFile() }
    into project.file('src/main/graphql')
}
task deleteSchema(type: Delete) {
    delete project.file('src/main/graphql/schema.json')
}
this.afterEvaluate { Project project ->
    def apolloSourcesTaskNames = project.tasks.getNames().findAll { it.contains("ApolloSources") }
    apolloSourcesTaskNames.each { String taskName ->
        def generateApolloSourcesTask = project.tasks.getByName(taskName)
        generateApolloSourcesTask.dependsOn(copySchema)
        generateApolloSourcesTask.finalizedBy(deleteSchema)
    }
}
```

> Is that repository public by any chance

It is not public unfortunately, but the steps described above are more or less the approach.

**Comment by shakola** [comment]
@martinbonnin 
We are facing the same issue and I wonder if there Is any update or alternative solution?

**Comment by martinbonnin** [comment]
If you're familiar with Gradle APIs, the solution to this would be to add the `metadata.json` to the publication. This might or might not be an easy thing to do, not sure at this point.

If that's not easy, a workaround would be to distribute the schema "out of band", like @chrisr-ifit is doing and generate classes in each module with a separate package name. It's sub optimal because it will generate duplicate classes but that might be good enough until proper maven publication is handled

**Comment by martinbonnin** [comment]
First drop there: https://github.com/apollographql/apollo-kotlin/pull/3904
Let me know what you think. If everything goes well, it should hit the SNAPSHOTS later this week.
