### ISSUE TITLE
Putting a schema in a test sourceSet fails with `only one schema file is supported`

### ISSUE THREAD

**Issue by rezammalik** [apollographql/apollo-kotlin#3058]
**Summary**
When my graphql stucture with multiple schemas is in `src/main` it works fine but when I move it into `src/test` it complains. It works in `src/test` when I just have one schema.

**Version**
2.5.4 (Also tried 2.5.6)
Gradle 6.x as well as 7.0

**Description**
Assuming the folder structure is this: 

```
src/main/graphql/gatewayPublic/schema.json
src/main/graphql/gatewayPublic/queries/GetRepositories.graphql
src/main/graphql/gatewayPublic/mutations/GenerateStuff.graphql
src/main/graphql/gatewayInternal/schema.json
src/main/graphql/gatewayInternal/queries/GetPopcorn.graphql 
src/main/graphql/gatewayInternal/mutations/GenerateStuff2.graphql 
src/main/graphql/qafactory/schema.json
src/main/graphql/qafactory/queries/GetIcecream.graphql 
```

it works perfectly fine while this is in `src/main` and when I have this in my `build.gradle.kts` file:
```
apollo {
    generateKotlinModels.set(true)
    service("gatewayPublic") {
        sourceFolder.set("gatewayPublic")
        rootPackageName.set("graphql.acme.gatewayPublic")
    }

    service("gatewayInternal") {
        sourceFolder.set("gatewayInternal")
        rootPackageName.set("graphql.acme.gatewayInternal")
    }

    service("qafactory") {
        sourceFolder.set("qafactory")
        rootPackageName.set("graphql.acme.qafactory")
    }
}
```
but when I move everything `graphql` into `src/test` I get an error

```
Could not determine the dependencies of task ':generateTestQafactoryApolloSources'.
> Failed to query the value of task ':generateTestQafactoryApolloSources' property 'schemaFile'.
   > Failed to query the value of property 'schemaFile'.
      > ApolloGraphQL: By default only one schema.[json | sdl] file is supported.
        Please use multiple services instead:
        apollo {

          service("service1") {
            sourceFolder.set("com/service1)"
            rootPackageName.set("com.service1)
          }

          service("service2") {
            sourceFolder.set("com/service2)"
            rootPackageName.set("com.service2)
          }
        }See https://www.apollographql.com/docs/android/essentials/plugin-configuration/#apolloextension-services-and-compilationunit for more details.
```
I've tried adding this to the above but that didn't help, I asssume test is already included so I shouldn't have to do this

```
    onCompilationUnit {
        graphqlSourceDirectorySet.srcDirs("${rootProject.projectDir}/src/test/graphql/*")
     }
```

then I tried adding the `schemaFile` explicity to the different services, like this

```
apollo {
    generateKotlinModels.set(true)
    service("gatewayPublic") {
        sourceFolder.set("gatewayPublic")
        rootPackageName.set("graphql.acme.gatewayPublic")
        schemaFile.set(file("${rootProject.projectDir}/src/test/graphql/gatewayPublic/schema.json"))
    }

    service("gatewayInternal") {
        sourceFolder.set("gatewayInternal")
        rootPackageName.set("graphql.acme.gatewayInternal")
        schemaFile.set(file("${rootProject.projectDir}/src/test/graphql/gatewayInternal/schema.json"))
    }

    service("qafactory") {
        sourceFolder.set("qafactory")
        rootPackageName.set("graphql.acme.qafactory")
        schemaFile.set(file("${rootProject.projectDir}/src/test/graphql/qafactory/schema.json"))
    }
}
```

This makes it go further but in the validation it is most likely only getting the first schema file and then tries to match all different service queries to that specific schema and fails 

```
  Failed to parse GraphQL file ... (1:29)
  Unknown variable type `GetIcecream!`
  ----------------------------------------------------

  [1]:query GetIcecream($input:GetIcecreamInput!) {
  [2]:  getIcecream(input: $input)
  ----------------------------------------------------
```
Apologies for the long thread. I tried looking into the logs and the wiki etc but wasn't getting anywhere. Is there something I am missing as to why `/src/test `does not honor multiple schemas while putting this in `/src/main `does?

**Comment by martinbonnin** [comment]
Hi Reza 👋 ! I don't have all the details in mind right now but we indeed have custom branches for test source sets:

https://github.com/apollographql/apollo-android/blob/8d7c969e5ce9bcec2977cd9a8ddcad6b460eaac3/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/DefaultCompilationUnit.kt#L35

From the comment there, it looks like this was done because the plugin will always try to add to the main source set by default and adding to test would duplicate a bunch of classes (and I _think_ trigger and error with d8 on Android even though non-Android project could certainly live with the duplicated classes).

This automatic way of doing things works well for the default cases but make custom configurations a bit challenging to handle. 

That might be a shot in the dark but can you try removing the `sourceFolder` and calling `graphqlSourceDirectorySet.srcDir` manually for your different folders? 

```kotlin
    onCompilationUnit {
        // here you can switch on the name of the compilationUnit
        when(it.name) { 
            // Not 100% sure what the actual name would be but that'd be the idea
            "TestGatewayPublic" -> graphqlSourceDirectorySet.srcDirs("${rootProject.projectDir}/src/test/graphql/gatewayPublic")
            "TestGatewayInternal" -> graphqlSourceDirectorySet.srcDirs("${rootProject.projectDir}/src/test/graphql/gatewayInternal")
            ...
        }      
     }
```

If that doesn't work, I'll look on Monday to see if there's a workaround you can apply.

If you want to read more about this, you can read https://github.com/apollographql/apollo-android/pull/2668 that details some upcoming changes to the Gradle configuration that should make these cases easier to handle.

**Comment by rezammalik** [comment]
I tried this but name `came` back as undefined. Is there a specific method I can grab the name of the `onCompilationUnit` from?

**Comment by martinbonnin** [comment]
Hi @rezammalik !

> Is there a specific method I can grab the name of the onCompilationUnit from?

My bad, Gradle will pass the `CompilationUnit` as a receiver to `onCompilationUnit` so just referencing `this.name` will give you the `CompilationUnit` name.

That being said, I spent some time with this this morning and by default, the plugin will always add the compilationUnits results to the main Android sourceSet, which doesn't seem to be what you're trying to achieve.

I'm guessing you want the test graphql files to be only in the test classpath, right? If that's the case, the way to do this would be to disable the plugin by default with `apply(false)` (but leave it in the buildscript classpath) and configuring instances of `ApolloGenerateSourcesTask` manually). I can make a small snippet to show how that's done if that helps?

**Comment by rezammalik** [comment]
Hi Martin,

Basically yea, I am using the client for testing gql endpoints and my concern was not including everything in src/main which lead me here. Appreciate the help with the snippet.

**Comment by martinbonnin** [comment]
Makes sense. The general idea would be to replicate a lot of what the plugin does but from your own Gradle scripts. 

Assuming `build.gradle.kts`:

```kotlin
plugins {
    ...
    id("com.apollographql.apollo").version("2.5.6").apply(false)
}
```

And then:

```kotlin
val generateSourcesTask = tasks.register("generateService1ApolloSources", com.apollographql.apollo.gradle.internal.ApolloGenerateSourcesTask::class.java) {
    generateKotlinModels.set(true)
    outputDir.set(layout.buildDirectory.dir("generated/source/apollo/service1"))
    schemaFile.set(file("src/test/graphql/service1/schema.sdl"))
    val sourceDirectorySet = objects.sourceDirectorySet("service1", "service1")
    sourceDirectorySet.include("**/*.graphql")
    sourceDirectorySet.srcDir("src/test/graphql/service1")
    graphqlFiles.from(sourceDirectorySet)
    projectName.set(name)
    generateMetadata.set(false)
    rootPackageName.set("com.service1")
    projectRootDir.set(rootDir)
    rootFolders.set(sourceDirectorySet.sourceDirectories.map { it.absolutePath })
    metadataOutputFile.set(layout.buildDirectory.file("metadata/apollo/metadata.json"))
    operationOutputGenerator = com.apollographql.apollo.compiler.OperationOutputGenerator.DefaultOperationOuputGenerator(com.apollographql.apollo.compiler.OperationIdGenerator.Sha256())
}

android {
    unitTestVariants.all {
        println("configuring variant: $name")
        addJavaSourceFoldersToModel(generateSourcesTask.get().outputDir.asFile.get())
        registerJavaGeneratingTask(generateSourcesTask.get(), generateSourcesTask.get().outputDir.asFile.get())
    }
}
```

That's more verbose and some parameters are a bit weird because they were initially meant to be hidden like `operationOutputGenerator` but using the default as above should work. Also this is unfortunately using internal APIs but 2.x is pretty stable and I don't expect this to change any time soon until 3.x (which would change a bunch of things anyway and especially make this use case easier)

**Comment by rezammalik** [comment]
Interesting. Thanks for the snippet. I really am looking forward to 3.x to make this a little easier and convenient in the future.

**Comment by martinbonnin** [comment]
`3.0.0` is now released, closing this issue.
