### ISSUE TITLE
Add fine grade control on auto persisted query 

### ISSUE THREAD

**Issue by aoudiamoncef** [apollographql/apollo-kotlin#3118]
Hi @martinbonnin,

Actually, I'm actively working on APQ support on some GraphQL OSS projects and I found that it could be interesting to individually enable/disable APQ. 

Add a Boolean parameter autoPersistedQuery to query builder and handle it in Okhttp interceptor. 

If it's seems feasible, I'm interested to implement with some helping.

**Comment by martinbonnin** [comment]
Hi @aoudiamoncef ! Can you elaborate a bit more on what the use case is? APQs usually work well when globally enabled and save some network bandwidth. Would you like to disable it for some requests in order to "warm" the server cache because you know through another way that it will be empty? Or something else?

**Comment by aoudiamoncef** [comment]
Imagine we have a GraphQL schema with 10 queries, we authorized only 3 queries to be persisted on server side. We should be able to disable APQ on the remaining 7 queries to avoid the first call with empty "query" parameter

**Comment by martinbonnin** [comment]
Got you! Selectively enabling them server side 👍 . To make sure I understand, what's the benefit of doing this? I'm guessing keeping the server cache small and reducing latency for small queries? So you'd only enable APQs for large queries?

> Add a Boolean parameter autoPersistedQuery to query builder 

Sounds good to me 👍 . That parameter should also exist for mutations so it's going to be some boilerplate, passing it through all `Builders` but I don't really see a way around that. 

> and handle it in Okhttp interceptor.

I'd do that in the `RealApolloCall`:

https://github.com/apollographql/apollo-android/blob/6bfbd791890811aadc5ba54fa5b4557f604b2f8d/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloCall.java#L414

`Okhttp` is most likely too late as everything as been serialized to bytes.

**Comment by aoudiamoncef** [comment]
You got it, for example, we have a policy to ignore small queries.

https://github.com/apollographql/apollo-android/blob/6bfbd791890811aadc5ba54fa5b4557f604b2f8d/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/Operation.kt#L101

We could achieve expected goal by adding `autoPersistQueries` to query builder which will force including query payload instead of sending only empty parameter.

**Comment by martinbonnin** [comment]
Makes sense 👍

**Comment by martinbonnin** [comment]
Fixed in 3.0.0 with `enableAutoPersistedQueries()`. See https://www.apollographql.com/docs/kotlin/advanced/persisted-queries/#disable-persisted-queries-for-some-queries
