### ISSUE TITLE
Make a high level abstraction for http client 

### ISSUE THREAD

**Issue by aoudiamoncef** [apollographql/apollo-kotlin#3119]
Hi @martinbonnin

I know that Apollo Android is closely coupled to Okhttp client but it's could be interesting to give the user the possibility to plug it's own http client. 

Use high level abstractions on Apollo Android in order to supply different implementations

I'm waiting for feedback, I'm conscient that's not easy.

Thanks

**Comment by martinbonnin** [comment]
Hi @aoudiamoncef ! 

That's something that will be easier to do in `3.x` using the `HttpEngine` API. It's available there:

https://github.com/apollographql/apollo-android/blob/57d1febcf8dc05ec9f416c96493f3935fe573a91/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/http/HttpEngine.kt#L11

For now it's relatively simple, a `HttpRequest` with headers and body and a `HttpResponse` with statusCode, headers and body. But I think that'd work for the vast majority of use cases. Let me know what you think

**Comment by martinbonnin** [comment]
Fixed in 3.0.0 through the `HttpEngine` interface. See https://www.apollographql.com/docs/kotlin/advanced/http-engine/
