### ISSUE TITLE
Allows nullable variables in non-null locations

### ISSUE THREAD

**Issue by darylsze** [apollographql/apollo-kotlin#3227]
Currently I am migrating AppSync sdk (although it embedded an internal Apollo sdk, it is way too outdated) to Apollo sdk v2.
However, I found that below query will be compile error:
```graphql

query myQueryABCD(
    $page: Int = 1,
    $first: Int = 20
) {
      myQueryABCD(first: $first, page: $page) {
          ...MyFragmentABCD
      }
}
```
because in query definition, the field `first` is optional with default value, but in schema query `first` is required.
So i change the query to below:
```graphql

query myQueryABCD(
    $page: Int = 1,
    $first: Int! = 20 // adding '!' as required
) {
      myQueryABCD(first: $first, page: $page) {
          ...MyFragmentABCD
      }
}
```
Then apollo client can generate query class successfully, and project got compile. Yeah!!
However, the problem is apollo client respond error because of `Variable "$first" of type "Int!" is required and will not use the default value. Perhaps you meant to use type "Int".`

I would suggest 
1. allowing required field to have default value, or
2. do not return error. Just warn me in project

**Comment by martinbonnin** [comment]
Hi 👋 

> I found that below query will be compile error:

This is most likely a bug in Apollo Android. The spec allows nullable variables in non-null locations when a default value exist:
http://spec.graphql.org/draft/#sec-All-Variable-Usages-are-Allowed.Allowing-optional-variables-when-default-values-exist
It's not going to be easy to fix but I think we should fix it.

> Variable "$first" of type "Int!" is required and will not use the default value. Perhaps you meant to use type "Int"

This is most likely an error in your backend. There was a change in the GraphQL spec to support that use case: https://github.com/graphql/graphql-spec/pull/418 that is most likely not ported there.

Overall both queries appear valid but trigger bugs in either Apollo Android or your backend validation logic. I'll look into the Apollo Android part. Until this is fixed, a workaround would be to remove the defaultValue and always set the variable from Kotlin code. Or if that's too many places to change, maybe add a Kotlin wrapper? Something like:


```
fun MyQueryABCD(
    page: Input<Int?> = Input.absent(),
    first: Int = 20
): MyQueryABCD {
  return MyQueryABCD(page, first)
}
```

**Comment by martinbonnin** [comment]
As a follow up, what needs to be changed is the input values coercion/validation logic: https://github.com/apollographql/apollo-android/blob/437bc50f4a893b6a06b8cb992fb8db1fe62b3ad2/apollo-graphql-ast/src/main/kotlin/com/apollographql/apollo3/ast/internal/InputValueValidationScope.kt#L39

**Comment by darylsze** [comment]
thanks for the following up. On my client side, i have replaced all required type + default value combination in query into required type, but the default value are assigned through kotlin code.
