### ISSUE TITLE
Rename the project to apollo-kotlin to reduce confusion

### ISSUE THREAD

**Issue by LouisCAD** [apollographql/apollo-kotlin#3317]
Hello!

Since this project went along from being exclusive to Android to being widely ~Kompatible~ compatible to most Kotlin targets that have absolutely nothing to do with Android (including iOS!), I think it should get renamed accordingly.

I understand that such a change has implications, but I think they're worth it considering the current confusion that `apollo-android` works on the JVM and on iOS, which is something a Kotlin Multiplatform developer is unlikely to expect.

The most natural new name for me would be `apollo-kotlin`.

Adopting such a name would be in line with how Kotlin has been embraced by this project, and should bring no issue when it comes to the discoverability for Android developers since it's been over 4 years that Google recommends to use Kotlin for Android, and the vast majority of them jumped ship (some even before that event from 2017 in fact).

Looking forward to reading your thoughts (in words, not in your mind),

Have a great day!

Louis CAD

**Comment by rocketraman** [comment]
Two relevant Slack discussions:

https://kotlinlang.slack.com/archives/C01A6KM1SBZ/p1627918746002300
https://kotlinlang.slack.com/archives/C01A6KM1SBZ/p1631183880022200

**Comment by martinbonnin** [comment]
Done. Say hello to `apollo-kotlin` 👋 😃
