### ISSUE TITLE
Client V3 Subscription Authentication

### ISSUE THREAD

**Issue by undermark5** [apollographql/apollo-kotlin#3373]
In the stable build, in order to provide authentication for subscriptions, `subscriptionConnectionParams` are utilized on the Apollo Client Builder. However, it appears there is not an equivalent parameter on the constructor in the v3 build. Is this something that is planned? If not, then how should we be authenticating in subscriptions? I've currently added a interceptor and am utilizing the upgrade request of the websocket to view these headers. Is this the intended way?

**Comment by martinbonnin** [comment]
Hi 👋 

You can use the `connectionPayload` parameter of `SubscriptionWsProtocol`:

```kotlin
    val apolloClient = ApolloClient(
        networkTransport = WebSocketNetworkTransport(
            serverUrl = "https://apollo-fullstack-tutorial.herokuapp.com/graphql",
            protocol = SubscriptionWsProtocol(
                connectionPayload = { emptyMap() }
            )
        )
    )
```

Let us know if that worked and we'll add helper methods to ease the transisition

**Comment by martinbonnin** [comment]
Hi @undermark5 ! Anything else I can help with here?

**Comment by undermark5** [comment]
Oh, I haven't had the chance to test that yet, but from what it looks like that is what I'm looking for.

**Comment by martinbonnin** [comment]
👍 Let us know how that works!

**Comment by CureleaAndrei** [comment]
Hi, is in plan to build a suspend function for connectionPayload if we want to use the recommended GraphQLWsProtocol? Now the only way to provide a connectionPayload is to give it a map in a sync way.

**Comment by martinbonnin** [comment]
@CureleaAndrei can you open a separate issue for this?

**Comment by CureleaAndrei** [comment]
Yeah sure. Thanks

**Comment by martinbonnin** [comment]
Follow up there: https://github.com/apollographql/apollo-kotlin/issues/4042
