### ISSUE TITLE
@defer support

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3556]
Add support for `@defer`  from https://github.com/graphql/graphql-js/issues/2848

See also https://github.com/apollographql/apollo-android/issues/3494

**Comment by hwillson** [comment]
Just a quick planning update - we're targeting `@defer` support only to start.

**Comment by BoD** [comment]
Let's use this one as the umbrella ticket.
- user-facing API changes PR: #3858

Sub tickets:
- #3881
- #3882
- #3883
- #3884 
- #3885 
- #3886 
- #3887

**Comment by hwillson** [comment]
As part of this work we'll need to verify everything is working as expected with the Apollo Router `@defer` alpha.

**Comment by jpvajda** [comment]
👋  `@defer` support is now available an experimental feature in our Kotlin client. You can read more about it's use in our [documentation](https://www.apollographql.com/docs/kotlin/fetching/defer) and [change log](https://github.com/apollographql/apollo-kotlin/blob/main/CHANGELOG.md#version-360)
