### ISSUE TITLE
Support inline fragments without a type condition

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#3623]
With inline fragments, the type condition is actually optional [in the GraphQL spec](https://spec.graphql.org/draft/#sel-GAFbfLBDaAADkBABr7L).

This means this example is valid:

```graphql
  products {
    ... @include(if: true)  {      
      id
    }
  }
```

Or even:

```graphql
  products {
    ... {
      id
    }
  }
```

But the parser in Apollo Android always expects a type condition and fails to parse such examples, with errors like:

```
Execution failed for task ':generateServiceApolloSources'.
> e: /Users/bod/gitrepo/Apollo 3 Scratch/src/main/graphql/com/example/Queries.graphql: (80, 13): Unsupported token `@`
  ----------------------------------------------------
  [79]:        cpu
  [80]:        ... @include(if: true)  {
  [81]:            id
  ----------------------------------------------------
```

**Comment by martinbonnin** [comment]
As of `4.0.0-beta.6` the parser supports it but the codegen doesn't as it's hard to name generated models if the fragments do not have a name (this is similar to how we require a name for operations)
