### ISSUE TITLE
move docs to https://www.apollographql.com/docs/kotlin/  

### ISSUE THREAD

**Issue by yogurtearl** [apollographql/apollo-kotlin#3711]
Would be good if we could move docs to https://www.apollographql.com/docs/kotlin/  and redirect https://www.apollographql.com/docs/android/ to https://www.apollographql.com/docs/kotlin/  

This lines up with the new name. https://github.com/apollographql/apollo-kotlin/issues/3317

Then update the URL on this project: 

![image](https://user-images.githubusercontent.com/1195562/146065514-2075d5e6-bdea-4c3a-9270-14b18b026cc0.png)

**Comment by martinbonnin** [comment]
Thanks! This should come shortly 🤞 . Sorry things are a bit in an intermediate state right now, there are a lot of moving parts.

**Comment by fmatosqg** [comment]
Not sure if this is the best place to reach out, but having issues accessing android documentation right now. Besides landing page nothing works:

https://www.apollographql.com/docs/android -> fine
https://www.apollographql.com/docs/kotlin/tutorial/01-configure-project/ -> not fine (I think I was following this yesterday). Pls see screenshot

![image](https://user-images.githubusercontent.com/5360753/146101330-da175b9c-2fdc-46fb-8ba6-0c5788e2e878.png)


If somebody else is stuck now trying to read docs go to https://github.com/apollographql/apollo-kotlin/tree/main/docs/source

**Comment by trevorblades** [comment]
Thanks for letting us know @fmatosqg. Just issued a fix for this. It should be working as expected now 👍

**Comment by yogurtearl** [comment]
@martinbonnin @trevorblades looks like the new URL is live, reminder to update the URL on the github "About" section. :) 

![image](https://user-images.githubusercontent.com/1195562/146442663-d3b8345e-a7bc-40a5-8684-5a805240ff03.png)

**Comment by martinbonnin** [comment]
@yogurtearl Done. Thanks for the reminder 💙
