### ISSUE TITLE
What's the preffered way to mock GraphQL responses

### ISSUE THREAD

**Issue by AKJAW** [apollographql/apollo-kotlin#3729]
Hello, I was looking through the documentation for Apollo Kotlin v3 and I wasn't able to find anything about how to mock responses for testing.

I was able to find the following resources on the topic:
1. https://community.apollographql.com/t/mock-apollo-client-on-the-kotlin-multiplatform/221 - This points to classes which were removed since the then
2. https://techblog.clashapp.co/mocking-apollo-graphql-operations-on-android-c3433051e8a1 - Leverages HttpInterceptors for providing pre-defined data
3. https://github.com/apollographql/apollo-kotlin/tree/main/apollo-mockserver - I couldn't find much information on this package, only the existing tests in commonTest

I wanted to ask what is the best way to make Apollo return predefined data in testing scenarios. Maybe it would be good to also include this information in the official documentation.

**Comment by BoD** [comment]
Hi! 👋 

Apollo Kotlin 3 introduced [test builders](https://www.apollographql.com/docs/kotlin/advanced/test-builders/) which can be used to easily instantiate the generated models in test code - could that help?

**Comment by AKJAW** [comment]
The test builders would be good for unit tests, however this type of mocking would require replacing the Apollo network layer with a fake that produces these models. This is something I would like to avoid, ideally I'd like to use as much production code as possible in these tests, including the network layer (as far as it is reasonably possible)

**Comment by BoD** [comment]
Thanks for the clarification. This is indeed an area that we'd like to improve, as we have received several questions on it (see #3681 for instance).

In the meantime, we've just added (#3719 which will be in the next release) a `toJson()` method that you can call on models built with the Test builders.  You could then use it in conjunction with a MockServer for instance.

**Comment by AKJAW** [comment]
Hi, I was able to get the MockServer and a Mock HttpInterceptor working and I'm wondering if the MockServer could be improved. 

Correct me if I'm wrong but currently the MockServer does not map the requests to responses, it only adds them to a queue and depending on the execution order the enqued mock is returned. The HttpInterceptor allows for more granular control because based on the X-APOLLO-OPERATION-NAME header we know the requested operation and we can return the exact mocks for that operation.

This allows mocking a feature / operation without needing to set up the MockServer for every test, and also in cases where the whole feed is not yet completed. Which allows the apps to use the Production and Mock feeds interchangeably, which doesn't force the app developers to wait for the completed feed as they can start building something from the get go.

Would it be possible for the MockServer to allow mapping requests / operations to mocked data without needing to set it up every time? Something like ktor does with its [MockEngine](https://ktor.io/docs/http-client-testing.html#test-client), example [here](https://github.com/AKJAW/ktor-mock-tests/blob/f2685b70d3d84da9fb5c0d86b82a6d22bcd2f711/app/src/main/java/com/akjaw/ktor/mock/tests/mock/GitHubApiMock.kt#L50)

**Comment by BoD** [comment]
> MockServer does not map the requests to responses, it only adds them to a queue

That's correct currently.

About improving MockServer, thanks for the insight! Yes we're certainly thinking of making it less "low level", and more "GraphQL aware", with ways to easily enqueue or map GraphQL responses! 

The KTor example you share is useful, thanks (and OkHttp's [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver#dispatcher) has a similar idea too), and don't hesitate to share ideas about how an API would look like ideally to be useful to in your test!

**Comment by martinbonnin** [comment]
For some context, `MockServer` was mainly written for our own integration tests because there was no MPP server available (and I think it's still the case?). It's working but also pretty limited in what it can do and its API is not versioned (it's `@ApolloExperimental`).

If we decide to add a [MockWebServer-like dispatcher](https://github.com/square/okhttp/tree/master/mockwebserver#dispatcher) function, I think it should actually stay at the HTTP level, not GraphQL. We want to be able to mock arbitrary HTTP status code, early connections, etc...

**Comment by AKJAW** [comment]
Got it, for now I think I'll stick to mocking the responses through HttpInterceptors, it seems to work out alright and as you mentioned it stays in the HTTP level only returning JSONs. Thanks for the answers!

**Comment by BoD** [comment]
There is now a way to control MockServer responses via [`MockServerHandler`](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-mockserver/src/commonTest/kotlin/com/apollographql/apollo3/mockserver/test/CustomHandlerTest.kt#L33). Closing this issue for now, don't hesitate to re-open if needed!
