### ISSUE TITLE
@Nullable field sould be nullable

### ISSUE THREAD

**Issue by AleMuzzi** [apollographql/apollo-kotlin#3741]
**Summary**
The class generation from GraphQL query threats @Nullable types wrongly.

**Version**
Apollo runtime with maven dependency, ver. 2.5.11
https://mvnrepository.com/artifact/com.apollographql.apollo/apollo-runtime

**Description**
I need to convert REST APIs into GraphQL ones, so I need to check if a field is null in the REST call body in order to omit in from the GraphQL query.
Since I'm using Sping and `@RestClient` with `@RequestBody`, the REST body is automatically parsed into an object with `null` value for the missing fields.
I'm currently preparing this object for Apollo doing this:

```
private ElasticSearchRequest prepareElasticSearchRequestForApollo(ElasticSearchRequest request) {
  // non-nullable fields
  Utils.checkNotNull(request.index(), "index == null");
  Utils.checkNotNull(request.text(), "text == null");
  Utils.checkNotNull(request.modelName(), "modelName == null");
  
  ElasticSearchRequest.Builder requestBuilder = ElasticSearchRequest.builder()
		  .index(request.index())
		  .text(request.text())
		  .modelName(request.modelName());
  
  // nullable fields
  if (request.from() != null)
	  requestBuilder.from(request.from());
  if (request.size() != null)
	  requestBuilder.size(request.size());
  // ....
  
  return requestBuilder.build();
}
```

But this throws an exception when "from" or "size" are null since the generated class is as follows:
```
public @NotNull String index() {
  return this.index;
}

public @NotNull String text() {
  return this.text;
}

public @NotNull String modelName() {
  return this.modelName;
}

public @Nullable Integer from() {
  return this.from.value;
}

public @Nullable Integer size() {
  return this.size.value;
}

// ....
```

This way the return from `from()` and `size()` will never be null (even is it's tagged with `@Nullable` so it should be allowed to be null) and, moreover, if the field it's null the application crashes because `.value` is invoked on a null object.

**Comment by BoD** [comment]
Hi! 👋

Could you share your `ElasticSearchRequest` GraphQL query? I'm wondering if the `from` and `size` arguments are marked as non nullable (with `!`) or not.

**Comment by AleMuzzi** [comment]
I don't know if you consider this a bug or if you just (and in that case, it would still be legitimate) pretend that if one uses a class generated by Apollo he must set a field `Input.absent()` instead of `null`.

**Comment by BoD** [comment]
Thank you for sending the Input definitions, and your code/explanation, that helps a lot!

I think I understand now:  using the generated model as a method parameter annotated with Spring's `@RequestBody` is indeed probably the culprit. I admit I'm not too familiar with Spring or how this annotation works precisely - but I am guessing it will use reflection, and will automatically assign `null` to `ElasticSearchRequest.from` whereas the rest of Apollo's logic expect it to _never_ be `null` (null would be represented not as `null` but as `Input{null, false}` or `Input{null, true}`).

In fact if I understand this correctly, it should also crash when `from` is not `null` (trying to assign an `Integer` to a field of type `Input<Integer>`?

In that case I recommend using your own intermediary class for this method's parameter, as the generated code really needs to keep `Input` (which by the way has been renamed to a more understandable name, `Optional`, in version 3).

**Comment by AleMuzzi** [comment]
Exactly, you got it totally right, the json is parsed via Gson using reflection and yes, it does crash saying _"Expected BEGIN_OBJECT but was NUMBER at line 5 column 14 path $.from"_.
I was already making a custom Spring converter as you suggested.
Thank you for the celerity and clearness, have a good day.
