### ISSUE TITLE
Automatic "codegenModels" migration

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3751]
Investigate if we can switch `codegenModels` 100% automatically with a script or IntelliJ command

**Comment by martinbonnin** [comment]
`compat` -> `operationBased` is done [here](https://github.com/apollographql/apollo-kotlin/pull/4840)

**Comment by BoD** [comment]
Closing for now, we'll re-open ad-hoc issues if needed.
