### ISSUE TITLE
Add DedupInterceptor

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3760]
In cases where the same query is executed twice in a short period of time, add an opt-in way to deduplicate the query. For an example, given the below scenario

```kotlin
// prefetch when initializing the app
apolloClient.query(myQuery).fetchPolicy(CacheFirst).execute()

// the main screen requests the data when the app starts
apolloClient.query(myQuery).execute()
```

It'd be nice to avoid the extra network roundtrip if the two request come at the same time. This could be done with an interceptor that "remembers" the requests in flight and avoids a round trip if one is already pending. 

Open question: Do we want to potentially dedup cache reads as well. At first sight, it looks more complicated but maybe it's only a matter of inserting the interceptor before/after the cache interceptor.

**Comment by ynkm169** [comment]
> Do we want to potentially dedup cache reads as well
If the cache read/write can have some costs, would be nice to dedup it as well. When I was looking at memory cache source code, it does a synchronized lock on LRU cache. Android LRU cache internally most likely uses lock stripping and hence very fast. With a synchronized lock on the entire LRU cache, there is a performance penalty (can't tell how much it cost without some profiling).

**Comment by BoD** [comment]
Closing for now as this didn't seem to get much traction - please re-open if you'd like to see this implemented.
