### ISSUE TITLE
Add support for CACHE_AND_NETWORK with watch()

### ISSUE THREAD

**Issue by demoritas** [apollographql/apollo-kotlin#3763]
**Use case**
following scenario, we have potentially data in cache but we need a network refresh and want to watch the cache after that:

cache first -> to have a fast response to the user
network second -> to have the current data in case it changed
watch -> we need cache updates

`executeCacheAndNetwork` is not useable in this scenario since it directly executes.

There is no `FetchPolicy` for this scenario so we can not call `watch`

**Describe the solution you'd like**

a.  `FetchPolicy.CacheAndNetwork` so we can decide to call `toFlow`, `execute` or `watch` after setting it
This has the downside that `execute()` has a definition problem sind we could have 2 results

b. add an extension function `watchCacheAndNetwork`

**Comment by BoD** [comment]
With #3829 a new `CacheAndNetwork` policy has been added 🎉. This will be in the next release, in the meantime it can be tried out with the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots).

**Comment by martinbonnin** [comment]
Fixed in 3.1.0
