### ISSUE TITLE
Make ./gradlew convertApolloSchema behave the same as downloadApolloSchema

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3764]
We've had some issues with cwd and Gradle tasks executed from the command line. See https://github.com/apollographql/apollo-kotlin/issues/3470

`downloadApolloSchema` now doesn't use the cwd but the rootProject directory. For consistency, `convertApolloSchema` should behave the same

**Comment by BoD** [comment]
Fixed by #3773
