### ISSUE TITLE
Migrating to Apollo 3: Usage of `SubscriptionManager`

### ISSUE THREAD

**Issue by AchrafAmil** [apollographql/apollo-kotlin#3766]
While migrating from Apollo 2 to Apollo 3, I can't find a trivial replacement for usage of `ApolloClient::addOnSubscriptionManagerStateChangeListener` and `ApolloClient::subscriptionManager.reconnect()`.

Any clues/suggestions ? 🙏

**Comment by martinbonnin** [comment]
Indeed, that logic has changed quite a bunch, the idea being that `WebSocketNetworkTransport` can reconnect on its own without external intervention. If you need to customize the reconnection, you can use `webSocketReconnectWhen`

```kotlin
    val apolloClient = ApolloClient.Builder()
        .serverUrl("http://localhost:8080/subscriptions")
        .webSocketReconnectWhen {
          // check the exception here and reconnect on server disconnect or something else.
        }
        .build()
```

See test code [there](https://github.com/apollographql/apollo-kotlin/blob/d0f29bff0f4c576e54e516f5c701114fd0681c44/tests/websockets/src/jvmTest/kotlin/WebSocketErrorsTest.kt#L94).
It can be that not all use cases are possible yet. If that doesn't work for you, can you share how you were using `addOnSubscriptionManagerStateChangeListener` and we'll add more APIs.

**Comment by AchrafAmil** [comment]
Thanks!

We currently listen for state and manually trigger a `reconnect()` that can indeed be replaced with `webSocketReconnectWhen`.

Just, will be cool if the `reconnectWhen` were a suspendable so we can call delay (e.g. backoff strategy) or wait for a trigger.
```kotlin
reconnectWhen: (suspend (Throwable) -> Boolean)?
```

**Comment by martinbonnin** [comment]
> Just, will be cool if the reconnectWhen were a suspendable so we can call delay (e.g. backoff strategy) or wait for a trigger.

Makes sense. Want to open a PR?

**Comment by AchrafAmil** [comment]
Sure, let me do that!

**Comment by BoD** [comment]
Thanks for the PR, it has been merged 👍. The change will be in the next release, in the meantime it can be tried out with the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots).
