### ISSUE TITLE
Migrating Multi module project to Apollo 3

### ISSUE THREAD

**Issue by dostalleos** [apollographql/apollo-kotlin#3767]
Hello,
I'm trying to update my multi module project to Apollo v3 (from v2) and I'm facing several issues.

**Here is my setup:**
- I'm applying Apollo Gradle plugin in all my modules (via common gradle file).
- I have a core module for graphql where I have Apollo-runtime dependency (api), apollo gradle config (see bellow), schema and some core kotlin code
- I have several feature modules, where core graphql module is included (including apolloMetadata).
- Each feature module has its own graphql files

```
apollo {
	generateApolloMetadata.set(true)

	useSemanticNaming = true

	customTypeMapping = [
			"DateTime"   : "java.time.LocalDateTime"
	]

	sealedClassesForEnumsMatching = [".*"]
}
```

**Issues I'm facing**

1. I'm getting following error when I try to sync the project:

```
Apollo: specify 'packageName':
apollo {
  packageName.set("com.example")
  
  // Alternatively, if you're migrating from 2.x, you can keep the 2.x   
  // behaviour with `packageNamesFromFilePaths()`: 
  packageNamesFromFilePaths()
}
```

I managed to solve this by adding `apollo { packageNamesFromFilePaths() }` to the common gradle file, which is imho not ideal. After this change I was able to sync the project.

2. I'm getting following error for multiple modules when I try to build the project:
 
```
No schema file found in:
src\main\graphql
```

I haven't found a way how to fix this one 😢 

Could you please help me?

Also I've checked Multi Modules documentation [here](https://www.apollographql.com/docs/kotlin/advanced/multi-modules/) and it seems to be not fully updated. It contains `generateKotlinModels` even though this command should be removed after v3 udpate.

**Comment by martinbonnin** [comment]
Thanks for reaching out! Can you make sure you have `apolloMetadata(project(":common"))` (where `common` is the name of the module containing your schema) inside each feature module?

```
//feature1/build.gradle

dependencies {
  apolloMetadata(project("common"))
}

```

If that's the case, can you share what module triggers the `No schema file found` error? Is it the common module or a feature module?

**Comment by dostalleos** [comment]
I do not have it in each module, because each module doesn't need it in my original project. Anyway I've just created new project with just two modules and I'm experiencing exactly the same behavior. 

You can find it [here](https://github.com/dostalleos/Apollo_v3). It's just empty project with two modules and Apollo v3 dependency. Try to run it to see the error. 

Thank you

**Comment by martinbonnin** [comment]
Thanks a lot, the reproducer helps a ton 🙏 . Turns out `generateApolloMetadata.set(true)` needs to be in the "core" module, not the feature ones. I can compile your sample project with this diff: https://github.com/dostalleos/Apollo_v3/pull/1/files

**Comment by dostalleos** [comment]
Yeah, I've just found that too 😅 

But it still requires all the modules to have `apolloMetadata project(':core-graphql')` though, otherwise No schema found error is thrown 😢  
This was not required before, is there any way how to not add that into all the modules? I can think of not including Apollo gradle plugin in the modules where it's not necessary.

**Comment by martinbonnin** [comment]
> it still requires all the modules to have apolloMetadata project(':core-graphql') 

Correct

> This was not required before

Would you have a sample project where it's not used? The docs mention the same `apolloMetadata` https://www.apollographql.com/docs/kotlin/v2/advanced/multi-modules/

>  I can think of not including Apollo gradle plugin in the modules where it's not necessary.

You'll need to include the Apollo Gradle Plugin in all modules that contain GraphQL files to generate models from. If you have some common configuration in feature modules, you can factor that in using convention plugins. A nice article about this is https://developer.squareup.com/blog/herding-elephants/.

**Comment by dostalleos** [comment]
Thank you for your reply and suggestions.

> Would you have a sample project where it's not used? The docs mention the same apolloMetadata

I'll try to explain it little bit more. Unfortunately I do not have time to create sample project for that. 
All my modules include Apollo Gradle plugin, but not all of them have graphql files so it was not necessary to use `apolloMetadata` in those modules without graphql files. But know with v3, it throws an error about missing scheme for such a modules. Hopefully it's clear now. There is probably no action need, I just wanted to point out, that this was not required before (no error was thrown).
<br/><br/>
Now I'm experiencing some inconsistency in packages in generated files. 
I have `apollo { packageNamesFromFilePaths() }` config in all the modules.
Scheme is in `core-graphql` module with following path `src/main/graphql/com/apollo/v3/schema.json`.

I have following script in `core-graphql` module (path `src/main/graphql/com/apollo/v3/core/Test.graphql`).
- `TestCore` query 
- `UserCore` fragment 

and in `app` module (path `src/main/graphql/com/apollo/v3/app/Test.graphql`).
- `TestApp` query 
- `UserApp` fragment 

This results in following generated files:
`com.apollo.v3.core.TestCoreQuery` - Corresponds with path.
`com.apollo.v3.fragment.UserCore` - Corresponds with schema path, but fragment is in the same file as query above.
`com.apollo.v3.app.TestAppQuery` - Corresponds with path.
`fragment.UserApp` - No package at all, but fragment is in the same file as query above.

You can build my sample project mentioned earlier to check this.
Is this expected behavior? 
Thank you

**Comment by martinbonnin** [comment]
> All my modules include Apollo Gradle plugin, but not all of them have graphql files so it was not necessary to use apolloMetadata in those modules without graphql files. But know with v3, it throws an error about missing scheme for such a modules. Hopefully it's clear now. There is probably no action need, I just wanted to point out, that this was not required before (no error was thrown).

I see, thanks for the details! I'd be in favour of keeping that behaviour. Applying the plugin in module that don't have any .graphql file is build overhead having an error is a forcing function to avoid this. 

> Is this expected behavior?

It is definitely not. In the 2.x logic, `fragment.UserApp` should be `com.apollo.v3.fragment.UserApp` because all fragments need to be in the same package name. So there's a bug there. But we can actually do better in 3.x and use the same logic as for operations. I'll look into it.

**Comment by dostalleos** [comment]
I went with `packageName.set()` in all my modules which resulted with fragment packages based on the package specified in the gradle. So it's the same as the `useSchemaPackageNameForFragments.set(false)` from the PR I believe.

**Comment by martinbonnin** [comment]
`packageName.set()` will use a flat package name (all your operations will have the same package name)

`useSchemaPackageNameForFragments.set(false)` allows you to have different package names depending on the folder hierarchy. 

If a flat package name works for you then it's definitely an easier solution 👍

**Comment by dostalleos** [comment]
Yea, `packageName.set()` works for me, because I have just one package name per module for graphql files.
