### ISSUE TITLE
Image file upload resulting an error "Image file not valid"

### ISSUE THREAD

**Issue by Subh0deep** [apollographql/apollo-kotlin#3781]
As I've mentioned the following code structure gave me an error of the 
```image file not being valid```
 need some suggestions to resolve this issue.

build/gradle configuration for apollo:
```
apollo {
    useVersion2Compat()
    customScalarsMapping = [
            "Upload" : "com.apollographql.apollo3.api.Upload"
    ]
}
```
using apollo 3.0.0
android studio 2021.2.1 Canary 6
product target SDK 31

![2](https://user-images.githubusercontent.com/69012694/148904165-2bb87d73-e5d9-42aa-9fd4-c7b98266e1af.JPG)
![ss](https://user-images.githubusercontent.com/69012694/148904170-b8e84063-2664-406a-999a-65200bc47ec5.JPG)
![1](https://user-images.githubusercontent.com/69012694/148904172-e8515fe3-f8fe-42b7-a1d7-ef3492e20a1a.JPG)

**Comment by BoD** [comment]
Hi! Thanks for reaching out. To help us understand the issue could you clarify what you mean by "image file not being valid"? From the first screenshot, an `Upload` with the image file is passed to a mutation which is executed - does that part work?

**Comment by Subh0deep** [comment]
Yes after that the response throws an error image file not valid.

**Comment by BoD** [comment]
Thanks!  From what I can see, you are calling `content` on the Upload builder, and pass `imageFile.path.toByteArray())`. The result is an `Upload` whose content is a string of the path - instead what you want is an `Upload` whose content is the actual content of the file.

To do this, try:

```kotlin
DefaultUpload.Builder()
              .file(imageFile)
//...
```

**Comment by Subh0deep** [comment]
.file is missing 
![Screenshot 2022-01-11 at 7 20 16 PM](https://user-images.githubusercontent.com/69012694/148954857-77cb6bb0-de50-411c-a91d-e078211c88f0.png)
g

**Comment by BoD** [comment]
Woops sorry the method is named `content`, not `file`. Also, it's an extension so make sure it's imported:
`import com.apollographql.apollo3.api.content`

**Comment by Subh0deep** [comment]
When i tried to do so ,found an exception and it just says `closed`


![Screenshot 2022-01-11 at 11 34 50 PM](https://user-images.githubusercontent.com/69012694/148997705-cedb86db-b5f2-48ec-88fd-1f9f5dfb7c66.png)
![Screenshot 2022-01-11 at 11 35 51 PM](https://user-images.githubusercontent.com/69012694/148997739-c6e440da-dec3-429c-ab22-04065a377a0a.png)
![Screenshot 2022-01-11 at 11 37 12 PM](https://user-images.githubusercontent.com/69012694/148997803-75ff61b7-0893-4638-9d0c-bc4cc0b11073.png)

**Comment by BoD** [comment]
It's a bit hard to know for sure without seeing all the code but could it be that you are using the same `Upload` as 2 parameters? This won't work because its `bufferedSource` would be closed twice, which would explain the exception you see. If that's the case, you can try to create 2 `Upload`s instead.

**Comment by Subh0deep** [comment]
created two uploads which has fixed the exception and now this gives an error as response which says 'File missing in the request'
![Uploading Screenshot
![Screenshot 2022-01-12 at 12 21 40 AM](https://user-images.githubusercontent.com/69012694/149004030-89fd17a3-6414-48f0-9efa-3660f21ce034.png)
 2022-01-12 at 12.22.06 AM.png…]()

**Comment by BoD** [comment]
At this point I would inspect the payload sent to the server with a tool like Charles Proxy, as a way to try to see if we can figure out what's happening.

**Comment by martinbonnin** [comment]
Hi @Subh0deep! Were you able to solve your issue?

**Comment by martinbonnin** [comment]
Closing for now. @Subh0deep let us know if you want us to reopen.
