### ISSUE TITLE
BodySource typo inside Http.kt

### ISSUE THREAD

**Issue by StylianosGakis** [apollographql/apollo-kotlin#3782]
https://github.com/apollographql/apollo-kotlin/blob/04b45663beacbcf81d9c9f77b796f7de5b9c03f6/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/http/Http.kt#L83

I'm not sure what was meant to be said there, but this looks like a typo right? Maybe "[bodySource] and [bodyString]"?

**Comment by BoD** [comment]
Woops, you're right it should be `bodySource` and `bodyString`, it's about the checks in lines 126 and 135.

**Comment by BoD** [comment]
Fixed via #3783
