### ISSUE TITLE
Enable Access to FetchPolicy associated with ApolloRequest

### ISSUE THREAD

**Issue by ArjanSM** [apollographql/apollo-kotlin#3798]
**Use case**
As of now access to an `ApolloRequest`'s `FetchPolicy` is labelled as `internal`. 
I am in the middle of capturing Apollo cache performance data and one of data points that is to be captured is the `FetchPolicy` associated with the request.
I am logging all the cache specific data in my implementation of `ApolloInterceptor`. 
While I can access the `ApolloRequest` inside an implementation of the `ApolloInterceptor`, I still cannot access the `FetchPolicy` associated to the request(since the extension function exposing the fetchpolicy of a request is labelled as internal).

Interestingly, on iOS client, I believe there's a similar construct in the `HttpRequest` called 'CachePolicy' which can be accessed via the `CacheReadInterceptor`

**Describe the solution you'd like**
Maybe, I'm jumping the gun but converting the extension function that enables access to `FetchPolicy` as non internal could be an option.

**Comment by ArjanSM** [comment]
I can take this one.

**Comment by martinbonnin** [comment]
So turns out that in the tip of `main`, there's no `ApolloRequest.fetchPolicy` anymore but instead `ApolloRequest.fetchPolicyInterceptor`. This was made to accommodate custom fetch policies (see https://github.com/apollographql/apollo-kotlin/issues/3689). 

I guess you could use something like:

```kotlin
when (fetchPolicyInterceptor) {
   CacheFirstInterceptor ->
   NetworkOnlyInterceptor -> 
   ...
}
```

While that could be made public, I wonder if you could use `ApolloRequest.cacheInfo` instead? It contains the time to read from the cache and whether it was a cache hit or miss (or null if the request didn't pass through cache at all). 

Maybe that'd suit your needs?

**Comment by ArjanSM** [comment]
Maybe I'm missing something. But isn't `ApolloRequest.fetchPolicyInterceptor` also `internal`?
As far as `CacheInfo` is concerned, yes, that is what I plan to use for other cache related data.

**Comment by martinbonnin** [comment]
> But isn't ApolloRequest.fetchPolicyInterceptor also internal

Yes, it's all internal right now. I was just pointing out that this code changed recently

> As far as CacheInfo is concerned, yes, that is what I plan to use for other cache related data.

Do you still need access to `fetchPolicyInterceptor` if you have `CacheInfo` or is `CacheInfo` not enough? 

Sorry for all the questions but I'd like to avoid increasing the API surface if there's already a way to satisfy your use case.

**Comment by ArjanSM** [comment]
ah I see. My bad.
We are re-evaluating our usecase to access the `FetchPolicy`.
I think I am good to close this request.
Thank you so much for your prompt responses :-)

**Comment by martinbonnin** [comment]
Sounds good. Let us know how that goes. If you need access to more internal, feel free to leave a message and I'll reopen this issue.
