### ISSUE TITLE
Implement a garbage collector to remove unreachable nodes

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-kotlin#3805]
* Remove unreachable Records
* Remove expired Records

(Dangling references are also an issue but related to low level usages of `remove(id)`, see https://github.com/apollographql/apollo-kotlin/issues/2507)

**Comment by jpvajda** [comment]
As a note from our team discussion today we talked about doing some more product discovery around the use cases of garbage collection to better understand it's intended use.  I'll work on an internal document that will help to define our approach to collecting that feedback from our users and customers. cc @martinbonnin @BoD

**Comment by jpvajda** [comment]
👋  I've pinned this issue to to repo, as we are looking for feedback on what type of use cases people may have around Garbage Collection and our Kotlin Client.

**Comment by BoD** [comment]
Closing in favor of https://github.com/apollographql/apollo-kotlin-normalized-cache-incubating/issues/83
