### ISSUE TITLE
Support manual cache eviction

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-kotlin#3806]
Broken out from https://github.com/apollographql/apollo-kotlin/issues/2331. We'll use this issue to track cache eviction feature work.

Side note: we need to look into how much of this is already possible with `apolloStore.remove()`.

**Comment by martinbonnin** [comment]
Turns out `apolloStore.remove(CacheKey)` is doing the job. What we're missing is a way to handle dangling references after an entity has been removed. See https://github.com/apollographql/apollo-kotlin/issues/2507 for a follow up.
