### ISSUE TITLE
Can't build iOS because of reserved keyword

### ISSUE THREAD

**Issue by drakegebhart2** [apollographql/apollo-kotlin#3808]
**Summary**
We are trying to add Apollo to our Kotlin Multiplatform SDK. We have a iOS framework that is statically including other frameworks. We are including Apollo in our project but in the statically included framework the generated code has a reserved symbol "DEBUG", which causes the build to fail. If we change the name of the compiled code to anything else, it runs successfully. [We've soon realized that the compiled code is actually the Apollo Logger in version 2.4.6](https://github.com/apollographql/apollo-kotlin/blob/80f1d76d12fee97446c4e52e8b3aec205f4dfdcb/apollo-api/src/main/java/com/apollographql/apollo/Logger.kt)

**Version**
2.4.6

**Description**
![image](https://user-images.githubusercontent.com/90862270/150570377-f4aee2c5-666e-45c4-8b4b-5ee7102f32c4.png)
We noticed on v3.0.0 of Apollo this logger does not exist anymore, maybe because of this reason? Attempting to update from 2.4.6 -> 3.0.0 is a very heavy task as we have large amount of code and would require us to update our Kotlin version, Ktor version, and becomes dependency hell. We don't know if this would fix our problem but think it might.

One other option we were thinking is to make a fork of 2.4.6, change the debug log to logDebug and use that fork in our app. We haven't done this before and think it could be an easy short term solution, although long term we would like to be able to update Apollo without having to worry about this. 

Are there any other options or is our theory incorrect?

**Comment by BoD** [comment]
Thanks for reaching out 👋

This name clash is unfortunate, sorry about that!

First of all, I can confirm that there is no symbol named `DEBUG` in version 3 so upgrading would solve this indeed.

I understand this may not be possible for you right now (however, just to confirm: v3 works on projects with Kotlin 1.4 or more - are you on a lower version of Kotlin?).

Having your own fork could indeed be a short term solution. I would offer to release a new version of v2 but I can’t think of a way to fix this without it being a breaking change.

(Also this is unrelated to your problem but the latest version of the v2 branch is `2.5.11`).

**Comment by BoD** [comment]
Oops it looks like I spoke too soon 😞  I forgot Multiplatform has specific restrictions when it comes to Kotlin versions, and forward compatibility is unfortunately not supported yet (more info [here](https://youtrack.jetbrains.com/issue/KT-42293)).

This means you will need Kotlin 1.6+ on your project after all.

(We should clarify this on the requirements section of the project's page).

Sorry if I gave you false hopes!

**Comment by martinbonnin** [comment]
I'm curious how come this hasn't been an issue so far. There are definitely native users of 2.x. Could it be that no one is using `ApolloLogger` on native? It feels weird that this would only come up now if it was happening all the time 🤔

**Comment by BoD** [comment]
Good point @martinbonnin ! 
I've just tried a minimalist KMP project with Apollo Android v2 (never tried before!) and don't seem to have this issue.

@drakegebhart2 From the screenshot, could it be that `DEBUG` is defined in `PaymentSDKLogger`, so not the Apollo one?

**Comment by drakegebhart2** [comment]
@BoD We think that the reason this fails is because our PaymentSDK is a static library. We already use Apollo Android v2 in a different SDK and it works correctly. It's only when it gets exported by the PaymentSDK we get this compilation error.

We were narrowing down what `PaymentSDKLogger` was before posting on here, as it doesn't match any of our code. We eventually found it matched Apollo's logger and realized the name spacing happening.

We are including Apollo in the CheckoutSDK, which then gets pulled into the PaymentSDK because of the dependency. Because it is static it has to namespace the files imported so it appends `PaymentSDK` to all the files, so the Apollo `Logger` class becomes `PaymentSDKLogger`. 

The PaymentSDK is a [static library that depends](https://kotlinlang.org/docs/mpp-build-native-binaries.html#export-dependencies-to-binaries) upon our SDK we are working on (CheckoutSDK). The static library code is done in build.gradle like so:
```
kotlin {
    android {}

    iosTarget.binaries {
        framework("PaymentSdk") {
            export project(":CheckoutSdk")
            transitiveExport = true
            isStatic = true
        }
    }
}
```

We also added Apollo directly to PaymentSDK and it had no problem compiling (but we can't use it in our SDK 😢 ). We already have it in the different SDK and that works as well. We are planning on centralizing this but that has the compilation problem since the PaymentSDK pulls that in.

**Comment by BoD** [comment]
Thanks a lot for the explanation, it is clearer now!

This is a wild guess but I'm wondering if you really need `transitiveExport = true` here?

**Comment by drakegebhart2** [comment]
> Thanks a lot for the explanation, it is clearer now!
> 
> This is a wild guess but I'm wondering if you really need `transitiveExport = true` here?

Yeah we need it otherwise compilation fails for other imports

**Comment by drakegebhart2** [comment]
@BoD Yeah that's one of our dependency graphs, however, the PaymentSDK also exports another project that needs the transitive export. I turned it off to test and there were lots of dependencies unresolved for compilation 😢 

We are pretty close to upgrading Kotlin to latest so we can test out Apollo3 to see if this will resolve our problem! 🤞

**Comment by BoD** [comment]
> the PaymentSDK also exports another project that needs the transitive export

Thanks for the clarification, that makes sense!

Hope you'll be able to upgrade smoothly and resolve the issue!

**Comment by drakegebhart2** [comment]
@BoD We tried updating Kotlin to 1.6.10 which allowed Apollo 3. However, we started having other issues where we need coroutines updated, ktor, and then ktor-network which then required Kotlin to be updated again and they are waiting for that fix. So one huge circular dependency which isn't fun 😭 

We have fallen back to doing the fork and making that change. We ran it locally and it built successfully 🎉 !

However, building it and trying to get Maven working is causing us some more headaches. You mentioned that doing this fork would have breaking changes but I'm wondering what those are? 

[Here is our fork for reference](https://github.com/drakegebhart2/apollo-kotlin/commit/e4221c7cb7c1bb980a891df3bc48d63cb164d2f7) 

[Here is our commit changes ](https://github.com/drakegebhart2/apollo-kotlin/commit/e4221c7cb7c1bb980a891df3bc48d63cb164d2f7)

**Comment by BoD** [comment]
Thanks for the update! And sorry to hear the Kotlin / Apollo 3.x update didn't work :( I hope the blocker will be resolved soon.

When I mentioned a breaking change I just meant that any projects using the constant and updating to the latest version of  2.x would need to update their code otherwise the compilation will fail. I was also thinking of libraries that using Apollo under the hood, used in projects using the new version (binary compatibility) - but now I wonder if this one may actually be ok since it's static constant (to be verified!). 

But yeah, basically we want to avoid this especially at this point where 2.x is in maintenance mode.

Not sure if this will help but if you want to publish your fork to a maven repository (Nexus or Artifactory for instance), you should use a specific `groupId` to ensure the fork is picked by Gradle.
