### ISSUE TITLE
Instant - NoClassDefFoundError

### ISSUE THREAD

**Issue by akshay253101** [apollographql/apollo-kotlin#3819]
We have recently migrated on Apollo-v3, and got a runtime crash on android versions 5,6,7.

Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/base.apk"],nativeLibraryDirectories=[/data/app/lib/arm, /vendor/lib, /system/lib]]

found out that HttpCachingInterceptor is using java.time.Instant in both networkMightThrow and cacheMightThrow
```
private suspend fun networkMightThrow(request: HttpRequest, chain: HttpInterceptorChain, cacheKey: String): HttpResponse {
    val response = chain.proceed(request)

    val doNotStore = request.headers.valueOf(CACHE_DO_NOT_STORE)?.lowercase() == "true"
    if (response.statusCode in 200..299 && !doNotStore) {
      // Note: this write may fail if the same cacheKey is being stored by another thread.
      // This is OK though: the other thread will be the one that stores it in the cache (see issue #3664).
      store.write(
          response.newBuilder()
              .addHeaders(
                  listOf(
                      HttpHeader(CACHE_KEY_HEADER, cacheKey),
                      HttpHeader(CACHE_SERVED_DATE_HEADER, Instant.now().toString()),
                  )
              )
              .build(),
          cacheKey)
    }
    return response
  }
````

And caller only catch ApolloException 

````
CACHE_FIRST -> {
        try {
          return cacheMightThrow(request, cacheKey)
        } catch (e: ApolloException) {
          //
        }
NETWORK_ONLY -> {
        return networkMightThrow(request, chain, cacheKey)
      }
````

**Comment by akshay253101** [comment]
https://developer.android.com/studio/write/java8-support#library-desugaring

In KotlinxInstantAdapter - It requires Android Gradle plugin 4.0 or newer and [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).

It should be provided in gradle implementation of apollo-v3

**Comment by martinbonnin** [comment]
Hi 👋 ! Indeed `Instant` requires desugaring. We can certainly replace this specific usage of Java8 with something more widely available but in the long run, Java8 is the minimum version supported and I'd suggest enabling `coreLibraryDesugaringEnabled`. Would that work for you?

**Comment by akshay253101** [comment]
yes it worked for me

**Comment by martinbonnin** [comment]
Documentation updates are [there](https://github.com/apollographql/apollo-kotlin/pull/3846). Let me know what you think!

**Comment by martinbonnin** [comment]
Documentation has been merged. Let me know if you see things to change and I'll update it accordingly.
