### ISSUE TITLE
Allow normalization to be disabled for specific types

### ISSUE THREAD

**Issue by apramana** [apollographql/apollo-kotlin#3827]
**Use case**
Some types represent transient data that doesn't need to be cached separately and can simply be embedded into parent objects. Apollo React allows normalized cache to be [disabled](https://www.apollographql.com/docs/react/caching/cache-configuration/#disabling-normalization) per type by setting `keyFields = false`. This might allow some compile [optimizations](https://github.com/apollographql/apollo-kotlin/issues/3656) to be made.

**Describe the solution you'd like**
Same or similar solution as the functionality in Apollo React.

**Comment by martinbonnin** [comment]
Closing as duplicate of https://github.com/apollographql/apollo-kotlin/issues/1812
