### ISSUE TITLE
:app:generateServiceApolloSources fails with "Extra token at end of file `﻿`"

### ISSUE THREAD

**Issue by Jacksotnik** [apollographql/apollo-kotlin#3830]
Hi there. I'm trying to migrate project to apollo-kotlin.

Currently i have trouble when building project

Execution failed for task ':app:generateServiceApolloSources'.
> e: 'file path:(1, 1)': Extra token at end of file `﻿`

Here is graphql file content:

`query getCustomerCards($modVer: Int!) {
    getCustomerCards(mod_ver: $modVer) {
        id
    }
}`

**Comment by martinbonnin** [comment]
Thanks for sending this. This looks like valid GraphQL at first sight 🤔 . Maybe it's an encoding issue or something? Can you upload your `.graphql` file somewhere (Google drive or any other place?) to double check this?

**Comment by martinbonnin** [comment]
The `(1, 1)` would hint at maybe unicode 16 bit wide chars? So that there's a zero at position 1? Maybe try to save the file in UTF-8 ?

**Comment by Jacksotnik** [comment]
I didn't do any changes in graphql files. On apollo-android 2.x everything works fine

**Comment by martinbonnin** [comment]
Any chance you can still upload a file somewhere? That'll save a huge amount of time.

**Comment by Jacksotnik** [comment]
Okay. Saving all graphql files as UTF-8 way helpful :)

**Comment by martinbonnin** [comment]
Thanks for the update!  
I opened https://github.com/apollographql/apollo-kotlin/issues/3830 so we can dig into this and support other encoding formats in the future.
