### ISSUE TITLE
How to retry a request chain in interceptors?

### ISSUE THREAD

**Issue by yuzushioh** [apollographql/apollo-kotlin#3832]
I'm looking for a method like `retry(request:completion:)` in apollo iOS. I have a trouble with retrying requests, when refreshing access tokens, without returning access token expired errors back to caller.

Doc: https://www.apollographql.com/docs/ios/api/Apollo/classes/RequestChain/#retryrequestcompletion

**Comment by BoD** [comment]
Hi! 👋 

Inside an interceptor, to retry a request you can simply call `chain.proceed` several times. We have an exemple [here](https://github.com/apollographql/apollo-kotlin/blob/main/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BearerTokenInterceptor.kt#L8), does that help?

**Comment by martinbonnin** [comment]
@yuzushioh anything else we can help with here?
