### ISSUE TITLE
"fields have different nullability shapes" validation is missing at compile time

### ISSUE THREAD

**Issue by kubode** [apollographql/apollo-kotlin#3840]
**Summary**
"fields have different nullability shapes" validation is missing or not working at compile time.

**Version**
3.0.0

**Description**
"fields have different nullability shapes" validation error is shown on IDE (with GraphQL plugin).
![image](https://user-images.githubusercontent.com/5885032/152463484-5c353f7c-dd24-4ffa-867e-c1ff12c691a5.png)

If the backend implements [this](https://graphql.org/graphql-js/validation/#specifiedrules) validation rule, executing this query will return an error.

This error is probably due to [Field Section Merging](https://spec.graphql.org/June2018/#sec-Field-Selection-Merging) specification.

However, this query will not cause any errors at compile time.
Is this the intended behavior?

**Pseudo code**

Schema
```graphql
type A {
  imageUrl: String
}

type B {
  imageUrl: String!
}

union X = A | B

type Query {
  x: X
}
```

Query
```graphql
query X {
    x {
        ... on A {
            name
        }
        ... on B {
            name
        }
    }
}
```

**Comment by martinbonnin** [comment]
Thanks for sending this. Looks like you bumped into https://github.com/apollographql/apollo-kotlin/pull/3799. This fix is available in the SNAPSHOT and will be in next release

**Comment by kubode** [comment]
Oh, I didn't notice.
I checked it with `3.0.1-SNAPSHOT` and got the compile error as expected.

Thanks!
