### ISSUE TITLE
Gradle-configured schema introspection in a multi-module project setup

### ISSUE THREAD

**Issue by theBradfo** [apollographql/apollo-kotlin#3842]
**Question.**
How does one configure schema introspection in a multi-module project, where there is one schema for the entire project?  I am planning to have a schema module, that serves as the dependency for all modules that contain apollo-managed graphql sources and was planning on configuring the `introspection` in this schema module's gradle config, as such:
```
apollo {
        introspection {
            endpointUrl.set("...")
            schemaFile.set(file("schema.graphql"))
            headers.set([
                    "...": "..."
            ])
        }
}
```
However, it appears the `introspection` block is ignored if not placed within a `service` as I receive the exception:
```    
Caused by: java.lang.IllegalStateException: Apollo: no schema property
        at com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask.taskAction(ApolloDownloadSchemaTask.kt:76)
```
In the multi-module setup, I'm unable to use a `service` config, as the Apollo plugin fails when multiple `service` configs with the same name are found.  Given we have one schema and multiple apollo/graphql modules, what is the recommended practice here?  Am i forced to use the `--endpoint`, `--schema`, etc arguments on the command line when running the `downloadApolloSchema` task (which to be clear works really well - but I was hoping to host this configuration within gradle!)?

**Comment by BoD** [comment]
Hi! 👋 

This should work even without a `service`, in that case the task name will be `downloadServiceApolloSchemaFromIntrospection` - just to be sure is it that task you ran and got the error message?

**Comment by theBradfo** [comment]
Thanks for the quick response @BoD!  I was running the `downloadApolloSchema` task and receiving the error, but `downloadServiceApolloSchemaFromIntrospection` works!  The doc update is much appreciated - thanks again.
