### ISSUE TITLE
Use @JvmOverloads on generated operation classes

### ISSUE THREAD

**Issue by theBradfo** [apollographql/apollo-kotlin#3848]
**Use case**
Our large project is adopting apollo kotlin (3.x), and has a mix of Java and Kotlin code that will be use the generated Apollo models.  The default arguments on the generated requests are great, for calling Kotlin code, but aren't usable by calling Java code.

**Describe the solution you'd like**
Add a more friendly interoperable way for Java code to call and use the generated classes, perhaps by simply adding the `@JvmOverloads` annotation to constructors that contain default arguments.

Seems like there was some discussion about it in #3281 but its not clear what the decision was.

**Comment by theBradfo** [comment]
We're _currently_ only using the `:apollo-runtime` artifact for model generation, so it's not an immediate concern for request execution.  Was just looking to improve the interop for the migration of our feature code written in Java!

**Comment by martinbonnin** [comment]
I'm confused. `apollo-runtime` doesn't generate any model. It contains the HTTP client and execution pipeline to execute requests. 

So once you have a generated query, you'd need to execute it somehow. Typically like this:

```graphql
query GetRepos($first: Int, $offset: Int) {
  repositories(first: $first, offset: $offset) {
    name ids
  }
}
``
`

```kotlin
val response = apolloClient.query(GetRepositories(offset = Optional.Present(50))).execute()
```

If you're instanciating the query from Java, I'd also expect you'd execute it in Java as well but looks like you're not?

**Comment by theBradfo** [comment]
Sorry, i mistyped, we are using `:apollo-api` for model generation only, not the runtime artifact.

**Comment by martinbonnin** [comment]
Ah gotcha, makes a lot of sense 👍 . 

Do you want to open a PR? Feel free to add `@JvmOverloads` unconditionally and I can deal with the tunneling of Gradle parameters all the way down to codegen .

**Comment by theBradfo** [comment]
Yes - will do later this week probably!
