### ISSUE TITLE
Allow to build a Json using the test builders

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3851]
Test builders make it easy to build a `Data` class using `MyQuery.Companion.Data`:

```kotlin
val data = HeroQuery.Data {
  hero = droidHero {
    name = "Luke"
  }
}
```

Sometimes though it's convenient to build a Json string or write it to a BufferedSink. It's possible but a bit awkward right now because it's only possible using the `_TestBuilder` classes. This issue is to investigate nicer APIs around this.

**Comment by BoD** [comment]
Test builders have been deprecated in favor of Data builders, closing for now.
