### ISSUE TITLE
v3 migration behavior difference

### ISSUE THREAD

**Issue by fmatosqg** [apollographql/apollo-kotlin#3859]
given a schema such as 

```

type Query {
    hello: String

    migrationDefaultQuery: MigrationDefaultType
}

type MigrationDefaultType {
    firstField:String
    default:String
}
```

and a query such as 
```
query Bug{
    migrationDefaultQuery {
        firstField
        default
    }
}

```

We have a difference in generated classes comparing apollo v2 vs v3

v3 with `codegenModels.set("compat")`
`app/build/generated/source/apollo/sse_poc/au/com/woolworths/example/graphqlsse/ssepoc/BugQuery.kt`
```

  public data class MigrationDefaultQuery(
    public val firstField: String?,
    public val default: String?
  )
```

v2:
```

  data class MigrationDefaultQuery(
    val __typename: String = "MigrationDefaultType",
    val firstField: String?,
    val default_: String?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller.invoke { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@MigrationDefaultQuery.__typename)
      writer.writeString(RESPONSE_FIELDS[1], this@MigrationDefaultQuery.firstField)
      writer.writeString(RESPONSE_FIELDS[2], this@MigrationDefaultQuery.default_)
    }

```

Apparently skipping `codegenModels.set("compat")` does not change behavior

======

Such difference may seem minor at first glance, but since we use kapt to inspect apollo generated classes, there seems to exist some special treatment by the kotlin language itself if there's a data class with a field called `default`. I expect to get more details on bytecode surprises soon.

**Comment by martinbonnin** [comment]
Good catch. `default` is a [reserved word in Java](https://en.wikipedia.org/wiki/List_of_Java_keywords) but not in Kotlin. The escaping in v3 is done for Kotlin reserved words only but you're right that might confuse `kapt`. 

`kapt` in general has multiple issues so if you can I'd recommend trying to move to [ksp](https://github.com/google/ksp) instead but I understand this might not always possible.

For the cases where it's not possible, we could add a `escapeJavaKeyWords` option, maybe even detect `kapt` automatically in the Gradle plugin and set the option accordingly.

**Comment by martinbonnin** [comment]
Also, as a quick workaround, you can use aliases: 

```graphql
query Bug{
    migrationDefaultQuery {
        firstField
        # default is reserved in Java but Apollo does not escape it in Kotlin models
        # This makes kapt unhappy so escape it here
        default_: default
    }
}
```

**Comment by fmatosqg** [comment]
the alias seems to be the cleaner and faster solution :)  apparently I ran into 2 quirks, one on apollo code generation side (already dealt with in my code) but with the upgrade it seemed to be about kapt/bytecode for java/kotlin details.
