### ISSUE TITLE
add ability to to trust self signed certificate for schema download task

### ISSUE THREAD

**Issue by kdk96** [apollographql/apollo-kotlin#3863]
**Use case**
Our private backend has self signed certificate, so `downloadApolloSchema` task fails with something like that
```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: 
    sun.security.provider.certpath.SunCertPathBuilderException:
    unable to find valid certification path to requested target
```

**Describe the solution you'd like**
As a solution I wrote custom gradle plugin, which uses typical [unsafe okhttp client](https://stackoverflow.com/a/25992879) [here](https://github.com/apollographql/apollo-kotlin/blob/main/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/internal/SchemaHelper.kt#L17).
Is it possible to add some flag for plugin, which will be used to set unsafe sslSocketFactory?

**Comment by martinbonnin** [comment]
We could add a `--insecure` command line parameter, like [curl has](https://curl.se/docs/manpage.html#-k). Do you want to open a pull request?

**Comment by kdk96** [comment]
I'll try to implement
