### ISSUE TITLE
Kotlin Native IncorrectDeferenceException when calling 3.x apollo on a background thread.

### ISSUE THREAD

**Issue by enyciaa** [apollographql/apollo-kotlin#3869]
**Summary**
Kotlin Native IncorrectDeferenceException when calling 3.x apollo on a background thread.

**Version**
3.1.0

**Description**
In 3.x+ this code will crash with the error message `Uncaught Kotlin exception: kotlin.Throwable: The process was terminated due to the unhandled exception thrown in the coroutine [StandaloneCoroutine{Cancelling}@83a05a48, MainDispatcher]: Non-main native call`
```
val query = AnyQuery()
return flowOf(1)
    .map { myApolloClient.query(query).execute() }
    .flowOn(Dispatchers.Default)
```

----------------------------------------------------------------------

This code will crash with the error message `Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: illegal attempt to access non-shared <object>@8239c448 from other thread`

IncorrectDereferenceExceptions are incredibly difficult to track down in large projects, so maybe this could throw a `Non-main native call` exception like the previous code sample?
```
val query = AnyQuery()
return myApolloClient.query(query).toFlow()
    .flowOn(Dispatchers.Default)
```

----------------------------------------------------------------------

Switching the flowOn dispatcher to Main in either case will make everything work as intended 👌  - example below
```
val query = AnyQuery()
return myApolloClient.query(query).toFlow()
    .flowOn(Dispatchers.Main)
```

----------------------------------------------------------------------

Other info which may of may be useful?
- No exceptions were thrown when triggering apollo calls on a background thread in versions pre-3.x
- The clients created on the main thread
- We're using native-mt coroutines
- This maybe relates to #2916

**Comment by enyciaa** [comment]
I'm mostly opening this is a reference if anyone runs into similar issues, as the problem will probably go away as soon as the new memory model becomes stable in Kotlin Native. 

If there is a simple fix to avoid IncorrectDeferenceExceptions that could potentially be quite handy though 👌

**Comment by martinbonnin** [comment]
Indeed, there is a requirement that requests execute on the `Main` dispatcher on native. That doesn't mean that the request is going to block the main thread. Both cache and network delegate to a worker thread so it is fine to call `execute()` from the main thread.

The tldr; of why there is such a limitation is that for a while we didn't want to force the `native-mt` version of coroutines on users and that workers need a "known" thread to give control back to. You can read more about it [there](https://github.com/apollographql/apollo-kotlin/blob/main/design-docs/Threading.md).

This will change with the new memory model but until it is there, you can call `execute()` from the main thread. Let us know if there are strong reasons not to do so but we haven't found any so far.

All that being said, we could make the error message better. I'll look into this.

**Comment by enyciaa** [comment]
> This will change with the new memory model but until it is there, you can call execute() from the main thread. Let us know if there are strong reasons not to do so but we haven't found any so far.

No strong reasons, it just means we need to do a bit of thread switching in our api layer, so it's a tad bug prone as these errors only show at runtime on iOS. 

Once the new memory model is stable, will apollo need an update before removing the main thread restriction on native?

**Comment by martinbonnin** [comment]
Gotcha 👍 . For the record, on Android `execute()` is meant to be called from the main thread too. It will dispatch internally so you could in theory use the same kind of threading model for both iOS and Android and leave ApolloClient offload cache/network work to other threads.

> Once the new memory model is stable, will apollo need an update before removing the main thread restriction on native?

Yes, most likely. Certainly not a huge update but removing the assert comes to mind. Maybe a few other small things.

**Comment by martinbonnin** [comment]
Closing this one in favor of https://github.com/apollographql/apollo-kotlin/issues/4100
