### ISSUE TITLE
Apollo-V3 mutation default cache policy

### ISSUE THREAD

**Issue by akshay253101** [apollographql/apollo-kotlin#3872]
**Summary**
After migrating to apollo-v3, mutation with same request body are cached by default, which can lead to 
1.  A user cant send same msg multiple times.
2. If a server has return the error then the mutation response is cached and user will always face the same error until cache is cleared or expired.

````val policy = request.headers.valueOf(CACHE_FETCH_POLICY_HEADER) ?: CACHE_FIRST ````

Here we are using default cache policy as CACHE_FIRST in CachingHttpInterceptor, is there any reason to fallback on CACHE_FIRST instead of NETWORK_ONLY
 
For now we have fixed this behaviour by manually setting cache policy on each mutation to NETWORK_ONLY

**Version**
3.0.0

**Description**
Execute mutation with same request body.

**Comment by martinbonnin** [comment]
Yikes, thanks for the heads ups! Fix is there: https://github.com/apollographql/apollo-kotlin/pull/3873
