### ISSUE TITLE
More compatibility between v2 and v3

### ISSUE THREAD

**Issue by fmatosqg** [apollographql/apollo-kotlin#3877]
**Use case**
We need more compatibility in the classes generated from queries and mutations between apollo v2 and v3.

**Describe the solution you'd like**
Gradle settings that allows for generating 100% same bytecode. Specifically when it comes to `__typename`

**Generated code comparison between v2 and v3**
Using Apollo v3.1.

We rely on reflection to read and process apollo generated classes. As such, we've run into a couple of differences that break lots of things in the most legacy par  ts of our app. One that caught our attention earlier was the difference in `__typename`, which we rely heavily. While we do use the `useVersion2Compat()` which implies `codegenModels.set("compat")`, it's not compatible enough for our needs.

Also probably a clarification would help, does `codegenModels` apply only to schema or also to queries/mutations/subscriptions? If so, is it possible to use different values for  `codegenModel`  on different gradle modules?

**Sample code**
query 
```graphql
query compat {
    marketplace {
        header {
            title
        }
    }
}
```

v2 
```kotlin
  data class Data(
    val marketplace: Marketplace
  ) : Operation.Data {
. . .
  data class Marketplace(
    val __typename: String = "Marketplace",
    val header: Header?
  ) {
. . .

  data class Header(
    val __typename: String = "InfoSection",
    val title: String
  ) {
. . .
```

v3 generated code
```kotlin
. . .
  public data class Data(
    public val marketplace: Marketplace
  ) : Query.Data

  public data class Marketplace(
    public val header: Header?
  )

  public data class Header(
    public val title: String
  )

```

**Comment by martinbonnin** [comment]
Fair enough. I have a work in progress that is going to remove even more `__typenames`: https://github.com/apollographql/apollo-kotlin/pull/3777

I was wondering whether this required to be opt-in and it looks like it does. I can a third option for 2.x compat:

```kotlin
apollo {
  // 2.x
  addTypename.set("allFields")
  // 3.0.0
  addTypename.set("fieldsWithFragments")
  // 3.2.0
  addTypename.set("polymorphicFields")
}
```

>  does codegenModels apply only to schema or also to queries/mutations/subscriptions?

It applies only to queries/mutations/subscriptions (operations). "models" is what is under `Data` in operations. This is generated from operations, not from the schema.

> is it possible to use different values for codegenModel on different gradle modules?

* If they use different schemas, you can. 
* If it's a multi-module setup sharing a schema, it requires codegenModels to have the same value

**Comment by fmatosqg** [comment]
I can find `addTypename` related to other apollo libraries but nothing for apollo-kotlin. Just clarifying, is there anything we can do with the current stable/unstable versions?

**Comment by martinbonnin** [comment]
> Something I did try was adding __typename to a couple queries, but it's not quite the same result.

**Comment by martinbonnin** [comment]
> Something I did try was adding __typename to a couple queries, but it's not quite the same result. 

Indeed, that's the most you can do right now.

> In v2 we did get something like val __typename:String = "somevalue" but v3 gets only val __typename:String

This code was wrong in a lot of cases because it was using the interface name as "someValue" instead of a possible concrete type. When a model matches an interface, it's impossible to know at compile time what `__typename` is going to be.

> when we try to match constructors our reflection code doesn't know how to deal with that extra constructor parameter

Can you share more details as to why you need reflection there? I'd usually recommend using the [Test builders](https://www.apollographql.com/docs/kotlin/testing/test-builders/) as a more idiomatic/reflection free way to build data classes for tests

**Comment by fmatosqg** [comment]
>Can you share more details as to why you need reflection there? I'd usually recommend using the [Test builders](https://www.apollographql.com/docs/kotlin/testing/test-builders/) as a more idiomatic/reflection free way to build data classes for tests

Think of clean architecture, where we use one set of POJO (Apollo generated classes) for networking and another set for UI. We have a `converter.toUiModel<ApolloModel, UiModel>( apolloModel ) : UiModel` so to speak (not actual code, but I hope it give an idea of what it does).

We're moving away from it in favor of something more stable we do with kotlinPoet, but we still have a massive fragment that's proving hard to convert.

**Comment by martinbonnin** [comment]
I see. I've always had mixed feeling about this. On the one hand, having separate models feels safer. There's better separation of concerns. One can update the UI layer without touching the networking and vice versa. 
On the other hand, automating the mappers feels like it's adding the coupling back. If the UI models are created 1:1 from the network models, might as well use the network models?

**Comment by martinbonnin** [comment]
I'm going to close this one with `3.2.0` `addTypename` Gradle option. It's _very_ close to what 2.x is doing. The only difference is inline fragments containing other inline fragments:

```graphql
{
  animal {
    ... on Pet {
       # 2.x adds __typename here, "always" doesn't, it only adds at the root of the "animal" field
       ... on Cat {
         meoww
       }
    }
  }
}
```

But this feels close enough that we don't add and maintain another configuration option
