### ISSUE TITLE
Support for required arguments with default values

### ISSUE THREAD

**Issue by rev0lgenX** [apollographql/apollo-kotlin#3878]
**Question.**
The [Graphql Spec](https://github.com/graphql/graphql-spec/pull/418) seems to have support for replacing required value with the default value. I think it was supported in version 2 as well, but currently if I try to generate by replacing `query Media($includeAny:Boolean!)` with `query Media($includeAny:Boolean = true)`  it gives error `Variable includeAny of type Boolean used in position expecting type Boolean!`. Is this feature implemented or am I missing something? If it's missing is it possible to implement it?

**Comment by BoD** [comment]
Hi! Could it be that the field you're using the variable with expect a `Boolean!`? If yes, it should just be a matter of declaring your query like this: `query Media($includeAny: Boolean! = true)`

**Comment by rev0lgenX** [comment]
If I try to use it like that then the server gives `Variable \"$includeAny\" of type \"Boolean!\" is required and will not use the default value. Perhaps you meant to use type \"Boolean\".`. Its a third party server and I have no control over it, so I was wondering if it is standard(according to specs) to implement it like that in server side. I have like little to no idea about graphql-servers validation like it is according to specs or anything else. If its nothing like that then the issue could be closed or there could be support for query without ! sign for default values.

**Comment by martinbonnin** [comment]
This is a duplicate with https://github.com/apollographql/apollo-kotlin/issues/3227

The current workaround until we change the coercion rules is to set the default value in Kotlin
