### ISSUE TITLE
Apollo Interceptor Migration from v2 to v3

### ISSUE THREAD

**Issue by Canato** [apollographql/apollo-kotlin#3899]
Hey people, good day! 

First for of all, thanks for the repository, the new version and the beauty and useful documentation we have! 🚀 

**Question.**
I'm having troubles when migrating from `v2` to `v3` (Android Kotlin) and I'm almost sure this is because I'm not finding the right information and/or the new way of doing it. 

On `v2` we us to have a `ApolloInterceptor` for authentication, this interceptor would be responsible to add a `HEADER` with our user `token` and deal with errors on the network. 

The first part was a piece of cake [like the documentation suggests](https://www.apollographql.com/docs/kotlin/tutorial/10-authenticate-your-queries/#add-the-interceptor) but I'm missing the second part.

- How can I _(or how is expected to be done/best practice for this lib)_ intercept a `response` to check any `UNAUTHENTICATED` or `INSUFFICIENT_TOKEN_GRANT_TYPE` code return from my server? Check an `error`.

Before I used to override `override fun onResponse(response: ApolloInterceptor.InterceptorResponse) { ... }` from `ApolloInterceptor.CallBack` and could refresh my user token automatically,

There is a way we can achieve this using `ApolloInterceptor`? 

What I got so far:
```kt
class AuthInterceptor(private val tokenUseCase: TokenUseCase) : ApolloInterceptor {

    override fun <D : Operation.Data> intercept(
        request: ApolloRequest<D>,
        chain: ApolloInterceptorChain
    ): Flow<ApolloResponse<D>> {
        val token = tokenUseCase.fetchToken().blockingGet().tokenResponse
        val response = chain.proceed(
            request
                .newBuilder()
                .addHttpHeader("Authorization", "Bearer $token")
                .build()
        )

        if (response.hasAuthenticationError()) {
            // Refresh code
            // ...
        } else {
            // Be happy code
            return response
        }
    }
}

private fun <D : Operation.Data> Flow<ApolloResponse<D>>.hasAuthenticationError(): Boolean =
    hasErrorCode("UNAUTHENTICATED")

private fun <D : Operation.Data> Flow<ApolloResponse<D>>.hasErrorCode(code: String): Boolean =
    this.collectLatest { response ->
        response.errors
            ?.any { error ->
                error.nonStandardFields.orEmpty().containsValue(code)
            }
    }
```

But of course this is not working because of the lack of coroutine/suspend function.
How do you guys expected this to be done? Maybe I over complicated!

Thanks!

**Comment by BoD** [comment]
Hi! 👋 

I think the trick is to use Flow operators, for instance, something like this:

```kotlin
class AuthInterceptor(private val tokenUseCase: TokenUseCase) : ApolloInterceptor {
  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    val token = tokenUseCase.fetchToken().blockingGet().tokenResponse
    return chain.proceed(request
        .newBuilder()
        .addHttpHeader("Authorization", "Bearer $token")
        .build()
    ).flatMapConcat { response ->
      if (response.hasAuthenticationError()) {
        // Refresh token
        val newToken = "newToken"

        // Now try again with the new token
        chain.proceed(request
            .newBuilder()
            .addHttpHeader("Authorization", "Bearer $newToken")
            .build()
        )
      } else {
         // Be happy code
        flowOf(response)
      }
    }
  }
}

private fun <D : Operation.Data> ApolloResponse<D>.hasAuthenticationError(): Boolean =
    hasErrorCode("UNAUTHENTICATED")

private fun <D : Operation.Data> ApolloResponse<D>.hasErrorCode(code: String): Boolean =
    errors?.any { error ->
      error.nonStandardFields.orEmpty().containsValue(code)
    } ?: false
```

Unfortunately `flatMapConcat` has the `FlowPreview` annotation at the moment - so it's kind of a warning.

**Comment by Canato** [comment]
Work like a charm, Thanks!
