### ISSUE TITLE
MapTestNetworkTransport doesn't work with zero-arg queries

### ISSUE THREAD

**Issue by BenTilbrook** [apollographql/apollo-kotlin#3924]
**Summary**
`MapTestNetworkTransport` doesn't work with zero-arg queries. This seems to be because the generated code is not a `data class`, unlike other queries/mutations, and therefore has no `equals/hashCode`, which is required by `MapTestNetworkTransport` because it uses the `Operation` as a `Map` key.

**Version**
Apollo Kotlin version: `3.1.0`

**Description**
See attached modified tutorial project. Run `./gradlew testDebugUnitTest`. It will fail.

[apollo-android-tutorial-map-transport-bug.zip](https://github.com/apollographql/apollo-kotlin/files/8249612/apollo-android-tutorial-map-transport-bug.zip)

**Comment by martinbonnin** [comment]
In all cases, I think it makes sense to make the operations data classes always, it keeps everything consistent and predictable.

**Comment by BoD** [comment]
> I'm wondering if we could use the Operation's id instead

Actually that wouldn't be enough as we need to distinguish same operation with different parameters. 

> it makes sense to make the operations data classes always

But `Data class must have at least one primary constructor parameter` 😅

**Comment by BenTilbrook** [comment]
Could make a zero arg operation an object. It's singleton status would make it a suitable map key.

**Comment by martinbonnin** [comment]
> But Data class must have at least one primary constructor parameter

Right!

> Could make a zero arg operation an object. It's singleton status would make it a suitable map key.

True but that'd make callsites less consistent... It'd be very weird for newcomers to have to instantiate some operations but not others.

**Comment by martinbonnin** [comment]
> Actually that wouldn't be enough as we need to distinguish same operation with different parameters.

What about we implement `hashCode/equals` with `operation.id` for operations without variables? (and leave the other as regular data classes)

**Comment by BoD** [comment]
> What about we implement hashCode/equals with operation.id for operations without variables? (and leave the other as regular data classes)

Good idea! 👍 I'll have a look!

> Or just based on the instance so that it works for Fragments too that don't have an id?

That's equivalent to the default equals/hashcode, right?

**Comment by martinbonnin** [comment]
> That's equivalent to the default equals/hashcode, right?

Sorry, I meant based on the **class**, not instance 🤦

**Comment by BoD** [comment]
> based on the class, not instance
> 2 operations with the same class and no variables should be equal?

Ooh yeah, makes sense!

**Comment by martinbonnin** [comment]
Closed in `3.2.0`
