### ISSUE TITLE
Is RxJava still supported with version >= 3.0.0?

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#3933]
I'm looking at the error documentation and would like to use `dataAssertNoErrors` but realised that the example uses Coroutines. I then noticed in the commits that it seems that a bunch of RxJava files have been slapped with a "deprecated since v3.0.0" annotation. If we upgrade to the latest version of apollo for Android (versions 3.0.0 and up), are we still able to use RxJava or are we forced to use Coroutines?

**Comment by BoD** [comment]
Hi 👋 

RxJava support is still present in v3 - the doc is [here](https://www.apollographql.com/docs/kotlin/advanced/rxjava).

**Comment by alvindizon** [comment]
Hi @BoD , thanks for answering! Thank you for linking to that document, but is there an RxJava equivalent for dataAssertNoErrors?

**Comment by BoD** [comment]
The Rx adapter return a `Single<ApolloResponse>` and `dataAssertNoErrors` is on `ApolloResponse`. So you would need to subscribe to the single and use the response, something like this:

```java
ApolloCall<MyQuery.Data> queryCall = client.query(new MyQuery());
Single<ApolloResponse<MyQuery.Data>> queryResponse = Rx3Apollo.single(queryCall);
queryResponse.subscribe(
            response -> {
              response.dataAssertNoErrors()
            },
            throwable -> {
              // Handle throwable
            }
);
```

**Comment by alvindizon** [comment]
Thank you @BoD! I shall now close this ticket
