### ISSUE TITLE
NetworkFirst wrong exception thrown

### ISSUE THREAD

**Issue by akshay253101** [apollographql/apollo-kotlin#3955]
**Summary**
While using cache policy NetworkFirst instead of network failure reason, Cache Miss : no snapshot is thrown
**Version**
v3.0.0

**Description**
In NetwokFirst cache policy networkMightThrow is wrapped in try/catch which in case of a very first network call failed due to 300..500 error code will result in bloating firebase with wrong stack trace by provide HttpCacheMissException. 
````
CACHE_FIRST -> {
        try {
          return cacheMightThrow(request, cacheKey)
        } catch (e: ApolloException) {
          //
        }

        return networkMightThrow(request, chain, cacheKey)
      }
      CACHE_ONLY -> {
        return cacheMightThrow(request, cacheKey)
      }
      NETWORK_ONLY -> {
        return networkMightThrow(request, chain, cacheKey)
      }
      NETWORK_FIRST -> {
        try {
          val response = networkMightThrow(request, chain, cacheKey)
          if (response.statusCode in 200..299) {
            //  let HTTP errors through
            return response
          }
        } catch (e: ApolloException) {

        }

        return cacheMightThrow(request, cacheKey)
      }
````
Can we re throw the network error in case of there is no cache

**Comment by martinbonnin** [comment]
Hi 👋 . Thanks for sending this. Can you try with version `3.1.0`? There have been some important changes to the cache interceptors. Not 100% sure it's related but it's worth checking out.

**Comment by akshay253101** [comment]
Hi martin, in v3.1.0 also while configuring persistent LRU httpCache using 
````
fun ApolloClient.Builder.httpCache(
    directory: File,
    maxSize: Long,
): ApolloClient.Builder {

  return addHttpInterceptor(
      CachingHttpInterceptor(
          directory = directory,
          maxSize = maxSize,
      )
  )
````
Which adds CachingHttpInterceptor and results in same issue.

**Comment by martinbonnin** [comment]
Thanks for double checking this 🙏 .

We could return an `ApolloCompositeException` if you're using `NETWORK_FIRST` and you get both a cache and a network error:

```kotlin
        var networkException: ApolloException? = null
        try {
          val response = networkMightThrow(request, chain, cacheKey)
          if (response.statusCode in 200..299) {
            //  let HTTP errors through
            return response
          }
        } catch (e: ApolloException) {
          networkException = e
        }

        try {
          return cacheMightThrow(request, cacheKey)
        } catch (e: ApolloException) {
          throw ApolloCompositeException(networkException, e)
        }
```

This way you would get access to the networkException through `ApolloCompositeException.first`. But I don't think it'll change anything to your Firebase errors since it will still throw?

**Comment by akshay253101** [comment]
Correct, but by this we can check what was the actual failure for API which was masked by HttpCacheMissException

**Comment by martinbonnin** [comment]
Gotcha 👍 . Do you want to open a pull request?

**Comment by akshay253101** [comment]
sure

**Comment by akshay253101** [comment]
PR raised - https://github.com/apollographql/apollo-kotlin/pull/3957
