### ISSUE TITLE
[Brainstorming] customize generated Kotlin models

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3958]
One of the things that can be achieved with Json parsers like Moshi is writing [custom adapters](https://github.com/square/moshi#custom-type-adapters) to map some types to the non-default ones.

This issue is to investigate adding the same kind of things for the generated models. Because there is a schema and models do not map the schema types directly but the requests fields in the query it's more difficult to do so but something might be done for simple case like for an example typesafe ids.

Let's say you have a kotlin class for a user id

```kotlin
// A small wrapper to make sure we don't pass a wrong id to a function expecting a user id
data class UserId(val id: String)
```

We could allow through schema extensions to override the type of `User.id` in the schema:

```graphql
# extra.graphqls
extend type User {
  # this is not valid GraphQL but we could support it (or find another way using directives maybe)
  id: UserId
}

scalar UserId
```

Then mapping userIds could be done like any other custom scalars. Looks like that could help for simple cases. Compound types are going to be more complicated to handled at first sight but might also benefit from something like this.

**Comment by BoD** [comment]
This can be achieved by changing in the schema the type of a field to a custom scalar, and write an adapter for it. But touching the schema on the client side is not ideal, as changes can be overridden when fetching the latest schema. This can be mitigated by a Gradle task that manipulates the schema automatically before the codegen is invoked.

**Comment by martinbonnin** [comment]
@sampengilly the "schemaTransformation" Gradle task could generate an additional artifact containing the type remapping. 

For an example, if we're saying we want to introduce a custom scalar for product ids called `ProductID`, the Gradle task could generate the mapping:

```json
{
  "Product.id": {
    "from": "ID!"
    "to": "ProductID"
  }
}
```

This same mapping could be used in subsequent runs of the task to ensure that the initial schema type hasn't changed and the transformation is still valid. 

Hope this helps?
