### ISSUE TITLE
[Cache] Expose global hook for cache write errors

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3963]
Although very unlikely, there can be rare occurrences where a cache write fails. Especially when using SQLite, there can be errors writing to persistent storage or anything else. Because writing to the cache can be asynchronous, we can't expose these errors to the caller. 

When this happens, we currently crash with an uncaught exception which is not ideal. 

Instead, we could add a static `ApolloCacheInterceptor.errorHandler: (Throwable) -> Unit` so that these errors can be logged for diagnostics purposes. We could also make it log to "stdout" by default.

**Comment by BoD** [comment]
In  #3989 we went with a globally usable `ApolloExceptionHandler` (marked experimental for the time being).
