### ISSUE TITLE
Do not crash if the previous record cannot be parsed

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3964]
The sqlite cache `merge` first reads the existing record before overwriting it. This is done so that we can compare by value and only publish cache keys that have really changed (and avoid triggering all watchers all the time).

When the initial read fails because of an IO error or because the data was corrupted, the app currently crashes while it's technically ok to continue and just publish all the cache keys.

This issue is to catch this error and try to recover.

**Comment by BoD** [comment]
Done in  #3989.
