### ISSUE TITLE
Getting the request URL from the ApolloHttpException in version 3

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#3996]
Before version 3, in the event of `ApolloHttpException`, we used to be able to obtain the request URL via `ApolloHttpException`'s `rawResponse`: `rawResponse()?.request?.url`. Is it possible to obtain the request URL with the latest version of Apollo? The new ApolloHttpException contains the body with type `BufferedSource` but I'm not sure if it contains the URL we need.

**Comment by BoD** [comment]
Hi! 👋 

You are right that the URL is not currently available in `ApolloHttpException`. Can you tell us a bit more about your use-case? I am guessing you have several services, otherwise the URL would always be the same, right?

**Comment by alvindizon** [comment]
Hi @BoD , we have two different endpoints corresponding to two different schemas--the old one is still used in one module but most of the project uses the new schema. I'm guessing this is the reason why we include the request URL so that we can distinguish between them. If we only had one endpoint we can happily drop the logging of the request URL

**Comment by BoD** [comment]
I see, thanks!

We could add a `requestUrl` field there. It would probably make sense to add it also to`ApolloNetworkException`. Do you fancy opening a PR?

**Comment by martinbonnin** [comment]
> It would probably make sense to add it also toApolloNetworkException

I'd keep it `ApolloHttpException` for now. We can always add it later in `ApolloNetworkException` if needed but there might be cases where `ApolloNetworkException` is thrown but the definition of `url` is unclear. For an example test network transport, or for other transports than HTTP.

**Comment by alvindizon** [comment]
@BoD thanks I'll try to make a PR for it

**Comment by alvindizon** [comment]
Hi @BoD  @martinbonnin we had a discussion with our team about our specific usecase and it turns out we might be okay with not logging the URL at all. Our team will have another discussion about this next week and I'll update/make a PR depending on the discussion's outcome. Thanks

**Comment by martinbonnin** [comment]
Hi @alvindizon how did the discussion go? Anything more required here?

**Comment by alvindizon** [comment]
Hi @martinbonnin @BoD  , I will be closing this issue for now. Thanks for all your support.
