### ISSUE TITLE
Multiple "Redeclaration" errors when migrating project that has two schemas to version 3

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#3998]
Our existing multimodule project has a separate `apollo.gradle` file that looks like this:
```
apply plugin: 'com.apollographql.apollo'

dependencies {

    ...
}

apollo {
    generateKotlinModels.set(true)

    service("v1") {
        sourceFolder = "v1"
        rootPackageName.set("v1")
    }

    service("v2") {
        sourceFolder = "v2"
        rootPackageName.set("v2")
    }
}
```

This file is applied to other `build.gradle` files. The schemas are in their own module, together with the .graphql files. The following describes our file structure:
For V1:
- the schema JSON file is located at `myproj/featuremodule/src/main/graphql/v1`
- the graphql files are located at `myproj/featuremodule/src/main/graphql/v1/com/mycompany/myproj/featuremodule/graphql/`

The V2 follows the same format:
- the schema JSON file is located at `myproj/featuremodule/src/main/graphql/v2`
- the graphql files are located at `myproj/featuremodule/src/main/graphql/v2/com/mycompany/myproj/featuremodule/graphql/`

For v3, I've set up the gradle file in this way:

```
apollo {
    service("v1") {
        srcDir("src/main/graphql/v1/")
        packageName.set("com.mycompany.myproj.featuremodule.graphql")
    }
    service("v2") {
        srcDir("src/main/graphql/v2/")
        packageName.set("com.mycompany.myproj.featuremodule.graphql")
    }
}
```

When I started building the project, redeclaration errors popped up--the errors seem point to generated classes that have the same names but in different folders, one for v1 and v2. How do we resolve this? Also, I'd like to know if my gradle setup is correct? There's no direct equivalent in the documentation for doing this two schema setup in v3.

**Comment by BoD** [comment]
It's also worth mentioning that if you're looking for an equivalent of `rootPackageName`, it is now `packageNamesFromFilePaths(<root package>)`.

**Comment by alvindizon** [comment]
Hi @BoD , I thought that `v1` /`v2` would be appended to the package name so that there would be no conflicts, but it turns out I was wrong. Using `packageNamesFromFilePaths(v1)` and `packageNamesFromFilePaths(v2)` worked. Thanks!
