### ISSUE TITLE
Add adapter for OffsetDateTime

### ISSUE THREAD

**Issue by benedict-lim** [apollographql/apollo-kotlin#4000]
**Use case**
I understand that there is already a collection of datetime-related adapters available in the `apollo-adapters` artifact.

However, as `java.time.Instant` is not timezone-aware and requires timezone information separately to retrieve the date and time correctly, I have decided to convert incoming server data of type `ISO8601DateTime` to `java.time.OffsetDateTime` instead.

[graphql-ruby documentation](https://graphql-ruby.org/api-doc/1.8.7/GraphQL/Types/ISO8601DateTime.html)
[w3c definition](https://www.w3.org/TR/NOTE-datetime)

**Describe the solution you'd like**
I have implemented the custom adapter in my project.

```
val offsetDateTimeAdapter = object : Adapter<OffsetDateTime> {
    override fun fromJson(
        reader: JsonReader,
        customScalarAdapters: CustomScalarAdapters
    ): OffsetDateTime {
        return OffsetDateTime.parse(reader.nextString())
    }

    override fun toJson(
        writer: JsonWriter,
        customScalarAdapters: CustomScalarAdapters,
        value: OffsetDateTime
    ) {
        writer.value(value.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME))
    }
}
```

If you are willing, I am able to contribute the same code (plus tests if possible) to the repository.

If there is not much demand to warrant such a change, I understand and I am perfectly fine declaring custom adapters in my project.

Thanks in advance for the consideration!

**Comment by martinbonnin** [comment]
Hi 👋 Thanks a lot for opening this! Interestingly there's been [a lot](https://github.com/apollographql/apollo-kotlin/pull/3997) of [focus](https://github.com/apollographql/apollo-kotlin/pull/3999) on this part recently.

I was actually wondering if `OffsetDateTime` was required yesterday :). Looks like the answer is yes! A pull request is very welcome!

Out of curiosity, what do you use the offset for in the client? I just realised yesterday that `offset` != `time zone`. While the offset is always fixed, the time zone rules may change according to local regulations and I _think_ ISO8601 cannot represent a `time zone` accurately, only an `offset`? So if you need a real "time zone", maybe you need something even different?

**Comment by benedict-lim** [comment]
Thanks for the reply!

Actually, that was my colleague. 😆 He alerted me to not use the `LocalDateAdapter` as it is due to possible formatting issues. He encouraged me to contribute the adapter I made for `OffsetDateTime`, so here I am.

To be honest, our product is only serving one country thus one timezone at the moment, so we do not actually utilize the offset/timezone information. We just want to make sure to handle it appropriately from the start, so that it will be much easier to ship the product to other countries when the need arises.

Having said that, I don't think I would need the timezone information, but the offset information should come in handy. (Sorry for the confusion as I was loosely throwing the term 'timezone' around just to mean different times for different countries)
Our product tracks monetary transactions, so as long as the time of transaction is correctly interpreted, I think that should suffice. (in future if we do launch the product in other countries)

I shall submit a pull request when time permits! If you decide to take over, do let me know. Thanks 👍

**Comment by martinbonnin** [comment]
Thanks for the context!
