### ISSUE TITLE
How to mock HTTP responses with RxJava in version 3?

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#4005]
Our project uses RxJava3 and with version 2, our JUnit5 tests have used  a combination of `MockWebServer` and ApolloClient's `dispatcher`, which accepted an `Executor`, in order to test our repositories that make calls using GraphQL. The code we use looks like this:

```kotlin
fun apolloClient(
        serverUrl: HttpUrl,
        okHttpClient: OkHttpClient = apolloOkHttpClient(),
    ): ApolloClient = ApolloClient.builder()
        .dispatcher(immediateExecutor())
        .serverUrl(serverUrl)
        .okHttpClient(okHttpClient)
        .build()

    private fun apolloOkHttpClient() = OkHttpClient.Builder()
        .dispatcher(Dispatcher(immediateExecutorService()))
        .build()

    private fun immediateExecutorService(): ExecutorService {
        return object : AbstractExecutorService() {
            override fun shutdown() = Unit

            override fun shutdownNow(): List<Runnable>? = null

            override fun isShutdown(): Boolean = false

            override fun isTerminated(): Boolean = false

            @Throws(InterruptedException::class)
            override fun awaitTermination(l: Long, timeUnit: TimeUnit): Boolean = false

            override fun execute(runnable: Runnable) = runnable.run()
        }
    }

    private fun immediateExecutor(): Executor = Executor { command -> command.run() }
```

Then in our unit tests, we create a `MockWebServer` and enqueue a mock JSON response from a file, something like this:

```kotlin
    @BeforeEach
    fun setup() {
       server = MockWebServer().apply {
            start()
        }

        apolloClient = Util.apolloClient(server.url("/"))

        repo = SomeRepoImpl(apolloClient)
    }

    @Test
    fun `some test`() {
        val body = Util.getResponseFromJson("SomeResponse.json")
        server.enqueue(MockResponse().setBody(body).setResponseCode(200)) // MockResponse here is from okhttp
       // test() comes from RxJava3
       // fetchSomething returns an Rx Observable
        repo.fetchSomething().test().apply {
            assertNoErrors()
        }
    }
```

This has worked fine with v2, but v3 now uses coroutines and we've hit some problems with our unit tests. I've mentioned in a previous [issue](https://github.com/apollographql/apollo-kotlin/issues/3940) about the replacement for `ApolloClient.builder`'s dispatcher, and unfortunately both solutions (using `Dispatchers.Unconfined` and `asCoroutineDispatcher`) did not work as we got the following error: `No values (latch = 1, values = 0, errors = 0, completions = 0)
java.lang.AssertionError: No values (latch = 1, values = 0, errors = 0, completions = 0)`

We also tried doing the official method for mocking HTTP responses [here](https://www.apollographql.com/docs/kotlin/testing/mocking-http-responses)--and code for setting up/tearing down our test Apollo Client have to be wrapped with `runTest` (we had to import `kotlinx-coroutines-test` dependency for this):

```kotlin
    fun setup() {
        ...
        server = MockServer()

        runTest {
            apolloClient = Util.apolloClient(server.url())
        }
       ...
    }

    @AfterEach
    fun tearDown() {
        runTest {
            server.stop()
        }
    }
```

But this did not work too-- we received `No values (latch = 1, values = 0, errors = 0, completions = 0)
java.lang.AssertionError: No values (latch = 1, values = 0, errors = 0, completions = 0)` errors. Any advice about how we can move forward with this or are we doing something wrong with our setup? (we can't migrate the whole codebase to Coroutines immediately BTW).

Thanks

**Comment by alvindizon** [comment]
This has been fixed (mostly), the solution to make most of the unit tests to work was to add a JUnit5 extension to our tests:

```kotlin
import io.reactivex.rxjava3.android.plugins.RxAndroidPlugins
import io.reactivex.rxjava3.plugins.RxJavaPlugins
import io.reactivex.rxjava3.schedulers.Schedulers
import org.junit.jupiter.api.extension.AfterTestExecutionCallback
import org.junit.jupiter.api.extension.BeforeTestExecutionCallback
import org.junit.jupiter.api.extension.ExtensionContext

class RxSchedulerExtension : BeforeTestExecutionCallback, AfterTestExecutionCallback {

    override fun beforeTestExecution(context: ExtensionContext?) {
        RxAndroidPlugins.setInitMainThreadSchedulerHandler { Schedulers.trampoline() }
        RxJavaPlugins.setIoSchedulerHandler { Schedulers.trampoline() }
        RxJavaPlugins.setComputationSchedulerHandler { Schedulers.trampoline() }
        RxJavaPlugins.setNewThreadSchedulerHandler { Schedulers.trampoline() }
        RxAndroidPlugins.setMainThreadSchedulerHandler { Schedulers.trampoline() }
    }

    override fun afterTestExecution(context: ExtensionContext?) {
        RxJavaPlugins.reset()
        RxAndroidPlugins.reset()
    }
}
```

We use this extension in this manner:

```kotlin
@ExtendWith(RxSchedulerExtension::class)
class SomeTest {
```

Our Apollo client that's used in unit tests make use of `requestedDispatcher` together with an Executor turned dispatcher via asCoroutineDispatcher:

```kotlin
val apolloClient = ApolloClient.Builder()
        .serverUrl(serverUrl)
        .requestedDispatcher(immediateExecutor().asCoroutineDispatcher())\
        .build()

private fun immediateExecutor(): Executor = Executor { command -> command.run() }
```

Using `Dispatchers.Unconfined` with requestedDispatcher worked as well.

**Comment by BoD** [comment]
Thanks a lot for the update! That's good info to know - and glad that worked out.
