### ISSUE TITLE
[3.x] Mutation is executed with GET (HTTP Method)  when using ApolloClient.Builder.autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Get)

### ISSUE THREAD

**Issue by omtians9425** [apollographql/apollo-kotlin#4006]
**Summary**
 When we used the previous version of Apollo (2.x), this problem didn't occur. 
 In 2.x, mutation was executed with POST, and query was executed with GET with below code
```kt
ApolloClient.builder()
        .enableAutoPersistedQueries(true)
        .useHttpGetMethodForPersistedQueries(true)
        ...
```

But now in 3.x, mutation was executed with GET, and also query was executed with GET with below code
```kt
ApolloClient.Builder()
        .autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Get)
        ...
```

**Version**
3.1.0

**Description**
Below code is okay (though both query and mutation are executed with POST)
```kt
ApolloClient.Builder()
        .autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Post)
        ...
```

But we want to use with GET method for using HTTP cache

**Comment by BoD** [comment]
Hi! 👋  Thanks for reporting this!

It looks like the Auto Persisted Queries interceptor in v3 doesn't distinguish queries vs mutations and will always use the method you configure, although it is not a good idea to use POST for mutations, as they could use the cache which is never wanted. In v2 the distinction was correctly made.

We'll make a fix for this!

In the meantime, you can manually override the method to always be POST for mutations, with an interceptor, like this:

```kotlin
ApolloClient.builder()
    .autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Get, httpMethodForDocumentQueries = HttpMethod.Get)
    .addInterceptor(object : ApolloInterceptor {
        override fun <D : Operation.Data> intercept(
            request: ApolloRequest<D>,
            chain: ApolloInterceptorChain,
        ): Flow<ApolloResponse<D>> {
            val newRequest = if (request.operation is Mutation) {
                // For mutations, we always want a POST to avoid it being cached
                request.newBuilder().httpMethod(HttpMethod.Post).build()
            } else {
                request
            }
            return chain.proceed(newRequest)
        }
    })
```

**Comment by omtians9425** [comment]
Thank you for a solution and quick fix 🎉

**Comment by martinbonnin** [comment]
This is now in 3.2.2
