### ISSUE TITLE
Built-in BigDecimal adapter not working?

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#4013]
We have a custom scalar type called `Decimal` and in v2, we use a CustomTypeAdapter for it:

```kotlin
class DecimalAdapter : CustomTypeAdapter<BigDecimal> {
    override fun encode(value: BigDecimal): CustomTypeValue<*> =
        CustomTypeValue.GraphQLString(value.toString())

    override fun decode(value: CustomTypeValue<*>): BigDecimal {
            if (value is CustomTypeValue.GraphQLString) {
                return BigDecimal(value.value)
            }

            throw IllegalArgumentException()
    }
}
```

We register this at runtime via ApolloClient builder:
```kotlin
    @Provides
    @Singleton
    fun provideApolloClient(
        okHttpClient: OkHttpClient,
        cacheFactory: LruNormalizedCacheFactory,
        serverUrl: String
    ) = ApolloClient.builder()
        .normalizedCache(cacheFactory)
        .serverUrl(serverUrl)
        .okHttpClient(okHttpClient)
        .addCustomTypeAdapter(v2.type.CustomType.DECIMAL, DecimalAdapter())
        .build()
```

In our code, casting variables with the said custom type to BigDecimal does not cause a crash and we obtain the correct BigDecimal value:

```kotlin
val sampleVal = sampleGraphQLFragment.amount as BigDecimal
```

However in v3, doing this causes a `ClassCastException: java.lang.String cannot be cast to java.math.BigDecimal` when using the built-in `BigDecimalAdapter`. We have registered our custom type to use the built-in `BigDecimalAdapter` like this:

```kotlin
    @Provides
    @Singleton
    fun provideApolloClient(
        okHttpClient: OkHttpClient,
        cacheFactory: MemoryCacheFactory,
        serverUrl: String
    ) = ApolloClient.builder()
        .normalizedCache(cacheFactory)
        .serverUrl(serverUrl)
        .okHttpClient(okHttpClient)
        .addCustomScalarAdapter(Decimal.type, BigDecimalAdapter)
        .build()
```

Looking at the generated code it looks like the built-in adapter should have been used:

```kotlin
public object SampleGraphQLFragmentImpl_ResponseAdapter {
  public object SampleGraphQLFragment :
      Adapter<v2.com.mycompany.myapp.feature1.graphql.fragment.SampleGraphQLFragment> {
    public val RESPONSE_NAMES: List<String> = listOf("title", "amount")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        v2.com.mycompany.myapp.feature1.graphql.fragment.SampleGraphQLFragment {
      var title: String? = null
      var amount: Any? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> title = StringAdapterfromJson(reader, customScalarAdapters)
          1 -> amount = AnyAdapter.fromJson(reader, customScalarAdapters)
        }
       }

      return v2.com.mycompany.myapp.feature1.graphql.fragment.SampleGraphQLFragment(
        title = title!!,
        amount = amount!!
      )
}
```

Any advice would be much appreciated. Thanks.

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for sending this ! 

Because BigDecimal is not part of the GraphQL spec and in order to keep `apollo-api` as small as possible, `apollo-api` doesn't know anything about BigDecimal in 3.x. This means you'll have to tell Gradle to map GraphQL "Decimal" to Kotlin "BigDecimal" during codegen:

```kotlin
apollo {
    mapScalar("Decimal", "com.apollographql.apollo3.adapter.BigDecimal")
}
```

If you want to avoid calling `addCustomScalarAdapter` and avoid a lookup at runtime, you can also define the adapter at runtime: 

```kotlin
  mapScalar(
      "Decimal",
      "com.apollographql.apollo3.adapter.BigDecimal",
      "com.apollographql.apollo3.adapter.BigDecimalAdapter"
  )
```

You can read more about scalar adapters [here](https://www.apollographql.com/docs/kotlin/essentials/custom-scalars). I'll also add a note to the migration guide to make this more explicit

**Comment by martinbonnin** [comment]
Updates to the migration guide there: https://github.com/apollographql/apollo-kotlin/pull/4014/files#diff-1d646979687b8af563a1c85084a20f5e039cfb53104ecc994e23a4f986258bdf

**Comment by alvindizon** [comment]
Hi @martinbonnin, thanks! Registering the adapter during compile time worked. I also had to do the same for other custom types for `Instant` and `Date` that have custom adapters. Closing this issue

**Comment by martinbonnin** [comment]
Thanks for the update!
