### ISSUE TITLE
Cannot resolve method 'okHttpClient' in 'Builder'

### ISSUE THREAD

**Issue by Mehonoshin** [apollographql/apollo-kotlin#4030]
**Question.**

Hey team :wave: 

I have a Java android app, and trying to use apollo-kotlin there.
Following the guide here https://www.apollographql.com/docs/kotlin/advanced/interceptors-http#reusing-okhttp-interceptors-on-jvm-only-projects I have the following code:

 ```
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, 4444));

            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .proxy(proxy)
                    .addInterceptor((Interceptor) new LoggingInterceptor())
                    .build();

            ApolloClient apolloClient = new ApolloClient.Builder()
                    .serverUrl("http://myhost.com/graphql")
                    .okHttpClient(okHttpClient)
                    .build();
```

But for some reason I get error:
`Cannot resolve method 'okHttpClient' in 'Builder'`

Can anyone give me a piece of advice how to fix it?

**Comment by martinbonnin** [comment]
Hi 👋 

`okHttpClient` is an extension function so while it works well in Kotlin, usage in Java is a bit awkward. You could use it through `OkHttpClientExtensionsKt.okHttpClient(apolloClient, okHttpClient)` but at this point, I think it's better to just call `httpEngine`:

```kotlin
apolloClient.httpEngine(DefaultHttpEngine(okHttpClient))
```

**Comment by Mehonoshin** [comment]
@martinbonnin thank you for fast response, the suggested approach fixed the problem indeed :pray:
