### ISSUE TITLE
Using apollo-ast in Java

### ISSUE THREAD

**Issue by andrey-nakin** [apollographql/apollo-kotlin#4031]
Is there a way to use `apollo-ast` functionality in Java code? Particularly, I need to parse a GraphQL schema into a `GQLDocument`. 

Is it possible? Where can I find corresponding examples?

**Comment by martinbonnin** [comment]
Hi 👋 !

It's technically possible albeit not documented at the moment as you found out. Your best bet is to use `parseAsGQLDocument` ([source](https://github.com/apollographql/apollo-kotlin/blob/6299f2acc8d2afd15a5a4669a817daa7f140e7fa/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/api.kt#L34)):

```java
GQLResult<GQLDocument> result = ApolloParser.parseAsGQLDocument(bufferedSource, null)
```

That should do the trick. As this code uses a bunch of Kotlin extension functions, the trick is to use the file name as class name and pass the receiver as first parameter and that usually works.

**Comment by andrey-nakin** [comment]
It works, thank you!
