### ISSUE TITLE
When sending persisted queries with long URLs, use POST method even if htpMethodForHashedQueries is set to HttpMethod.Get

### ISSUE THREAD

**Issue by nkmrh** [apollographql/apollo-kotlin#4032]
**Use case**
We have encountered a case where persisted queries are sent via GET, and if the query variables are long, the URL becomes too long, resulting in a 414 error.
To prevent this error, increase the allowable HTTP request line size on the server side, but I would like to propose the following two solutions.

**Describe the solution you'd like**
a. Add an option in the Apollo Client's Persisted Queries function to specify a string length limit for variables, and switch to POST instead of GET when the limit is exceeded.
b. Add a function to retry persisted query with POST if sending GET of persisted query fails.
  - In apollo-ios, this behavior is achieved when ApolloClient options are set to `autoPersistQueries = true`, `useGETForQueries = true`, `useGETForPersistedQueryRetry = false` https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/JSONRequest.swift#L79

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for sending this!

Is there any reason why you're not using the default POST method all the time for the full document query? The rationale being that these requests should be very unfrequent and therefore do not require CDN-level caching. Or is there another reason you need `GET` for these?

**Comment by nkmrh** [comment]
Hi!
We are basically specifying GET because we want the CDN cache to work for most queries. However, there are some queries where query variables can get long and we want to send them as POST.
Is there any way to dynamically switch the http method of the persisted query in such a case?

> also if I'm reading the iOS code correctly, the "retry" is for "PersistedQueryNotFound" errors not for 414 HTTP errors
This was my mistake, my apologies 😇

**Comment by martinbonnin** [comment]
> We are basically specifying GET because we want the CDN cache to work for most queries.

I would say it's very little use caching the full document queries in your CDN as in theory they should happen very very occasionally. Basically such queries happen once every time a new query is added to your app (overall, for all app users). Let's say you have 1000 users. The first one to connect will do a POST and all the other users and other queries will do a GET. So it's a 1/1000 hit ratio. And the more people use your app, the more they will hit the hashed query. The difference is even bigger if you have 1M users.

It might even be counterproductive to store this in your CDN given it takes some spaces for something that should have a very very low request/min.

> Is there any way to dynamically switch the http method of the persisted query in such a case?

Yes! You can override the default `HttpRequestComposer`:

```kotlin
  class MyHttpRequestComposer(serverUrl: String) : HttpRequestComposer {
    private val delegate = DefaultHttpRequestComposer(serverUrl)
    override fun <D : Operation.Data> compose(apolloRequest: ApolloRequest<D>): HttpRequest {
      val request = delegate.compose(apolloRequest)
      return if (request.method == HttpMethod.Get && request.url.length > 1024) {
        // fallback to POST
        delegate.compose(apolloRequest.newBuilder().httpMethod(HttpMethod.Post).build())
      } else {
        request
      }
    }
  }
```

```kotlin
    apolloClient = ApolloClient.Builder()
        .networkTransport(HttpNetworkTransport.Builder()
            .httpRequestComposer(MyHttpRequestComposer("https://.."))
            .build()
        ).build()
```

But again I would recommend against that unless you have actual data that shows it's more efficient/less expensive.

**Comment by nkmrh** [comment]
@martinbonnin 
I was able to use `ApolloInterceptor` in the following way to take a `HTTPRequest` from `DefaultHttpRequestComposer`, determine the length of the URL and switch the HTTPMethod.
Thanks for your advice!!

```kotlin
ApolloClient.Builder()
        .addInterceptor(object : ApolloInterceptor {
            private val delegate = DefaultHttpRequestComposer(serverUrl)
            override fun <D : Operation.Data> intercept(apolloRequest: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
                val request = delegate.compose(apolloRequest)
                return if (request.method == HttpMethod.Get && request.url.toByteArray().size > 8000) {
                    chain.proceed(apolloRequest.newBuilder().httpMethod(HttpMethod.Post).build())
                } else {
                    chain.proceed(apolloRequest)
                }
            }
        })
```

**Comment by martinbonnin** [comment]
Thanks for the update 😊 . Glad you found a solution! Do you mind if I close this one?

**Comment by nkmrh** [comment]
Yes, of course 👍
