### ISSUE TITLE
GraphQLWsProtocol suspend function for connectionPayload

### ISSUE THREAD

**Issue by CureleaAndrei** [apollographql/apollo-kotlin#4042]
Using the recommended GraphQLWsProtocol you can pass the connectionPayload only as a map in a sync way at initialisation. It would be nice to pass it as a suspend function as build in the SubscriptionWsProtocol for all the auth tokens obtained in an async way.

**Comment by martinbonnin** [comment]
Thanks for opening this. We did a similar change for `SubscriptionWsProtocol` not too long ago. Makes a lot of sense to add it for `GraphQLWsProtocol` too. Do you want to open a pull request?

**Comment by martinbonnin** [comment]
For the record, the PR is there: https://github.com/apollographql/apollo-kotlin/pull/4043

**Comment by BoD** [comment]
Available in v3.3.0.
