### ISSUE TITLE
Update to Kotlin 1.7

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#4080]
Kotlin 1.7 Beta [has been released](https://blog.jetbrains.com/kotlin/2022/05/kotlin-1-7-0-beta/), let's try it on the project and see if we encounter any issue with it.

**Comment by BoD** [comment]
Initial findings:
- the workaround to pick an older version of Kotlin when inside the IDE for [this issue](https://youtrack.jetbrains.com/issue/KTIJ-21583/HMPP:-1.6.20-breaks-autocomplete-in-multiplatform-composite-buil#focus=Comments-27-6022244.0-0)) doesn't work. Issue open [here](https://youtrack.jetbrains.com/issue/KT-52375/With-1-7-0-Beta-can-t-ise-Gradle-s-useModule)
- needed to update `org.jetbrains.kotlinx:kotlinx-datetime` to latest version to avoid a native compiler crash
- other than that, all tests pass 👍

**Comment by martinbonnin** [comment]
Update the name of this issue to "Update to Kotlin 1.7" ? 

That being said, I don't really see us adopting it in the near future. [Using 1.7 features will break compiling with 1.6](https://kotlinlang.org/docs/kotlin-evolution.html#compatibility-tools), which means unfortunately, we'll have to wait until a significant portion of the user base has switched to Kotlin 1.7 before enabling it.

**Comment by martinbonnin** [comment]
Note: we could still have a [dedicated shadow branch](https://slack.engineering/shadow-jobs/) to test 1.7 on CI and make sure it doesn't break.

**Comment by BoD** [comment]
WIP branch [here](https://github.com/apollographql/apollo-kotlin/compare/kotlin-1-7?expand=1).

**Comment by BoD** [comment]
Done.
