### ISSUE TITLE
Apollo kotlin spawns non-deamon background threads by default

### ISSUE THREAD

**Issue by yogurtearl** [apollographql/apollo-kotlin#4084]
**Summary**

Run this code on Kotlin/JVM: 
```kotlin
fun main() {
     ApolloClient.Builder().serverUrl("https://example.com").build()
}
```

**Expected**
The JVM terminates immediately when running `main`. 

**Actual**
JVM just runs forever and doesn't terminate. 

**Version**
apollo-kotlin 3.3.0, JVM

**Description**

By default, `ApolloClient` creates a background dispatcher:
https://github.com/apollographql/apollo-kotlin/blob/a5e7a68d862a0f592cb1237b7380a58137152042/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/internal/dispatchers.kt#L14

Which is used here: 
https://github.com/apollographql/apollo-kotlin/blob/a5e7a68d862a0f592cb1237b7380a58137152042/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/WebSocketNetworkTransport.kt#L81

This creates a non-daemon background thread that keep the JVM running. 

This code DOES terminate immediately on JVM (because it avoids `WebSocketNetworkTransport`) : 
```kotlin
fun main() {
        ApolloClient.Builder().serverUrl("https://example.com")
            .subscriptionNetworkTransport(HttpNetworkTransport.Builder().serverUrl("https://example.com").build())
            .build()
}
```

**Possible Solution**

You can do something like this, which uses daemon threads: 
```
val threadCount = AtomicLong(0)
...
Executors.newSingleThreadScheduledExecutor { Thread(it, "background-dispatcher-${threadCount.getAndIncrement()}").also { it.isDaemon = true } }
```

**Comment by martinbonnin** [comment]
Hi 👋 . The general expectation is to call `apolloClient.dispose()` when done with the `ApolloClient` to properly join the threads. Daemons threads are an interesting idea but I'm concerned it would just hide them so someone creating a lot of client without disposing them would end up with a lot of zombie threads.

**Comment by yogurtearl** [comment]
ah, I see. 🤔 

the `dispose` method has no kdoc, so it is unclear that it is supposed to cancel background threads. 
https://apollographql.github.io/apollo-kotlin/kdoc/apollo-runtime/com.apollographql.apollo3/-apollo-client/index.html

Maybe make `ApolloClient` `Closable`, so we can `.use { ... }` and ensure it gets closed?

**Comment by martinbonnin** [comment]
Yep, all good points 👍 . We also have `Closeable` in other places like `JsonReader` so I think it makes a lot of sense. Do you want to make a PR?

**Comment by yogurtearl** [comment]
Looks like apollo [uses `okio.Closeable`](https://square.github.io/okio/3.x/okio/okio/okio/-closeable/close.html) which is multiplatform, and then is [employs `okio.use` ](https://square.github.io/okio/3.x/okio/okio/okio/use.html)

We could add a `Disposable` interface and then add it to any existing type (e.g. `ApolloStore`, `ApolloClient`, `NetworkTransport`, `HttpEngine`, etc)  that has a `dispose` function? 

in the `apollo-api` module, in `package com.apollographql.apollo3.api` ?
```kotlin
interface Disposable : okio.Closeable {
  /**
   * Disposes/cancels/closes any resources (connections, i/o, Threads, [CoroutineScope]s, etc) that are held by this object.
   * Do not use this object after it has been disposed, as behavior is undefined.
   */
  fun dispose()

  /**
   * Calls [dispose]
   */
  override fun close() {
    dispose()
  }
}
```

Thoughts?

**Comment by yogurtearl** [comment]
Sounds good: https://github.com/apollographql/apollo-kotlin/pull/4142

There are lots of `dispose()` functions that could probably use a similar treatment.

**Comment by yogurtearl** [comment]
Closing this, but opened this to do a similar refactoring across other types: 
https://github.com/apollographql/apollo-kotlin/issues/4150
