### ISSUE TITLE
Fail on unused return values in test builders 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4093]
When using the test builders, it is tempting to write GraphQL-like syntax:

```kotlin
val data = UserDataQuery.Data {
  userViewer {
    userId = "userId"
  }
}
```

This has no effect because the result of `userViewer` is never used. Investigate if we could detect that at runtime at fail early as a hint towards the working code:

```kotlin
val data = UserDataQuery.Data {
  viewer = userViewer {
    userId = "userId"
  }
}
```

(or use a Kotlin `@CheckResult` annotation if one becomes available at some point, see https://youtrack.jetbrains.com/issue/KT-12719/Add-CheckResult-MustUseReturnValue-to-warn-about-unused-return-v)

**Comment by BoD** [comment]
Change available in v3.3.1.
