### ISSUE TITLE
Kotlin Native: remove the old memory manager restrictions

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#4100]
The [new memory manager](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md) simplifies sharing code between targets by lifting the specific concurrency rules that have existed on Kotlin Native (more details in [this Kotlin blog post](https://blog.jetbrains.com/kotlin/2021/05/kotlin-native-memory-management-update/)).

Switching to the new MM will mean:
- removing `freeze()` calls and some object duplications
- removing the need to call `runTest`
- removing the requirement to execute calls on the main thread on Apple

Users of the library will need to switch their project to the new MM as well.

Let's use this issue to track progress on this change, but also to gather user feedback on potential blockers preventing such a switch.

**Comment by martinbonnin** [comment]
Can we rename this as "Kotlin Native: remove the old memory manager restrictions". As technically we don't have to switch to the new memory manager (except for tests)

**Comment by BoD** [comment]
[Looks like](https://github.com/cashapp/sqldelight/blob/master/gradle.properties#L26) SQLDelight is planned to make the switch in v2.0.0

**Comment by Tieru** [comment]
I still hope you will allow us using ApolloGraphql with the new memory model a bit sooner. Currently I'm struggling with the old MM, and new one would make my life 100 times easier, but I have choose between "not working part of my app" and "entire app is not working due to asserts in apollo"

**Comment by BoD** [comment]
Hi @Tieru! We are under the impression that the library should already work with projects using the new MM. A sample project is [here](https://github.com/BoD/apollo-kotlin-template-mpp) but maybe it is too simplistic and we are missing something? Can you tell us what is not working with your project?

**Comment by Tieru** [comment]
Sorry for delay, but well, it does work!
My problem was that I was starting requests on background thread. Somehow it worked this way earlier on old MM, before I switched to the new MM.

Thanks a lot for your work :)

**Comment by BoD** [comment]
Done with #4287 and is part of version 3.5.0
