### ISSUE TITLE
enum not effective

### ISSUE THREAD

**Issue by doesDWQ** [apollographql/apollo-kotlin#4109]
**Summary**
```graphql
subscription CollectorStatus($analysisID: ID!) {
    collectorStatus(analysisID: $analysisID) {
        status: CollectorStatus!
    }
}

enum CollectorStatus {
    Waiting
    Collecting
    Failed
    Success
    Ready
}
```

error message:  " symbol:   method rawValue() "

It can operate normally after the following modifications:

```graphql
subscription CollectorStatus($analysisID: ID!) {
    collectorStatus1: collectorStatus(analysisID: $analysisID) {
        status: CollectorStatus!
    }
}

enum CollectorStatus {
    Waiting
    Collecting
    Failed
    Success
    Ready
}
```

**Version**
2.5.11

I use it through  https://github.com/aoudiamoncef/apollo-client-maven-plugin

**Comment by martinbonnin** [comment]
Hi! Thanks for sending this! That's an unfortunate consequence of the model for `data.collectorStatus` having the same name as the `CollectorStatus` enum. I think KotlinPoet could resolve these nameclashes and this issue might actually not happen on 3.x. Unfortunately, there's no Maven plugin there yet and the Java APIs could need some love (see https://github.com/apollographql/apollo-kotlin/issues/3694)

So all in all, what you did ([using aliases](https://www.apollographql.com/docs/kotlin/advanced/using-aliases)) is the correct solution. Or were you expecting something else?

**Comment by doesDWQ** [comment]
> Hi! Thanks for sending this! That's an unfortunate consequence of the model for `data.collectorStatus` having the same name as the `CollectorStatus` enum. I think KotlinPoet could resolve these nameclashes and this issue might actually not happen on 3.x. Unfortunately, there's no Maven plugin there yet and the Java APIs could need some love (see #3694)
> 
> So all in all, what you did ([using aliases](https://www.apollographql.com/docs/kotlin/advanced/using-aliases)) is the correct solution. Or were you expecting something else?

I have no other questions. I just think it's a question, so I mentioned it. Thank you for your answer

**Comment by martinbonnin** [comment]
Sounds good, thanks for reporting this 😊 . I'm going to close this one. For folks interested in more longer term Java improvements, please subscribe to https://github.com/apollographql/apollo-kotlin/issues/3694.
