### ISSUE TITLE
Generate Java source-compatible classes when using responseBased code-gen (kapt compatibility)

### ISSUE THREAD

**Issue by rsttst** [apollographql/apollo-kotlin#4113]
Not sure whether this should actually be labelled a bug, so I went with feature just to be sure:

Consider the following schema:
```graphql
type Example1 {
  foo: Example2!
}

type Example2 {
  foo: Example3!
}

type Example3 {
  bar: String!
}

type QueryType {
  exampleQuery(input: Int!) : Example1!
}

schema {
  query: QueryType
}
```

And the following query:
```graphql
query ExampleQuery(
  input: $input
) {
  exampleQuery(
    input: $input
  ) {
    foo {
      foo {
        bar
      }
    }
  }
}
```

As expected, when using the default `operationBased` code generation mode a flat class hierarchy is generated, with integer suffixes for classes that would otherwise have the same name (`Foo` and `Foo1`).
```kotlin
class ExampleQuery(...) {
  class Data(...)
  class ExampleQuery(...)
  class Foo(...)
  class Foo1(...)
}
```

With `responseBased` code-gen, we get the following code, with no suffixes being necessary anymore:
```kotlin
class ExampleQuery(...) {
  class Data(...) {
    class ExampleQuery(...) {
      class Foo(...) {
        class Foo(...)
      }
    }
  }
}
```

The generated code is valid Kotlin, but unfortunately it's structure is not valid if converted to Java, since the latter doesn't allow clashing names for nested classes. This makes the generated code incompatible with [kapt](https://kotlinlang.org/docs/kapt.html), the kotlin annotation processor, which relies on creating Java stubs for all classes by converting kotlin code to its Java equivalent. 
This won't be an issue anymore when [ksp](https://kotlinlang.org/docs/ksp-overview.html) will finally replace `kapt` at some point in the future, but currently some major libraries only support `kapt`, including [Dagger/Hilt](https://github.com/google/dagger). 

The solution to this is pretty simple: Also using integer suffixes for clashing nested class names in `responseBased` mode. I think, this should probably be a feature you have to opt-in to, by adding a setting to the gradle plugin, or by adding another code-gen mode like 'operationBased-java'.

**Comment by BoD** [comment]
Hi! 👋 

One thing you could do is to keep a 'flat' hierarchy even with the `responseBased` codegen, by enabling the flag `flattenModels.set(true)`. In that case they will also be suffixed to avoid clashes.

Another thing you can do if that's only a few isolated cases, is to [use aliases](https://www.apollographql.com/docs/kotlin/advanced/using-aliases).

Would that work for your kapt use-case?

**Comment by BoD** [comment]
Another thing you may be able to do, is to isolate the part of your project that uses Apollo into its own module, which doesn't use kapt. Katp should generate the stubs only in the modules where it's applied.

**Comment by rsttst** [comment]
Hi! Thanks for the quick answer. All three approaches actually seem really promising, I'll have to give them a try to figure out what works best for my use case. Also I'm closing this issue, since there are existing solutions for the kapt problem.
