### ISSUE TITLE
Kotlin Multiplatform - Hasura Subscription

### ISSUE THREAD

**Issue by ynsok** [apollographql/apollo-kotlin#4123]
Hello :D 

I will try quickly to describe my problem. 

I would like to subscribe to the Hasura table but unfortunately, while I'm doing it I'm receiving the error message ```com.apollographql.apollo3.exception.ApolloNetworkException: Operation error notifications: {extensions={path=$, code=start-failed}, message=cannot start as connection_init failed with : Missing Authorization header in JWT authentication mode}```, which is weird because I'm passing Authorization Header. My first thought was that maybe headers weren't added to the request, so I've tried adding `x-Hasura-admin-secret` and everything started working. Is it related to Apollo itself or Hasura configuration? 

```

        ApolloClient.Builder()
            .serverUrl(BASE_URL)
            .webSocketServerUrl(BASE_URL)
            .wsProtocol(SubscriptionWsProtocol.Factory(connectionPayload = {
                mapOf("Authorization" to token)
            }))
            .addHttpHeader("Authorization", token)
            .build()
            .subscription(NotificationsSubscription())
            .toFlow()
            .onEach {
                println("success response")
            }.catch {
                println("error $it")
            }.collect()

```
apollo = "3.3.0"
kotlin = "1.6.21"

**Comment by BoD** [comment]
Hi! 

At first glance, I can see you are calling `addHttpHeader` on the ApolloClient Builder, which is not relevant for WebSockets - instead, it can be called on the `WebSocketNetworkTransport` like so:

```kotlin
ApolloClient.Builder()
    ...
    .subscriptionNetworkTransport(
        WebSocketNetworkTransport.Builder()
            .serverUrl(BASE_URL)
            .protocol(SubscriptionWsProtocol.Factory(connectionPayload = {
                mapOf("Authorization" to token)
            }))
            .addHeader("Authorization", authorization) 
            .build()
    )
   ...
   .build()
```

These headers will be passed when opening the WebSocket.

That being said, I'm not sure this is relevant for Hasura authentication. I'm not really familiar with it but from what I can see, it looks like the `connectionPayload` should be enough - but you you can try it to be sure.

Did you manage to authenticate with your token for queries/mutations?

**Comment by BoD** [comment]
I've just tried with this sample Hasura project: https://hasura.io/learn/graphql/graphiql, and managed to make a subscription work like this:

```kotlin
    val serverUrl = "https://hasura.io/learn/graphql"
    val TOKEN = "Bearer eyJhb............."

    val apolloClient = ApolloClient.Builder()
        .serverUrl(serverUrl)
        .subscriptionNetworkTransport(
            WebSocketNetworkTransport.Builder()
                .serverUrl(serverUrl)
                .protocol(SubscriptionWsProtocol.Factory())
                .addHeader("Authorization", TOKEN)
                .build()
        )
        .build()

    apolloClient.subscription(TodoListSubscription()).toFlow().collect{ response ->
        println(response)
    }
```

Meaning my assumption ("looks like the connectionPayload should be enough") was wrong - at least in this example, it's the `addHeader` that works instead.

However if that doesn't work for your case, I must admit I don't really have other ideas.

**Comment by ynsok** [comment]
I've tried and is not working :(

**Comment by martinbonnin** [comment]
You could try to run through a proxy like [Charles](https://www.charlesproxy.com/) and dump the traffic/compared to a working implementation? Maybe that can give you a hint on what you need to change?

**Comment by ynsok** [comment]
Ok, I've found a problem 😄 

1. I needed to send the Authorization header under the headers object `mapOf("headers" to mapOf("Authorization" to token))`

the final form looks like this:
```
        ApolloClient.Builder()
            .serverUrl(Base_url)
            .webSocketServerUrl(Base_url)
            .wsProtocol(SubscriptionWsProtocol.Factory(connectionPayload = {
                mapOf("headers" to mapOf("Authorization" to token))
            }))
            .build()

```

**Comment by BoD** [comment]
Wow, interesting! I noticed [this issue](https://github.com/hasura/graphql-engine/issues/994) before which seems to be consistent with this. I wonder why the todo sample behaves differently. But glad it now works!

**Comment by martinbonnin** [comment]
@ynsok anything else we can help with? Is it ok to close this issue?

**Comment by ynsok** [comment]
Yes, you can close, thanks again 😄
