### ISSUE TITLE
Merging multiple SDLs into one

### ISSUE THREAD

**Issue by andrey-nakin** [apollographql/apollo-kotlin#4141]
Hello!

Is it possible to merge multiple SDL schemas parsed to `GQLDocument` into a single SDL or `GQLDocument`?

**Comment by martinbonnin** [comment]
Hi 👋 A `GQLDocument` is just a list of `GQLDefinition` so you can concat the list and create a new document from the new list.

**Comment by andrey-nakin** [comment]
How should I properly handle duplicating definitions like `Query`? An example:

**SDL 1:**

`
type TypeA {
  id: ID!
}

type Query {
  getTypeA(id: ID): TypeA
}
`

**SDL 2**

`
type TypeB {
  id: ID!
}

type Query {
  getTypeB(id: ID): TypeB
}
`

Both SDL's have `Query` definition. Should I manually convert `type Query` to `extend type Query` in the seconds SDL? Is there an API for this?

**Comment by martinbonnin** [comment]
For cases like this, you can certainly merge manually. There's no specific API but I think you can take the `GQLFieldDefinition` from the second `Query` and add them to the first one?

**Comment by andrey-nakin** [comment]
I managed to merge multiple schemas using manipulations with lists of definitions. A question: I'm using some methods with `Internal` suffix such as `GQLDocument.writeInternal` or `GQLTypeDefinition.copyWithNewChildrenInternal` in my Java code. Is it safe? Won't these methods be removed from API in future releases?

**Comment by andrey-nakin** [comment]
In the following snippet I'm getting a string representation of GraphQL schema:

```
GQLDocument src = ...
var buffer = new Buffer();
src.writeInternal(new SDLWriter(buffer, "  "));
var os = new ByteArrayOutputStream();
buffer.writeTo(os);
var sdl = os.toString(StandardCharsets.UTF_8);
```

What is a correct way to do this using the public API?

**Comment by martinbonnin** [comment]
There is [GQLNode.utoUtf8()](https://github.com/apollographql/apollo-kotlin/blob/dc31a9a5fa1c539aa7ca8e1269f877a00561e5df/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/gqlnode.kt#L9) but it's a Kotlin extension. This means it's a static method seen from java. You should be able to do something like this:

```
GQLDocument src = ...
var sdl = GQLNodeKt.toString(src, indent = "  ");
```

**Comment by martinbonnin** [comment]
Wait, sorry, the code you pasted was Kotlin already, not sure why I assumed Java... If you're using Kotlin then you should be able to do just 
```kotlin
GQLDocument src = ...
var sdl = src.toString()
```

(without semicolons 🙌 )

**Comment by andrey-nakin** [comment]
`GQLNodeKt.toUtf8` works like a charm, thank you!

Another one question: I'm using `GQLTypeDefinition.copyWithNewChildrenInternal` to create a new instance of `GQLTypeDefinition` using a `List` of definitions.

A code snippet:

```
GQLTypeDefinition query1 = ... // Query type definition from the first SDL
GQLTypeDefinition query2 = ... // Query type definition from the second SDL
List<GQLNode> defs = new ArrayList<GQLNode>();
defs.addAll(query1.getChildren());
defs.addAll(query2.getChildren());
GQLTypeDefinition result = (GQLTypeDefinition) query1.copyWithNewChildrenInternal(
                                new NodeContainer(defs));
```

Is there a better way for this task?

**Comment by martinbonnin** [comment]
In Kotlin, it leverages default parameters:

```kotlin
val result = query.copy(fields = query1.fields + query2.fields)
```

But because Java doesn't know about Kotlin default parameters you'll have to specify them all:

```java
    GQLObjectTypeDefinition query1 = ... // Query type definition from the first SDL
    GQLObjectTypeDefinition query2 = ... // Query type definition from the second SDL

    GQLTypeDefinition result = query1.copy(
        query1.getSourceLocation(),
        query1.getDescription(),
        query1.getName(),
        query1.getImplementsInterfaces(),
        query1.getDirectives(),
        query1.getFields() + query2.getFields()
    );
```

All in all, if you're doing a lot of AST transformations in Java, you can also take a look at [graphql-java](https://github.com/graphql-java/graphql-java) that will expose more Java-friendly APIs.

**Comment by andrey-nakin** [comment]
@martinbonnin thanks a lot! I fixed my code accordingly.

BTW we're already using `graphql-java` in another project, but I found your library more suitable to my current task. And I'm not sure `graphql-java` has SDL parsing capabilities I need.
