### ISSUE TITLE
Support Ktor 2.x

### ISSUE THREAD

**Issue by maribelmai** [apollographql/apollo-kotlin#4178]
**Summary**
When trying to build a Kotlin Multiplatform project with JS target, I got:
`Module "com.apollographql.apollo3:apollo-runtime" has a reference to symbol io.ktor.client.features/HttpTimeout.Feature|null[0]. Neither the module itself nor its dependencies contain such declaration.`
If a project uses Ktor 2.0.2 it causes a conflict with the Apollo one that's 1.6.7

**Version**
3.3.0

**Description**
In a Kotlin Multiplatform project I got declared:

```
        val ktor_version = "2.0.2"
        val apollo_version = "3.3.0"

        val commonMain by getting {

            dependencies {
                ...
                implementation("io.ktor:ktor-client-core:$ktor_version")
                implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
                implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
              
                implementation("com.apollographql.apollo3:apollo-api:$apollo_version")
                implementation("com.apollographql.apollo3:apollo-runtime:$apollo_version")
                ...
            }
        }
      
        val jsMain by getting {

            dependencies {
                ...
                implementation("io.ktor:ktor-client-js:$ktor_version")
                implementation("io.ktor:ktor-http-cio-js:2.0.2")
                ...
            }
        }
```
Trying to build the module results in `Module "com.apollographql.apollo3:apollo-runtime" has a reference to symbol io.ktor.client.features/HttpTimeout.Feature|null[0]. Neither the module itself nor its dependencies contain such declaration.`

**Comment by martinbonnin** [comment]
Thanks a lot for sending this! 

Do you know how much change is needed to upgrade to Ktor 2? IIRC we only used Ktor for JS clients so hopefully there isn't a too big impact?

**Comment by BoD** [comment]
@maribelmai We've updated the dependency, this will be in the next release, in the meantime if you want to try it, you can use the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots)!

**Comment by maribelmai** [comment]
I used the snapshot! looks good 👍 
Thanks so much for prioritizing and fixing this one!
