### ISSUE TITLE
Generated class is so big that JVM returns Method too large exception

### ISSUE THREAD

**Issue by filippkowalski** [apollographql/apollo-kotlin#4179]
**Question.**
Is it possible to optimize generated by GraphQL classes to make them smaller? 

My current query looks like this:
```
query Proto($input: Proto!, $appInput: AppInput!) {
    proto(input: $input) {
        appId
        balances {
            products {
                breakdown {
                    breakdown {
                        breakdown {
                            ...TokenBreakdownFragment
                        }
                        ...TokenBreakdownFragment
                    }
                    ...TokenBreakdownFragment
                }
            }
        }
    }
}
```

due to nesting, the generated class gets so big that JVM returns `method too large error`:
```
Error generating class file com/asd/app/LiveLiterals$Proto.class (compiled from [..../Proto.kt]): Method too large: com/asd/app/LiveLiterals$Proto.<clinit> ()
```

According to the [Java Virtual Machine specification](https://docs.oracle.com/javase/specs/jvms/se13/html/), [the code of a method must not be bigger than 65536 bytes](https://docs.oracle.com/javase/specs/jvms/se13/html/jvms-4.html#jvms-4.7.3).

I'm trying to build it on Android and the build never finishes due to this.

**Comment by martinbonnin** [comment]
Are you using `responseBased` codegen by any chance? It is [known](https://github.com/apollographql/apollo-kotlin/issues/3144) to generate potentially big classes if using a lot of fragments. 

There are unfortunately no simple solution to that issue as it is the very nature of the `responseBased` codegen to map 1:1 with a potentially big response. I'd recommend either using less fragments or `operationBased` codegen. You can also read more at https://www.apollographql.com/blog/mobile/kotlin/the-story-behind-apollo-kotlin-3-codegen/

**Comment by filippkowalski** [comment]
Yes, I was using `responseBased`. Switching to `operationBased` solved the issue. Thanks!
