### ISSUE TITLE
Apollo v2 Kotlin 1.7.0 incompatibility

### ISSUE THREAD

**Issue by remcomokveld** [apollographql/apollo-kotlin#4183]
**Summary**
The v2 com.apollographql.apollo Gradle fails to configure the project after updating Kotlin to 1.7.0.

**Version**
2.5.11

**Description**
I completely understand if you don't want to invest any additional time in the 2.x releases so I'm also happy to dig deeper and put up a PR to fix this, but it would be nice to not force users of Apollo 2.x to stick to Kotlin 1.6 until they've migrated to 1.7.

TBH I have not yet looked at the upgrade path for 3.x so if there is strong recommedation to do that instead, also happy to do that. But if the fix for 2.x is simple I think that would be nice for anyone else that's not fully up-to-date on their apollo updates.

I created a bare mimimum sample repository here. https://github.com/remcomokveld/apollo-kotlin-repro

**Comment by BoD** [comment]
Hi! Thank you for reporting this, and the repro project!

Indeed we recommend moving to to 3.x, however if a fix is possible, a new release of 2.x is not out of the question. If you want to investigate you are welcome!

**Comment by martinbonnin** [comment]
+1 to doing a maintenance release there. 

@remcomokveld also the upgrade guide to 3.x is there: https://www.apollographql.com/docs/kotlin/migration/3.0.

**Comment by BoD** [comment]
The issue was a signature change in the KotlinCompile task. A fix is in #4187, and we'll release a new 2.x version soon.

**Comment by remcomokveld** [comment]
Thank you! 🙏

**Comment by BoD** [comment]
The fix is in v2.5.12 which was just released.
