### ISSUE TITLE
Using Apollo-Kotlin on Server Side?

### ISSUE THREAD

**Issue by alandoni** [apollographql/apollo-kotlin#4193]
**Question.**
I saw in this article: https://www.apollographql.com/blog/announcement/introducing-apollo-kotlin/ that it's possible to use Apollo Kotlin even on server using Kotlin (and maybe Ktor?)

So I am curious about how to do that, is it a plugin? I can write resolvers for each query/mutation/etc ?

how to handle it?

**Comment by BoD** [comment]
Hi 👋 

Apollo Kotlin is definitely a **client** library. That being said you can use it in any Kotlin or Java project that needs to execute GraphQL queries - which is sometimes useful on the backend side. But it can't be used as a server library, there are no notion of resolvers. If that's what you need, should probably take a look at [GraphQL-Java](https://www.graphql-java.com/) or [GraphQL-Kotlin](https://opensource.expediagroup.com/graphql-kotlin/docs/) for instance.

**Comment by alandoni** [comment]
thank you, I'm just a student, I don't want to work with spring, I just liked the library and since it works with nodejs, I thought it could be a good idea to use it with ktor, or even use it with independent of the framework, I found KGraphQL interesting to use with Ktor
