### ISSUE TITLE
Validation for custom schema directives

### ISSUE THREAD

**Issue by theBradfo** [apollographql/apollo-kotlin#4205]
**Use case**
Our schema has a few custom server-side directives defined, but the validation does not seem to exist at code generation time when evaluating the GraphQL operation source.

**Describe the solution you'd like**
Currently with the apollo introspected schema, the server directives are not written to the defined schema file from the introspection task.  This makes validation likely not possible if these custom directives are added to the operation files.  It would be great if these directives could be written to the introspected schema file output by apollo, and also validated in the operation source files.  I realize that generated source with these directives is not yet possible (and detailed discussion present in #3985), but it would be great if at generation time these directives could at least be validated, to help prevent things like typos for example.

**Comment by BoD** [comment]
Hi! 👋 

Yes, it would certainly be possible to save the directives there. An additional plus is that their usage won't be red in the IDE when using the GraphQL plugin 😊

Would you be interested in trying a PR for this?

**Comment by theBradfo** [comment]
If you could point me in the right direction i can maybe find some time to take this on 😁

**Comment by BoD** [comment]
Closing, as this should work now - directive definitions are fetched during introspection, and validation was enabled in #5758.
