### ISSUE TITLE
Generated mutation class has wrong name / only named Mutation

### ISSUE THREAD

**Issue by wondering639** [apollographql/apollo-kotlin#4208]
**Question.**
I am using Kotlin Apollo Client 3.3.1 and for my mutation `addBook(input: AddBookInput!): Book!` the generated class isn't called `AddBookMutation` as expected, but instead only `Mutation`:
![studio64_pw1xHJQTv7](https://user-images.githubusercontent.com/25722498/174406964-dc2a5816-85af-4f08-a40c-9edd407c1d6f.png)

This is my complete schema:

```
type Query {
  books: [Book!]!
}

type Mutation {
  addBook(input: AddBookInput!): Book!
}

input AddBookInput {
  title: String!
}

type Book {
  id: ID
  title: String!
}

schema {
  query: Query
  mutation: Mutation
}
```

I already tried a Rebuild, but it didn't change anything. Why doesn't Apollo name the class `AddBookMutation`? How to fix it? Thanks!

**Comment by martinbonnin** [comment]
Hi 👋 Can you share your operation `.graphql` file? Apollo Kotlin generates models based on operation (query, mutation or subscription) files. Something like this:

```graphql
mutation AddBook($addBookInput: AddBookInput!) {
  addBook(addBookInput: $addBookInput) {
    id
  }
}
```

**Comment by wondering639** [comment]
> Apollo Kotlin generates models based on operation (query, mutation or subscription) files. 
Ah, thanks, your idea was correct, that was the issue. It looked like this:

```
mutation Mutation($input: AddBookInput!) {
    addBook(input: $input) {
        id
        title
    }
}
```

I changed it and now it is
```
mutation AddBookMutation($input: AddBookInput!) {
    addBook(input: $input) {
        id
        title
    }
}
```
and everything is working as expected :-)
