### ISSUE TITLE
Query cache not updated as expected after mutation

### ISSUE THREAD

**Issue by wondering639** [apollographql/apollo-kotlin#4209]
**Question.**
I am using the latest Apollo Kotlin 3.3.1 and I've read the caching docs, but I still have an issue that I couldn't understand/fix myself.

High level overview of what I am doing, details follow below:
1. Execute a query `BooksQuery` which gets all books. The result of this query is watched using `apolloClient.query(BooksQuery()).watch().collect()` and on changes, the UI is updated accordingly
2. I execute a Mutation `AddBookMutation` which adds a new book. I request the book (ID and Title) result from the mutation result. I would expect this to update the `BooksQuery` result in the cache and trigger the query watcher from step 1. Unfortunately this does not happen.

Details:
My **Apollo client** is created as follows. Note the CacheKeyGenerator, creating the cache key from type name plus the Id.

```
    @Singleton
    @Provides
    fun provideApolloClient(): ApolloClient {
        // https://www.apollographql.com/docs/kotlin/caching/programmatic-ids/
        val cacheKeyGenerator = object : CacheKeyGenerator {
            override fun cacheKeyForObject(
                obj: Map<String, Any?>,
                context: CacheKeyGeneratorContext
            ): CacheKey? {
                val typename = context.field.type.leafType().name
                val id = obj["id"] as String
                assert(id.isNotEmpty())

                return CacheKey(typename, id)  // <==================== relevant line
            }
        }

        // 10 MB cache
        val cacheFactory = MemoryCacheFactory(maxSizeBytes = 10 * 1024 * 1024)

        return ApolloClient
            .Builder()
            .serverUrl("<serverurl>")
            .normalizedCache(
                normalizedCacheFactory = cacheFactory,
                cacheKeyGenerator = cacheKeyGenerator
            )
            .build()
    }
```

This is my **Query**:
```
query BooksQuery {
    books {
        id
        title
    }
}
```

And this is my **Mutation** (note how id and title are requested, so exactly the fields that are also used in the books query)
```
mutation AddBookMutation($input: AddBookInput!) {
    addBook(input: $input) {
        id
        title
    }
}
```

This is my Kotlin code for watching the query result and adding a new book:

```
    init {  // <============= init block
        viewModelScope.launch {
            apolloClient.query(BooksQuery())
                .watch() // flow
                .collect() { response ->
                    Timber.i("apollo watch/collect was called")

                    response.data?.books.let { bookItems ->
                        books = bookItems!!
                    }

                    val dump = apolloClient.apolloStore.dump()
                    Timber.i("ApolloStore dump after watch/collect follows: ${NormalizedCache.prettifyDump(dump)}")
                }
        }
    }

    fun addBook() {
        viewModelScope.launch {
            // for testing purposes we will always use the same title,
            // however it will get a different ID each time (on the server side)
            // and we will also show the ID in the UI
            val input = AddBookInput(title = "yet another book")
            val mutation = AddBookMutation(input)

            // no exception handling on this test case
            val response = apolloClient.mutation(mutation).execute()
            val id = response.data?.addBook?.id
            Timber.i("AddBookMutation ok: added new book with id $id")

            val dump = apolloClient.apolloStore.dump()
            Timber.i("ApolloStore dump follows: ${NormalizedCache.prettifyDump(dump)}")
        }
    }
```

I think the issue already starts with caching, so I captured the cache content:
After the data was requested in the init block, the cache looks like this (looks fine to me as expected)

```
2022-06-18 12:09:59.201 13535-13535/com.example.graphqlsandbox I/BooksViewModel: ApolloStore dump after watch/collect follows: OptimisticCache {}
    MemoryCache {
      "Book:1" : {
        "id" : 1
        "title" : First book
      }
    
      "Book:2" : {
        "id" : 2
        "title" : Second book
      }
    
      "Book:2102991483" : {
        "id" : 2102991483
        "title" : yet another book
      }
    
      "QUERY_ROOT" : {
        "books" : [
          CacheKey(Book:1)
          CacheKey(Book:2)
          CacheKey(Book:2102991483)
        ]
      }
    }
```

Now, after calling the `addBook()` method the cache looks wrong to me, because

- The new book 1078677015 is added to the cache, but not to QUERY_ROOT books field
- In QUERY_ROOT there's now addBook, which I don't need. I just need the result of addBook (which is cached as "Book:1078677015", but not as part of the QUERY_ROOT books field)

Expectation: the new book gets added to QUERY_ROOT books and `apolloClient.query(BooksQuery()).watch().collect()`  notices  the update and fires.

```
2022-06-18 12:12:54.518 13535-13535/com.example.graphqlsandbox I/BooksViewModel$addBook: ApolloStore dump follows: OptimisticCache {}
    MemoryCache {
      "Book:1" : {
        "id" : 1
        "title" : First book
      }
    
      "Book:2" : {
        "id" : 2
        "title" : Second book
      }
    
      "Book:2102991483" : {
        "id" : 2102991483
        "title" : yet another book
      }
    
      "QUERY_ROOT" : {
        "books" : [
          CacheKey(Book:1)
          CacheKey(Book:2)
          CacheKey(Book:2102991483)
         // note that "Book:1078677015" is missing here <===========================
        ]
        "addBook({"input":{"title":"yet another book"}})" : CacheKey(Book:1078677015)
      }
    
       // new entry <==================================
      "Book:1078677015" : {
        "id" : 1078677015
        "title" : yet another book
      }
    }
```

Hope I could make my issue clear and looking forward to hints/solution, thanks :-)

Just for completeness, this my schema:
```
type Query {
  books: [Book!]!
}

type Mutation {
  addBook(input: AddBookInput!): Book!
}

input AddBookInput {
  title: String!
}

type Book {
  id: ID
  title: String!
}

schema {
  query: Query
  mutation: Mutation
}
```

**Comment by martinbonnin** [comment]
Unfortunately, there's no way from the mutation to tell what lists are going to be updated. Imagine you have multliple lists of books:

```graphql
type Query {
  books: [Book!]!
  adventureBooks: [Book!]!
  romanceBooks: [Book!]!
}
```

Whether the book is added to all three lists or just one (or two) of them is business logic and there is no way to express this in GraphQL.

What you can do after your mutation is write the new book programmatically using the [ApolloStore API](https://www.apollographql.com/docs/kotlin/caching/store/#writing-operation-data). But this would have to be done manually. 
What happens automatically though is if another watcher were listening on book `1078677015` then it would get the new title and ID automatically. But that doesn't work for lists

**Comment by wondering639** [comment]
Thanks for your explanation, very clear now :-)

> What you can do after your mutation is write the new book programmatically using the [ApolloStore API](https://www.apollographql.com/docs/kotlin/caching/store/#writing-operation-data). But this would have to be done manually. 

I implemented this manually by reading the current cache content, adding the new item and then replaced the whole cache entry for `books` like this:

```
val apolloStore = apolloClient.apolloStore

// read current cache content
// TODO: errorhandling
val cachedData = apolloStore.readOperation(
	BooksQuery()
)

// build new cache content = current cache content with the new book added
val updatedCachedData = cachedData.books
	.toMutableList()
	.apply {
		add(
			BooksQuery.Book(
				response.data!!.addBook.id,
				response.data!!.addBook.title
			))
	}

// update the cache with the new cache content
apolloStore.writeOperation(
	BooksQuery(),
	BooksQuery.Data(updatedCachedData),
	apolloClient.customScalarAdapters,
	publish = true
)
```
Ignoring the missing errorhandling (will add this in a next step) for cache misses, is this how you would do it? Or is there e.g. any shorter code to do it? Thanks.

**Comment by martinbonnin** [comment]
You got it right 👍 . There are some thoughts about making modifying cache data less verbose, maybe using something like Arrow lenses but this hasn't been implemented so far. You can follow https://github.com/apollographql/apollo-kotlin/issues/3573 for updates.

**Comment by wondering639** [comment]
Thanks for your feedback and the hint about the other ticket :-)
