### ISSUE TITLE
Documentation for apollo 3 is outdated

### ISSUE THREAD

**Issue by dcabasson** [apollographql/apollo-kotlin#4221]
**Summary**
Documentation from https://www.apollographql.com/docs/kotlin/tutorial/10-authenticate-your-queries
Includes
```
val apolloClient = ApolloClient.Builder()
        .serverUrl("https://apollo-fullstack-tutorial.herokuapp.com/graphql")
        .okHttpClient(okHttpClient)
        .build()
```

When the method `okHttpClient()` has been removed in `3`

**Version**
Apollo `3`

**Comment by martinbonnin** [comment]
Hi 👋 It should be there as [a JVM-only extension function](https://github.com/apollographql/apollo-kotlin/blob/96db33ae93aa6f3417a52267a43d7d1e87a41b36/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/network/OkHttpExtensions.kt#L19). Are you using Java by any chance? 

If yes, you'll have to do something like:

```java
OkHttpClientExtensionsKt.okHttpClient(apolloClientBuilder, okHttpClient)
```

**Comment by martinbonnin** [comment]
Hi @dcabasson, anything else we can help with?

**Comment by GOVYANSONG** [comment]
https://www.apollographql.com/docs/kotlin/advanced/http-engine/ and ApolloClient.builder().httpEngine(new DefaultHttpEngine( okhttpclient instance))

**Comment by martinbonnin** [comment]
Closing for now. Please follow https://github.com/apollographql/apollo-kotlin/issues/3694 for Java runtime updates and/or leave a message if you need anything else here.
