### ISSUE TITLE
How to use Operations.composeJsonRequest with CustomScalarTypes

### ISSUE THREAD

**Issue by GOVYANSONG** [apollographql/apollo-kotlin#4244]
Please search the [existing Github issues](https://github.com/apollographql/apollo-android/issues), [Community Discourse](https://community.apollographql.com/tag/mobile), [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-android) before asking your question. Questions are welcome but avoid duplicating issues and discussions. If you'd like a Github issue to be reopen, please leave a message on the issue.

For an informal chat about the project, you can also [say hi in the #apollo-android channel in the KotlinLang Slack](https://app.slack.com/client/T09229ZC6/C01A6KM1SBZ)(get your invite [here](https://slack.kotl.in/)).

**Question.**
I was able to use ApolloClient.addCustomScalarType() for a UUID type and custom adapter. I decided to try Operations.composeJsonRequest and hoped to achieve the same. I could not figure out a way to pass my custom adapter to a CustomScalarTypes instance. the public constructor looks a bit confusing. please enlighten me

**Comment by BoD** [comment]
Hi!

To create a `CustomScalarAdapters` with your adapter, you have to use its builder like so:

```kotlin
val customScalarAdapters = CustomScalarAdapters.Builder()
  .add(yourType, yourAdapter)
  .build()
```

**Comment by GOVYANSONG** [comment]
@BoD thanks for pointing me to the right direction. I use it in a java maven project. I just tried following and vs code intellisense is able to prompt for correct method signature: 

CustomScalarAdapters.Empty.newBuilder().add(arg0, arg1)

Cheers,
