### ISSUE TITLE
Support watchosArm32 (Apple Watch Series 3 and before)

### ISSUE THREAD

**Issue by glureau** [apollographql/apollo-kotlin#4259]
### Use case
Be able to support those models could be great, also I presume it doesn't involve too much trickery/support for that.

### Describe the solution you'd like
I can write the PR if there is no constraint on your side to provide support for this platform ([looks simple enough](https://github.com/apollographql/apollo-kotlin/search?q=watchosArm64)) and if you're ok for the added build time on CI. Also I'm not sure if the current CI can support building on arm32 🤔

**Comment by BoD** [comment]
Hi! 👋 

I think this could be added without any issue - pretty sure the MacOS images we use for the CI should work (at least it looks like Okio use the same machines and they do target `watchosArm32`).

A PR would be welcome!
