### ISSUE TITLE
Java example for GraphQL subscription client

### ISSUE THREAD

**Issue by andrey-nakin** [apollographql/apollo-kotlin#4263]
Hello!

How can I implement a GraphQL subscription client in Java? I found the following example from the docs but I can't make it working in Java:

```kotlin
apolloClient.subscription(TripsBookedSubscription())
    .toFlow()
    .collect {
      println("trips booked: ${it.data?.tripsBooked}")
    }
```

Will the following Java code work?

```Java
var flow = apolloClient.subscription(new TripsBookedSubscription());
Rx3Apollo.flowable(flow).doOnEach(e -> {
    var data = e.getValue().data;
    // process data
});
```

**Comment by BoD** [comment]
Hi 👋 

To use Java, you'll need to add a dependency to RxJava and use the provided extensions - this is explained in [this guide](https://www.apollographql.com/docs/kotlin/advanced/rxjava).

That being said, if you are on a Java project you may find that Apollo Kotlin v3 is not optimized for it. We are monitoring [this issue](https://github.com/apollographql/apollo-kotlin/issues/3694) to gather feedback about a better Java interop - don't hesitate to add your voice to it. Another option would be to use [v2 of the library](https://www.apollographql.com/docs/kotlin/v2).
