### ISSUE TITLE
Codegen target Java - generateOptionalOperationVariables = false for complex inputs

### ISSUE THREAD

**Issue by stengvac** [apollographql/apollo-kotlin#4268]
Hello Once Again me :) As [kotlin generic red highlighting](https://youtrack.jetbrains.com/issue/KTIJ-22127) is being investigated and I have to codegen with target Java here is another question about codegen behavior/bug.

### Question - Expected behavior with `generateOptionalOperationVariables.set(false)` for complex input
Tried on version 3.4.0

With settings

```
apollo {
    generateKotlinModels.set(false)
    generateOptionalOperationVariables.set(false)
}
```

scalar inputs for Query/Mutation are generated without `com.apollographql.apollo3.api.Optional` which is correct I believe. And I would expect this behavior also for lets say this kind of input

```
input ComplexInput {
  myCoolValue: String
}

query {
    someQuery(value: String, complexInput: ComplexInput): Boolean
}
```

codegen output
```
public class SomeQuery implements Query<SomeQuery.Data> {
    public final String value;
    public final ComplexInput complexInput;
   ...
}

public class ComplexInput {
  public final Optional<String> myCoolValue;
  ...
}  
```

I did expect to get 
```
public class ComplexInput {
  public final String myCoolValue;
  ...
}  
```

Is this by desing?

**Comment by BoD** [comment]
Hi!

Yes, this is expected - the `generateOptionalOperationVariables` only impacts the generation of operation variables, but not the input fields themselves. When input fields are nullable they can be omitted per the GraphQL spec, hence the generation of Optional.

**Comment by stengvac** [comment]
Ok, 

I am confused with one more thing. I would expect Optional to be used for 3 state json generation.
Lets go again with

```
public class ComplexInput {
  public final Optional<String> myCoolValue;
  ...
}  
```
1, `myCoolValue` is null -> not even `myCoolValue` field is present in request JSON.
2, `myCoolValue` is Optional.Absent -> field `myCoolValue` is present with null value in request JSON.
3, `myCoolValue` is Optional.Present -> field `myCoolValue` is present with value from Optional.Present in request JSON.

Generated adapter looks like this 

```
public enum ComplexInput_InputAdapter implements Adapter<ComplexInput> {
  INSTANCE;

  @Override
  public ComplexInput fromJson(JsonReader reader, CustomScalarAdapters customScalarAdapters) throws
      IOException {
    throw new IllegalStateException("Input type used in output position");
  }

  @Override
  public void toJson(JsonWriter writer, CustomScalarAdapters customScalarAdapters,
      ComplexInput value) throws IOException {
    if (value.myCoolValue instanceof Optional.Present) {
      writer.name("myCoolValue");
      new OptionalAdapter<>(Adapters.NullableStringAdapter).toJson(writer, customScalarAdapters, (Optional.Present<String>)value.myCoolValue);
    }
  }
}
```

Which has only 2 state serialization for input. Case 1 +2 -> not present at all. Case 3 -> serialized value.
Like this Optional in input is not needed right?

**Comment by BoD** [comment]
Well the semantics is that you should not pass `null`, so there's only 2 cases. You should pass either:
-  `Optional.Absent`: field not present in the JSON
- `Optional.Present`: field present in the JSON (possibly with value `null`)

But this is not enforceable in Java - however, if you pass `null`, it will behave as if you passed `Optional.Absent`.

**Comment by martinbonnin** [comment]
> not sure why it is enum

For the record, that's because these adapters are singletons. Using enums allows thread-safe singletons in Java. See https://shunix.com/efficient-thread-safe-singleton-in-java/. 
Since this is mostly internal code, this was an easy and concise way to implement singletons.

**Comment by stengvac** [comment]
Thx for enum clarification.

My point is that Query input is generated as normal java field (without optional) with ` generateOptionalOperationVariables.set(false)` even for complex objects. Then nested fields are generated with optional, but optional for java behave same as if there was is not optional at all (null or Absent) has same result. So I don't see need for Optional in those cases.

So I would expect, that  `generateOptionalOperationVariables.set(false)` would affect all levels of input objects.
