### ISSUE TITLE
cannot write type of Any with value of BigDecimal to json

### ISSUE THREAD

**Issue by CompileConnected** [apollographql/apollo-kotlin#4280]
### Summary
when using Any java.lang.IllegalStateException: Cannot write 0 to Json

### Version
Using the latest version 3.4.0

### Logs
 java.lang.IllegalStateException: Cannot write 0 to Json
        at com.apollographql.apollo3.api.json.-JsonWriters.writeAny(JsonWriters.kt:40)
        at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.toJson(Adapters.kt:173)
        at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.toJson(Adapters.kt:181)

**Comment by martinbonnin** [comment]
Hi 👋 Can you share your code that writes Json? In general `BigDecimal` is not supported by `AnyAdapter` as it's not multiplatform. You can use `JsonNumber` instead:

```kotlin
    val zero = BigDecimal("0")
    val value = buildJsonByteString {
      AnyAdapter.toJson(this, CustomScalarAdapters.Empty, JsonNumber(zero.toString()))
    }
```

**Comment by CompileConnected** [comment]
Thank you now i understand it now
