### ISSUE TITLE
Body Request to json

### ISSUE THREAD

**Issue by DuduFiverrCohen** [apollographql/apollo-kotlin#4281]
Please search the existing resources before asking your question:
- https://github.com/apollographql/apollo-android/issues
- https://community.apollographql.com/tag/mobile
- https://stackoverflow.com/questions/tagged/apollo-android

- Questions are welcome but avoid duplicating issues and discussions. If you'd like a Github issue to be reopen, please leave a message on the issue.

For an informal chat about the project, you can also say hi in the #apollo-android channel in the KotlinLang Slack, channel #apollo-kotlin. You can get your invite at https://slack.kotl.in/.

### Question
Hey 👋,

I'm migrating to v3 from v2.
At v2 we used the method: `operation.composeRequestBody()` this method removed at v3.
Do you know another way to get the composeRequestBody from `Operation` object?

Thanks.

**Comment by martinbonnin** [comment]
Hi 👋 . You can use `composeJsonRequest`. See https://www.apollographql.com/docs/kotlin/advanced/no-runtime/#composing-an-http-request-body for some examples

**Comment by DuduFiverrCohen** [comment]
Thanks for the quick answer.

The `composeJsonRequest` I have required `JsonWriter` object and `CustomScalarAdapters` as parameters.

**Comment by martinbonnin** [comment]
Right! That doc is wrong! I'll fix it in a bit. In the meantime you can do something like this:

```kotlin
val body = buildJsonString {
  query.composeJsonRequest(this, CustomScalarAdapters.Empty)
}
```

**Comment by martinbonnin** [comment]
Documentation updates there: https://github.com/apollographql/apollo-kotlin/pull/4282. Thanks again for catching this and sorry for the inconvenience. Let us know how it works for you!

**Comment by DuduFiverrCohen** [comment]
Working just fine!
Thank you.
