### ISSUE TITLE
parsing Dates without time components

### ISSUE THREAD

**Issue by zebehringer** [apollographql/apollo-kotlin#4286]
### Question
We use Postgraphile for our backend, and many of our tables have `date` columns (just the year month day). Sending GraphQL `Date` types in mutations with Apollo Kotlin works fine, but returning the sent value in the result of that mutation fails with message like "Text '2021-06-04' could not be parsed at index 10". Queries returning dates fail as well. We are using the `com.apollographql.apollo3.adapter.DateAdapter` custom adapter, but I have tried the one for Java Instant as well. Under the hood both use `OffsetDateTime.parse` which uses `DateTimeFormatter.ISO_OFFSET_DATE_TIME` which expects a string with time and zone info.
Is this a backend issue or should the parser be more lenient?

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for reaching out! 

Looks like this is a mission for [`KotlinxLocalDateAdapter`](https://github.com/apollographql/apollo-kotlin/blob/7994350f3d83016666a2bb76c11a1bf2197a6326/apollo-adapters/src/commonMain/kotlin/com/apollographql/apollo3/adapter/KotlinxTimeAdapters.kt#L44)

Or if you want the JVM-only `java.time` equivalent, [`JavaLocalDateAdapter`](https://github.com/apollographql/apollo-kotlin/blob/a430c8ad32b6214ae472e84ac908df678bc9ee59/apollo-adapters/src/jvmMain/kotlin/com/apollographql/apollo3/adapter/JavaTimeAdapters.kt#L36) should work too.

**Comment by martinbonnin** [comment]
The underlying issue you're bumping into is that `2021-06-04`, doesn't tell the time or offset so it's not possible to get a `Date` from it without making assumptions about what time/timezone you want. I'd strongly recommend using the newer `java.time` API instead of `java.util.Date` as they model time much more precisely.

If you absolutely need a `java.util.Date`, you can get one from a `LocalDate` with something like this:

```kotlin
Date(localDate.atStartOfDay().atOffset(ZoneOffset.UTC).toEpochSecond() * 1000)
```

**Comment by zebehringer** [comment]
Yeah, I totally agree about not using java.util.Date

Switching to `JavaLocalDateAdapter` helps resolve this particular issue, so that's nice. But what if I wanted `postgres date` fields represented as LocalDate and `postgres timestamptz` fields as `LocalDateTime`. Can I use `JavaLocalDateAdapter` and `JavaLocalDateTimeAdapter` at the same time, or can there be only one `mapScalar("Date", ...)`?

**Comment by martinbonnin** [comment]
You can only use one adapter for a given custom scalar. If the format returned by your backend sometimes has a time and sometimes doesn't, you'll have to write your own adapter. But I'd encourage you to ask your backend team to use different GraphQL scalars for this. Like maybe `LocalDate` and `LocalDateTime`. Or at least make it clear that if no time is present then some particular time must be assumed like `"00:00"`

**Comment by zebehringer** [comment]
Only now do I see that our `postgres timestamptz` columns are being represented as `Datetime` in GraphQL. I had been assuming they were just `Date`. 🤦 
Thanks again!

**Comment by martinbonnin** [comment]
Sure thing!
