### ISSUE TITLE
Caching with Hasura where's

### ISSUE THREAD

**Issue by gringofe** [apollographql/apollo-kotlin#4288]
### Question

Hi,

I am using Hasura and am trying to use Apollo's SQLite cache, but I'm not quite sure how to handle Hasura's [where arguments](https://hasura.io/docs/latest/queries/postgres/query-filters/#the-where-argument) (how would I cache the second example with two where's?)

**Comment by martinbonnin** [comment]
Hi 👋 

By default, Apollo Kotlin will use a cache key containing the field arguments. For the example on that page:

```graphql
query {
  authors (where: {articles: {rating: {_gt: 4}}}) {
    id
    name
    articles (where: {rating: {_gt: 4}}) {
      id
      title
      rating
    }
  }
}
```

The cache will contain records for these cache keys (pseudo data):

```
"QUERY_ROOT": ...
"authors (where: {articles: {rating: {_gt: 4}}})": ...
"authors (where: {articles: {rating: {_gt: 4}}}).articles (where: {rating: {_gt: 4}})[0]": ...
"authors (where: {articles: {rating: {_gt: 4}}}).articles (where: {rating: {_gt: 4}})[1]": ...
```

If you specify [`id` as keyField](https://www.apollographql.com/docs/kotlin/caching/programmatic-ids/), it will become something like this (pseudo data):

```
"QUERY_ROOT": ...
"Author(1)": ...
"Article(10)": ...
"Article(11)": ...
```

Long story short, in both cases, the cache should work but case 2 will also deduplicate data so that you can use [watchers](https://www.apollographql.com/docs/kotlin/caching/query-watchers).

Is there something in particular that doesn't work in your case?

**Comment by gringofe** [comment]
Hi,

my schema consists of many-to-many table mapping `User`s to `TaskAssignee`s (so a user can view the task of multiple assignees); `TaskAssignee`s can have multiple `Task`s.

My query looks like this:

```
query GetUserAssigneeTasks($after: timestamp!) {
    UserAssignee {
        assigneeRel {
            id
            tasksRel(where: {start: {_gte: $after}}) {
                id
            }
        }
    }
}
```

Apollo crashes with `Suppressed: com.apollographql.apollo3.exception.CacheMissException: Object 'TaskAssignee:3' has no field named 'tasksRel({"where":{"start":{"_gte":"2022-07-22T17:55:58.245"}}})'`

**Comment by martinbonnin** [comment]
Is the `$after` variable changing every time by any chance? If that the case, that will change the cache key and result in a cache miss effectively.

If you really want to cache this, you might be able to workaround with a custom `CacheResolver`:

```kotlin
  // A CacheResolver that ignores the where argument
  object IgnoreWhereCacheResolver : CacheResolver {
    fun CompiledField.nameWithArguments(variables: Executable.Variables): String {
      val arguments = this.arguments.filterNot { it.name == "where" }
      val map = arguments.associateBy { it.name }.mapValues { it.value.value }
      val resolvedArguments = resolveVariables(map, variables)
      return try {
        val buffer = Buffer()
        val jsonWriter = BufferedSinkJsonWriter(buffer)
        jsonWriter.writeAny(resolvedArguments)
        jsonWriter.close()
        "${name}(${buffer.readUtf8()})"
      } catch (e: Exception) {
        throw RuntimeException(e)
      }
    }

    override fun resolveField(
        field: CompiledField,
        variables: Executable.Variables,
        parent: Map<String, @JvmSuppressWildcards Any?>,
        parentId: String,
    ): Any? {
      val name = field.nameWithArguments(Executable.Variables(variables.valueMap.filter { it.key != "where" }))
      if (!parent.containsKey(name)) {
        throw CacheMissException(parentId, name)
      }

      return parent[name]
    }
  }



    // Configure your client with the CacheResolver
    val apolloClient = ApolloClient.Builder()
        .serverUrl(mockServer.url())
        .normalizedCache(MemoryCacheFactory(), cacheResolver = IgnoreWhereCacheResolver)
        .build()
```

Could that work for you?

**Comment by gringofe** [comment]
Yes, you are absolutely right, `$after` uses the current time of the device, thank you!

I just implemented it like they [this](https://github.com/apollographql/apollo-kotlin/issues/4251) so now all `taskRel`s get merged together, but thank you anyway for your suggestion!

**Comment by martinbonnin** [comment]
Yup that works too 👍 . Thanks for the follow up. Ping @BoD that's another use case for `paginationArgs`  👀
