### ISSUE TITLE
'type' is a reserved enum value name

### ISSUE THREAD

**Issue by RoryO** [apollographql/apollo-kotlin#4293]
### Summary
When using a schema that has a `type` field in an enum, the compiler fails at the task `generateServiceApolloSources`. The last Apollo Kotlin release I used prior to upgrading 3.2.0, and this definition worked fine with that version.

It looks like there was something similar or identical in #4023, and was possibly fixed in 3.3.1. This seems like a regression to direct someone to using an experimental feature of overriding schema definitions as suggested in the PR and in the error message.

### Version
3.4.0

### Logs

```
schema.graphqls: (2180, 3): 'type' is a reserved enum value name, please use the @targetName directive to specify a target name
----------------------------------------------------
[2179]:
[2180]:  """
[2181]:  column name
----------------------------------------------------
```

### Steps to reproduce the behavior
Using this exact schema definition, the compiler errors on the `type` field

```graphql
"""
select columns of table "Device"
"""
enum Device_select_column {
  """
  column name
  """
  appBuildNumber

  """
  column name
  """
  brand

  """
  column name
  """
  createdAt

  """
  column name
  """
  id

  """
  column name
  """
  model

  """
  column name
  """
  osVersion

  """
  column name
  """
  personId

  """
  column name
  """
  type

  """
  column name
  """
  uniqueIdentifier

  """
  column name
  """
  updatedAt
}
```

**Comment by martinbonnin** [comment]
Diving into this again, I realized that since we could display the error message, we could do the escaping automatically so I gave it a shot in https://github.com/apollographql/apollo-kotlin/pull/4295. 

@BoD that also relaxes a bunch of validation rules. I think it's ok? Let me know what you think

**Comment by RoryO** [comment]
Thank you for looking at this. That is good insight of working around the issue internally instead of directing someone to do something undocumented. I will continue to use 3.2 until this is resolved.

**Comment by BoD** [comment]
@martinbonnin Yeah this looks good to me 👍  It's good to have `@targetName` but if names can automatically be escaped, it's even better.

**Comment by martinbonnin** [comment]
Hi @RoryO 3.5.0 now automatically escapes `type` to `type_`. Let us know how that goes.

**Comment by RoryO** [comment]
3.5.0 compiles with the same schema without any issues now.

**Comment by martinbonnin** [comment]
Thanks for the update!
