### ISSUE TITLE
input enum how to support int value

### ISSUE THREAD

**Issue by ZuiRenA** [apollographql/apollo-kotlin#4294]
### Question
When I use go to generate code, I get `Value 0 cannot be used in position expecting SortingOrderEnum`
``` graphql
input QuestionListFilterInput {
  orderBy: QuestionOrderByEnum

  sortOrder: SortingOrderEnum = 0

  difficulty: DifficultyEnum
}
```
It's not support default `int` value. But in `query` it's OK.
``` graphql
type Query {
    managementUserFlags(orderBy: SortingOrderEnum = 1, skip: Int!, limit: Int! = 10, " userSlug: String!): UserFlagDetail!
}
```

**Comment by martinbonnin** [comment]
Hi 👋 

Do you mind sharing your schema? According to the [GraphQL Grammar](https://spec.graphql.org/draft/#Name), Enums must start with a letter so that "1" should not be a valid enum value for `SortingOrderEnum`.

**Comment by ZuiRenA** [comment]
@martinbonnin 
Hi 
Sorry, because of the business code involved, I have greatly reduced the code in a state where it can be run as much as possible. you can download it from [here](https://github.com/ZuiRenA/repos/blob/main/question/apollographql:apollo-kotlin/schema.graphqls)

**Comment by martinbonnin** [comment]
Thanks for sending this. Your enum is defined as 

```graphql
enum SortingOrderEnum {
  ASCENDING

  DESCENDING
}
```

I don't think your input definition is valid? According to https://spec.graphql.org/draft/#sec-Enums.Input-Coercion, 

> GraphQL has a constant literal to represent enum input values

So your input value definition should be something like this:

```
input QuestionListFilterInput {
  orderBy: QuestionOrderByEnum

  sortOrder: SortingOrderEnum = ASCENDING

  difficulty: DifficultyEnum
}
```

I'm curious if you have any other tooling that can coerce enum values from their index? Can your schema be parsed on other platforms?

**Comment by ZuiRenA** [comment]
In fact, this is directly obtained from the graphql address of the backend, and it seems to be running fine. This is what puzzles me too, and assigning `0` to `sort_order` in the query will not cause a compile error.

**Comment by martinbonnin** [comment]
> and assigning 0 to sort_order in the query will not cause a compile error.

Even that seems weird. Your schema seems to use `sortOrder` and not `sort_order`. My current guess is that we do not validate this (the schema validations are relatively slim in Apollo Kotlin) but that it wouldn't work as expected.

**Comment by martinbonnin** [comment]
In the short term, I'd recommend you speak to your backend team, see if they have a strong reason to define the schema like this. 
And until this is figured out, you can still commit a modified schema in your Kotlin repo by manually replacing the `0` with `ASCENDING`, that should work

**Comment by ZuiRenA** [comment]
Thanks for your suggestion, it's very useful to me

**Comment by martinbonnin** [comment]
Sure thing! I'll leave this issue open a few days. Let us know if you hear from your backend team. If not I'll close it because this is not supported by the GraphQL spec.

**Comment by martinbonnin** [comment]
Closing for now. Please leave a message if you want us to reopen
