### ISSUE TITLE
Custom adapter reading raw JSON

### ISSUE THREAD

**Issue by boldijar** [apollographql/apollo-kotlin#4297]
We have a new value in our database, that is a scalar of type JSONObject, and I'm trying to parse it with the adapter.

I have the build.gradle config:
```
  customScalarsMapping.set(
        mapOf(
            "UUID" to "kotlin.String",
            "JSONObject" to "kotlin.String"
        )
    )
```
And what I want to do, is parse the JSONObject as String.
And do the parsing later, because this is a experimental json config, that may be different in the future, so I don't want to parse it in the adapter.

The problem is that when creating the adapter, I can read the json like this

```
override fun fromJson(
        reader: JsonReader,
        customScalarAdapters: CustomScalarAdapters
    ): String {

        return reader.toString()
```

But this will return me the json escaped, without the quotes, like this:
'{blabla=true, blabla2=true, blabla=ok, okok=12}'

Is there a way to use the reader to return the raw json?

**Comment by martinbonnin** [comment]
> Is there a way to use the reader to return the raw json?

There is not at the moment but this is something we could look into. As of today, the easiest way is certainly to parse everything to a `Map` and back to a String. Something like this:

```kotlin
    val value = buildJsonString {
      AnyAdapter.toJson(
          this,
          CustomScalarAdapters.Empty,
          AnyAdapter.fromJson(jsonReader, CustomScalarAdapters.Empty)
      )
    }
```

**Comment by boldijar** [comment]
That works perfectly @martinbonnin thank you.
My only problem now is when I'm using the cache.

I've tried this:
  override fun toJson(
        writer: JsonWriter,
        customScalarAdapters: CustomScalarAdapters,
        value: String
    ) {
        writer.value(value)
    }
```

The next time when I'm getting from cache the json will look like this:
```
"{\"aaa\":\"true\",\"bbb\":\"true\",\"ccc\":\"a\"}"
```

Instead of
```
{"aaa":"true","bbb":"true","ccc":"a"}
```

**Comment by martinbonnin** [comment]
That's because you'll need to do the same transformation when writing your String. Something like:

```kotlin
      override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: String) {
        AnyAdapter.toJson(
            writer,
            CustomScalarAdapters.Empty,
            Buffer().writeUtf8(value).jsonReader().use {
              AnyAdapter.fromJson(it, CustomScalarAdapters.Empty)
            })
      }
```

**Comment by boldijar** [comment]
Works perfectly, thank you.
