### ISSUE TITLE
ApolloResponse errors is null

### ISSUE THREAD

**Issue by DuduFiverrCohen** [apollographql/apollo-kotlin#4307]
### Question
Hey ✋, After migrating from v2.5.1 to v3.4.0 I response.errors returned null.

I using `response: ApolloResponse<out Operation.Data>` as response.

And our server response is: 
```json
{
  "errors": [
    {
      "message": "Server Error",
      "extensions": {
        "status": 410,
        "code": "INTERNAL_SERVER_ERROR",
        "path": [
          "orders"
        ]
      }
    },
    {
      "message": "Cannot return null for non-nullable field Query.orders.",
      "extensions": {
        "status": 500,
        "code": "INTERNAL_SERVER_ERROR",
        "path": [
          "orders"
        ]
      }
    }
  ],
  "data": null
}
```

Any ideas about what's wrong?

**Comment by martinbonnin** [comment]
Hi 👋 Looks like some parameter is different, making the server return an error. Can you share your query?

**Comment by DuduFiverrCohen** [comment]
Hi, we make the server return an error so we can check the `response.errors` object.
My question is why does `response.errors` fail to parse the error response?

**Comment by martinbonnin** [comment]
Ah, `response.erros` used to be non-null in `v2.5.1` ?

**Comment by DuduFiverrCohen** [comment]
That's right, all worked perfectly at `v2.5.1`.

**Comment by DuduFiverrCohen** [comment]
`apolloClient.operation(operation).httpHeaders httpHeaders).execute().also {
                        
                        var baseResponse: BaseResponse? = null

                        if (baseRequest.isResponseValid(it)) {
                            // Convert the data to BaseResponse
                            baseResponse = it.data?.let { data ->
                                baseRequest.convertToBaseResponse(data)
                            }

                        }

                        if (baseResponse != null) {
                            onResultListener.onSuccess(baseResponse)

                        } else {
                            // here i want to do some logic with the error but is null it.errors == null!!
                            handleErrorResponse(it, operation, onResultListener)
                        }
                    }`

**Comment by martinbonnin** [comment]
Thanks for sending this 🙏 That looks like it should work indeed. I'll try to setup a small reproducer. In the meantime, it might be worth adding an interceptor to try to see if anything is different on the wire. Something like this:

```kotlin
    ApolloClient.Builder()
        .addHttpInterceptor(LoggingInterceptor())
        .serverUrl("https://...")
        .build()
```

I'll report here if I can reproduce the issue

**Comment by DuduFiverrCohen** [comment]
Thanks.

**Comment by DuduFiverrCohen** [comment]
We do have operation extension we call it before we execute each call: 
`    fun ApolloClient.operation(operation: Operation<*>): ApolloCall<out Operation.Data> {
        return when (operation) {
            is Query -> query(operation)
            is Mutation -> mutation(operation)
            else -> TODO()
        }
    }`

**Comment by martinbonnin** [comment]
Gotcha 👍 . It's something else then but not sure why. Can you check the reproducer? You can run the test from Android Studio or from the command line with `./gradlew test`

**Comment by DuduFiverrCohen** [comment]
Forgot to mention that we using: `useVersion2Compat()` attribute.

**Comment by martinbonnin** [comment]
> And forgot to mention that we using: useVersion2Compat() attribute.

That shouldn't change much. I just updated the reproducer to use it too: https://github.com/martinbonnin/reproducer-4307/commit/0a240f11542e28bfe532c51f548e5eb361c74d36

**Comment by DuduFiverrCohen** [comment]
Hay, the issue is solved.

We had a custom interceptor that didn't pass the errors to the final response.

@martinbonnin thank you for the help,
I'm closing this thread.
