### ISSUE TITLE
Generate Java builders for operations

### ISSUE THREAD

**Issue by dwbutler** [apollographql/apollo-kotlin#4312]
### Use case
At Indeed, we are heavy consumers of GraphQL APIs from Java in backend code. We have used Apollo Android in the past to consume GraphQL APIs. Apollo Android had support for generating convenient builders for operations, variables, and responses. This made it easy to construct operation inputs, and also responses (for unit tests).

Support for Java builders isn't present in Apollo Kotlin. This means that large, complex operation variables and responses have to be constructed using the `new` syntax, which is unwieldy and painful. We've have some engineers revert back to Apollo Android just because of this reason.

### Describe the solution you'd like
We would like for Apollo Kotlin to generate Java builder code for operations, variables, and responses.

**Comment by martinbonnin** [comment]
Released in 3.6.0
