### ISSUE TITLE
Build fails with 3.5.0

### ISSUE THREAD

**Issue by ber4444** [apollographql/apollo-kotlin#4336]
### Summary
`Type com.xxx.data.type.GraphQLBoolean$Companion is defined multiple times: /Users/xxx/StudioProjects/android/data/impl/build/.transforms/89cf263fd4b869150a76b86294d4cd9d/transformed/debug/com/xxx/data/type/GraphQLBoolean$Companion.dex, /Users/xxx/StudioProjects/android/data/api/build/.transforms/b343652318146aacf1716ab0799f7ce5/transformed/debug/com/xxx/data/type/GraphQLBoolean$Companion.dex`

`impl` module depends on Apollo and the `api` module, which in turn also depends on Apollo and has the Apollo plugin with configs. Since both the schema and queries are in `api`, the Apollo plugin is not used in `impl`.

### Version
3.5, fixed by downgrading to 3.4

**Comment by BoD** [comment]
Hi! 👋 

Not sure why you are seeing this. To help us understand, I've created a little repro project [here](https://github.com/BoD/apollo-kotlin-template-2-modules) with 2 modules, `api` with the apollo gradle plugin, and `impl` without, which depends on `api`. Can you tell us if that corresponds to your project, or if there is more to it?

**Comment by BoD** [comment]
Also, this could be an instance of [this issue](https://issuetracker.google.com/issues/223365583) - depending on the version of the Android Gradle Plugin you are using (if was fixed on 7.1.3).

**Comment by ber4444** [comment]
We are using AGP 7.2.1, could you test with that version? Your sample isn't an Android sample, so that might be the source of the issue.

**Comment by BoD** [comment]
Hi! I've updated the repro project to add an Android module, using AGP 7.2.1, which depends on `:impl`. I still can't reproduce the issue on my side, but feel free to fork and tweak the project to bring it closer to your own project, so we can make the issue happen.

**Comment by martinbonnin** [comment]
Hi @ber4444 Do you still have this issue? If you're not applying the `com.apollographql.apollo3` plugin in `impl`, there shouldn't be any `GraphQLBoolean` class generated there. Maybe try deleting the `impl/build` folder and rebuild? Maybe disable build cache if you have it enabled?

**Comment by ber4444** [comment]
Thanks Martin, I think it was a build cache issue
