### ISSUE TITLE
Interceptor with a screen for validating the user

### ISSUE THREAD

**Issue by pradyotprksh** [apollographql/apollo-kotlin#4345]
Hello devs,

**Small Description -** 
Have a requirement where I need to retry the GraphQL request when it gives an error like 401 something.

**Detailed Description -**
I am making a GraphQL request where there is a possibility in the errors I can get an error code with 401-OTP, and whenever this error code is received I want to open an OTP screen. And on the OTP screen when user entered the OTP I need to append that OTP on the same query which gave 401-OTP and retry the call and get the new success response.

Attached an image for reference
![qneBW](https://user-images.githubusercontent.com/35835404/185053477-3fb91ff6-d95f-4d1a-8b6f-aa4bc8eaee41.png)

Please let me know if any more info is needed.

**Comment by BoD** [comment]
Hi!

This can certainly be achieved with an Interceptor, either Apollo or OkHttp. See [this documentation](https://www.apollographql.com/docs/kotlin/advanced/interceptors-http/) on Interceptors. The Interceptor's code can react to the 401 by opening the OTP screen and retry the request, something like this (pseudo-code):

```kotlin
override suspend fun intercept(request: HttpRequest, chain: HttpInterceptorChain): HttpResponse {
    val response = chain.proceed(request)
    return if (response.statusCode == 401) {
      val otp = startOtpScreenAndAwaitResult()
      chain.proceed(request.newBuilder().addHeader("Otp", otp).build())
    } else {
      response
    }
  }
```

**Comment by pradyotprksh** [comment]
thanks @BoD for the response, let me check because I tried but was getting an "Stream closed IO Exception" error.
Will update if works or any other issue.

**Comment by pradyotprksh** [comment]
One more doubt,
In error we also getting the mutation string. I need to change that to the mutation object. Is it possible to change the string to mutation object dynamically?

**Comment by BoD** [comment]
I'm not sure I understand. Do you mean that the backend is replying with the text of the GraphQL mutation that should be sent back by the client, in addition to the OTP? In that case, you don't need to transform it to a `Mutation` object, you could use the text directly by calling `request.newBuilder().body(<the mutation text>)` in your interceptor.
