### ISSUE TITLE
Generate possibleTypes enum for GQLInterface and GQLUnion

### ISSUE THREAD

**Issue by chalermpong** [apollographql/apollo-kotlin#4346]
### Use case

This is an alternative solution for my previous problem #4272.

Handling GQLInterface and GQLUnion will be easier if the generate code provides information about possible types.

For example,
```graphql
# schema
interface ThingWithID {
  id: ID!
}
type Human implements ThingWithID {
  id: ID!
  name: String!
}
type Droid implements ThingWithID {
  id: ID!
  model_name: String!
}
type Query {
  something: ThingWithID
}

# Operation
query TestOperation {
  something {
    id
    ... on Human {
      name
    }
    ... on Droid {
      model_name
    }
  }
}
```
The current way to handle something (using operationBased codegen model):
```kotlin
// current way of doing things
when {
  data.something?.onHuman != null -> {
    data.something.onHuman.name
  }
  data.something?.onDroid != null -> {
    data.something.onDroid.model_name
  }
}
```
The new way to handle something:
```kotlin
// new way of doing things
when (something.__typeEnum) {
  ThingWithID.PossibleTypes.Human -> {
    // something.onHuman?.name
  }
  ThingWithID.PossibleTypes.Droid -> {
    // something.onDroid?.name
  }
  ThingWithID.PossibleTypes.UNKNOWN__ -> {
    // Handle unknown type
  }
}
```
This new code is easier to maintain from the following benefits:
- IDE can help generating code to handle all possible case
- IDE can help detecting missing case when new types are added in schema

### Describe the solution you'd like
In generated GQLInterface/GQLUnion class, add `enum class PosssibleTypes`.
```kotlin
public class ThingWithID {
  public enum class PossibleTypes {
    Human("Human"),
    Droid("Droid"),
    /**
     * Auto generated constant for unknown enum values
     */
    UNKNOWN__("UNKNOWN__"),
    ;

    public val rawValue: String = rawValue

    public companion object {
      public fun safeValueOf(rawValue: String): ThingWithID =
          values().find { it.rawValue == rawValue } ?: UNKNOWN__
    }
  }
}
```
In generated operation code, add a compute field `val __typeEnum`.
```kotlin
public class TestOperation() : Query<TestOperation.Data> {
  public data class Data(
    public val something: Something?,
  ) : Query.Data {
    public data class Something(
      public val __typename: String
    ) {
      // Added compute field
      public val __typeEnum: ThingWithID.PossibleTypes
        get() = ThingWithID.PossibleTypes.safeValueOf(__typename)
    } 
  }
}
```

This solution is less intuitive than my previous solution in #4272, but it should be much easier to implement. If you guy ok with this solution, I can create PR for this feature.

**Comment by chalermpong** [comment]
@martinbonnin Not sure if you guys agree with this idea. Anyway, I just finished my code and sent my PR. I just only implemented for operationBased codegen Kotlin. 

Please let me know if you agree or disagree with this idea.

**Comment by martinbonnin** [comment]
Damn. Very sorry I missed this issue :-(, it fell through the summer notifications.

Overall I like this solution less than #4272 for 2 main reasons:

1. you have to do safe calls on fragments:

```graphql
# query
{
   animal {
      ...catFragment
      ...lionFragment
   }
}
```

```kotlin
// Kotlin usage
when (animal.__typeEnum) {
  Animal.PossibleTypes.Cat -> {
    //  onCat is nullable
    animal.onCat?.name
  }
  Animal.PossibleTypes.Lion -> {
    //  onLion is nullable
    animal.onCat?.name
  }
  // ...
}
```

2. If you have fragments on interfaces you now need when branches for all possible types:

```graphql
# query
{
   node {
      ...animalFragment
      # other fields...
   }
}
```

```kotlin
// Kotlin usage
when (node.__typeEnum) {
  Animal.PossibleTypes.Cat,
  Animal.PossibleTypes.Lion,
  // The list goes on...
  // ...
  // If you have 50 animals in your schema in becomes cumbersome real quick
  Animal.PossibleTypes.Turtle -> {
    //  onCat is nullable
    animal.onCat?.name
  }
  else -> {
    // ...
  }
}
```

All in all, 2. might be acceptable but I think 1. is a dealbreaker. If we're going the type inference route, I would expect as a user that fragments nullability is inferred depending the branch of the `when` I'm in. I'll try to look into what's required to enable this later this week.

**Comment by chalermpong** [comment]
@martinbonnin OK. I also like this idea less than #4272. 

I will cancel this PR soon. But before I cancel this PR, I need some advice on my code (please see my comment in PR).

> All in all, 2. might be acceptable but I think 1. is a dealbreaker. If we're going the type inference route, I would expect as a user that fragments nullability is inferred depending the branch of the when I'm in. I'll try to look into what's required to enable this later this week.

I hope to solve fragments nullability in #4272.

**Comment by martinbonnin** [comment]
> I will cancel this PR soon. But before I cancel this PR, I need some advice on my code (please see my comment in PR).

👍 I do not see a comment in https://github.com/apollographql/apollo-kotlin/pull/4362/files. Did you have a specific question or was it more about the general state of the PR?

**Comment by chalermpong** [comment]
@martinbonnin My question is about implementation. In my code [InterfacePossibleTypeEnumBuilder.kt](https://github.com/apollographql/apollo-kotlin/pull/4362/files#diff-dc78244cc300d6f65fd908d087823f54e913d1d348775707bbe4017e0168a339), I generate and register the new `xxxPossibleTypes` enum class.
```kotlin
internal class InterfacePossibleTypeEnumBuilder(
    private val context: KotlinContext,
    private val iface: IrInterface
) : CgFileBuilder {

  private val simpleName = possibleTypesEnumTypeName(iface.name)
  private val compiledTypeName = "${layout.compiledTypeName(iface.name)}${Identifier.PossibleTypes}"

  override fun prepare() {
    context.resolver.registerMapType(simpleName, ClassName(packageName, compiledTypeName))
  }
```
I'm not sure which registerType function should be used for this enum class (or if it should not be registered at all).

I register this class because I need to use it later when generating compute field in [PossibleTypesEnumCommon.kt](https://github.com/apollographql/apollo-kotlin/pull/4362/files#diff-1df0fb48184e315b23abf7f8b4ec692246d7f7d96781be23f4be9e4be69dd757)
```kotlin
internal fun TypeSpec.Builder.addPossibleTypesEnumField(
    context: KotlinContext,
    model: IrModel
): TypeSpec.Builder {
  return (context.resolver.resolveIrType2(
          IrNonNullType2(IrCompositeType2(possibleTypesEnumTypeName(model.polymorphicTypeName!!))))
      as? ClassName)?.let { possibleEnumType ->
    addProperty(PropertySpec.builder("__type", possibleEnumType)
        .addKdoc("%L", "Synthetic field for enumerable possible type of ${model.polymorphicTypeName}\n")
        .getter(FunSpec.getterBuilder()
            .addCode("return ${possibleEnumType.simpleName}.safeValueOf(${Identifier.__typename})")
            .build()
        )
        .build()
```

**Comment by chalermpong** [comment]
Also, it would be very helpful for me if someone could review my PR and let me know if there is something I should not do.

**Comment by martinbonnin** [comment]
> I'm not sure which registerType function should be used for this enum class (or if it should not be registered at all).

For this use case, you can add a new one: `registerPossibleTypes(name: String, className: ClassName)`/`resolvePossibleTypes(name: String)`.  The idea is that the `ClassName` for a given interface name must be unique for all `requtestPossibleTypes`

> Also, it would be very helpful for me if someone could review my PR and let me know if there is something I should not do.

I'll look into it

**Comment by chalermpong** [comment]
Thank you for reviewing my code. I'll close this issue now.
