### ISSUE TITLE
gradle - Setting the header property on the download graphql schema

### ISSUE THREAD

**Issue by maria-nemeti** [apollographql/apollo-kotlin#4348]
Hello all,

We are currently migrating from apollo 2 to apollo 3 and all went pretty well.
We are using a monorepo with multiple modules and in apollo 2 we had a custom task for downloading graphql schemas :

```
tasks.register("downloadSchema", ApolloDownloadSchemaTask::class) {
	…
    endpoint.set(…)
    schemaRelativeToProject.set(…)
    header = listOf("X-Hasura-Admin-Secret: blablapassword")
}
```

when migrating to apollo 3 we just fail on setting the header on our gradle task

```
tasks.register("downloadSchema", com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask::class.java) {
	…
	endpoint.set(project.properties.getOrDefault(…)
	schema.set(…)
	header.add("X-Hasura-Admin-Secret: blablapassword")
}
```

Any help would be appreciated for setting correctly the header property.
Thanks in advance!
Maria

**Comment by stengvac** [comment]
Maybe more general problem is, that documentation is not available for apollo tasks/config parts in Gradle. So deprecations etc are not visible. 

Lets say I will place config into gradle
```
apollo {
    customScalarsMapping.put("Long", "java.lang.Long")
}
```
which is deprecated according to https://github.com/apollographql/apollo-kotlin/blob/main/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/api/Service.kt

But in gradle I am getting linked only into decompiled class (`Service.class`) without documentation/sources.

**Comment by BoD** [comment]
@stengvac For what it's worth, the doc in question is available [here](https://www.apollographql.com/docs/kotlin/kdoc/apollo-gradle-plugin-external/com.apollographql.apollo3.gradle.api/-service/index.html), but I agree something can probably be done to improve this area of the documentation!

**Comment by maria-nemeti** [comment]
@BoD Thanks a lot for your help, I actually saw that part of documentation, but for some reason I was stuck with the tasks.register in order to keep the name "downloadSchema". But probably I can live with another name as well (but would be nice to be able somehow to keep it).
Here is what I have now in my projectA from the monorepo: 

```
apollo {
    service("safenow") {
        packageName.set("de.safenow.projectA")

        // This should create a downloadSafenowApolloSchemaFromIntrospection task
        introspection {
            endpointUrl.set("project.properties.getOrDefault(…))
            schemaFile.set(file(..))
            headers.set(mapOf("X-Hasura-Admin-Secret" to "blablapassword"))
        }
    }
}
```

For generating the schema for it I run (I guess it's the default generated task name):

```
./gradlew projectA:downloadSafenowApolloSchemaFromIntrospection
```

When executing the previous command, I get the following error:

```
* What went wrong:
A problem occurred configuring project ':projectA.
> Configuring the default service is ignored if you specify other services, remove your configuration from the root of the apollo {} block:
  apollo {
    // remove everything at the top level

    // add individual services
    service("service1") {
      // ...
    }
    service("service2") {
      // ...
    }
  }
```

If removing the line `packageName.set("de.safenow.projectA")`
I get the same error.

**Comment by BoD** [comment]
@maria-nemeti  Do you have any other options in the overall `apollo` block? If not, this definitely shouldn't happen.

In any case, if you have only one service, you don't need a `service` block. If you go back to putting your settings in the main `apollo` block, you will be able to use a task named `downloadServiceApolloSchemaFromIntrospection` (this is because the default service is named "service").

**Comment by martinbonnin** [comment]
About this part:

> in order to keep the name "downloadSchema"

A quick way to do this is to create a new task that points to `downloadServiceApolloSchemaFromIntrospection `:

```kotlin
tasks.register("downloadSchema") {
  dependsOn(":downloadServiceApolloSchemaFromIntrospection")
}
```

For some background there, we'd like to avoid exposing the task classes themselves because they contain a lot of internal plumbing that is really hard to keep backward compatible/track public API.

**Comment by maria-nemeti** [comment]
Thanks you guys for your help, download of the schema works :)
