### ISSUE TITLE
Align @defer v1 implementation with latest proposed spec updates

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-kotlin#4349]
While `@defer` support work is in flight (https://github.com/apollographql/apollo-kotlin/issues/3556), it has been implemented against a now-outdated version of the proposed spec.

This is a placeholder issue for aligning with the latest implementation (`graphql-js` PR here https://github.com/graphql/graphql-js/pull/3659, spec edits PR here https://github.com/graphql/graphql-spec/pull/742)

**Comment by BoD** [comment]
See https://github.com/robrichard/defer-stream-wg/discussions/41

**Comment by jpvajda** [comment]
See https://github.com/robrichard/defer-stream-wg/discussions/50
