### ISSUE TITLE
Subscription state listener

### ISSUE THREAD

**Issue by damienvieira** [apollographql/apollo-kotlin#4355]
### Question
How can you get a subscription's current state on Apollo 3.5?

### Context
Previously on Apollo 2 we could have access through the subscription manager doing the following:

```
 apolloClient.subscriptionManager.addOnStateChangeListener { fromState, toState ->
         if(toState = SubscriptionManagerState.DISCONNECTED) {
              ....
         }
         if (toState = SubscriptionManagerState.ACTIVE) {
             ....
         }
    }
```

**Comment by BoD** [comment]
Hi!

There is no equivalent in 3.x. Did you use this as a way to reconnect automatically? If so, there is now a [`webSocketReopenWhen`](https://www.apollographql.com/docs/kotlin/kdoc/apollo-runtime/com.apollographql.apollo3/-apollo-client/-builder/web-socket-reopen-when.html) lambda that you can set on the `ApolloClient`. If you used it for another reason maybe you can tell us a bit more and try to find a way to do it with v3.

**Comment by damienvieira** [comment]
Hi @BoD, so I'm currently using the [webSocketReopenWhen](https://www.apollographql.com/docs/kotlin/kdoc/apollo-runtime/com.apollographql.apollo3/-apollo-client/-builder/web-socket-reopen-when.html) to reconnect automatically.

Basically I would like to know when my socket is disconnected and when is back to an active state so I know when to fetch from the server the data that should have been delivered during this subscription downtime.

**Comment by BoD** [comment]
Interesting! To know when it is disconnected, `webSocketReopenWhen` would work, but there is no signal for connected.

We could add an API (to be determined) for this, but in the meantime what you could do is have your own implementation of `WebSocketEngine` based on the default one, but adding a listener. Something like this:

```kotlin
// Taken from https://github.com/apollographql/apollo-kotlin/blob/96db33ae93aa6f3417a52267a43d7d1e87a41b36/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/network/ws/OkHttpWebSocketEngine.kt#L18
class MyWebSocketEngine(
    private val webSocketFactory: WebSocket.Factory = OkHttpClient(),
    private val onConnected: () -> Unit
) : WebSocketEngine {

    override suspend fun open(
        url: String,
        headers: List<HttpHeader>,
    ): WebSocketConnection {
        val messageChannel = Channel<String>(Channel.UNLIMITED)
        val webSocketOpenResult = CompletableDeferred<Unit>()

        val request = Request.Builder()
            .url(url)
            .headers(headers.toOkHttpHeaders())
            .build()

        val webSocket = webSocketFactory.newWebSocket(request, object : WebSocketListener() {
            override fun onOpen(webSocket: WebSocket, response: Response) {
                webSocketOpenResult.complete(Unit)
                onConnected()
            }

            override fun onMessage(webSocket: WebSocket, text: String) {
                messageChannel.trySend(text)
            }

            override fun onMessage(webSocket: WebSocket, bytes: ByteString) {
                messageChannel.trySend(bytes.utf8())
            }

            override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) {
                webSocketOpenResult.complete(Unit)
                messageChannel.close(t)
            }

            override fun onClosing(webSocket: WebSocket, code: Int, reason: String) {
                webSocketOpenResult.complete(Unit)

                val t = ApolloWebSocketClosedException(code, reason)
                messageChannel.close(t)
            }

            override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
                messageChannel.close()
            }
        })

        webSocketOpenResult.await()

        messageChannel.invokeOnClose {
            webSocket.close(CLOSE_GOING_AWAY, null)
        }

        return object : WebSocketConnection {
            override suspend fun receive(): String {
                return messageChannel.receive()
            }

            override fun send(data: ByteString) {
                if (!webSocket.send(data)) {
                    messageChannel.close()
                }
            }

            override fun send(string: String) {
                if (!webSocket.send(string)) {
                    messageChannel.close()
                }
            }

            override fun close() {
                webSocket.close(CLOSE_NORMAL, null)
            }
        }
    }

    override suspend fun open(url: String, headers: Map<String, String>): WebSocketConnection =
        open(url, headers.map { HttpHeader(it.key, it.value) })

    private fun List<HttpHeader>.toOkHttpHeaders(): Headers =
        Headers.Builder().also { headers ->
            this.forEach {
                headers.add(it.name, it.value)
            }
        }.build()
}
```

**Comment by damienvieira** [comment]
Great, thank you @BoD!!
That will work, hopefully there will be a cleaner solution later on :)

**Comment by martinbonnin** [comment]
Thinking out loud about the best solution for this problem:

> know when my socket is disconnected and when is back to an active state so I know when to fetch from the server the data that should have been delivered during this subscription downtime.

I think [live queries](https://medium.com/open-graphql/graphql-subscriptions-vs-live-queries-e38302c7ab8e) is the ultimate solution you're looking for (which is neither specified nor implemented yet unfortunately). 

Until we have that nice future-proof technology, I'm wondering if it'd make sense to handle the state "locally" instead of relying on the "global" reconnect. Something like this:

```kotlin
    flow {
      apolloClient.subscription(TripsBookedSubscription())
          .toFlow()
          .onStart {
            // Get the latest "initial" state
            emit(apolloClient.query(GetDataQuery()).toEvent())
          }
          .retry { true }
          .collect {
            emit(it.data)
          }
    }
```

Since the data that you're missing is somewhat related to the subscription, it might make sense to colocate this? Would you mind sharing more details about your use case there?

**Comment by admund** [comment]
Hi @martinbonnin
Any updates about Live Query? I can't find anything related.
