### ISSUE TITLE
How to create CacheKey with Union type

### ISSUE THREAD

**Issue by davidalbers** [apollographql/apollo-kotlin#4366]
### Question
I have a query like:

```
query GetThing {
  thing {
   id
  }
}
```

and I have the CacheKeyGenerator/Resolver set up like:

```
class ExampleCacheKeyGenerator : CacheKeyGenerator {
    override fun cacheKeyForObject(obj: Map<String, Any?>, context: CacheKeyGeneratorContext): CacheKey? {
        val typename = context.field.type.leafType().name
        return when (typename) {
            "Thing" -> CacheKey("$typename:${obj["id"]}")
            else -> null
        }
    }
}

class ExampleCacheResolver : CacheKeyResolver() {
    override fun cacheKeyForField(field: CompiledField, variables: Executable.Variables): CacheKey? {
        val typename = field.type.leafType().name
        return when (typename) {
            "Thing" -> CacheKey("$typename:${field.resolveArgument("id", variables)}")
            else -> null
        }
    }
}
```

Which seems to work fine for caching the query. 

However, there is a mutation that returns a Union of `Thing`:

```
union CreateThingResult = Thing | ThingExistsError
```

The mutation looks something like:

```
mutation CreateThing {
    createThing {
        ... on Thing {
            id 
        }
        ... on ThingExistsError {
            id
            message
        }
    }
}
```

After calling the mutation, `Thing` does not get updated in the cache because typename is `CreateThingResult`, the name of the union. Is there a way to resolve `CreateThingResult` to `Thing` correctly so the cache gets updated?

**Comment by martinbonnin** [comment]
You can use the `__typename` field instead of `leafType.name()`:

```kotlin
class ExampleCacheKeyGenerator : CacheKeyGenerator {
    override fun cacheKeyForObject(obj: Map<String, Any?>, context: CacheKeyGeneratorContext): CacheKey? {
        val typename = obj.get("__typename") 
        return when (typename) {
            "Thing" -> CacheKey("$typename:${obj["id"]}")
            else -> null
        }
    }
}
```

`__typename` will be added in this specific case because you have fragments. If you want to make sure to always query `__typename` set the `addTypename` option in your Gradle config:

```kotlin
apollo {
  addTypename.set("always")
  // 
}
```

**Comment by davidalbers** [comment]
Thanks for the quick reply, that seems to work!

**Comment by ArjanSM** [comment]
Hey @martinbonnin 
Would it make sense to include this [info](https://github.com/apollographql/apollo-kotlin/issues/4366#issuecomment-1234523772) in the documentation and make it more explicit that the `field.type.leafType().name`
would yield unexpected typenames for Union Types?

**Comment by martinbonnin** [comment]
@ArjanSM yes, definitely! Do you want to open a PR? Since you've had the issue first hand, you'll probably voice it better than myself.
