### ISSUE TITLE
Test builders generator breaks when fields are named as language keywords

### ISSUE THREAD

**Issue by francescocervone** [apollographql/apollo-kotlin#4369]
### Summary
I tried to enable test builders but we have a GraphQL field named `package`. Test builders are generated but the resulting code cannot be compiled because package is a reserved word.

### Version
3.5.0

### Steps to reproduce the behavior
* Enable test builders generation https://www.apollographql.com/docs/kotlin/testing/test-builders#enabling-test-builders
* Declare a GraphQL query with at least one field named as a reserved Kotlin keyword like `package`
* Generate the Apollo sources and compile the module

### Additional information
Apollo standard generator uses backticks to handle situations like this
```kotlin
`package`
```
This behavior might be ported also on the test builders generator.

**Comment by martinbonnin** [comment]
Thanks for sending this! We're in the process of finalizing [data builders](https://github.com/apollographql/apollo-kotlin/issues/4016) as a simpler replacement for test builders. Any chance you can [try the `-SNAPSHOTS`](https://github.com/apollographql/apollo-kotlin#snapshots) and see if it's working any better?

**Comment by martinbonnin** [comment]
You can enable them with 

```
apollo {
  generateDataBuilders.set(true)
}
```

**Comment by francescocervone** [comment]
Thanks @martinbonnin. Yes, it works!

**Comment by martinbonnin** [comment]
@francescocervone mind if I close this one?

**Comment by francescocervone** [comment]
@martinbonnin not at all.
