### ISSUE TITLE
Document hasNext: False response case

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-kotlin#4373]
Relates to https://github.com/apollographql/router/issues/1687

I think it's fine to release as-is and let users debounce for now. Functionality is still there. It's just sub-optimal. Users can still call `.watch()`, they just get an extra event in the initial Flow.  

Though we should document how handle this case in our preliminary `@defer` [documentation](https://github.com/apollographql/apollo-kotlin/blob/88a602faa7041985eb57c758e3ec5b268310ff58/docs/source/fetching/defer.mdx)

**Comment by martinbonnin** [comment]
I added a paragraph in https://github.com/apollographql/apollo-kotlin/commit/56cc68a3730f0ad20572ea23dbcfbee4722ceb84. Let me know what you think
