### ISSUE TITLE
Which maven coordinates should be included in refreshVersions

### ISSUE THREAD

**Issue by thederputy** [apollographql/apollo-kotlin#4381]
Hi!  I'm working on adding built-in dependencies for this project in the refreshVersions plugin in this issue: https://github.com/jmfayard/refreshVersions/issues/518

Looking at the artifact list [here](https://mvnrepository.com/artifact/com.apollographql.apollo), [here](https://search.maven.org/search?q=g:com.apollographql.apollo) and browsing the 3.0 documentation, here is the list that I have come up with:

```
apollo-adapters
apollo-api
apollo-ast
apollo-cache-interceptor
apollo-http-cache
apollo-idling-resource
apollo-mockserver
apollo-mpp-utils
apollo-normalized-cache
apollo-normalized-cache-sqlite
apollo-runtime
apollo-runtime-kotlin
apollo-rx2-support
apollo-rx3-support
apollo-testing-support
```

Is this a sufficient list to be included as built-in dependencies, or are there some that I might be missing?
For the multi-platform supported artifacts, does it make sense to expose all platforms via refreshVersions, or would exposing just the Kotlin ones be sufficient?

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for looking into this! 

> Is this a sufficient list to be included as built-in dependencies, or are there some that I might be missing?

You can remove `apollo-runtime-kotlin`, `apollo-cache-interceptor`, `apollo-rx2-support` and `apollo-rx3-support`. There are legacy artifacts that are not supported anymore.

FWIW, 95% of users typically only use `apollo-runtime` with optional `apollo-normalized-cache` and/or `apollo-normalized-cache-sqlite`. I'll leave the decision whether to include the others up to you. It's exhaustiveness at the price of more complexity. But I guess exhaustiveness is more correct?

> For the multi-platform supported artifacts, does it make sense to expose all platforms via refreshVersions, or would exposing just the Kotlin ones be sufficient?

I'd vote for exposing just the Kotlin ones. If anyone needs `-jvm` specifically, we'll make https://github.com/apollographql/apollo-kotlin/issues/4020 work ultimately

**Comment by thederputy** [comment]
The dependency notations have been added in the following PR on the refreshVersions project: https://github.com/jmfayard/refreshVersions/pull/602

Thanks again for your input and support!

**Comment by martinbonnin** [comment]
Nice! Thanks for taking care of this 💙
