### ISSUE TITLE
Kotlin v3 refetchQueries()

### ISSUE THREAD

**Issue by Fi-Taka** [apollographql/apollo-kotlin#4405]
We are in the process of attempting to migrate from v2 to v3. I wasn't able to find a replacement for this `refetchQueries()` call when performing mutations - is this call planned to be reimplemented soon in v3? If not, is there a recommended alternative here?

```
com.apollographql.apollo.ApolloMutationCall.Builder<T>
@NotNull ApolloMutationCall.Builder<T> refetchQueries(@NotNull java.util.List<com.apollographql.apollo.api.Query> queries)
Sets a list of Query to be re-fetched once this mutation completed.
```

**Comment by martinbonnin** [comment]
Hi 👋 

`refetchQueries()` was not added in v3 because we found that most of the times coroutines gave a better API and more control over caching and error handling and concurrency. For a simple version, you can do something like this:

```kotlin
  suspend fun <MutationData: Mutation.Data> mutation(mutation: Mutation<MutationData>, vararg refetchQueries: Query<*>) {
    apolloClient.mutation(mutation).execute()
    refetchQueries.forEach {
      apolloClient.query(it).execute()
    }
  }  
```

If you want to bind the refetches to the scope of your ApolloClient, you can do:

```kotlin
  suspend fun <MutationData: Mutation.Data> mutation(mutation: Mutation<MutationData>, vararg refetchQueries: Query<*>) {
    apolloClient.mutation(mutation).execute()
    apolloClient.executionContext[ConcurrencyInfo]!!.coroutineScope.launch {
      refetchQueries.forEach {
        apolloClient.query(it).execute()
      }
    }
  }
```

**Comment by martinbonnin** [comment]
Hi @Fi-Taka did that help? If yes, I'll add this to the migration guide. If not, let us know and we'll dive deeper into this.

**Comment by Fi-Taka** [comment]
@martinbonnin Yup, that's perfect and exactly what I was looking for, appreciate the explanation! Adding this to the migration guide sounds great as well, please do 👍
