### ISSUE TITLE
Input fromNullable failing to send null fields on mutation

### ISSUE THREAD

**Issue by Byakko** [apollographql/apollo-kotlin#4438]
### Summary
A nullable field within an input object, when set to null, is incorrectly omitted on the actual query.  A field with a value of null was expected.

### Version
Initially attempted on version 2.5.11.  Persisted after updating to version 2.5.13.

### Steps to reproduce the behavior
Based on this section of the schema:
  ```
    {
        "kind": "INPUT_OBJECT",
        "name": "AddressInput",
        "description": "",
        "fields": null,
        "inputFields": [
          {
            "name": "addressLine1",
            "description": "Address Line 1",
            "type": {
              "kind": "NON_NULL",
              "name": null,
              "ofType": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              }
            },
            "defaultValue": null
          },
          {
            "name": "addressLine2",
            "description": "Address Line 2",
            "type": {
              "kind": "SCALAR",
              "name": "String",
              "ofType": null
            },
            "defaultValue": null
          },
```
addressLine1 is specified as non-null. addressLine2 is allowed to be null.
The resulting input object thus looks like this, as expected:

```
        public AddressInput.Builder addressLine1(@NotNull String addressLine1) {
            this.addressLine1 = addressLine1;
            return this;
        }

        public AddressInput.Builder addressLine2(@Nullable String addressLine2) {
            this.addressLine2 = Input.fromNullable(addressLine2);
            return this;
        }
```
Now, for the field of concern, addressLine2, the documentation states:
```
    /**
     * Creates a new [Input] instance that is always defined for any provided [value].
     */
    @JvmStatic
    fun <V> fromNullable(value: V?): Input<V> {
      return Input(value, true)
    }

```
```
/**
 * A wrapper class to provide a [value] with a [defined] state.
 *
 * Wrapper can be in one of 2 states:
 * - *defined* (`defined == true`) means reference to [value] is set explicitly
 * - *undefined* (`defined == false`) means reference is not set.
 *
 * It provides a convenience way to distinguish the case when [value] is provided explicitly and should be
 * serialized (even if it's null) and the case when [value] is undefined (means it won't be serialized).
 */
class Input<V> internal constructor(
    @JvmField val value: V?,
    @JvmField val defined: Boolean
) { ...

```
**"the case when [value] is provided explicitly and should be serialized (even if it's null)"**

This is my use case.  With the following builder I would thus expect a query sent to the server with addressLine2 having a value of null.

```
    AddressInput
            .builder()
            .addressLine1("some address line 1")
            .addressLine2(null)
            ...
            .build()
```

However, instead addressLine2 is omitted on the mutation sent to the server.
This has been observed based on the server response, as well as direct observation of the call using Charles.

**Comment by martinbonnin** [comment]
Hi 👋 sorry that slipped through my notitifications yesterday. Do you mind sharing more of your test code? I just[ tried to reproduce](https://github.com/martinbonnin/test-4438/blob/main/src/test/java/MainTest.java) without success so far.

Could it be that you're calling `marshall` manually? If you do, you'll need to set `setSerializeNulls(true)` on your `JsonWriter` to ensure the nulls are sent over the network.

**Comment by Byakko** [comment]
@martinbonnin 
That was a very astute guess.  While that's not exactly what we're doing, it was enough to point me in the right direction, thanks!

In our case we are using the GsonBuilder() class, and needed to make use of:
```
  /**
   * Configure Gson to serialize null fields. By default, Gson omits all fields that are null
   * during serialization.
   *
   * @return a reference to this {@code GsonBuilder} object to fulfill the "Builder" pattern
   * @since 1.2
   */
  public GsonBuilder serializeNulls() {
    this.serializeNulls = true;
    return this;
  }
  ```
  Thanks again for the quick reply, and feel free to close/remove this, as it's not actually an issue with apollo.
