### ISSUE TITLE
Conflicting declarations happens when name of a field and name of its type are identical

### ISSUE THREAD

**Issue by abbas-oveissi** [apollographql/apollo-kotlin#4447]
### Summary
"_Conflicting declarations_" happens when there is a field whose name and its type's name are identical. Build failed with this error:
`Conflicting declarations: public final data class City, public final val City: AddressFragment.City?`

### Version
v3.6.2

### Steps to reproduce the behavior
"_Conflicting declarations_" happens when there is a field whose name and its type's name are identical. e.g. see below schema, there is a `City field` in the `Address type`, also type of `City field` is `City type`.

```
type Address {
    ID: Uint64!
    Title: String
    Address: String!
    City: City
}

type City {
    ID: Uint64!
    Name: String!
}
```

In Apollo v2, because Apollo's compiler converted the field's first characters to lowercase in the generated models, everything worked fine. But in the V3, the generated code is like this:

```kotlin
public data class AddressFragment(
  public val ID: Any,
  public val Title: String?,
  public val Address: String,
  public val City: City?,
) : Fragment.Data {
  public data class City(
    public val __typename: String,
    /**
     * Synthetic field for 'CityFragment'
     */
    public val cityFragment: CityFragment,
  )
}
````
So build failed with this error:
`Conflicting declarations: public final data class City, public final val City: AddressFragment.City?`

Is there any workaround or Gradle config to solve this issue?

**Comment by BoD** [comment]
Hi! Thank you for reporting this.

Indeed, there is a check in the Apollo compiler for this but it doesn't report this case with fragments.

We could add an option to the compiler to generate the fields as lowercase (like this was done in v2) for this case.

In the meantime, one thing you could do is use aliases in your fragment selections, for example:

```graphql
fragment AddressFragment on Address {
    Address
    city: City {
        name: Name
    }
}
```

**Comment by abbas-oveissi** [comment]
> We could add an option to the compiler to generate the fields as lowercase (like this was done in v2) for this case.

It would be great if an option is added to the compiler.


> In the meantime, one thing you could do is use aliases in your fragment selections, for example:

Thanks, it works. I will close this issue and use your solution.

**Comment by BoD** [comment]
Thanks! I've created a ticket to follow this [here](https://github.com/apollographql/apollo-kotlin/issues/4449).

**Comment by BoD** [comment]
There is now a `decapitalizeFields` option. This will be in the next release, in the meantime it can be tried out with the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots).

**Comment by abbas-oveissi** [comment]
@BoD 
Wow, So fast, Thanks a lot!
Do you have any estimation of when I can use this option in a stable release?
I mean should I refactor my code base to use your workaround or I can use this option very soon?

**Comment by BoD** [comment]
Hi @abbas-oveissi! A new release should happen in the coming weeks - in the meantime if you can try the snapshots to make sure it works as intended, that would be terrific!

**Comment by abbas-oveissi** [comment]
@BoD 
Sure, I will test it and write the result here.

**Comment by abbas-oveissi** [comment]
@BoD 
I tested the decapitalizeFields option and It works as expected. I didn't find any bugs or issues. 

However I don't know if it's important or not, but just FYI, I had two other issues during the migration process:
1- I had to change all codes that are related to Enum because as written in the migration document, Apollo V2 always converts enums and enum value names to uppercase, But Apollo V3 uses the schema case. Maybe another compiler option can help developers to migrate Apollo V3 easier.

2- Changing [this line](https://github.com/apollographql/apollo-kotlin/blob/b65d282af2e60ef9e2f98bcbfaa6f35181d6ab2a/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/internal/json/Utils.kt#L36) in [Utils.kt Apollo V2](https://github.com/apollographql/apollo-kotlin/blob/b65d282af2e60ef9e2f98bcbfaa6f35181d6ab2a/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/internal/json/Utils.kt) into [this line](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/JsonWriters.kt#L40) in [JsonWriters.kt Apollo v3](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/JsonWriters.kt) causes an exception in our app, and took time from me to find why the error happened. If there is input like this in Schema:
```
input ListRequest {
    Page: Int
    PageSize: Int
    Filter: Map
    Search: Map
 }
 ```
 In V2, Apollo called ".toString()" for values of Map which aren't primitive, but V3 raised an exception. Maybe it's better to note this on the Migration document too.

**Comment by BoD** [comment]
Good to hear that this worked for you, thanks for the feedback!

About the enums, this could be done but would add another compiler option which we try to avoid when possible. 

Thanks for the feedback about the change in how Any is handled. Just to check: you didn't define an adapter for your `Map` custom scalar, right? In that case `AnyAdapter` is used by default which has the behavior difference from v2 that you saw. We can definitely put a warning about this in the migration guide.

**Comment by abbas-oveissi** [comment]
@BoD 
Sorry for the late reply.
> Good to hear that this worked for you, thanks for the feedback!

Thanks to you

> About the enums, this could be done but would add another compiler option which we try to avoid when possible.

I understand. Just maybe it is worth mentioning it in the "The quick route 🚀" section.

> Thanks for the feedback about the change in how Any is handled. Just to check: you didn't define an adapter for your Map custom scalar, right? In that case, AnyAdapter is used by default which has the behavior difference from v2 that you saw. We can definitely put a warning about this in the migration guide.

No, we didn't define a custom adapter for `Map`, because it doesn't have a fixed structure and we can't use an adapter for all variations.
As a workaround, I think based on your suggestion, I can create a custom adapter for `Map` with the old V2 implementation to convert Any fields, I think this way our problem will be solved.
