### ISSUE TITLE
Have a way to share mock data between multiple requests

### ISSUE THREAD

**Issue by davidshepherd7** [apollographql/apollo-kotlin#4453]
### Use case
A clear and concise description of what the problem is. 

I'm trying to figure out a robust way to share mock data between multiple requests. A lot of our requests query different things about the currently logged in user. So ideally we would be able to do something like this:

```
val user = Builder(__CustomScalarAdapters).run {
    buildUser {
        contactMobile = "+2217730634835"
        // etc, lots of setup 
    }
}

addMockResponse(LoginMutation, LoginMutation.Data(fakeResolver) { user = user })
addMockResponse(PermissionsQuery, PermissionsQuery.Data(fakeResolver) { user = user })
addMockResponse(AnnouncementsQuery, AnnouncementsQuery.Data(fakeResolver) { user = user })
// ^ not actually this simple, but this gives the idea
```

But this code has a problem: anything generated by the fake resolvers will be different for the different responses even though it's supposed to be the same user. 

If we specified every field in the builder then there would be nothing generated by the fake resolver so this would work. But a big draw of databuilders is that you don't need to specify fields that you don't care about, and they will just get some sensible value.

### Describe the solution you'd like

We came up with two ideas for solutions:

#### Seed arguments

Builders have an optional seed argument which is passed to the fake resolver, fake resolvers should generate the same value given the same seed

e.g.
```
val user = Builder(__CustomScalarAdapters).run {
    buildUser(seed = "42") {
        contactMobile = "+2217730634835"
        // etc, lots of setup 
    }
}
```

This has the advantage that it fits quite well into the current API. But the disadvantage is that if you want to use fixed seeds you'd need to be careful when writing fake resolvers.

#### Run fake resolvers at data object build time

Currently fake resolvers run when generating the response, but we could also/instead run them at the end of e.g. buildUser and fill the generated objects into the map which buildUser outputs.

e.g.

```
val user = Builder(__CustomScalarAdapters, fakeResolver).run {
    buildUser {
        contactMobile = "+2217730634835"
        // etc, lots of setup 
    }
}
```

The advantage of this is that it's simpler: the fake generated values are simply stored alongside the other values. Unfortunately it would require a breaking change to the current fake resolvers API because at this point we don't know what the `path` will be (and the path is currently provided to the fake resolver when it runs).

(Note: I don't fully understand this part, this is from discussion in slack with Martin) Another potential problem is around aliases, consider:

```
{
  viewer {
    personalPhone: phone(PERSONAL)
    professionalPhone: phone(PROFESSIONAL)
  }
}
```
Here we don't know about the alises `personalPhone` and `professionalPhone` at the time when we run buildUser (we only know that there is a `phone` field), so we can't set fake values for them there.

**Comment by martinbonnin** [comment]
Turns out both our options would not work 🙃 

**Seed arguments** do not work because depending the queries, the selections might be different and the number of calls to `resolveLeafFields` would differ. For an example:

```kotlin
val user = Builder(__CustomScalarAdapters).run {
    buildUser(seed = "42") {
        contactMobile = "+2217730634835"
    }
}
```

```graphql
# query1
{
  user {
    field1
    contactMobile
    field3
  }
}

# query2
{
  user {
    # not querying field1
    contactMobile
    # because a call to resolveLeafField is missing, field3 will actually have the value of field1
    field3
  }
}
```

**Run fake resolvers at data object build time** does not work because objects can have cycles. For an example:

```
type User {
  contactMobile: String!
  # Oopsie, if we try to fake this one, we're looping forever. Only actual queries break that cycle
  friend: User
}
```

I made another attempt there: https://github.com/apollographql/apollo-kotlin/pull/4468

It exposes `cacheKey` in `FakeContextResolver` and makes `DefaultStateResolver` stateless so that the values are derived from `cacheKey` (mainly uses `hashCode()` at the moment). It works with the [`@typePolicy` directive](https://www.apollographql.com/docs/kotlin/caching/declarative-ids) so that if you specify id, all the child fields of this object will have deterministic values:

```kotlin
val user = Builder(__CustomScalarAdapters).run {
    buildUser {
        // specifying the id makes sure that all sibling fields will have deterministic values 
        id = "42"
    }
}
```

Writing this, I realize that not everyone will use `@typePolicy` so we'd need another API to do things more pragmatically. I'll revisit shortly but wanted to get your feedback. Let me know how that sounds to you.

**Comment by davidshepherd7** [comment]
Hi, thanks so much for thinking about and working on this! :pray:

Yeah I think using things derived from the cacheKey sounds like a good approach: since the cacheKey is already used to define "object identity" it seems sensible to reuse it here for the same thing.

I can't think of any kind of data that couldn't be generated deterministically from a hash of the cache key. Numbers are obviously easy, but anything can be done by having an array of possible values and then doing something like `values[hash(cacheKey) % values.length()]`. Might be good to document or even provide a default implementation which does this though if we expect most people to use that approach? It's a fairly subtle thing to figure out on your own.

It might be good to have an (opt-in) way to prevent it from generating new values where the dev expects to be the same, e.g. by enforcing that the cacheKey field(s) is/are explicitly set in every call to a builder. I think for Wave's version of this we can just make the fakeResolver throw if asked to generate an ID (because all of our cacheKeys are IDs and all/almost all of our IDs are cacheKeys). I'm not sure if this is solvable in more general cases though since the CacheKeyGenerator can run arbitrary code to create a key.

Re typePolicy: will code that uses `CacheKeyGenerator` work in the same way? We use a CacheKeyGenerator which returns the field named `id`.
