### ISSUE TITLE
Generate base `interface` for `__typename` operations

### ISSUE THREAD

**Issue by agrosner** [apollographql/apollo-kotlin#4456]
### Use case
When using ` addTypename.set("always")`, Apollo generates models all with `__typename` fields. 
These fields are unique to each fragment, query data, etc. We want to capture those field names for debugging / logging purposes easily in a unified way. :
```kotlin
public data class SomeType(
  public val __typename: String,
  public val title: String,
) : Fragment.Data
```

```kotlin
public data class AnotherType(
  public val __typename: String,
  public val title: String,
) : Fragment.Data
```

We cannot find a common interface to easily do this, and have to manually switch on each instance of fragment , which is not safe and prone to error:
```kotlin
fun logTypeName(input: Fragment.Data) {
 when(input){ 
  is SomeType -> input.__typename
  is AnotherType -> input.__typename
  else -> error("Unhandled fragment type")
 }
} 
```

### Describe the solution you'd like

Create an `interface`:

```kotlin
interface HasTypeName {
  val typename: string
}
```

that all generate files implement if:
1.  ` addTypename.set("always")`
2. Or `__typename` is requested in the query:
```graphql
query SomeQuery {
  user {
     __typename
   }
}
```

Then

```kotlin
public data class SomeType(
  public override val __typename: String,
  public val title: String,
) : Fragment.Data, HasTypeName
```

```kotlin
public data class AnotherType(
  public override val __typename: String,
  public val title: String,
) : Fragment.Data, HasTypeName
```

 `logTypename` becomes:

```kotlin
fun logTypeName(input: HasTypeName)  = input.__typename 
```

**Comment by martinbonnin** [comment]
Thanks for sending this 🙏 . I'd love this to be another use case of https://github.com/apollographql/apollo-kotlin/issues/4026. 
We're currently thinking of an API that would expose the KotlinPoet typeSpecs before actually writing them so that you have the chance to patch them. This would allow to experiment with this kind of things without having to make a new release of apollo every time and more generally be more flexible in what is generated. Any thoughts about this?

**Comment by martinbonnin** [comment]
@agrosner You can know use the `KotlinCompilerHooks` API from `3.7.0` to do so. You can find an example in the integration tests: https://github.com/apollographql/apollo-kotlin/blob/fb51dafaa4b02a55b6926546927d176078513543/tests/compiler-hooks/build.gradle.kts#L134

Let us know how that works for you.

**Comment by agrosner** [comment]
woah @martinbonnin this is so cool. ill have to try this out when we upgrade. we're on 3.5.0 at the moment, but in process of upgrading this week.

**Comment by agrosner** [comment]
I apologize for not responding so fast previously

**Comment by martinbonnin** [comment]
No worries at all, let us know what you think!

**Comment by martinbonnin** [comment]
I'm going to close this one for now, feel free to comment if the `KotlinCompilerHooks` solution doesn't work and we'll dive more.

**Comment by agrosner** [comment]
Oh thanks for reminding me. We are using the compiler hooks with success. Thank you!
