### ISSUE TITLE
[Data Builders] Generating classes which are not used in queries

### ISSUE THREAD

**Issue by AKJAW** [apollographql/apollo-kotlin#4457]
### Summary
I'm working on a Multiplatform [multi-module](https://www.apollographql.com/docs/kotlin/advanced/multi-modules/) project, where I have two "feature" modules with queries and fragments and one "base" module which contains the schema and shared fragments. 

Everything worked good while using [Test Builders](https://www.apollographql.com/docs/kotlin/testing/test-builders/), however I've encountered a limitation caused by the fact that the test builders are only visible in the test package (commonTest) making it invisible outside the module.

To try and solve this I used [Data Builders](https://www.apollographql.com/docs/kotlin/testing/data-builders/) which from the description should solve this issue. 

### Version
I tried on:
3.6.0
3.6.1
3.6.2

### Steps to reproduce the behavior
After adding `generateDataBuilders.set(true)` to feature1 module, the code did not compile because some required classes where not present e.g. *SomeType*Map:
```
Unresolved reference: TagMap
```
I noticed that this happens only for types which are declared in alwaysGenerateTypesMatching (even for types which are not used in the feature1 module)

I tried fixing it by adding `generateDataBuilders.set(true)` to feature2 module, however I got a lot of errors like:
```
Cause: duplicate Type 'ResolverKey(kind=Schema, id=*SomeName*)' generated in modules: feature1,feature2
Use 'alwaysGenerateTypesMatching' in a parent module to generate the type only once
```

This happened over and over, so I wanted to quickly resolve it by adding
```kotlin
    alwaysGenerateTypesMatching.set(
        listOf(
            ".*",
        )
    )
```
However this resulted the following error:
```
Cause: duplicate Type 'ResolverKey(kind=Schema, id=)' generated in modules: feature1,feature2
Use 'alwaysGenerateTypesMatching' in a parent module to generate the type only once
```
I tried adding an empty string to alwaysGenerateTypesMatching, but it did not work. And I got the same error

From my understanding Data Builders generate builders for all available types, even the ones which are not used. This causes some problems for multi-module project because all of the types need to be in alwaysGenerateTypesMatching (not sure, just guessing).

Would it be possible for Data Builders to work like Test Builders, and only generate the builders for types which are used in the feature modules?

PS. also https://www.apollographql.com/docs/kotlin/testing/data-builders/ GitHub issue link enters the title [Test Builders]

**Comment by martinbonnin** [comment]
Thanks for catching this. Looks like it's a matter of enforcing that the `generateDataBuilders` property is the same in all modules. Can you try to add `generateDataBuilders.set(true)` to your schema module?

> Would it be possible for Data Builders to work like Test Builders, and only generate the builders for types which are used in the feature modules?

Data Builders generate actually a lot less code than Test Builders, which was one of the main motivation for going this route. Instead of generating builders based on your operations Json response, it only generates a thin `Data{}` method that is reusing the schema-based builders. It's a lot less code generated (see https://github.com/apollographql/apollo-kotlin/issues/3144).

> PS. also https://www.apollographql.com/docs/kotlin/testing/data-builders/ GitHub issue link enters the title [Test Builders]

Yikes, good catch 🙏 . Fixing this now.

**Comment by AKJAW** [comment]
Thanks for the quick response!

After adding `generateDataBuilders.set(true)` to all modules, everything is compiling. In hindsight I should've thought of  that since the "base" module also needs to create some of the builders 😆 

As for the code gen, I wasn't aware, it was just my hunch which turned out to be wrong 😛 

Thanks a bunch for this, much appreciated. As for resolving this issue, maybe it might be worth specifying this requirement in the documentation for the test builder? I was going off on what I did previously with the test builders, where it wasn't a required to add the test generation to the schema module

**Comment by martinbonnin** [comment]
> might be worth specifying this requirement in the documentation for the test builder

I think we can enforce that through Gradle. Ideally, we want to throw a nice actionable error message if that ever happens so that there's no need to go to the documentation. I'll take a stab at this and update this thread!

**Comment by martinbonnin** [comment]
With #4462 , this will now fail with the following message: 

```
Execution failed for task ':feature1:generateServiceApolloSources'.
> Apollo: set `generateDataBuilders.set(true)` in upstream module 'schema' in order to use data builders from current module 'feature1'
```

**Comment by AKJAW** [comment]
Great! I'm sure it will help speed things up when implementing the Data builder. I think it's safe to close this now
