### ISSUE TITLE
Query returns null instead of expected array/list

### ISSUE THREAD

**Issue by Emplexx** [apollographql/apollo-kotlin#4460]
I am executing a query in my Android app and the response I get does not match with the response I get from the same query on the Apollo sandbox website

My query: 
```
query ThreadComments($threadId: Int!) {
	Page(perPage: 50) {
		threadComments(threadId: $threadId, sort: ID) {
			comment
			childComments
		}
	}
}
```

Expected response (Apollo sandbox): 
![image](https://user-images.githubusercontent.com/64900852/196134126-7666eb54-f391-4086-a3e3-6feed602219b.png)
![image](https://user-images.githubusercontent.com/64900852/196136418-33639ef7-a820-4a8d-9523-3fe400b6557b.png)
(note that in the array "threadComments" there is an object which holds "comment" and an array "childComments")

The response I get in my app:
```
D/TAG: Data(Page=Page(threadComments=[ThreadComment(comment=It is on apple music under VisualArt's / Key Sounds Label. Might be location specific., childComments=null)]))
```
(childComments is null, even though I'm expecting it to hold an Array/List of ThreadComment like in the expected response above. childComments is expected to be null only when the ThreadComment has no child comments, which is not the case here)

I don't think I'm doing anything wrong, could this be a bug? Is it possible to fix this?

**Comment by BoD** [comment]
Hi!

I am a bit surprised to see the response shown in the screenshot from your query, as in general you should need to specify the specific `childcomments` fields you want returned from your query. Could you share your schema?

**Comment by Emplexx** [comment]
`childComments` does not have any child fields, it is Json in the schema
```
"""Forum Thread Comment"""
type ThreadComment {
  """The id of the comment"""
  id: Int!

  """The user id of the comment's owner"""
  userId: Int

  """The id of thread the comment belongs to"""
  threadId: Int

  """The text content of the comment (Markdown)"""
  comment(
    """Return the string in pre-parsed html instead of markdown"""
    asHtml: Boolean
  ): String

  """The amount of likes the comment has"""
  likeCount: Int!

  """If the currently authenticated user liked the comment"""
  isLiked: Boolean

  """The url for the comment page on the AniList website"""
  siteUrl: String

  """The time of the comments creation"""
  createdAt: Int!

  """The time of the comments last update"""
  updatedAt: Int!

  """The thread the comment belongs to"""
  thread: Thread

  """The user who created the comment"""
  user: User

  """The users who liked the comment"""
  likes: [User]

  """The comment's child reply comments"""
  childComments: Json

  """If the comment tree is locked and may not receive replies or edits"""
  isLocked: Boolean
}
```

**Comment by BoD** [comment]
Thank you! That makes sense with a scalar, and that should work indeed.

Could you configure a logger to have a look at the received payloads? Something like:

```kotlin
    client = ApolloClient.Builder()
        .serverUrl(...)
        ...
        .addHttpInterceptor(LoggingInterceptor())
        .build()

```

**Comment by Emplexx** [comment]
```
I/System.out: Post https://graphql.anilist.co
I/System.out: X-APOLLO-OPERATION-ID: 52ca744c8827b53148d2b34df6e9728d975fe1fdb54797eb37ae5a837fb507ab
I/System.out: X-APOLLO-OPERATION-NAME: ThreadComments
I/System.out: Accept: multipart/mixed; deferSpec=20220824, application/json
I/System.out: [end of headers]
I/System.out: {"operationName":"ThreadComments","variables":{"threadId":60047},"query":"query ThreadComments($threadId: Int!) { Page(perPage: 50) { threadComments(threadId: $threadId, sort: ID) { comment childComments } } }"}
I/System.out: HTTP: 200
I/System.out: date: Mon, 17 Oct 2022 09:50:30 GMT
I/System.out: content-type: application/json
I/System.out: cache-control: no-cache, private
I/System.out: x-ratelimit-limit: 90
I/System.out: x-ratelimit-remaining: 87
I/System.out: set-cookie: laravel_session=SVLjDqWSxItIlhSB4Uhuqe3YV4xCRwLuC2v0ZLOD; expires=Mon, 17-Oct-2022 21:50:30 GMT; Max-Age=43200; path=/; httponly
I/System.out: x-frame-options: SAMEORIGIN
I/System.out: x-xss-protection: 1; mode=block
I/System.out: x-content-type-options: nosniff
I/System.out: access-control-allow-origin: *
I/System.out: access-control-allow-methods: GET, POST, OPTIONS
I/System.out: access-control-allow-headers: Authorization,Accept,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
I/System.out: access-control-expose-headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Content-Length, Content-Range
I/System.out: cf-cache-status: DYNAMIC
I/System.out: report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=KZ9ASYToRSNDVlo5wrfhQnojIiAq1Xkjqu5PI%2FAGrPz15ztZT3EngGC4ZIwPzYxotASYwrw1XhQEkjdOyp9Z%2Bt3oSbdJm8PBuP36EXGdOzvZn7OiZd%2BzsbcN1GuJoGyRfGUSbA%3D%3D"}],"group":"cf-nel","max_age":604800}
I/System.out: nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
I/System.out: server: cloudflare
I/System.out: cf-ray: 75b82160cb3ebb56-FRA
I/System.out: [end of headers]
I/System.out: {"data":{"Page":{"threadComments":[{"comment":"It is on apple music under VisualArt's \/ Key Sounds Label. Might be location specific.","childComments":null}]}}}

```

(I'm not sure if I did this correctly 😅 let me know if the logs you need are supposed to be sent somewhere else)

**Comment by BoD** [comment]
No this is perfect, thanks.

But as we can see in the logs, the value of `childComments` is indeed `null` in the returned payload, so that's consistent with it being also `null` in the object returned by Apollo.

Were you using the same Id and same server in the screenshot above? Or maybe the data has changed since then?

**Comment by Emplexx** [comment]
Yep, it's the same server URL, `threadId` and the data hasn't changed, I'm still getting a correct response in the sandbox 

(it's also not limited to this specific thread, in general it always returns `childComments` as null regardless of if they actually exist or not)

**Comment by BoD** [comment]
I just tried with https://studio.apollographql.com/sandbox/explorer, using `https://graphql.anilist.co/` as the server URL, and also getting a `null` `childComments` with this query:
```graphql
query ThreadComments { Page(perPage: 50) { threadComments(threadId: 60047, sort: ID) { comment childComments } } }
```

```json
{
  "data": {
    "Page": {
      "threadComments": [
        {
          "comment": "It is on apple music under VisualArt's / Key Sounds Label. Might be location specific.",
          "childComments": null
        }
      ]
    }
  }
}
```

What am I missing?

**Comment by martinbonnin** [comment]
FWIW, you can directly link to the operation:

<img width="1045" alt="Screenshot 2022-10-17 at 12 23 49" src="https://user-images.githubusercontent.com/3974977/196154272-ea2ddea4-30f4-4385-b8e5-a31ef33e609d.png">


This gives that link:

https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABACoAWeCAhmAMIRyKoDORwRAClQOYIAUAB3xde6IgFYADAEo2RFBWp0GTFMz4LKNAJJgxANkmSALAHYANEWYQ8KMdoAis9lBXIURKGQCWAG2WM7qwAvkShwSDBQA

**Comment by Emplexx** [comment]
I'm sorry if this is a stupid question, but do query names matter? 

The only difference I noticed between the query in the sandbox and in my app was the name, Page (automatically named by the sandbox) vs ThreadComments. Changing the query name from ThreadComments to seemingly anything that doesn't involve the words Thread or Comment fixes the issue...

**Comment by BoD** [comment]
Wow good catch! I can confirm that using another name does change the result indeed ([null](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABACoAWeCAhmAMIRyKpHBEAKVA5ggBQAO%2BDt3REArAAYAlCyIoK1OgyYoAzjzmUaASTAiAbOPEAWAOwAaIioh4UIrQBFprKEuQoiUMgEsANosZuKkQAviEhIMFAA) / [not null](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABACoAWeCAhmAEwDCEciqRwRAClQOYIAUAB3xde6IgFYADAEo2RFBWphGzZCgDOfBZRoBJMGIBskyQBYA7ABoi6iHhRjdAEVnsoTFiiJQyASwA2yh5q6kQAvuHhIGFAA)).

I am afraid I have no explanation, indeed the name of the operation should not matter 😊.  My wild guess is that it could be an ad-hoc limitation put on some specific requests used by some clients? To know for sure we'd need to talk with the backend team :)

**Comment by Emplexx** [comment]
Thank you for the help! It would not occur to me that the name causes this otherwise 😅 I will mark this as closed now

**Comment by martinbonnin** [comment]
Maybe some server cache somewhere that uses the operation name as a key? If that's the case, you'll need to invalidate these caches
