### ISSUE TITLE
Howto Migrate a Custom ApolloExtension from 2.x -> 3.x?

### ISSUE THREAD

**Issue by jamesonwilliams** [apollographql/apollo-kotlin#4465]
Hey there! We’re working to upgrade from Apollo [2.5.12](https://github.com/apollographql/apollo-kotlin/releases/tag/v2.5.12) to [3.6.2](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.6.2), and we’re using the [Migrating to Apollo Kotlin 3.0](https://www.apollographql.com/docs/kotlin/migration/3.0/) documentation as a guide. Right now we’re stuck on our Apollo Gradle Plugin integration, with a bit of an advanced use case.

We have some custom Gradle code that relies on Apollo Kotlin 2’s [`onCompilationUnit`](https://github.com/apollographql/apollo-kotlin/blob/b711ef9fab9a1b4f9f959d9f4cc629956966acbd/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/api/ApolloExtension.kt#L40) API, which was [removed](https://github.com/apollographql/apollo-kotlin/blob/72bc495c51262b95e0b74fa9f65d85f78289579f/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/api/ApolloExtension.kt#L9) in 3.x. We rely on this hook to integrate into the plugin’s Gradle lifecycle and register additional tasks. Specifically, we use the `serviceName`, `androidVariant`, `operationOutputFile` and `rootPackageName` fields of the [`DefaultCompilationUnit`](https://github.com/apollographql/apollo-kotlin/blob/b711ef9fab9a1b4f9f959d9f4cc629956966acbd/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/DefaultCompilationUnit.kt#L14) when registering tasks.

At a high level, our custom Gradle tasks support our use of persisted IDs on the backend. We register three Gradle tasks inside of `onCompliationUnit`:

1. A task to fetch our GraphQL manifests from our two GraphQL endpoints (Apollo Federation, and an older, monolithic Graphene endpoint.)
2. A task to validate that the client’s current operations have been persisted on both of those endpoints
3. A task to generate Kotlin source files that contain constants for these operation IDs (we use these at runtime when building request bodies.)

We’ve seen the new [`createAllAndroidVariantServices`](https://github.com/apollographql/apollo-kotlin/blob/72bc495c51262b95e0b74fa9f65d85f78289579f/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/api/ApolloExtension.kt#L9) hook, and are thinking that will probably be part of our solution. But we’re struggling to find direct analogs for all four of the fields we’re using– particularly the `androidVariant` which we use to build appropriate names and dependencies when calling `project.tasks.register()`.

We’d appreciate any guidance you could lend on this aspect of the migration!

**Comment by martinbonnin** [comment]
Hi 👋 ! 
For some historical background there, `onCompilationUnit` was called for each variant which means that the codegen would run many times. 4 times by default IIRC (`debug`, `release`, `debugTest`, `debugAndroidTest`). This is a waste in the vast majority of cases because the generated files are all exactly the same. 

What's needed most of the times is to generate the sources only once and then add these sources to the `main` sourceSet. This sourceSet is then included by all different variants.

If you do need different operations/schemas between different variants, you can also use different "services". A service is a schema/a single codegen task. Something like this (wildly untested, will depend your actual needs):

```kotlin
apollo {
  service("debug") {
    // use a debug schema
    schemaFile.set(file("src/debug/graphql/schema.graphqls"))
    srcDir("src/main/graphql")
    packageName.set("com.example")
    outputDirConnection {
      connectToAndroidSourceSet("debug")
    }
  }
  service("release") {
    // use a release schema
    schemaFile.set(file("src/release/graphql/schema.graphqls"))
    // use the same operations as for debug
    srcDir("src/main/graphql")
    packageName.set("com.example")
    outputDirConnection {
      connectToAndroidSourceSet("release")
    }
  }
}
```

But again, you might very well be ok with only one service.

**Comment by martinbonnin** [comment]
Hi @jamesonwilliams anything else we can help with? Were you able to migrate your Gradle files?

**Comment by sforood** [comment]
Hey @martinbonnin, we resolved the original issue, but haven't fully migrated yet due to some additional issues unrelated to Apollo. We can close out this issue. Thanks for your help!

**Comment by martinbonnin** [comment]
Sounds good. Thanks for the update!
