### ISSUE TITLE
Unresolved reference: type after migrate to kotlin version 1.7.20

### ISSUE THREAD

**Issue by juckrit** [apollographql/apollo-kotlin#4483]
After migrate kotlin from 1.7.10 to 1.7.20
I got this error for all apollo generated file

Gradle build failed but I can open ConsentInput and ConsentNameEnumType class in generated file under my libraries package

Screen shot here
https://drive.google.com/file/d/1hCEtASLiZ_6JEG32GeLBR16do-Yboc95/view?usp=sharing

**Comment by martinbonnin** [comment]
Can you try with [latest version](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.6.2)? Kotlin 1.7.20 needed some changes in how we connect the generated sources to the compileKotlin tasks

**Comment by martinbonnin** [comment]
@juckrit Anything else we can help with?

**Comment by juckrit** [comment]
use apollo 3.6.2 instead so problem solved
