### ISSUE TITLE
"java.io.FileNotFoundException", "File name too long"

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4484]
### Summary
Once the nesting of fragments get long, the generated class file will have very long name, build will print error. Once the I deleted some part of the nesting, build works again.

### Logs

Caused by: java.io.FileNotFoundException: /Users/johndoe/android/feature/fancyfeature/build/tmp/kapt3/incrementalData/fastdevDebug/com/xcompany/apollo/fancyfeature/SomeQuery$Data$XXXXXXXXXXXXXXXXXXX$YYYYYYYYYYYYYYYYYYYYY$ZZZZZZZZZZZZZZZZ$AAAAAA$BBBBB$CCCCCCC$DDDDDDD$FFFFFF$GGGGGGG$Android$Companion.class (File name too long)

### Steps to reproduce the behavior

1. Write a deeply nested query.
2. Run ./gradlew generateApolloSources, it will work!
3. Build app, and error.

**Comment by martinbonnin** [comment]
Hi 👋 !
Congrats on bumping into another limitations of the `responseBased` codegen 😅.

There's only so much we can do here. Possible workarounds:
* Use aliases to 'shorten' the name of classes
* Use `flattenModels.set(true)` to flatten models (at the cost of suffixes)
* Use another filesystem that supports file names > 256 chars

**Comment by martinbonnin** [comment]
@ynkm169 I'll close this one for the moment as there is so much we can do. Anyone coming here, please consider using the `operationBased` codegen that will generate more "flat" hierarchies of classes.
