### ISSUE TITLE
generateApolloSources can't find schema because schema download task wasn't run first.

### ISSUE THREAD

**Issue by amansaryal** [apollographql/apollo-kotlin#4491]
### Summary

generate[myService]ApolloSources task is executed without executing download[myService]ApolloSchemaFromIntrospection task first.

This produces the following error:

```
No schema file found in:
src\main\graphql\[myService]
```

Manually running the download task first or configuring gradle build order with the following code fixes the issue.

`generate[myService]ApolloSources.dependsOn download[myService]ApolloSchemaFromIntrospection`

### Version
3.6.2

### Logs

```
> Task :app:generateStagingDebugRootServiceApolloSources FAILED
Execution failed for task ':app:generateStagingDebugRootServiceApolloSources'.
> No schema file found in:
  src\debug\graphql\com\tinvio\odin\rootservice
  src\main\graphql\com\tinvio\odin\rootservice
  src\stagingDebug\graphql\com\tinvio\odin\rootservice
  src\staging\graphql\com\tinvio\odin\rootservice
```

### Steps to reproduce the behavior
Configure a service with introspection and build the project.

### Expected behavior
The task execution order should be: downloadSchema -> generateSources.

**Comment by BoD** [comment]
Hi! As you may not want to re-download your schema every single time you build your project, I believe the current behavior makes sense.

However if that would be useful in your workflow, you may declare a gradle task that depends on both the download and generate source tasks, and run that instead.

**Comment by amansaryal** [comment]
Usually, during a dev cycle, the schema is constantly evolving. So resyncing with every build ensures that there are no gaps in what the client expects and what the server can deliver whenever we do a release. 

I have a custom script in place but it becomes a little boilerplate-y and creates a maintenance overhead when there are a bunch of services in place.
I was hoping if we could have a config flag for this? To explicitly tell apollo to run the corresponding download task for a service before generating code for it.

**Comment by martinbonnin** [comment]
You can make an explicit dependency:

```kotlin
apollo {
  service("service") {
    // ...
  }
}

// Make the codegen task depend on the download schema task to run it every time
tasks.named("generateServiceApolloSource").configure { 
  dependsOn("downloadServiceApolloSchemaFromIntrospection")
}

```

As @BoD said, it's not something we recommend because it makes builds not-reproducible and has a direct performance impact on every build so it's not something we'll make easier to do.

A nice way to handle your schema updates is to commit it in source control and update it from a CI cron job using something like https://github.com/apollographql/update-graphql-schema. This way, your build are reproducible and you get a nice diff about what changes in your schema every night (or whenever you decide 😃 )

**Comment by amansaryal** [comment]
I see. We're still in the early stages of working with a gql backend so I'm yet to find out how the workflow is or isn't affected by continuous syncs but I'll be mindful of what you said.

For now, I guess I'll just go with the task dependency way. Thanks for pointing to the CI action, that's definitely something we could use down the line.
