### ISSUE TITLE
[Data Builders] Fields with aliases are always using Resolver default values

### ISSUE THREAD

**Issue by AKJAW** [apollographql/apollo-kotlin#4493]
### Summary
When a query uses aliases, no matter what value is assigned inside the data builder, the default resolver value is used.

### Version
3.6.2

### Steps to reproduce the behavior
I have an open source repository which illustrates this issue https://github.com/AKJAW/ApolloDataBuilders/tree/alias-issue

Basically after this [commit](https://github.com/AKJAW/ApolloDataBuilders/commit/32434ea1c3478ab63db7a1ff757565ab50ca792e) all of the tests stopped working. 

At [214493b377b1b768ff867194805eb3352ed9db32](https://github.com/AKJAW/ApolloDataBuilders/commit/214493b377b1b768ff867194805eb3352ed9db32)
<img width="394" alt="Screenshot 2022-11-06 at 13 40 09" src="https://user-images.githubusercontent.com/26874608/200171284-8ebdd1ac-26c7-44c5-b7b9-dade4aeabd06.png">

At [32434ea1c3478ab63db7a1ff757565ab50ca792e](https://github.com/AKJAW/ApolloDataBuilders/commit/32434ea1c3478ab63db7a1ff757565ab50ca792e)
<img width="780" alt="Screenshot 2022-11-06 at 13 41 29" src="https://user-images.githubusercontent.com/26874608/200171337-725ce68d-f7a8-4eec-bc4f-e3371ca1be8d.png">

**Comment by martinbonnin** [comment]
Hi 👋 Many thanks for the detailed report 🙏 

I made a follow up PR there: https://github.com/AKJAW/ApolloDataBuilders/pull/1

When using aliases, you'll need to specify the aliases name when building the fake object:

```diff
index ee336a9..0391067 100644
--- a/app/src/test/java/com/akjaw/apollo/builders/domain/GetCountryTest.kt
+++ b/app/src/test/java/com/akjaw/apollo/builders/domain/GetCountryTest.kt
@@ -121,9 +121,9 @@ object Responses {
 
     val SUCCESS =
         CountryQuery.Data {
-            country = buildCountry {
+            this["countrySchema"] = buildCountry {
                 name = "United Kingdom"
-                languages = listOf(
+                this["languagesSchema"] = listOf(
                     buildLanguage {
                         name = "English"
                     }
```

There isn't a way to "guess" the aliases name automatically because the same field can have multiple aliases:

```graphql
{
  poland: country(code: "PL") {
    name
  } 
  france: country(code: "FR") {
    name
  } 
}
```

**Comment by AKJAW** [comment]
I see, must've missed that, maybe it might be worth adding an example with aliases in the docs? I tried finding info about it, but had no luck. Thanks for the quick response and the PR!

**Comment by martinbonnin** [comment]
Makes sense 👍  Doc updates are there: https://github.com/apollographql/apollo-kotlin/pull/4503
