### ISSUE TITLE
Keep getting 400 error with "the JSON object must be str, bytes or bytearray, not dict"

### ISSUE THREAD

**Issue by shumin0809** [apollographql/apollo-kotlin#4510]
### Question
I tried to make query with a custom input but keep getting the error.

Here's my setup:

in schema.graphqls
`scalar Filters`

query.graphql
```
query GetProductsWithFilters(
    $filters: Filters,
) {
    getFramesWithFilter(
        filters: $filters
    ) {
    }
}
```

data class
`class Filters(
    val filters: List<String>? = null
)`

class adapter
```
val filtersAdapter = object : Adapter<Filters> {
    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Filters {
    }

    override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Filters) {
        writer.beginObject()
        writer.name("SIZE")
        writer.beginArray()
        value.filters.forEach{
                 writer.value(it)    
        }
        writer.endArray()
        writer.endObject()
    }
}
```

actual query
```
{"operationName":"GetProductsWithFilters","variables":{"filters":{"SIZE":["large", "small"]}},"query":"query GetProductWithFilters
```

error
```
{"errors":[{"message":"the JSON object must be str, bytes or bytearray, not dict"}]}
```

Any suggestions? should I have backend to update the filters to take a list of array instead of object class? thanks.

**Comment by BoD** [comment]
Hi! 👋

Your Adapter code looks correct, however, with custom scalars, it's hard to know what exact format the server expects. I would suggest to ask the backend team (maybe directly an array instead of an object?).

**Comment by shumin0809** [comment]
> filters: {
>       SIZE: ["large"]
>     }

Nope it doesn't work. 

query
```
query GetProductsWithFilter($filters: Filters) {
  getProductsWithFilter(
    filters: $filters
  ) {
    edges {
      node {
        items {
          id
        }
      }
    }
  }
}
```

variables:
```
{"filters":{"SIZE":["large"]}}
```
{"BRAND":["COACH"]} has highlighted error: expected value of type "Filters"

Interesting, it does look like that variable can't detect Filters type while apply filters directly into the query it can.

**Comment by BoD** [comment]
This is odd indeed. Is this a public server that we could have a look at by any chance?

**Comment by shumin0809** [comment]
Sorry It's private server. But here's the update:

Our backend engineer found the issue, it turned out it's a graphene issue. 
It was assumed that we'd get a string back but it came back as a native dictionary in python. so no parsing was actually required.

Thanks for your context and suggestion :)

**Comment by BoD** [comment]
Thanks for the update! Glad to hear you found the culprit.
