### ISSUE TITLE
Automatic adapters registration

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4515]
In version 3.7.0 and below, custom scalars like `Date` require a custom Gradle configuration and a runtime call to `addCustomScalarAdapter()` to behave correctly. This is all working but it's a bit cumbersome and also means we have to carry `CustomScalarAdapters` all over the place (see https://github.com/apollographql/apollo-kotlin/issues/3823 and data builders have this issue too).

Instead of this, we could do annotation processing using KSP to get the adapters and custom scalars at compile time:

```kotlin
@ApolloAdapter(service = "service", forScalar = "Date")
object DateAdapter : Adapter<Date> {
  override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Date {
    return Date(OffsetDateTime.parse(reader.nextString()!!).toInstant().toEpochMilli())
  }

  override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Date) {
    writer.value(Instant.ofEpochMilli(value.time).toString())
  }
}
```

This means that users will have to instanciate a specific apollo client:

```
val apolloClient = ServiceApolloClient.Builder().serverUrl("https://...").build()
```

Questions:

* How do we make this work with Java?
* Do we need to keep both mechanisms?

**Comment by BoD** [comment]
Part of this done in `apollo-ksp`

**Comment by martinbonnin** [comment]
Closing as unplanned for now. I played with the idea and it's complicated because we would need KSP to run before codegen so that the codegen knows about the adapters. But KSP also wants to know about the generated code so there's a chicken and egg problem. We could move all the codegen to KSP but this has a lot of implications. Closing for now.
