### ISSUE TITLE
`@defer` graduated from experimental to GA

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-kotlin#4525]
The `@defer` feature in Kotlin should no longer be marked as experimental.

**Comment by jpvajda** [comment]
Relates to: #4524

**Comment by martinbonnin** [comment]
The current (Aug 2023) status is that Web is GA and mobile clients stay experimental until `@defer` is in the spec.

**Comment by martinbonnin** [comment]
Closing as not actionable for now. We'll remove the experimental flag when the spec is released.
