### ISSUE TITLE
The POM for com.apollographql.apollo3:apollo-rx3-support-java:jar:3.7.1 is missing, no dependency information available

### ISSUE THREAD

**Issue by doucheng** [apollographql/apollo-kotlin#4530]
### Summary
[POM ](apollo-rx3-support-java:jar:3.7.1 is missing)

### Logs

[Paste your full stacktrace here.](apollo-rx3-support-java:jar:3.7.1 is missing)

### Steps to reproduce the behavior
```xml
<properties>
        <apollo.version>3.7.1</apollo.version>
</properties>

<dependency>
    <groupId>com.apollographql.apollo3</groupId>
    <artifactId>apollo-rx3-support-java</artifactId>
    <version>${apollo.version}</version>
</dependency>
```

https://mvnrepository.com/search?q=apollo-rx3-support-java

**Comment by BoD** [comment]
Closing as the dedicated [Java runtime](https://www.apollographql.com/docs/kotlin/v4/advanced/java) is available to try with the v4 betas. Feedback warmly welcome!
