### ISSUE TITLE
Add support for additional Apple Kotlin Multiplatform Targets

### ISSUE THREAD

**Issue by ScottPierce** [apollographql/apollo-kotlin#4535]
### Use case
The exact same code that is written for ios would also work without modification for many other multiplatform targets.

### Describe the solution you'd like
Without any additional code modification, the following platforms could be supported:
```
iosX64(),
iosArm64(),
iosSimulatorArm64(),
iosArm32(),
tvosArm64(),
tvosX64(),
tvosSimulatorArm64(),
```

and the following platforms could PROBABLY be supported with no modification:
```
macosArm64(),
macosX64(),
```

It probably wouldn't be very difficult to support ALL mac based

**Comment by ScottPierce** [comment]
It appears most or all of these are already supported. It looked like they weren't though based on the multiplatform documentation - https://www.apollographql.com/docs/kotlin/v2/essentials/get-started-multiplatform

**Comment by martinbonnin** [comment]
> https://www.apollographql.com/docs/kotlin/v2/essentials/get-started-multiplatform

This is a link to the 2.x version. [More recent versions](https://www.apollographql.com/docs/kotlin/)(3.x) have wider compatibility
