### ISSUE TITLE
M1 Chip MacBook Support avaiable?

### ISSUE THREAD

**Issue by sam43** [apollographql/apollo-kotlin#4546]
### Question
Do we have support to run this project on M1 chip MacBook yet? Because I am getting some error which are following.

### What is my configuration:
- Have the latest OpenJDK installed from [HomeBrew](https://brew.sh/) version 19.0.1
- Using Android Studio as the IDE (Dophin) including Embedded JDK support

### Error during building the project:
I am encountering the issue in my build log. I have imported the project before in my windows PC and it didn't show such issue there. [Here is the error in build log](https://pastebin.com/NT2EgMd2)

**Comment by martinbonnin** [comment]
Looks like you bumped into https://github.com/apollographql/apollo-kotlin/pull/4492. Can you try forcing the AZUL vendor? 

```
java {
  toolchain.languageVersion.set(JavaLanguageVersion.of(8))
  toolchain.vendor.set(JvmVendorSpec.AZUL)
}
```

**Comment by martinbonnin** [comment]
You can also try with https://github.com/apollographql/apollo-kotlin/pull/4547 (branch `jdk-11`). I think that should fix it.

**Comment by martinbonnin** [comment]
Alright, that did the trick 🎉 . The problem was that Adoptium isn't releasing a JDK8 version of the M1 JDKs. It was only working on the maintainers + CI machines because we had one installed already and Gradle was able to find it.

With #4547, we're using JDK11 everywhere and this one is released for M1. @sam43 let us know how that worked for you!

**Comment by sam43** [comment]
@martinbonnin I will try above solutions and let you know asap. Thanks man 🙏👍🏻

**Comment by sam43** [comment]
Hi @martinbonnin bro, your suggested solutions are working perfectly. Thanks man! take <3

**Comment by sam43** [comment]
@martinbonnin , hey man, I think I am able to run the project now on my machine. Thanks <3
