### ISSUE TITLE
Deprecation warning is printed into output without regard for log levels

### ISSUE THREAD

**Issue by StefanChmielewski** [apollographql/apollo-kotlin#4560]
### Summary

https://github.com/apollographql/apollo-kotlin/blob/8f21601b62ee44873682ff24e04bea855a1967d0/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt#L139

Using a simple print here causes gradle flags like `--quiet` & `--warning-mode` to have no effect, breaking any scripts that rely on clean output. Please consider [logging](https://docs.gradle.org/current/userguide/logging.html#logLevels) it through the built-in SLF4J with the appropriate warning level instead.

### Version

3.7.2

### Steps to reproduce the behavior

Run any gradle task in a project with an apollo extension config

### Logs

```
 Apollo: using the default service is deprecated and will be removed in a future version. Please define your service explicitly:
            
            apollo {
              service("service") {
                $packageNameLine
              }
            }
```

**Comment by BoD** [comment]
Hi 👋 Thank you for reporting this, and sorry about the non skippable warning. Would you like to open a PR for this? If not I can do it, no worries!

**Comment by StefanChmielewski** [comment]
> Hi 👋 Thank you for reporting this, and sorry about the non skippable warning. Would you like to open a PR for this? If not I can do it, no worries!

Sure thing, [here](https://github.com/apollographql/apollo-kotlin/pull/4561) you go

**Comment by martinbonnin** [comment]
@StefanChmielewski thanks for the PR 👍. 

FWIW, and for anyone else reading this, the good fix is to wrap everything under `service("service") {}`:

```
apollo {
  // add this block here
  service("service") {
    // Everything else here is unchanged
    packageName.se("...")
    // ... 
  }
}
```

If your build is relying on `--quiet`, it will break with the next Apollo major where we will stop supporting the default service. So you might as well do the change now.
