### ISSUE TITLE
Gradle task `generateXXXApolloSource` is not compatible with configuration cache

### ISSUE THREAD

**Issue by alvr** [apollographql/apollo-kotlin#4563]
### Summary

After upgrading Apollo to the latest 3.7.2 version and changing Gradle's configuration as-per relases notes, the task `generateXXXApolloSource` is failing with the error:

> Task `:data:remote:account:generateAnilistApolloSources` of type `com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask`: invocation of 'Task.project' at execution time is unsupported.

I have configuration cache enabled, but even after clearing all cache from Github actions is still happening. The weird thing is that in local, with and without configuration cache, compiles without problem.

### Version

3.7.2

### Steps to reproduce the behavior

[Here is the PR](https://github.com/alvr/katana/pull/253) with the changes.

### Logs

Here is the job with the stacktrace: https://github.com/alvr/katana/actions/runs/3647842447/jobs/6160551356

And a full detail of Gradle: https://scans.gradle.com/s/mnjuv5psfrn2o

**Comment by BoD** [comment]
Hi 👋 

Thanks for reporting this! 

FWIW, I could reproduce locally with your project:
```
find . -name build -exec rm -rf  {} \;
rm -rf .gradle/configuration-cache/
./gradlew --no-daemon --no-build-cache  assembleDebug
```

This is a regression introduced [here](https://github.com/apollographql/apollo-kotlin/pull/4527/files?w=1#diff-0a0d324d0e4fd61cf803cac9fb66b12de1fddad8de4338bdfda444e064017079R380) (thanks @martinbonnin for spotting it!), tentative fix is [here](https://github.com/apollographql/apollo-kotlin/pull/4564).

**Comment by BoD** [comment]
v3.7.3 has just been released with the fix
