### ISSUE TITLE
js client requests can fail due to inclusion of apollo specific headers

### ISSUE THREAD

**Issue by jeran** [apollographql/apollo-kotlin#4574]
### Summary

When making a request to Shopify's Storefront API, the backend will deny the request because it includes unapproved headers:

`Access to fetch at '....myshopify.com/api/2022-10/graphql.json' from origin '...' has been blocked by CORS policy: Request header field x-apollo-operation-name is not allowed by Access-Control-Allow-Headers in preflight response.`

The preflight request returns the following allowed headers:

```
access-control-allow-headers: Authorization, Content-Type, X-SDK-Variant, X-SDK-Variant-Source, X-SDK-Version, X-Shopify-Storefront-Access-Token, Shopify-Storefront-Private-Token, Shopify-Storefront-Buyer-IP, Shopify-Storefront-Id, Shopify-Storefront-S, Shopify-Storefront-Y, Custom-Storefront-Request-Group-ID, shopify-core-canary
```

I was able to make a successful request by providing an `HttpNetworkTransport` with a custom `HttpRequestComposer` that does not have `x-apollo-operation-name` or `x-apollo-operation-id`. I did this by basically duplicating `DefaultHttpRequestComposer` and removing the auto-inclusion of those two headers.

This is a little bit out of my wheelhouse, so I'm not sure how common it is to implement a custom `HttpRequestComposer`, but `DefaultHttpRequestComposer` looks like it has sufficient complexity that most users wouldn't want to be responsible for creating their own implementation.

Not sure what the best fix for this is, but it would be nice if there were an easier way to configure the addition of the apollo specific headers.

### Version

3.7.2

### Steps to reproduce the behavior

1. Create a kotlin multiplatform project with a js target
2. Implement a call using ApolloClient to Shopify's Storefront API
3. Make request in the browser

### Logs

```
Access to fetch at '....myshopify.com/api/2022-10/graphql.json' from origin '...' has been blocked by CORS policy: Request header field x-apollo-operation-name is not allowed by Access-Control-Allow-Headers in preflight response.
```

### Anything else?

Thank you kindly for your time and effort, please let me know if there's more information I can provide.

**Comment by martinbonnin** [comment]
Hi 👋 

Thanks for sending this! Your best bet is to provide a custom `HttpInterceptor`:

```kotlin
    val httpInterceptor = object: HttpInterceptor {
      override suspend fun intercept(request: HttpRequest, chain: HttpInterceptorChain): HttpResponse {
        val newRequest = request.newBuilder()
            // remove apollo headers
            .headers(request.headers.filter { it.name.lowercase().startsWith("x-apollo") })
            .build()
        return chain.proceed(newRequest)
      }

    }
    apolloClient = ApolloClient.Builder()
        .serverUrl(mockServer.url())
        .addHttpInterceptor(httpInterceptor)
        .build()
```

**Comment by jeran** [comment]
thank you! my mistake i could've sworn they were being added after the interceptors run. 🙏

**Comment by martinbonnin** [comment]
No worries! Glad it worked!

**Comment by jeran** [comment]
hey @gregjotau! everything looks right from what i can tell. it looks pretty much identical to what we have.

my guess is it's probably an issue with the access token. maybe try to inspect `System.getenv("shopify_access_token")` and make sure it looks right?

another possibility is that you could have a valid access token from shopify but the scope doesn't cover the api you're trying to access

hope that helps! feel free to hit me up on the kotlin slack or twitter if you need

**Comment by martinbonnin** [comment]
For anyone reading this, version 4 does not send apollo-specific headers by default so you can remove any workaround when updating.
