### ISSUE TITLE
 Android (JAVA)Apollo subscription only onConnected() is called

### ISSUE THREAD

**Issue by Brijesh116** [apollographql/apollo-kotlin#4576]
I have a subscription to my server and it is connected successfully onConnected() method is called,
but when I upload something to the server no subscription methods is invoked.

Please note that my code is in JAVA

Thanks in Advance

**Comment by martinbonnin** [comment]
Hi 👋 

Thanks for sending this! Can you share:

* What Apollo version you're using?
* What kind of server you're using for subscriptions? (Apollo, AppSync, graphql-ws, other?)
* Your ApolloClient builder code?

The websocket transport is not part of the spec so there are different implementations out there. You might have to provide custom headers or options to make it work.

**Comment by Brijesh116** [comment]
1. My Apollo Version is v2

Here is dependeci implementation
```
//--------------------------
    // Apollo Client
    //--------------------------
    implementation("com.apollographql.apollo:apollo-runtime:2.5.10")
    implementation("com.apollographql.apollo:apollo-coroutines-support:2.5.10")
    implementation'com.apollographql.apollo:apollo-rx2-support:2.5.10'
```

I used below Plugin

`id 'com.apollographql.apollo'`
--------------------------------------------------------------------------

2. Appsync server you're using for subscriptions
--------------------------------------------------------------------------

3. Here is my Apollo client builder code
`public static com.apollographql.apollo.ApolloClient getEventApolloClientSubscription() {

        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor();
        httpLoggingInterceptor.level(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(httpLoggingInterceptor).build();
        SubscriptionConnectionParams connectionParams = new SubscriptionConnectionParams();
        connectionParams.put(x_api_key, BuildConfig.HALO_EVENT_API_KEY);
        connectionParams.put("Authorization", accessToken);

        return com.apollographql.apollo.ApolloClient.builder()
                .serverUrl(BuildConfig.HALO_EVENT_GRAPHQL_API)
                .okHttpClient(okHttpClient)
                .subscriptionHeartbeatTimeout(15, TimeUnit.SECONDS)
                .subscriptionConnectionParams(connectionParams)
                .subscriptionTransportFactory(new WebSocketSubscriptionTransport.Factory(BuildConfig.HALO_EVENT_WEB_SOCKET_API, okHttpClient))
                .build();

    }`

**Comment by martinbonnin** [comment]
Hi 👋 Version 4 has a big rework of the WebSockets API that should address this. Closing this one as stale. If this happens again on v4, please open a new issue.
