### ISSUE TITLE
Inconsistent code vs docs

### ISSUE THREAD

**Issue by sewerk** [apollographql/apollo-kotlin#4599]
### Question

Looks like a bug and confuses me, is this correct?
Documentation [here](https://github.com/apollographql/apollo-kotlin/blob/main/docs/source/essentials/subscriptions.mdx) says:
> Apollo Kotlin comes with built-in support for the protocols above:
- subscriptions-transport-ws: `SubscriptionWsProtocol` (default)
- graphql-ws: `GraphQLWsProtocol`
- appsync: `AppSyncWsProtocol`

Code for `SubscriptionWsProtocol.Factory` [here](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/SubscriptionWsProtocol.kt#L100) says `name = "graphql-ws"`
Code for `GraphQLWsProtocol.Factory` [here](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/GraphQLWsProtocol.kt#L261) says `name = "graphql-transport-ws"`

**Comment by martinbonnin** [comment]
Hi 👋 I know this is super confusing but don't really have another solution right now. `SubscriptionsWsProtocol` was first and using `name = "graphql-ws"` but then https://github.com/enisdenjo/graphql-ws was created and used `name = "graphql-transport-ws"`. This is a very unfortunate state of affairs but everybody started referring at the protocols using the repository name so `graphql-ws` gained some traction even though that name was already used by another protocol. 

Using another completely different name would have certainly been better but it's too late now, hence the overall confusion. If you have ideas how to clear that up, I'll take them as this has been itching me for a while.

**Comment by martinbonnin** [comment]
Closing this one. Given all the backward compat constraints, etc... I'd rather not touch this right now. If you have suggestions for the next major version, please comment here and we can consider changing the naming in 4.0
