### ISSUE TITLE
Query duplication

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4604]
### Version

3.7.0

### Summary

Hello, when I click action button,  network debugger shows 50 outgoing requests are sent to our server.
I noticed existing issue that was closed long time ago, not sure if things have changed. https://github.com/apollographql/apollo-kotlin/issues/646

```
    @Inject
    @AuthenticatedClient
    internal lateinit var apolloClient: ApolloClient

    private fun onActionButtonClicked() {
        for (i in 1..50) {
            disposables.add(
                apolloClient.query(
                    OffsiteQuery(
                        url = "https://thesassyowlboutique.com/products/hearts-aflutter-skort?variant=39947075715150"
                    )
                ).fetchPolicy(FetchPolicy.CacheFirst).rxSingle()
                // Ignore the result since this is just a prefetch
                .subscribe(Functions.emptyConsumer(), Functions.emptyConsumer())
            )
        }
    }
```

<img width="1208" alt="Screen Shot 2023-01-04 at 12 50 00 PM" src="https://user-images.githubusercontent.com/1810298/210618062-5ec06a2c-7d08-46c6-856a-f19cb8acdebf.png">

-----
Unrelated, with our REST Retrofit Repository implementation, it only fetches from server once.

    @Inject
    lateinit var urlInfoRepository: UrlInfoRepository

    private fun onActionButtonClicked() {
        for (i in 1..50) {
            disposables.add(
                urlInfoRepository.getUrlInfo(
                    "https://thesassyowlboutique" +
                        ".com/products/hearts-aflutter-skort?variant=39947075715150", "1059401512322041701", null
                )
                .subscribe(Functions.emptyConsumer(), Functions.emptyConsumer())
            )
        }
    }

**Comment by BoD** [comment]
Hi!

There is no mechanism as of today to do this in Apollo Kotlin. Issue #646 is closed but we issue #3760 can be used to track this.

Thanks for the heads up about Retrofit, I wasn't aware that it had such a mechanism, I'll have a look. 
I am assuming this only works for `GET` though? I can imagine scenarios where you actually want to execute several identical `POST`s on the same resource even if one is already ongoing. For GraphQL I think this would only be allowed to work on queries, not mutations.

**Comment by ynkm169** [comment]
@BoD Hi Sorry for confusion, the dedup mechanism is from our own Repository implementation, not Retrofit. Basically we cache a Map<request, Observable>. If our code calls Repository.get(url) multiple times with same url, the map will retrieve the same observable.

**Comment by BoD** [comment]
Ooh right! Thanks for clarifying. I guess this could also work on top of Apollo?

**Comment by ynkm169** [comment]
We are using Apollo store as cache and ridding off our own repository implementation.

Sent from my iPhone

On Jan 4, 2023, at 1:48 PM, Benoit Lubek ***@***.***> wrote:

﻿

Ooh right! Thanks for clarifying. I guess this could also work on top of Apollo?

**Comment by BoD** [comment]
Thanks for clarifying! Is it ok to close this ticket in favor of #3701?

**Comment by ynkm169** [comment]
For sure thank you!
