### ISSUE TITLE
[IJ/AS plugin] Support for multiple schemas according to configuration

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#4625]
In an Apollo Kotlin project, by default the GraphQL schema file(s) are in src/main/graphql. But there can be several ones when using multiple services and modules. In that case the GraphQL plugin should recognize them as expected.
```[tasklist]
- [x] Show a progress indication while fetching tolling models
```

**Comment by martinbonnin** [comment]
Blocked on https://github.com/JetBrains/js-graphql-intellij-plugin/pull/639
