### ISSUE TITLE
Type with "Companion" name causes compile error

### ISSUE THREAD

**Issue by jorrhe** [apollographql/apollo-kotlin#4629]
### Version

3.7.3

### Summary

When a graphql schema contains a type with the name "Companion" it causes the project to not compile.

### Steps to reproduce the behavior

1. Create a schemea with a type named "Companion" ex:
```graphql
type Companion{
   name: String
}
```
2.  Compile the project

### Logs

```
Conflicting declarations: public companion object, public final data class Companion
```

**Comment by martinbonnin** [comment]
Thanks for raising this 🙏 . We'll add auto escapes rules for that. In the meantime, you can workaround by using `@tragetName` ([source](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-ast/src/main/resources/apollo-v0.2.graphqls#L73))

Add an `extra.graphqls` file next to your schema with these contents:

```graphql
extend type Companion @targetName(name: "Companion_")
```

That should use `Companion_` in the generated code. Hope this helps, let us know if that did!

**Comment by jorrhe** [comment]
Hi, thank you for responding so quick!

I've tried your solution but it didn't work, the same error appears on compilation. Do you think it may be related to having various schemas in the project?

This is an example of the folder structure I have with two schemas: one with a "Companion" type. I added the `exta.graphqls` file to the folder with the service2 schema, which is the schema that has the problem.
```
graphql/
├─ service1/
│  ├─ service1schema.graphqls
├─ service2/
│  ├─ extra.graphqls
│  ├─ service2schema.graphqls
```

On my app build.gradle I have defined the two apollo schemas like this:
```groovy
apollo {

    service("service1"){
        srcDir("src/main/graphql/service1")
        packageName.set("com.mo2o.melia.apollo.service1")
    }

    service("service2"){
        srcDir("src/main/graphql/service2")
        packageName.set("com.mo2o.melia.apollo.service2")
    }

}
```

I hope this helps! Thank you again!

**Comment by martinbonnin** [comment]
Could it be that the issue is on a `companion` field (and not on the `Companion` type)? I don't have any issue with a class named `Companion` at the top level but indeed it fails if it's nested with another actual companion object.

Do you have anything like this in your queries? 

```query
query GetFoo {
  companion {
    bar
  }
}
```

If yes, then the workaround would be to use [aliases](https://www.apollographql.com/docs/kotlin/advanced/using-aliases/) in your query:

```query
query GetFoo {
  companion_ {
    bar
  }
}
```

**Comment by jorrhe** [comment]
That's was it! Thank you for helping me!

**Comment by martinbonnin** [comment]
Nice, thanks for confirming. 
I'll keep this issue open to see if we can  auto-escape this
