### ISSUE TITLE
Apollo gradle plugin has conflict with appSync plugin 

### ISSUE THREAD

**Issue by giorgospat** [apollographql/apollo-kotlin#4646]
### Question

I am already using Apollo client in my app and want to also use AppSync for subscriptions.
When I add the `com.amazonaws.appsync` plugin in gradle, along with `com.apollographql.apollo3`, gradle build fails with error:

`What went wrong: An exception occurred applying plugin request [id: 'com.apollographql.apollo3', version: '3.3.2']
> Failed to apply plugin 'com.apollographql.apollo3'.
   > Cannot add extension with name 'apollo', as there is an extension already registered with that name.`

**Environment**
 - AppSync SDK Version: [3.3.2]
 - Apollo SDK Version: [3.3.2]

**Comment by BoD** [comment]
Hi! I wasn't aware of this project but from its description it appears to be based on Apollo, which explains the conflict. I see that you've just opened [an issue](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/405) on that project which I think makes sense.

In the meantime maybe you could still use both plugins, but in separate modules of your project?

**Comment by giorgospat** [comment]
> Hi! I wasn't aware of this project but from its description it appears to be based on Apollo, which explains the conflict. I see that you've just opened [an issue](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/405) on that project which I think makes sense.
> 
> In the meantime maybe you could still use both plugins, but in separate modules of your project?

You are very right, creating separate module for AppSync SDK resolved the issue! Thank you very much.
