### ISSUE TITLE
warnOnDeprecatedUsages

### ISSUE THREAD

**Issue by parijat-shah** [apollographql/apollo-kotlin#4647]
### Question

I want to suppress the deprecated field warnings. I tried using warnOnDeprecatedUsages.set(false) but it did not work. Any suggestions on how to suppress the warnings? 

`apollo {
    service("xyzzy") {
        warnOnDeprecatedUsages.set(false)
        failOnWarnings.set(false)
    }
}`

**Comment by BoD** [comment]
Hi! 

`warnOnDeprecatedUsages` is used to control whether the a warning will be logged at code generation time, if an operation uses a deprecated element. But regardless of this flag the generated code will include a `@Deprecated` annotation on deprecated fields, and using them in your code will generate a warning from the Kotlin compiler. There is currently no option to disable this.
