### ISSUE TITLE
Missing documentation for ApolloInterceptor

### ISSUE THREAD

**Issue by todorovik** [apollographql/apollo-kotlin#4649]
Hello,

There seems to be no documentation about ApolloInterceptor (not HttpInterceptor). Particularly manipulating the body of the response & returning a different one.

Use Case:
Parse body to check for UnAuthorised, refresh auth token, re-do original request and hand it off to the chain.

**Comment by BoD** [comment]
Updated doc is [here](https://www.apollographql.com/docs/kotlin/advanced/interceptors-http/).
