### ISSUE TITLE
Add option to not resume subscriptions when websocket connection is reestablished

### ISSUE THREAD

**Issue by vincentjames501** [apollographql/apollo-kotlin#4655]
### Use case

We have a use case where we subscribe to a change log at a specific point in time. As changes come in, we move our "cursor" so to speak. The problem is when the websocket disconnects and resumes the subscription, it starts again from the initial point in time and not our most recently processed change so we need to manually control the recreation of the subscription. 

### Describe the solution you'd like

Seems like being able to describe the resume semantics either on the Subscription or the WebSocketNetworkTransport.Builder would be a nice place to put that.

**Comment by BoD** [comment]
Hi!
Just to be sure: you are referring to `webSocketReopenWhen`, right?  Did you have specific ideas of an API for this?

I think for your specific case, it makes sense to handle this at the level of the subscription in question, and just restart it (with the updated parameter) whenever an error occurs, something like:

```kotlin
        while (true) {
            apolloClient.subscription(createSubscriptionWithCurrentCursor()).toFlow()
                .catch { e ->
                    // Ignore errors
                }
                .collect { resp ->
                    // ...
                }
        }
```

**Comment by vincentjames501** [comment]
@BoD , yeah and `WebSocketNetworkTransportBuilder.reopenWhen`. Something like this is an idea:

```kotlin
client.subscription(
  createSubscriptionWithCurrentCursor(), 
  SubscriptionOptions
    .Builder()
    // Simple option, defaults to true.
    .resumeOnReconnect(true)
    // Can't be supplied if resumeOnReconnect=false
    .resumeSubscriptionOnReconnectWith(e -> 
      if (canResume(e)) {
        createSubscriptionWithCurrentCursor() // return the new subscription (must be of same "type" as original subscription)
      } else {
        null // return null to not resume on reconnect
      }
    )
    .build()
)
```

```kotlin
ApolloClient
  .Builder()
  .automaticallyResumeWebSocketSubscriptions(true) // true by default
  .build()
```

**Comment by BoD** [comment]
Thanks! Interesting. At the moment I am not 100% convinced this brings a lot of value vs dealing with the subscription's Flow directly (maybe there exist, or one could create, a Flow operator like `.retryWhen` but taking a lambda providing a new Flow) - in any case let's keep this issue open and see if it gets traction/feedback.

**Comment by vincentjames501** [comment]
@BoD , I think my main thing is that the connection and subscriptions are coupled. If you want to recover the websocket connection automatically by the `ApolloClient`, you don't have a way to opt-out of the subscription or alter it when it is resumed. This means that in our case we have to bail on all the Apollo Client recovery mechanisms and roll our own. So at the very least I'd propose an option to disable the automatic resumption of subscriptions so it can be self managed like you showed above in the `while` loop.

**Comment by BoD** [comment]
I see! Thanks for clarifying. So the idea could be to keep the ability to reconnect and resume ongoing subscriptions globally (what `websocketReopenWhen` does currently), but add the ability to opt-out for certain subscriptions only.

**Comment by martinbonnin** [comment]
@vincentjames501 what about writing an extension function for all your subscriptions?

Something like this:

```kotlin
fun <D: Subscription.Data> ApolloClient.subscribeAndRetryAutomatically(subscriptionProvider: () -> Subscription<D>): Flow<ApolloResponse<D> {
  return subscription(subscriptionProvider()).toFlow().catch {
    // call ourselves and update the subscription if needed
    emitAll(subscribeAndRetryAutomatically(subscriptionProvider))
  }
}
```

Then for regular, no-variables subscriptions, you can just do 

```kotlin
apolloClient.subscribeAndRetryAutomatically { mySubscription }
```

And for the changelog:

```kotlin
apolloClient.subscribeAndRetryAutomatically { 
  GetChangelogSubscription(from = System.currentTimeMillis())
}
```
