### ISSUE TITLE
Arguments order for generated Kotlin/Java code

### ISSUE THREAD

**Issue by FrancescoRigoni** [apollographql/apollo-kotlin#4659]
### Question

We are currently facing an issue with schema updates related to changing the order of parameters inside input objects.
Let me provide an example, we have an input object defined in our schema, the codegen generates the following kotlin code for it:
```
public data class SomeMutationInput(
  /**
   * External URL
   */
  public val url: String,
  /**
   * Mime type of the input file, image/jpeg or application/pdf for example
   */
  public val type: String,
  /**
   * Name of the original file
   */
  public val name: String,
)
```
All 3 members of this input object are of type String. The order in which they are generated in Kotlin seems to only depend on the order they are found inside the schema (please correct me if I am wrong).
We are now trying to have all these parameters sorted by name, thus updating the schema, thus the codegen now generates
```
public data class SomeMutationInput(
  /**
   * Name of the original file
   */
  public val name: String,
  /**
   * Mime type of the input file, image/jpeg or application/pdf for example
   */
  public val type: String,
  /**
   * External URL
   */
  public val url: String,
)
```
The problem is that, all members of this input object being of the same type, we have a very high chance of breaking our app, if in some place we do not use named arguments, then the values of these member will get mixed up. Even worse if we use java models (in some older parts of the app) where named args are not even possible.

```
CaseMessageAttachmentInput(it.url, it.name, it.type) // this is not correct anymore
```

Then, thinking more about this, we realised that even without this alphabetical sorting change, if anyone at any point switches around two members of the same type, for any reason, we'd have the same issue. So the needs arises now to find a way to deal with this possibility.

The question is, what is the proper way of dealing with this? Is there a way to force our Kotlin codegen to always generate input objects with members in a predictable order? Is there a way to specify some sort of sorting parameter in the schema?

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for sending this. I'm like 99% sure the order of input fields matches the order schema. For a given schema, this is 100% defined and reproducible or else it'd cause the Gradle build cache and up-to-date check to fail all the time and we don't want that.

Now when you change the schema new input fields are added as you found out. Whether the order is alphabetical, schema or something else doesn't matter, addition could end up swapping two input fields. 

What you're looking for is a stateful sort method. Something that not only takes the list of input fields but also the previous state to only append new input fields at the end. 

```kotlin
/**
 * Sorts the given input fields according to current state and outputs the sorted list and the new state
 */
fun sort(currentState, List<String>): Pair<State, List<String>)
```

This state would need to be persisted somewhere and tracked by the Gradle tasks. This is all doable but not sure it's worth the complexity?

**Comment by martinbonnin** [comment]
Thinking about this more, I like using the schema order by default. It maps nicely and is easy to read. What we need is a way do enforce named parameters.

Some things we could do:

* For Kotlin, use [this hack](https://stackoverflow.com/a/37394267/752630) to force using named parameters. Not a huge fan of this as it's violates the principle of least surprise. Someone reading the generated code will have a hard time understanding what this `vararg Nothing` thing is.
* For Kotlin, until this is in the language (see [this Youtrack](https://youtrack.jetbrains.com/issue/KT-14934)), one solution would be to use the [RequireNamedArgument](https://github.com/chao2zhang/RequireNamedArgument) compiler plugin. This will require some changes (see [this issue](https://github.com/chao2zhang/RequireNamedArgument/issues/8)) but sounds doable.
* For Java, we could hide the public constructors and force to use Builders for everything. Sounds like it should maybe be the default actually.

**Comment by martinbonnin** [comment]
I'm going to close this one as non-actionable from Apollo-Kotlin until [`KT-14934`](https://youtrack.jetbrains.com/issue/KT-14934) is released. 

In the meantime, the [`@RequireNamedArgument`](https://github.com/chao2zhang/RequireNamedArgument) + [compiler hooks](https://github.com/apollographql/apollo-kotlin/blob/main/CHANGELOG.md#%EF%B8%8F-new--experimental-compiler-hooks-api-4474-4026) solution should work. If anyone has it working, please share your results!
