### ISSUE TITLE
Apollo GraphQL not generating null-able fragment

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-kotlin#4672]
### Version

2.4.5

### Summary

I have a fragment defined like this:

fragment MyThreadFragmnt on Thread {
 
   ...PermissionFragment @include (if: $includePermissionAttributes)

}

and PermissionFragment itself is defined as

fragment PermissionFragment on Thread {
  userHasPermissionToView
  userHasPermissionToDelete
  userHasPermissionToEdit
}

What I am finding is apollo graphql is generating code where permissionFragment is marked as non-nullable, that breaks things if I set includePermissionAttributes to false.

Is this a bug, am I not able to set optional inclusion of fragment. 

Optional inclusion of attributes works fine.

I am using version 2.4.5

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment]
Hi!

Indeed, `permissionFragment`  should be nullable.
I tried on a simple project [here](https://github.com/BoD/apollo-android-v2-sample-for-intellij-plugin/blob/master/app/src/main/graphql/com/example/operations.graphql) and couldn't reproduce the issue: fragments with `@include` are generated as nullable in my case. Would it be possible for you to share a project showing the issue?

**Comment by BoD** [comment]
@snijsure Did you have a chance to look at this or anything else we can do?

**Comment by snijsure** [comment]
@BoD  Apologies for late reply. Turns out there was typo in my $if statement! - Your example certainly helped. 

Marking this issue as closed.
