### ISSUE TITLE
Watcher not getting callled for null subqueries

### ISSUE THREAD

**Issue by juangameromoreno** [apollographql/apollo-kotlin#4673]
### Question

**Situation**
SQL normalized cache and store partial response.
Let's say you have a query composed by other queries

`query MainQuery{
    query1 {
    }
 query2 {
    }
 query3 {
    }
 query4 {
    }
}`

Now after it completes I start listening for changes using a watcher. The result of query2 was null and this wasn't saved in the cache. I can't see "query2" = null when dumping all cached data.

So if I were to manually update the cache when the result for query2 was returned, after a mutation, the watcher wouldn't get called as the content of the main query didn't actually change becuse query2 wasn't in the cache before.

**Question**
I can think of a couple of ways to solve this and get the result I want. But I was wondering what the right approach to this problem would be?

**Comment by BoD** [comment]
Hi!

If you are watching `MainQuery`, other queries or mutations that update the result of `query2` should lead to a new result to be emitted.

> I can't see "query2" = null when dumping all cached data.

You should see a null `query2` field inside of `QUERY_ROOT` though.

I've tried to reproduce with a very simple example [here](https://github.com/BoD/apollo-kotlin-template/blob/issue-4673/src/main/kotlin/com/example/Main.kt#L51), with it, we get the watch triggered twice.

**Comment by juangameromoreno** [comment]
Your right I was missing the QUERY_ROOT part. Thank you so much for the help 💯
