### ISSUE TITLE
Apollo - Downloading schema using downloadApolloSchema does not work for deprecated input fields

### ISSUE THREAD

**Issue by s4r4r** [apollographql/apollo-kotlin#4677]
When trying to download the schema from the apollo server it does not download fields that are deprecated,  probably because https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-tooling/src/main/kotlin/com/apollographql/apollo3/tooling/SchemaDownloader.kt#L202 does not have the `includeDeprecated: true` set. 

Can this be updated so that we can download the schemas with deprecated input fields.

**Comment by martinbonnin** [comment]
@s4r4r thanks for sending this! Do you want to make a pull request? You can do it from the GitHub UI. 
If not, no worries, we'll do it!

**Comment by ndwhelan** [comment]
I work with @s4r4r and will submit a PR.

**Comment by ndwhelan** [comment]
PR submitted: https://github.com/apollographql/apollo-kotlin/pull/4678

If it's viewed that this change needs tests added, I can look into that. Pointers to similar tests would be helpful.

Though, I don't have experience developing Gradle plugins. I'm sure I can figure it out, just will take a bit longer.

The contribution guide mentioned using labels, but I'm unsure what labels to use? Can you provide guidance or update the PR?

**Comment by s4r4r** [comment]
@ndwhelan - probably a test can be added in https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-gradle-plugin/src/test/kotlin/com/apollographql/apollo3/gradle/test/DownloadSchemaTests.kt

**Comment by ndwhelan** [comment]
Thank for the pointer. I will likely take this on tomorrow (USA based)

**Comment by BoD** [comment]
This has been released as part of [v3.7.5](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.7.5)
