### ISSUE TITLE
ApolloInterceptor doesn't intercept 4XX error responses

### ISSUE THREAD

**Issue by nikonhub** [apollographql/apollo-kotlin#4680]
### Question

Hello,

I'd like to add an AuthorizationInterceptor at Graphql level (implementing ApolloInterceptor). I've succesfully got to work an HttpInterceptor but http status codes are not enough because server returns different extensions codes at graphql level.
```json
"extensions": {
    "code": "EXPIRED_ACCESS_TOKEN",
}
```

Looking at the official doc + [github solutions](https://github.com/apollographql/apollo-kotlin/issues/3899) I have something working. But as soon as the response is 4XX ApolloInterceptor does not let intercept the response.

```kotlin
@OptIn(FlowPreview::class)
override fun intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return flow {
        val requestToken = mutex.withLock {
            ...
            tokenProvider.loadToken()
            ...
        }

        val authRequest = request.newBuilder().addHttpHeader("Authorization", requestToken.toHeader()).build()
        emit(authRequest)
    }.flatMapConcat { authRequest ->
        chain.proceed(authRequest).map { response ->
           // Here all responses go through. Network + cache
           // But once the token has really expired 
           // and response status code is 400 only cache responses arrive and network are cut somewhere above
            if (response.isFromCache) {
                return@map response
            }
            if (!response.hasErrors()) {
                  return@map response
            }
           // Code never reached. Because requests here never have errors

           val hasTokenExpired = hasExpired(response.errors)
           if(hasTokenExpired) {
                ...refreshToken()
           }
        }
    }
}

```

I've tried to change the response code to 200 from the server and it works ok. So I worder if this is inteded behavior. At graphql level we can't intercept other than 2XX status codes ?

Because the default behavior of Apollo Server Errors is 400 for Validation, Authentication, Forbidden, etc. And it's only overridable since V4. But still I don't think we should override it with 200 code.

**Comment by martinbonnin** [comment]
Hi 👋 

Right. HTTP 400 stop further processing of the response as I don't think we can have any garantee that the body would contain a valid GraphQL response in that case.

What you'd need to do is configure your ApolloClient with [`exposeErrorBody`](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/HttpNetworkTransport.kt#L191) catch the HTTP 400 in your ApolloInterceptor and then parse (and close) that body manually. Something like this:

Configure your client:
```kotlin
    ApolloClient.Builder()
        .networkTransport(
            HttpNetworkTransport.Builder()
                .serverUrl("https://...")
                .exposeErrorBody(true)
                .build()
        )
        .build()
```

And then create your interceptor:
```kotlin
  abstract class  AuthorizationInterceptor : ApolloInterceptor {
    abstract fun getCurrentToken(): String
    abstract fun refreshToken(extensions: Any): String

    override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {

      return chain.proceed(request.newBuilder().addHttpHeader("Authorization", "Bearer ${getCurrentToken()}").build())
          .catch { 
            if (it is ApolloHttpException) {
              if (it.statusCode == 400 && it.body != null) {
                // parse body manually
                val response = request.operation.parseJsonResponse(it.body!!.jsonReader(), request.executionContext[CustomScalarAdapters]!!)
                
                // and use extensions here.
                emitAll(chain.proceed(request.newBuilder().addHttpHeader("Authorization", "Bearer ${refreshToken(response.extensions)}").build()))
              } else {
                it.body?.close()
                throw it
              }
            } else {
              throw it
            }
          }
    }
  }
```

HTH

**Comment by nikonhub** [comment]
Thank for your answer @martinbonnin 

I've tried to implement something. But it looks a little cumbersome with a lot of differences cases to handle. 

PS : I finally finished by parsing the body in the HttpInterceptor. Even with the manual parsing, the code is much smaller and it looks easier to implement.
