### ISSUE TITLE
ApolloCompilerKotlinHooks Unresolved Reference

### ISSUE THREAD

**Issue by asriram-25** [apollographql/apollo-kotlin#4686]
### Question

I am trying to add a customKotlinCompilerHook to add an annotation to the generated GraphQL file.

```
compilerKotlinHooks.set(
            listOf(
                object : DefaultApolloCompilerKotlinHooks() {
                    override val version: String
                        get() = "Add Immutable to Graph QL Files"

                    override fun postProcessFiles(
                        files: Collection<ApolloCompilerKotlinHooks.FileInfo>
                    ): Collection<ApolloCompilerKotlinHooks.FileInfo> {
                        return files.map {
                            it.copy(
                                fileSpec = it.fileSpec
                                    .toBuilder()
                                    .apply {
                                        this.addAnnotation(
                                            ClassName(
                                                "androix.compose.runtime.Immutable",
                                                "Immutable"
                                            )
                                        )
                                    }.build()
                            )
                        }
                    }
                })
        )
```
But I'm getting unresolved reference error on doing gradle sync for `toBuilder()` and `addAnnotation()` methods.
The Gradle Plugin version is 3.7.4 and I'm already using id("com.apollographql.apollo3.external")

**Comment by martinbonnin** [comment]
That looks like a Gradle classloader issue. If you have `kotlinPoet` in `buildSrc` or in your root project buildscript classpath, it will override the one that `apollo-gradle-plugin-external` depends on. A workaround is to add `com.squareup:kotlinpoet:1.12` to your `buildSrc` dependencies to force it.

**Comment by asriram-25** [comment]
Still getting the same error even after adding kotlinPoet in `buildSrc` dependencies

**Comment by martinbonnin** [comment]
Do you mind sharing the full stacktrace of the error you're getting? Is it only during Gradle sync or does it also happen when building from the command line?

**Comment by asriram-25** [comment]
Tried building from terminal but getting the error there too. Here's the stacktrace
<img width="1162" alt="Screenshot 2023-02-15 at 6 03 08 PM" src="https://user-images.githubusercontent.com/125462678/219028849-af6d6131-b5e2-48ae-a923-9f8c4f173a68.png">

**Comment by martinbonnin** [comment]
Could it be that you still have the relocated version of the Apollo plugin in the classpath somewhere? Can you search for `apollo-gradle-plugin`? There should be not of that but `apollo-gradle-plugin-external` instead.

**Comment by asriram-25** [comment]
Other modules in the project might be using the non-external plugin. Are you saying that only the external plugin should be used inside the project (all modules)?

**Comment by martinbonnin** [comment]
Most likely yes. To workaround Gradle classloader issues, the `apollo-gradle-plugin` artifact relocates all dependencies (including kotlinpoet). So `kotlinpoet.FileSpec` might end up at `com.reloacted.kotlinpoet.FileSpec` for an example and you have 2 versions of `FileSpec` in your classpath. 
There might be ways to use different classpaths for different modules but I'm not 100% sure how to accomplish this (and it also depends your setup). So all in all, the answer might very well be to use `apollo-gradle-plugin-external` in all your modules.

**Comment by asriram-25** [comment]
Made the plugin changes and the gradle sync issue got solved. But while building the project, I'm getting `NoSuchMethodException` in the `generateProductionApolloSources` task.

<img width="1085" alt="Screenshot 2023-02-15 at 6 38 22 PM" src="https://user-images.githubusercontent.com/125462678/219036243-9adf1ac8-32bd-4eea-b553-bca6733b3885.png">

**Comment by martinbonnin** [comment]
Damn classpaths are hard... That's something new... If you can, can you add `apollo-gradle-plugin-external` to your `buildSrc` to force the plugin and dependencies in the "top-level" classloader? 

Sorry I don't have a better answer for this. This mess was the reason we relocated the plugin in the first place but that doesn't work anymore if we expose transitive libraries in the plugin API

**Comment by asriram-25** [comment]
Is there any other way to customize the generated GraphQL classes maybe before they been processed? (I understand that the compilerHooks are used to modify files after they've been generated)

**Comment by martinbonnin** [comment]
Not really. You _could_ wire the generated models to a temporary directory, modify them to another directory and connect that to `kotlinCompile` but that sounds even more involved. 
From your comment, looks like forcing everything into `buildSrc` did not help? Any chance you can put a small reproducer project somewhere? That'd be super helpful to investigate those issues.

**Comment by asriram-25** [comment]
But I can't see the annotation added to the generated files, the import statement has been added but not the annotation. 
Any suggestions you might have on how to add annotations to generated files?

**Comment by martinbonnin** [comment]
> Any suggestions you might have on how to add annotations to generated files?

I'm guessing you want the annotation to the generated classes, not files? In which case, you can do something like this:

```kotlin
  override fun postProcessFiles(files: Collection<FileInfo>): Collection<FileInfo> {
    return files.map {
      it.copy(
          fileSpec = it.fileSpec
              .toBuilder()
              .apply {
                members.replaceAll { member ->
                  if (member is TypeSpec) {
                    member.toBuilder().addAnnotation(ClassName(
                        "androix.compose.runtime.Immutable",
                        "Immutable"
                    )).build()
                  } else {
                    member
                  }
                }
              }.build()
      )
    }
  }
```

**Comment by asriram-25** [comment]
This worked 💯
Thank you for helping out with this.

**Comment by martinbonnin** [comment]
Nice! Glad I could be of some assistance and thanks for the update!

**Comment by asriram-25** [comment]
@martinbonnin The above code add the annotation only on the parent class but no on child data classes. Is there a recommended approach to modify the parent as well as child classes ?(basically some type of recursive method)

**Comment by martinbonnin** [comment]
This is a KotlinPoet question. I'm no expert but I guess you could do something like this to add the annotation recursively:

```kotlin
  private fun TypeSpec.addAnnotation(): TypeSpec {
    return toBuilder()
        .apply { 
          val oldTypeSpecs = typeSpecs
          typeSpecs.clear()
          typeSpecs.addAll(oldTypeSpecs.map { 
            it.addAnnotation()
          })
        }
        .addAnnotation(ClassName(
        "androix.compose.runtime.Immutable",
        "Immutable"
    )).build()
  }
  override fun postProcessFiles(files: Collection<FileInfo>): Collection<FileInfo> {
    return files.map {
      it.copy(
          fileSpec = it.fileSpec
              .toBuilder()
              .apply {
                members.replaceAll { member ->
                  if (member is TypeSpec) {
                    member.addAnnotation()
                  } else {
                    member
                  }
                }
              }.build()
      )
    }
  }
```

**Comment by BoD** [comment]
@asriram-25 Did you manage to make this work in the end? If yes, ok to close the ticket?
