### ISSUE TITLE
Kotlin/Wasm

### ISSUE THREAD

**Issue by dbaroncelli** [apollographql/apollo-kotlin#4701]
### Use case

Do you have an ETA for targeting Kotlin/Wasm?

**Comment by BoD** [comment]
Hi!

We haven't looked at Wasm yet, but it would definitely be a target we would like to have! So no ETA at this point, but if anything it would most likely to be in the upcoming [4.0 version](https://github.com/apollographql/apollo-kotlin/blob/main/ROADMAP.md#40).

Contributions are definitely welcome if you'd like to have a look at it.

Also if you don't mind sharing a bit about your project (do you already use WASM currently? etc.), that would be valuable information to us.

**Comment by dbaroncelli** [comment]
I am actually not using WASM yet, as it just came out with Kotlin 1.8.20 beta:
https://kotlinlang.org/docs/whatsnew-eap.html#new-kotlin-wasm-target

But I have a perfect use case for a Compose project with Kotlin/Wasm and GraphQL.

**Comment by martinbonnin** [comment]
Looks like it's a new target to add? If it's not too big of a change, that could be a part of the next 3.x I guess. As long as it's clear that the artifacts are experimental of course but I think it's pretty clear in the community right now.

**Comment by skuzmich** [comment]
This seems to depend on having a Wasm target in Okio.

**Comment by martinbonnin** [comment]
@skuzmich indeed, good catch! Relevant issue there: https://github.com/square/okio/issues/1203

**Comment by martinbonnin** [comment]
There's now a [wasm branch](https://github.com/apollographql/apollo-kotlin/tree/wasm) with work in progress. It's based on a lot of experimental dependencies and there are still a lot of `TODO("Not implemented")`. It's going to take a while until this is shipped but you can see a very-minimal live demo at wasm.confetti-app.dev.

**Comment by BoD** [comment]
Initial support has been released in [4.0.0-beta.4](https://github.com/apollographql/apollo-kotlin/releases/tag/v4.0.0-beta.4)
