### ISSUE TITLE
A/B testing and client side schema

### ISSUE THREAD

**Issue by cyberhck** [apollographql/apollo-kotlin#4703]
### Question

We have a scenario where the backend team has implemented a `DateTime` scalar. We made a mistake and initially didn't handle that which as a result produced a type `Any`, now we want to implement a proper type-safe scalar. But because we already have existing code that used `Any` type, we are having difficulty A/B testing the migration from `Any` type to our typesafe `DateTime` type.

We tried duplicating the operation and passing `String` instead of `DateTime` but that was rejected by the server.

Doing this in query would be relatively easy since the client can just change their own schema, but mutations require the type to be defined for each input, as a result, if the type isn't present on the server side, it's rejected.

One approach would be to simply create a new mutation on the server. But we're afraid we will need to do this every single time moving forward. We'd like to find a solution that works in the future as well.

Is there a way to define a client-side schema (just like they can in react) in apollo-kotlin? Maybe that helps?

Any other ideas we can play around with?

We basically want to A/B test using the `Any` vs a `DateTime` scalar on the client side.

**Comment by BoD** [comment]
Hi!

One idea would be to have [2 services](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration#using-multiple-graphql-apis):
A. what you currently have, with the scalar not configured
B. same as above except the scalar is configured

Make sure they are generated to a different package name, and you can use the generated code from A or B to switch.

The drawback of doing this is that it will generate everything twice. Shipping duplicated code may not be an issue if minification is used, but the build performance penalty is there.

Also, B could use a different version of the schema (if you need to A/B test different versions of the server for instance).

Hope this makes sense!

**Comment by cyberhck** [comment]
hello @BoD is it possible to hook into code generation and do some custom code generation?

**Comment by martinbonnin** [comment]
@cyberhck can you elaborate a bit more what code you want to customize? Are you trying to A/B test registering a [custom scalar adapter](https://www.apollographql.com/docs/kotlin/essentials/custom-scalars) vs using the default `Any` type? 

To do that, you'd have to generate the models twice using two services as @BoD described [above](https://github.com/apollographql/apollo-kotlin/issues/4703#issuecomment-1441443745). But you'd basically add a lot more code to your app and any performance difference between `Any` and `DateTime` is probably annihilated by generating twice the code. So I'd just go with `DateTime` (or maybe kotlinx `LocalDateTime` ?)

**Comment by cyberhck** [comment]
Whenever I see a `Date` scalar, I'd like to generate 2 operations, one that accepts `Any` and another that accepts the `DateTime`, 

Unfortunately I'm not even an android developer, so I'm trying to understand and navigate the waters, we can't go without A/B tests here (not my decision)

My current idea revolves around:
- extend some mutations and call those on B variants.
- Generate duplicate code ONLY for the operations with the scalar present.

I can't think of a 3rd way.

**Comment by cyberhck** [comment]
I could in theory, temporarily write manually typed class which extends from main one and accepts DateTime and converts that to scalar as well. But I don't see how we're gonna be able to take that implementation once it's accepted, since it wasn't actually generated.

**Comment by cyberhck** [comment]
another way we're looking into:
- duplicate the operation on the server side and use `Date2` scalar and map that instead, and slowly migrate that way instead.

**Comment by martinbonnin** [comment]
> another that accepts the DateTime

What `DateTime` are you talking about? Java has [java.time.LocalDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html), Kotlin has [kotlinx.datetime.LocalDateTime](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-local-date-time/-local-date-time.html) but I can't find a `DateTime`

> Whenever I see a Date scalar, I'd like to generate 2 operations, one that accepts Any and another that accepts the DateTime

The canonical way to do this is to use 2 services like described [above](https://github.com/apollographql/apollo-kotlin/issues/4703#issuecomment-1441443745).

> we can't go without A/B tests here (not my decision)

I'd try to challenge that decision if you can. I'm not sure what data/assumption this A/B test would validate.

> extend some mutations and call those on B variants.
> duplicate the operation on the server side and use Date2 scalar and map that instead, and slowly migrate that way instead.

`Any` vs `DateTime` is purely a client side thing. You should not need to change anything in your backend.

All in all, I'd try to challenge that A/B test decision. What are you trying to prove with an A/B test? If you're looking at Android app performance, there's probably not much difference and it's a lot of effort (and even certainly counterproductive) to generate two versions of the operations.

**Comment by cyberhck** [comment]
> What DateTime are you talking about? Java has java.time.LocalDateTime, Kotlin has kotlinx.datetime.LocalDateTime but I can't find a DateTime

doesn't matter what DateTime exactly, some sort of Strongly typed time information object that's not just string `Any`, I guess they'll go with either of what you described.

> The canonical way to do this is to use 2 services like described

That's what I proposed, have 2 module that generates 2 sets of code and do A/B on that, they expressed it'll increase the APK size by about 1MB (we have about 19 operations, and size of schema isn't that large, I also don't understand why it'd be that big)

> I'd try to challenge that decision if you can. I'm not sure what data/assumption this A/B test would validate.

I also asked for that, but let me push on this.

**Comment by cyberhck** [comment]
> Any vs DateTime is purely a client side thing. You should not need to change anything in your backend.

I know!! this is what makes my blood boil.

**Comment by cyberhck** [comment]
I'll let you guys know how it goes, I just felt it was dirty to have to create new scalars like `Date2` and `Time2` just because the client-side forgot to define the scalar mapping before using them.

**Comment by martinbonnin** [comment]
If you want to use `kotlinx.datetime.LocalDateTime`, Apollo Kotlin comes with [builtin adapters](https://www.apollographql.com/docs/kotlin/essentials/custom-scalars#apollo-provided-adapters) for this. 

You can configure this in your Gradle file:

```
dependencies {
  implementation("com.apollographql.apollo3:apollo-runtime")
}

apollo {
  service("service") {
    mapScalar("DateTime", "kotlinx.datetime.LocalDateTime", "com.apollographql.apollo3.adapter.KotlinxLocalDateTimeAdapter")
  }
}
```

**Comment by cyberhck** [comment]
We're using rfc-3339 formatted strings, so I'm not sure if that handles it

**Comment by martinbonnin** [comment]
@cyberhck any update here? Did you find a solution? Anything else we can help with?

**Comment by cyberhck** [comment]
@martinbonnin the reason we wanted to do a/b testing was to de-risk, we basically do experimentation on every change that's possible.

The way we approached this was just by letting android team change the schema to their liking, this only works in queries and not in mutations, but that was enough for the current needs.

**Comment by martinbonnin** [comment]
@cyberhck nice, thanks for the update!
