### ISSUE TITLE
Ability to disable APQ for subscriptions

### ISSUE THREAD

**Issue by baconz** [apollographql/apollo-kotlin#4730]
### Use case

Our subscription server does not support APQ, and we would like to be able to disable the feature only for subscriptions.

**Comment by martinbonnin** [comment]
I don't think APQs are supported for subscriptions anyways? Subscriptions are using WebSockets so it's a completely different code path. What am I missing there? Is there something that makes you think subscriptions send hashed queries?

**Comment by martinbonnin** [comment]
Woops my bad, [it's reusing parts of the APQ logic](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/http/DefaultHttpRequestComposer.kt#L251) indeed 👍 

There might be ways to disable this with an interceptor or something like this, looking into it.

**Comment by martinbonnin** [comment]
Something like below should work:

```kotlin
class BypassApqForSubscriptions: ApolloInterceptor {
  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return if (request.operation is Subscription<*>) {
      chain.proceed(request)
    } else {
      chain.proceed(request.newBuilder().enableAutoPersistedQueries(false).build())
    }
  }
}
```

And call it in your `ApolloClient.Builder` before configure APQs:

```kotlin
  val client = ApolloClient.Builder()
      .httpServerUrl("https://..")
      .webSocketServerUrl("http://...")
      // needs to be before autoPersistedQueries
      .addInterceptor(BypassApqForSubscriptions())
      .autoPersistedQueries()
      .build()
```

**Comment by baconz** [comment]
Ah, nice!!

**Comment by martinbonnin** [comment]
Did it work? Mind if I close this one?

**Comment by baconz** [comment]
Yep, it works! Feel free to close it! Thank you!!
