### ISSUE TITLE
Apollo Legacy version gradle issue after upgrading gradle version to 7.2 

### ISSUE THREAD

**Issue by pparvathaneni2** [apollographql/apollo-kotlin#4731]
### Question

1: Task failed with an exception.
-----------
* What went wrong:
Some problems were found with the configuration of task ':app:generateDebugApolloClasses' (type 'ApolloExperimentalCodegenTask').
  - In plugin 'com.apollographql.android' type 'com.apollographql.apollo.gradle.ApolloExperimentalCodegenTask' property 'generateKotlinModels' of mutable type 'org.gradle.api.provider.Property' is writable.
    
    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.
    
    Possible solution: Remove the 'setGenerateKotlinModels' method.
    
    Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
  - In plugin 'com.apollographql.android' type 'com.apollographql.apollo.gradle.ApolloExperimentalCodegenTask' property 'generateModelBuilder' of mutable type 'org.gradle.api.provider.Property' is writable.
    
    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.
    
    Possible solution: Remove the 'setGenerateModelBuilder' method.
    
    Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
  - In plugin 'com.apollographql.android' type 'com.apollographql.apollo.gradle.ApolloExperimentalCodegenTask' property 'generateVisitorForPolymorphicDatatypes' of mutable type 'org.gradle.api.provider.Property' is writable.
    
    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.
    
    Possible solution: Remove the 'setGenerateVisitorForPolymorphicDatatypes' method.

**Comment by martinbonnin** [comment]
Thanks for opening this. Looks like you are quite on some old version. Can you try with [2.5.14](https://github.com/apollographql/apollo-kotlin/releases/tag/v2.5.14)?

**Comment by pparvathaneni2** [comment]
Thanks for your quick response @martinbonnin after updating to 2.5.14 it is not generating GraphQL queries and mutations import com.apollographql.apollo.response.CustomTypeValue;
                                        ^
  symbol:   class CustomTypeValue
  location: package com.apollographql.apollo.response 
these are some of the errors

**Comment by martinbonnin** [comment]
CustomTypeValue should be available. Did you add `apollo-runtime` to your dependencies? 

```kotlin
dependencies {
  implementation("com.apollographql.apollo:apollo-runtime:2.5.14")
}
```

**Comment by pparvathaneni2** [comment]
Yes i have @martinbonnin

**Comment by martinbonnin** [comment]
Then I'm not sure what's happening. Can you share the full error with `./gradlew build --stacktrace`?

**Comment by pparvathaneni2** [comment]
I can email you could you please share you email @martinbonnin

**Comment by martinbonnin** [comment]
You can write at martin at apollographql.com

**Comment by martinbonnin** [comment]
You can write at martin at apollographql.com
