### ISSUE TITLE
ApolloCall.addHttpHeader rewriting all existing headers from ApolloClient for request but not add them.

### ISSUE THREAD

**Issue by Ezhvtumane** [apollographql/apollo-kotlin#4753]
### Question

Hello

I am creating an ApolloClient with common for all requests authorization header:

`ApolloClient.Builder().serverUrl(apolloClientProperties.url).addHttpHeader(HttpHeaders.AUTHORIZATION, "Token ${apolloClientProperties.token}").build()`

Then for each request I need to add another custom header - for each request its own: 
`apolloClient.mutation(...).addHttpHeader("my-custom-header", header)`

Calling `apolloClient.mutation().addHttpHeader()` should perform the `add` operation, but it does not add a header to already existing Authorization header from client, but add only header from request and delete header from client. That is, the authorization header from apolloClient is disappear. Should it be that the headers are replaced and you need to re-add the authorization header from client for each request, or is this a bug?

I've found place where we rewrite headers from client by headers from request:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/8047401/225000238-04bbbf49-820c-49c3-b273-7fd69cc27596.png">

As a result I lost my Authorization header.
As workarond I can add all headers before request, but my question is this a bug or feature?

versions:
apollo 3.7.4

**Comment by martinbonnin** [comment]
Tentative fix/improvement there: https://github.com/apollographql/apollo-kotlin/pull/4754. Let me know what you think

**Comment by Ezhvtumane** [comment]
Thank you for quick answer. 
It looks like your PR solving my problem and I can add additional headers per request by calling addHttpHeaders. I hope it's not breaking changes?) 
Waiting for new release!

**Comment by martinbonnin** [comment]
>  It looks like your PR solving my problem and I can add additional headers per request by calling addHttpHeaders. I hope it's not breaking changes?)

It'll be in the SNAPSHOTs soon. It's not a breaking change although it obviously changes the behaviour a bit. I think that should be the default behaviour so we should certainly backport that to 3.x. @BoD any thoughts?

**Comment by Ezhvtumane** [comment]
You guys are amazing!

**Comment by martinbonnin** [comment]
Fixed in 3.8.0
