### ISSUE TITLE
How i can modify model class of graph-ql in android?

### ISSUE THREAD

**Issue by anilthummar** [apollographql/apollo-kotlin#4758]
### Question

i have created below class by apollo graph ql, i want to modify this class in android.
can i modify model class of graph-ql in android? how to modify this model class ? is any way to do it ?

```kotlin
 public data class LoginMutation(
  public val email: String,
  public val password: String,
) : Mutation<LoginMutation.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    LoginMutation_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> = LoginMutation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.example.graphqlquerymutationdemo.type.Mutation.type
  )
  .selections(selections = LoginMutationSelections.__root)
  .build()

  @ApolloAdaptableWith(LoginMutation_ResponseAdapter.Data::class)
  public data class Data(
    public val login: Login,
  ) : Mutation.Data

  public data class Login(
    public val meta: Meta,
    public val `data`: Data1,
  )

  public data class Meta(
    public val status: Boolean,
    public val message: String,
    public val message_code: String,
    public val status_code: Int,
  )

  public data class Data1(
    public val token_type: String,
    public val expires_in: String,
    public val access_token: String,
    public val refresh_token: String,
    public val user: User?,
  )

  public data class User(
    public val uuid: String,
    public val first_name: String?,
    public val last_name: String?,
    public val email: String,
    public val mobile_number: String?,
  ) 
```

**Comment by martinbonnin** [comment]
Hi @anilthummar 👋 

You can modify the files manually before sending them to the Kotlin compiler or you can use [codegen hooks](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.7.0) to modify them with KotlinPoet. These are 2 options. Can you share more about your use case? What do you want to do?

**Comment by anilthummar** [comment]
@martinbonnin  Thank you so much for the feedback.
i want to edit data model class at runtime its possible ?
i mean want to change from val to var in mode class.

Below is my model class and its created auto generated, so i want to modify and update my data with this class.

`public class CountryListQuery() : Query<CountryListQuery.Data> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This operation doesn't have any variable
  }

  public override fun adapter(): Adapter<Data> = CountryListQuery_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.example.graphqlquerymutationdemo.type.Query.type
  )
  .selections(selections = CountryListQuerySelections.__root)
  .build()

  @ApolloAdaptableWith(CountryListQuery_ResponseAdapter.Data::class)
  public data class Data(
    public var CountryList: CountryList?,
  ) : Query.Data

  public data class CountryList(
    public var meta: Meta,
    public var `data`: List<Data1?>?,
  )

  public data class Meta(
    public var message: String,
    public var message_code: String,
    public var status: Boolean,
    public var status_code: Int,
  )

  public data class Data1(
    public var uuid: String?,
    public var country_code: String?,
    public var name: String?,
    public var phone_code: String?,
    public var is_default: Boolean?,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "fb4473422dcdbf847d6078266cda5394ccd8d9b68c7e451247d19075a181ed89"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query CountryList {
     *   CountryList {
     *     meta {
     *       message
     *       message_code
     *       status
     *       status_code
     *     }
     *     data {
     *       uuid
     *       country_code
     *       name
     *       phone_code
     *       is_default
     *     }
     *   }
     * }
     */
    public val OPERATION_DOCUMENT: String
      get() =
          "query CountryList { CountryList { meta { message message_code status status_code } data { uuid country_code name phone_code is_default } } }"

    public const val OPERATION_NAME: String = "CountryList"
  }
}
`

**Comment by martinbonnin** [comment]
> i want to edit data model class at runtime its possible ?

Apollo Kotlin promotes using immutable data structures. You can read more about immutability in Kotlin in [this article](https://elizarov.medium.com/immutability-we-can-afford-10c0dcb8351d) from Roman Elizarov. 

Instead of mutating your class, you can use the `copy` method on data classes: 

```kotlin
val data = apolloClient.query(CountryListQuery()).data!!

val modifiedData = data.copy(
   countryList = data.countryList.`data`.map { country ->
     if (country. country_code == "fr") {
       // make France the default country
       country.copy(is_default = true)
     } else {
       // other countries do not change
       country
     }
   }
)
```

We're aware it's a bit tedious to update deeply nested fields as you have to copy all the way down. We're planning to improve this with https://github.com/apollographql/apollo-kotlin/issues/3573

**Comment by anilthummar** [comment]
@martinbonnin  okayt let me check with copy method

**Comment by anilthummar** [comment]
@martinbonnin isany other way to changed model class field automatically like-  

' public data class CountryList(
    public val meta: Meta,
    public val `data`: List<Data1?>?,
  ) '
i want this class like below :

' public data class CountryList(
    public var meta: Meta,
    public var `data`: List<Data1?>?,
  )

**Comment by anilthummar** [comment]
ok @martinbonnin thank you.

**Comment by martinbonnin** [comment]
Sure thing! Let me know if there's anything we can do. Else I'll close this issue.

**Comment by anilthummar** [comment]
@martinbonnin  no more issue please close this issue.
