### ISSUE TITLE
Does Apollo Kotlin support multiple interfaces?

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4771]
### Question

GraphQL official spec says: "An object type may declare that it implements one or more unique interfaces."
Does Apollo Kotlin supports this?
[reference](https://stackoverflow.com/questions/45227332/is-it-possible-to-implement-multiple-interfaces-in-graphql)

**Comment by martinbonnin** [comment]
Yep, that works. Apollo Kotlin claims full compatibility with the latest version of the spec and most of the draft. If something doesn't work, please give some specifics.

**Comment by ynkm169** [comment]
Thank you!
