### ISSUE TITLE
Partial memory cache hit

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4773]
### Question

Hi, say I am querying this 

```
author {     # Author object
      id
      first_name
      last_name
}
```

Question 1: Say if cache contains id and first_name but not last_name, would CacheOnly policy result in no data returned when there is partial cache hit? 
Question 2: What if I change last_name in the schema to nullable, would the partial cache hit return partial data or no data?

Is there a way around this? I want the cache to return partial result of id and first_name. It’s ok for last_name to be missing. However if last_name is not nullable I imagine this wouldn’t work.

I can’t write a custom query to query only id and first_name. I want to query the full author object and retrieve only from cache, with possibility of certain fields missing.

—————
Realistic situation:
App has 50 screens. Each screen retrieve a list of author objects. Each list will request different fields from author object. One list may retrieve all fields, another may skip last_name.

1. Clicking on the author view in any of the 50 screens, will result in opening an AuthorDetailPage.
I want to fetch from the cache of the particular author object with id of “1” for the AuthorDetailPage. I will write a query with policy of CacheOnly to fetch all the fields of this author object. The reason I am fetching all fields is because different screens request different fields, there is no way for  AuthorDetailPage to know which fields may be in cache. I want AuthorDetailPage to display fields that are available and those not available will be set as View.Gone.
I am trying to display as much info from cache as possible so user doesn’t feel like they are waiting forever.

2. Later on, I will fetch from network the full author object and display/update whatever fields are missing/out-of-date.

As far as I can tell, I don’t see a way to achieve #1.
The only option I possibly have is for all lists in the 50 screens to fetch exactly same fields or more fields than what AuthorDetailPage will fetch from cache. This way it will either be cache hit or miss and there wouldn’t be a situation of partial cache hit at all (which I suppose will result in no data returned with CacheOnly fetch policy).

This is not ideal, since if only 1 out of 50 lists show last_name, I will be forced to request last_name for all lists if AuthorDetailPage wants to fetch last_name from cache.

**Comment by martinbonnin** [comment]
As of today, there is no notion of partial cache result. It's either a full cache hit or a cache miss.

> Is there a way around this? I want the cache to return partial result of id and first_name. It’s ok for last_name to be missing. However if last_name is not nullable I imagine this wouldn’t work.

We could in the future imagine having the cache behave like the network and return partial data with errors in `response.errors` but you guessed right that this won't work for non-nullable fields, the error will bubble to the next nullable field. 

> The only option I possibly have is for all lists in the 50 screens to fetch exactly same fields or more fields than what AuthorDetailPage will fetch from cache

Depends your use case but that might be an option. You can use fragments to group fields together. You'll pay an higher price for the initial query but subsequent ones should be faster and be able to use the cache.

**Comment by ynkm169** [comment]
Thanks for confirming!

I read this buried in the doc
“A single missing field in the cache for a query will trigger a network fetch. Sometimes it might be useful to query an extra field early on so that it can be reused by other later queries.”
