### ISSUE TITLE
creating multiple services with single interface having Redeclaration issue

### ISSUE THREAD

**Issue by mrutyunjay193** [apollographql/apollo-kotlin#4774]
### Question

upgrading version 1.2.1 to 1.3 its telling to add multiple services after adding multiple services it creating problem for class Redclaration
<img width="404" alt="Screenshot 2023-03-20 at 8 02 22 PM" src="https://user-images.githubusercontent.com/39740416/226372029-b1547ca6-442d-4cdf-919f-9dd5cc613415.png">
<img width="404" alt="Screenshot 2023-03-20 at 8 02 22 PM" src="https://user-images.githubusercontent.com/39740416/226372228-d3c068c5-4500-477c-a021-0ee1dac95c5d.png">
<img width="707" alt="Screenshot 2023-03-20 at 8 03 24 PM" src="https://user-images.githubusercontent.com/39740416/226372240-ade869d7-c1b8-4ed6-ae1b-d7b08d3efd72.png">

**Comment by mrutyunjay193** [comment]
buildscript {
    ext.kotlinVersion = '1.3.61'
    ext.apolloVersion = '1.3.3'
    ext.androidNavigation = '2.3.5'

    ext.ktorVersion = '1.1.5'
    ext.coroutinesVersion = '1.2.1'
    ext.serializationVersion = '0.11.0'

    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "com.apollographql.apollo:apollo-gradle-plugin:$apolloVersion"
        classpath "com.google.gms:google-services:4.3.3"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$androidNavigation"
        classpath "com.jaredsburrows:gradle-spoon-plugin:1.5.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.22.0"
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        // For espresso-helper
        maven { url "https://jitpack.io" }
        // PS Home Webservices this liberary is deprecated
//        maven { url "https://dl.bintray.com/kotlin/ktor" }
        // TODO: Remove after coroutines is on JCenter (https://github.com/apollographql/apollo-android/issues/1325)
//        maven { url "https://dl.bintray.com/apollographql/android" }
    }

    tasks.withType(Test) {
        // Log each test as they are run. See https://stackoverflow.com/a/36130467/3946288
        testLogging {
            events TestLogEvent.FAILED, TestLogEvent.PASSED, TestLogEvent.SKIPPED
            exceptionFormat TestExceptionFormat.FULL
            showExceptions true
            showCauses true
            showStackTraces true

            afterSuite { desc, result ->
                if (!desc.parent) { // will match the outermost suite
                    def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes, ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
                    def startItem = '|  ', endItem = '  |'
                    def repeatLength = startItem.length() + output.length() + endItem.length()
                    println('\n' + ('-' * repeatLength) + '\n' + startItem + output + endItem + '\n' + ('-' * repeatLength))
                }
            }
        }

        // Don't fail the build on a test failure.  CI has additional steps it needs to run to build a report, it will still fail the build.
        ignoreFailures = true
    }

    // Treat Kotlin compiler warnings as errors.  See https://stackoverflow.com/a/46244803/3946288
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
        kotlinOptions.allWarningsAsErrors = true
    }
}

subprojects {
    apply from: '../dependencies.gradle'
    apply from: '../versions.gradle'
    apply from: '../detekt.gradle'

    // Copy test classes so Android Studio properly displays code coverage
    // https://stackoverflow.com/questions/45350561/android-studio-3-kotlin-code-coverage
    task copyTestClasses(type: Copy) {
        from "build/tmp/kotlin-classes/debug"
        into "build/intermediates/classes/debug"
    }

    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                // tensorflow lite files cannot be compressed
                aaptOptions {
                    noCompress "tflite"
                    noCompress "lite"
                }

                kotlinOptions {
                    jvmTarget = "1.8"
                }
            }
        }
    }
}



=======



apply plugin: 'com.android.library'
apply plugin: 'com.apollographql.apollo'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion versions.compileSdkVersion
    defaultConfig {
        minSdkVersion versions.minSdkVersion
        targetSdkVersion versions.targetSdkVersion
        versionCode versions.versionCode
        versionName versions.versionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    apollo {
       generateKotlinModels.set(true)

//
        service("v2") {
            sourceFolder = "/Users/mrutyunjay.swain/AndroidStudioProjects/WorkSpace/push_notification/webservices/src/main/graphql/com/power/webservices/v2"
        }

        service("v3") {
            sourceFolder = "/Users/mrutyunjay.swain/AndroidStudioProjects/WorkSpace/push_notification/webservices/src/main/graphql/com/power/webservices/v3"
        }

        service("global") {
            sourceFolder = "/Users/mrutyunjay.swain/AndroidStudioProjects/WorkSpace/push_notification/webservices/src/main/graphql/com/power/webservices/global"
        }
        onCompilationUnit {
            // Overwrite some options here for single CompilationUnit if needed
        }

        customTypeMapping = [
            "Date" : "java.util.Date",
            "DateTime": "java.util.Date"
        ]
    }
}

kapt {
    // Offers links to locations in the original Kotlin code rather than generated Java stubs
    // as it reports errors encountered during annotation processing
    mapDiagnosticLocations = true
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar']) // TODO Changed from implementation to API for webservices

    implementation project(':common')

    // Apollo
    api "com.apollographql.apollo:apollo-runtime:$apolloVersion"
    api "com.apollographql.apollo:apollo-rx2-support:$apolloVersion"
    api "com.apollographql.apollo:apollo-http-cache:$apolloVersion"
    api "com.apollographql.apollo:apollo-coroutines-support:$apolloVersion"

    // OkHttp
    api "com.squareup.okhttp3:okhttp:$sharedVersions.okhttp"

    // PS Home WebServices
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.13.0"
    implementation "io.ktor:ktor-client-core-jvm:1.2.5"
    implementation "io.ktor:ktor-client-json-jvm:1.2.5"
    implementation "io.ktor:ktor-client-serialization-jvm:1.2.5"
    implementation "io.ktor:ktor-client-okhttp:1.2.5"

    // Testing
    testImplementation testImplementationLibraries
    androidTestImplementation androidTestImplementationLibraries
    testImplementation project(':testcommon')

}

**Comment by BoD** [comment]
Thank you! I guessed wrong, it looks you are trying to use version 1.3.3. As 1.x is fairly ancient, can you try a more recent version (last one is 3.7.5)?

**Comment by mrutyunjay193** [comment]
i updated but still issue

apollo {
        service("global") {
            packageName.set("com/power/webservices/global")
            generateKotlinModels.set(true)
            customTypeMapping = [
                "Date" : "java.util.Date",
                "DateTime": "java.util.Date"
            ]
        }
        service("v2") {
//            sourceFolder.set("com/powerschool/webservices/v2")
            packageName.set("com/power/webservices/v2")
            generateKotlinModels.set(true)
            customTypeMapping = [
                "Date" : "java.util.Date",
                "DateTime": "java.util.Date"
            ]
        }
        service("v3") {
            packageName.set("com/power/webservices/v3")
            generateKotlinModels.set(true)
            customTypeMapping = [
                "Date" : "java.util.Date",
                "DateTime": "java.util.Date"
            ]
//            rootPackageName.set("com.powerschool.webservices.v3")
        }
<img width="1610" alt="Screenshot 2023-03-21 at 8 23 28 PM" src="https://user-images.githubusercontent.com/39740416/226646552-c207522a-7bc4-41dd-91da-f0cc6cf84090.png">
<img width="1260" alt="Screenshot 2023-03-21 at 8 24 14 PM" src="https://user-images.githubusercontent.com/39740416/226646569-ac7394fb-d5d9-47cc-aaa0-beddaddc7abb.png">

**Comment by BoD** [comment]
When using multiple services you should use the `srcDir` option to instruct the plugin where to look for the graphql files.
Also `packageName` should use dots.

 Something like:

```
apollo {
	service("global") {
		packageName.set("com.power.webservices.global")
		srcDir("src/main/graphql/com/power/webservices/global")
        // ...
	}

	service("v2") {
		packageName.set("com.power.webservices.v2")
		srcDir("src/main/graphql/com/power/webservices/v2")
        // ...
	}

    // etc.
}
```

Also, note for the scalar declaration you should now use `mapScalar` (doc is [here](https://www.apollographql.com/docs/kotlin/essentials/custom-scalars#define-class-mapping)).

**Comment by mrutyunjay193** [comment]
After change  ApolloQueryCall not importing and also HttpCachePolicy
<img width="1095" alt="Screenshot 2023-03-23 at 11 27 35 AM" src="https://user-images.githubusercontent.com/39740416/227116527-e054c6d8-db48-40f5-bba4-55f697b71ac8.png">

**Comment by BoD** [comment]
That's because some classes have been renamed or the way to use them have changed between major versions. You would have to follow the migration guides [here](https://www.apollographql.com/docs/kotlin/v2/essentials/migration) and [here](https://www.apollographql.com/docs/kotlin/migration/3.0).

**Comment by mrutyunjay193** [comment]
can you tell me  replacement method for  ApolloQueryCall,ApolloMutationCall, i am unable find this method details in apollo documentation

**Comment by BoD** [comment]
Here's how you execute a query now:
```kotlin
apolloClient.query(MyQuery(parameters)).execute()
```
The `query` method returns an `ApolloCall`. More info [here](https://www.apollographql.com/docs/kotlin/essentials/queries).

Similarly, here's how you execute a mutation:
```kotlin
apolloClient.mutation(MyMutation(parameters)).execute().
```
More info about mutations [here](https://www.apollographql.com/docs/kotlin/essentials/mutations).

**Comment by martinbonnin** [comment]
@mrutyunjay193 I'm going to close this one for now. Please leave a comment if you need us to reopen it.
