### ISSUE TITLE
Gracefully degrate to non-APQ if server doesn't support APQ

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-kotlin#4787]
### Use case

In Apollo 2.x, when client has APQ enabled but server doesn't support it, Apollo would eventually fall back to full query with document:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/3951580/227232988-d0d36b1d-9ce0-4d8f-889f-476a4c87bf21.png">

Now, if server doesn't support APQ, Apollo will simply return an error:
https://github.com/apollographql/apollo-kotlin/blob/99126fdf4ebf7330a3dab7a3d7fc1f5b0fa122b7/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/interceptor/AutoPersistedQueryInterceptor.kt#L52-L58

### Describe the solution you'd like

It seems reasonable to fall back (or at least have an option to do so) to a full document query if server is misconfigured and doesn't support APQ. The reasoning is that it's possible, and would avoid client downtime due to e.g. temporary server problems. Clients can then log APQ errors to issue tracker of choice and resolve the issue on the backend while not losing functionality.

**Comment by BoD** [comment]
Hi! This does sound reasonable to me. Would you be interested in giving it a go? Otherwise I can have a look at it!

**Comment by lwasyl** [comment]
I can try! 

Would it make sense to expose information about this error through `AutoPersistedQueryInfo` or a similar mechanism? Unfortunately it only supports `val hit: Boolean` so I'd need to do

```kotlin
AutoPersistedQueryInfo(
  val hit: Boolean,
  val serverApqEnabled: Boolean,
)
```

I suppose, wdyt? 🤔 Or I can not expose new information, just add `AutoPersistedQueryInfo(hit = false)` and let the user get errors via additional interceptors like https://github.com/apollographql/apollo-kotlin/pull/4709, though `AutoPersistedQueryInfo` is pretty convenient 🙂

**Comment by BoD** [comment]
Oh yes if you need to get back that information, `AutoPersistedQueryInfo` is probably perfect for that, and yes adding this field sounds good to me.

**Comment by martinbonnin** [comment]
I think you can do this quite easily with an `ApolloInterceptor` you put in front of the APQ interceptor?

```kotlin
val interceptor = object : ApolloInterceptor {
  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return (chain.proceed(request).catch { 
      if (it is AutoPersistedQueriesNotSupported) {
        // Recover
        emitAll(chain.proceed(request.newBuilder().enableAutoPersistedQueries(false).build()))
      } else {
        throw it
      }
    })
  }
}
```

It could even be made stateful so that the interceptor remembers a given server does not support APQ

**Comment by martinbonnin** [comment]
@lwasyl did you end up finding a satisfying solution there? I don't want to leave this hanging so if you have a use case for it, go for it.

**Comment by lwasyl** [comment]
Ah, sorry I didn't see notification. No, actually it turned out that the interceptor you suggested is perfectly fine for my use case, even without https://github.com/apollographql/apollo-kotlin/pull/4709 :slightly_smiling_face:
