### ISSUE TITLE
Adapter convert a Time to/from [java.time.LocalTime]

### ISSUE THREAD

**Issue by jarroyoesp** [apollographql/apollo-kotlin#4828]
### Use case

Our GraphQL Server is sending us one Scalar type that represents `java.time.LocalTime`, and we would like to use an `Adapter` to convert this data to LocalTime. The format for this type is: "HH:mm[:ss[.SSS]]" (e.g. 14:25:00)

### Describe the solution you'd like

It would be great to have an adapter similar to `JavaLocalDate`: https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-adapters/src/jvmMain/kotlin/com/apollographql/apollo3/adapter/JavaTimeAdapters.kt#L43 but for `JavaLocalTime`. 

Something like this:
```Kotlin
import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import java.time.LocalTime

object JavaLocalTimeAdapter : Adapter<LocalTime> {
    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): LocalTime {
        return LocalTime.parse(reader.nextString()!!)
    }

    override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: LocalTime) {
        writer.value(value.toString())
    }
}
```

**Comment by BoD** [comment]
Hi!

I think it could make sense to have it (and the kotlinx version as well). Would you be interested in opening a PR?

**Comment by jarroyoesp** [comment]
Hey, sure, PR is already created 🚀: https://github.com/apollographql/apollo-kotlin/pull/4829

**Comment by BoD** [comment]
Thanks a lot for the contribution! It has been merged to our main branch, so it will be part of the upcoming v4 🙏.

**Comment by jarroyoesp** [comment]
Hey @BoD cool! So glad to contribute to this amazing library! 🚀
