### ISSUE TITLE
ExpireDateCacheResolver issue

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4831]
### Version

3.8.0

### Summary

Hello. 
I couldn't get it to work. This is the cache control header server send to client.
`cache-control: max-age=10`

Note, the following is just guesses. I am not 100% if my guess is correct. Apollo code is quite deep.
The reason it is not working is MAYBE because maybeWriteToCache seems to write empty header into cache.

1. response.executionContext.headers size is 18 with correct header. See screenshot.
<img width="785" alt="Screenshot 2023-04-03 at 5 09 24 PM" src="https://user-images.githubusercontent.com/1810298/229628158-2b839a71-3b8b-4bf1-8848-febd91f9e907.png">

2. response.cacheHeaders on line 75 in previous screenshot returns empty due to

- response.cacheHeaders is implemented like this
```
val <D : Operation.Data> ApolloResponse<D>.cacheHeaders
  get() = executionContext[CacheHeadersContext]?.value ?: CacheHeaders.NONE
```
- executionContext is an instance of HttpInfo. If you look at definition of HttpInfo, I think calling executionContext[CacheHeadersContext] on an instance of HttpInfo will always return empty. 
It should probably call this instead
`executionContext[HttpInfo]?.headers`
<img width="758" alt="Screenshot 2023-04-03 at 5 10 13 PM" src="https://user-images.githubusercontent.com/1810298/229628282-83c4340a-b1b9-4ef1-9689-4c99d1efaeab.png">

**Another thing I noticed is**
StoreExpirationInterceptor intercept is returning correct expires value. However, store.writeOperation inside maybeWriteToCache is invoked before StoreExpirationInterceptor intercept.
<img width="493" alt="Screenshot 2023-04-03 at 6 04 38 PM" src="https://user-images.githubusercontent.com/1810298/229637560-132bdd4c-bfcf-4158-8db2-03994f97f08b.png">

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment]
Hi!

Just to be sure, are you using the incubating normalized cache (`apollo-normalized-cache-incubating`, `apollo-normalized-cache-sqlite-incubating` dependencies)?

At the moment, the storage of the cache headers (where the dates are stored) only works with those. If yes, make also sure to initialize the SQLite cache with `withDates = true`.

You can have a look at [this test](https://github.com/apollographql/apollo-kotlin/blob/99590381c4dfbeed2b72665da6df6b2a9a941ac9/tests/sqlite/src/commonTest/kotlin/ExpirationTest.kt#L81) to check if anything is different in your setup.

**Comment by ynkm169** [comment]
Hello, 
apollo-rx2-support is including api(project(":apollo-normalized-cache")) as dependency. It results in duplicate dependencies build error.

What's best way to resolve this?

**Comment by BoD** [comment]
Can you try to exclude the transitive dependency like so:

```kotlin
    implementation("com.apollographql.apollo3:apollo-rx2-support") {
        exclude("com.apollographql.apollo3:apollo-normalized-cache")
    }
```

**Comment by BoD** [comment]
@ynkm169 Did you pass `withDates = true` to your `SqlNormalizedCacheFactory` and call `.storeReceiveDate(true)` on your `ApolloClient.Builder` like in [this example](https://github.com/apollographql/apollo-kotlin/blob/e6c02d6cb9d0a24ef76af237f827d68a4ff57c27/tests/sqlite/src/commonTest/kotlin/ExpirationTest.kt#L44)?

**Comment by ynkm169** [comment]
@BoD We don't use Sql cache, only the memory cache. May I ask what's reason to use SqlNormalizedCacheFactory?

**Comment by BoD** [comment]
> Is it possible to use server driven expiry with only memory cache?

Sorry I didn't realize you were using the memory cache only! Currently this is not available with the memory cache, but only with the SQL one.

**Comment by ynkm169** [comment]
Thanks for confirming, will close out the ticket. I don't think we currently have a use case to specify expiry at a query level. We will migrate our feature to GraphQL once this feature request is delivered: https://github.com/apollographql/apollo-kotlin/issues/4158
Thanks!
