### ISSUE TITLE
Remove initRuntimeIfNeeded() in Project

### ISSUE THREAD

**Issue by ProVir** [apollographql/apollo-kotlin#4858]
### Version

3.8.0

### Summary

In the new memory model, the `initRuntimeIfNeeded()` call is no longer required.
This was suggested to me by one of the Kotlin/Native developers.

Also in Kotlin 1.9 there will be an explicit warning that the function is no longer needed.
https://github.com/JetBrains/kotlin/commit/9dd778bc8980a62bf05f1f2fedbb9c1d83ff2c4f

In your code, I have seen such a function in at least one place: https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-runtime/src/appleMain/kotlin/com/apollographql/apollo3/network/http/NSURLSessionHttpEngine.kt

**Comment by martinbonnin** [comment]
Good callout 👍 . Want to do the honours and open a PR?

**Comment by echo304** [comment]
Can I take this issue instead? @martinbonnin ✋

**Comment by martinbonnin** [comment]
@echo304 sure thing, go for !t
