### ISSUE TITLE
Introspection not downloading schema

### ISSUE THREAD

**Issue by AdieOlami** [apollographql/apollo-kotlin#4863]
### Version

3.8.0

### Summary

the introspection does not download for me.
```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id 'com.google.dagger.hilt.android'
    id 'kotlin-kapt'
    id 'com.apollographql.apollo3'
}

dependencies {
    // Apollo
    implementation "com.apollographql.apollo3:apollo-runtime:$apollo_version"
    implementation "com.apollographql.apollo3:apollo-normalized-cache-sqlite:$apollo_version"
}

apollo {
    service("service") {
        packageName.set("co.xx.xy")

        introspection {
            endpointUrl.set("https://api.com/query")
            schemaFile.set(file("src/main/graphql/schema.graphqls"))
//            // headers.put("key","val")
        }
    }
}
```
Then my Project level build.gradle
```
buildscript {
    ext {
        apollo_version = '3.8.0'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false
    id 'com.apollographql.apollo3' version "$apollo_version" apply false
}
```
My download does not work at all.

I have tried registering a task but nothing still

This are the tasks that run

> Task :app:checkApolloVersions UP-TO-DATE
> Task :app:generateServiceApolloSources UP-TO-DATE
> Task :checkServiceApolloDuplicates UP-TO-DATE
> Task :app:generateApolloSources UP-TO-DATE
> Task :app:prepareKotlinIdeaImport UP-TO-DATE
> Task :prepareKotlinBuildScriptModel UP-TO-DATE

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Hi 👋 

Not downloading the schema automatically is a conscious decision. Instead, we recommend you commit your schema in source control so that:

1. the build doesn't require a network call
2. most importantly, the build is reproducible

The `introspection {}` block is still useful as it creates a `downloadServiceApolloSchemaFromIntrospection` task that you can call manually:

```
./gradlew downloadServiceApolloSchemaFromIntrospection
```

And then commit the `src/main/graphql/schema.graphqls` file

**Comment by martinbonnin** [comment]
@AdieOlami can you try with the [SNAPSHOTs](https://github.com/apollographql/apollo-kotlin#snapshots)? [3.8.1-SNAPSHOT](https://s01.oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo3/apollo-runtime/3.8.1-SNAPSHOT/) should be available with a fix

**Comment by martinbonnin** [comment]
@AdieOlami anything else we can we help with here?

**Comment by martinbonnin** [comment]
Closing this one. Please leave a message if you want us to investigate more.
