### ISSUE TITLE
Can't able to download schema after updating version to 3.8.0

### ISSUE THREAD

**Issue by vishalbhanderii** [apollographql/apollo-kotlin#4883]
### Version

3.8.0

### Summary

I can't able to download schema from command in 3.8.0

### Steps to reproduce the behavior

I am using this command:

./gradlew downloadApolloSchema --endpoint="https://staging-graphql.outerspatial.com/v1/graphql" --schema="app/src/main/graphql/com/trailheadlabs/outerspatial/schema.json" --header="X-Hasura-Admin-Secret: my-token-here"

this command works fine in 3.7.5 version

### Logs

```
> Task :app:downloadApolloSchema FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:downloadApolloSchema'.
> Cannot decode introspection 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

```

**Comment by martinbonnin** [comment]
Hi 👋 . Thanks for filing this. This seems to be the same issue as https://github.com/apollographql/apollo-kotlin/issues/4859. Can you try with the [SNAPSHOTs](https://github.com/apollographql/apollo-kotlin#snapshots)? [3.8.1-SNAPSHOT](https://s01.oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo3/apollo-runtime/3.8.1-SNAPSHOT/) should be available with a fix

**Comment by vishalbhanderii** [comment]
I tried to change maven url but same error is happening

**Comment by vishalbhanderii** [comment]
@martinbonnin What exactly i need to update/change?

**Comment by martinbonnin** [comment]
You'll need to add the sonatype snapshot repo:

```
// build.gradle.kts
repositories {
  maven {
    url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
  }
  mavenCentral()
  // other repositories...
}

// settings.gradle.kts
pluginManagement {
  repositories {
    maven {
      url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
    gradlePluginPortal()
    mavenCentral()
    // other repositories...
  }
}
```

**Comment by vishalbhanderii** [comment]
@martinbonnin Yeah i did this already check this:

allprojects {
    repositories {
        google()
        maven {
            url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = 'mapbox'
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ''
            }
        }
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}

**Comment by vishalbhanderii** [comment]
@martinbonnin I did that but same error is happening

**Comment by martinbonnin** [comment]
[here](https://github.com/apollographql/apollo-kotlin-tutorial/commit/85e044f348f6185b3d651e971f67e23c1195401a) is an example how to use snapshots for the tutorial. 

Depending how you apply your plugins you might have to declare your repositories in other places like `build-logic` or `buildSrc` but it's hard to tell given there are many ways to include plugins.

**Comment by vishalbhanderii** [comment]
@martinbonnin Everything is fine but still same error happening

**Comment by martinbonnin** [comment]
Alright, thanks for trying it 👍 , I'll double check

**Comment by martinbonnin** [comment]
Is your backend available publicly by any chance?

**Comment by martinbonnin** [comment]
Looks like `3.8.1-SNAPSHOT` is working for me with the tutorial though 🤔 . Can you try the following?

```
git clone https://github.com/apollographql/apollo-kotlin-tutorial
cd apollo-kotlin-tutorial/compose/final
git checkout use-snapshot
./gradlew downloadApolloSchema --endpoint https://staging-graphql.outerspatial.com/v1/graphql --schema schema.graphqls
# you should have a schema.graphqls now
```

**Comment by hiren369** [comment]
Hello @martinbonnin,

I've tried with the above command and all and it's working perfectly!
But when i tried same command "**./gradlew downloadApolloSchema --endpoint https://staging-graphql.outerspatial.com/v1/graphql --schema schema.graphqls"** in mine then getting BUILD FAILED!

**Comment by hiren369** [comment]
![233087047-75fbb391-777e-4108-bb07-90248271d228](https://user-images.githubusercontent.com/24586458/233087155-7222718f-7628-4770-a03f-3861bfab7e9a.png)

You can see the screenshot. If you've any idea what is wrong here then please let me know

Thanks

**Comment by martinbonnin** [comment]
Looks like you're still using a non-snapshot version of the gradle plugin. Maybe try `./gradlew :app:buildEnvironment`? Does it show your plugin version?

**Comment by hiren369** [comment]
![image](https://user-images.githubusercontent.com/24586458/233088391-a9dc96d2-981c-44c8-b56e-8c1a27e2409f.png)
See this screenshot

**Comment by martinbonnin** [comment]
I think it's the wrong screenshot? It shows the same "cannot decode introspection" error, not `buildEnvironment`?
PS: this screenshot also contains a secret, you probably want to delete it.

**Comment by hiren369** [comment]
This is the error I am always getting when i changed version 3.7.4 to 3.8.0 

Can you exactly tell me what I need to do in my gradle file so this error resolves

**Comment by martinbonnin** [comment]
You'll most likely need version `3.8.1` (not released yet). It would have been interesting to confirm with `3.8.1-SNAPSHOT` but if it's too much of a hassle, stay on `3.7.4` until we release `3.8.1`

**Comment by BoD** [comment]
@vishalbhanderii @hiren369 This should work now as 3.8.1 as been released. Waiting for your confirmation before closing this issue.

**Comment by hiren369** [comment]
@BoD Yes it's working well using 3.8.1 thanks for you help so now you can close this issue.
Thanks
