### ISSUE TITLE
Task `downloadFooApolloSchemaFromIntrospection` fails to comply with configuration cache

### ISSUE THREAD

**Issue by StylianosGakis** [apollographql/apollo-kotlin#4925]
### Version

3.8.1

### Summary

Discussion started here https://kotlinlang.slack.com/archives/C01A6KM1SBZ/p1683288526488069, but the summary is pretty straightforward. When gradle configuration cache is on, we can't run that generated task as it does not comply with the rules of it, making it crash as soon as it tries to run itself.

### Steps to reproduce the behavior

* Enable configuration cache
* Run the download apollo schema from introspection task

### Logs

```
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:apollo:giraffe:downloadGiraffeApolloSchemaFromIntrospection` of type `com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.0.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

Can also take a look at the report I got out of it 
[configuration-cache-report.html.zip](https://github.com/apollographql/apollo-kotlin/files/11406105/configuration-cache-report.html.zip)

**Comment by StylianosGakis** [comment]
As a current workaround, what I've done was configure the ApolloDownloadSchemaTask to explicitly set that it does not conform to configuration cache, and this does let me run it without having to pass in the --no-configuration-cache flag. Something like this:
```
tasks.withType<com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask>().configureEach {
  notCompatibleWithConfigurationCache("https://github.com/apollographql/apollo-kotlin/issues/4925")
}
```

**Comment by martinbonnin** [comment]
Sorry for the huge delay on this. I tried reproducing with no success so far (reproducer [here](https://github.com/martinbonnin/reproducer-4925)).

Error says something like

```
field `actions` of com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask
``` 

But `actions` is an internal Gradle field. Could it be that you have a `doLast {}` or something like this that references a `Project` instance?

**Comment by StylianosGakis** [comment]
Oh interesting, it might be so! This is how I register them https://github.com/HedvigInsurance/android/blob/791bcf21fa70bee65398fd557760b9aed84e4995/build-logic/convention/src/main/kotlin/ApolloConventionPlugin.kt#L26-L33 and this https://github.com/HedvigInsurance/android/blob/791bcf21fa70bee65398fd557760b9aed84e4995/build-logic/convention/src/main/kotlin/ApolloConventionPlugin.kt#L15-L24 is my doLast.
I see that on line 19, I call `file()` and I see that this is actually the Project.file function, so could it be that I am indirectly referencing the project there from the `with(project)` that I do above? I could write `this@with.file(schemaPath)` to make it more explicit of what I am doing wrong.
If that's the case, I just need to find a better way to fetch that file without going through the project instance maybe?

**Comment by martinbonnin** [comment]
>  this is actually the Project.file function, so could it be that I am indirectly referencing the project there from the with(project) that I do above?

That looks like it. The lambda is serialized to the configuration cache and since it captures a reference to the `Project`, this fails. I'm not super versed into lambdas and configuration cache but I would try capture serializable types like `File` or `String`:

```kotlin
        val rootDirVar = rootDir
        doLast {
            val schemaPath = schema.get()
            val schemaFile = File(rootDirVar).resolve(schemaPath)
            val schemaText = schemaFile.readText()
            val convertedSchema = schemaText.performClientSideChanges()
            schemaFile.writeText(convertedSchema)
        }
```

**Comment by StylianosGakis** [comment]
Worked like a charm, thanks a lot for this! And sorry for the false alarm 🫣 Since it turned out to be 100% on my end instead.
