### ISSUE TITLE
It seems `fun remove(cacheKey: CacheKey, cascade: Boolean)` cache doesn’t work as expected for `cascade = true` value.

### ISSUE THREAD

**Issue by ihermandev** [apollographql/apollo-kotlin#4932]
### Version

3.8.1

### Summary

**Context:** I'm using `SqlNormalizedCacheFactory` with 7 cached rows in the database. I'm trying to perform delete actions using `apolloClient.apolloStore.accessCache { cache -> // perform delete actions}`.

**Table:** I have the following cached rows in the database:
| _id | key | record |
| -------- | -------- | -------- |
| 1 | user.workPermit | {“__typename":"WorkPermit","documents":["ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732}","ApolloCacheReference{Document:6050a8eb-dbe0-4e9e-9afc}"]} |
| 2| Document:191e771f-4c2e-4a2d-8732.group | {} |
| 3| Document:191e771f-4c2e-4a2d-8732.type | {} |
| 4| Document:191e771f-4c2e-4a2d-8732.validity | {} |
| 5| Document:191e771f-4c2e-4a2d-8732 | {"id":"191e771f-4c2e-4a2d-8732”,”group":"ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732.group}","type":"ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732.type}","validityRange":"ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732.validityRange}","__typename":"Document","pages":["ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732.pages.0}"]} |
| 6| Document:191e771f-4c2e-4a2d-8732.pages.0.type | {} |
| 7| Document:191e771f-4c2e-4a2d-8732.pages.0 | {} |

**Code snippets:**
I'm using `cache.remove()` to perform delete actions. Here's what I observed:

1. `cache.remove(CacheKey(key = "Document:191e771f-4c2e-4a2d-8732"),cascade = false )` —> returns `true` and removes just ID: 5 row as expected.
2. `cache.remove(pattern = "Document:191e771f-4c2e-4a2d-8732%")` —> returns `6` and removes 2-7 IDs rows as expected.
3. `cache.remove(CacheKey(key = "Document:191e771f-4c2e-4a2d-8732"),cascade = true )` —> returns `true` and removes **nothing**. The expected behavior is to remove at least ID 5 row and the reference `ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732} ` from the record of ID 1 row.

Another question is how I can remove `ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732}` reference from `user.workPermit` key in case of using the second delete method with a predefined pattern? It looks too complicated to just remove some record references manually.

### Steps to reproduce the behavior

- configure`SqlNormalizedCacheFactory`
- populate the apollo cache with similar or identical data from the **Summary** section
- try to use `apolloClient.apolloStore.accessCache { cache -> cache.remove(key, cascade = true)} `

**Comment by BoD** [comment]
Thanks a lot for reporting this! For `cascade = true`, a fix is pending [here](https://github.com/apollographql/apollo-kotlin/pull/4938).

> Another question is have I can remove ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732} reference from user.workPermit key in case of using the second delete method with a predefined pattern? It looks too complicated to just remove some record references manually.

I am not 100% sure I fully understand the question, but if `cascade = true` is working, you shouldn't need to use the version with `pattern` anymore, right? Please don't hesitate to elaborate if I missed the question.

**Comment by ihermandev** [comment]
> Thanks a lot for reporting this! For `cascade = true`, a fix is pending [here](https://github.com/apollographql/apollo-kotlin/pull/4938).
> 
> > Another question is have I can remove ApolloCacheReference{Document:191e771f-4c2e-4a2d-8732} reference from user.workPermit key in case of using the second delete method with a predefined pattern? It looks too complicated to just remove some record references manually.
> 
> I am not 100% sure I fully understand the question, but if `cascade = true` is working, you shouldn't need to use the version with `pattern` anymore, right? Please don't hesitate to elaborate if I missed the question.

Yes, you are right, I don't need the version with `pattern` remove in case of proper `cascade = true` functionality, sorry I didn't clarify the question well. 
My intention was to somehow replace desired functionality of `cascade = true `, for that I tried to use `pattern` remove and clear the corresponding ApolloCacheReference manually, but it seems too complicated to achieve with `apolloClient.apolloStore.accessCache`

**Comment by ihermandev** [comment]
Do you know ETA for the fix for Apollo V3 client?

**Comment by martinbonnin** [comment]
The fix is available in 3.8.2
