### ISSUE TITLE
cannot find symbol in adapter class

### ISSUE THREAD

**Issue by namdroid** [apollographql/apollo-kotlin#4937]
I have multi module app. It was so complicated to configure apollo3 running in my project. Pls make it easer for multi module project !

Now are the query classes generated, but i get this error:

/app/build/tmp/kapt3/stubs/sLiveDebug/adapter/MyClassQuery_VariablesAdapter.java:6: error: cannot find symbol
public final class TopNavigationQuery_VariablesAdapter implements com.apollographql.apollo3.api.Adapter<MyClassQuery> {
                                                                                                        ^
  symbol: class MyClassQuery

Why in this folder in tmp/kapt3/stubs/ ?
How do i fix this ? thanks

Here my config:

    apollo {
        service("service") {
            //packageNamesFromFilePaths()
            packageName.set("")
            srcDir("src/main/graphql")
            generateApolloMetadata.set(true)
}

**Comment by BoD** [comment]
Hi!

Not exactly sure what the issue with kapt is, but do you have the kapt plugin applied in your Apollo module(s)? You could try to remove it, or isolate Apollo in independent modules that don't use kapt.

More generally, would you be able to share a minimal project that reproduces the issue?

**Comment by namdroid** [comment]
@BoD How can i isolate Apollo that don't us kapt ?

**Comment by BoD** [comment]
It's difficult to say without knowing the structure of your project, but I meant something like this:

- `app`: Android module, depends on `api` module, uses kapt (if needed)
- `api`: not an Android module, depends on Apollo lib, defines GraphQL schema and operations, doesn't use kapt

**Comment by namdroid** [comment]
I can't post the app structure, its big

I see only package adapter in header ,maybe kapt do not find imports in header.

`package adapter;

@kotlin.Metadata
public final class MyClassQuery_VariablesAdapter implements com.apollographql.apollo3.api.Adapter<MyClassQuery> {
    @org.jetbrains.annotations.NotNull()
    public static final adapter.MyClassQuery_VariablesAdapter INSTANCE = null;`

**Comment by martinbonnin** [comment]
Hi @namdroid were you able to find a solution to this problem?

**Comment by martinbonnin** [comment]
I'm assuming you found a solution. If not, please leave a comment and I'll reopen this issue.

**Comment by jacobras** [comment]
I ran into this same issue, I think. For me it was caused by the empty package name (like I see here). Fixed by setting one. (From your comment in https://github.com/apollographql/apollo-kotlin/issues/3292#issuecomment-894377860)
