### ISSUE TITLE
[IJ/AS plugin] Show errors when mixing .graphql / .graphqls file contents

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#4977]
### Use case

With Apollo Kotlin, `.graphqls` files are for schema, whereas `.graphql` are for executables.

### Describe the solution you'd like

Therefore to help users as early as possible it would be nice if the plugin displayed errors whenever type definitions are found in .graphqls files and vice versa.

**Comment by martinbonnin** [comment]
Done ✅
