### ISSUE TITLE
Allow changing name of generated types

### ISSUE THREAD

**Issue by darvelo** [apollographql/apollo-kotlin#4991]
### Use case

When using Apollo-Kotlin in my iOS project, a GraphQL type called `Task` that is generated, compiled to Objective-C, and imported into iOS is conflicting with the native iOS class `Task` for running asynchronous code.

### Describe the solution you'd like

Generally I think it would be useful to allow a prefix and/or suffix to generated Apollo types (e.g. `TaskApolloDTO` in this case). For example I have the generated Apollo models, client-side Sqlite models, and corresponding domain models, and it's tricky not to get the models names to clash when they're basically 1:1 representations of each other, just for different domains (HTTP, client DB, app code).

**Comment by darvelo** [comment]
I'm trying to use the CompilerHook you mentioned but it seems some Poet method aren't available, in particular `fileSpec.toBuilder()` and `member.toBuilder()`:

<img width="862" alt="Screenshot 2023-05-26 at 12 20 41 AM" src="https://github.com/apollographql/apollo-kotlin/assets/523169/3b00f9c2-7439-439d-850b-94ed25fe8b69">

**Comment by martinbonnin** [comment]
You'll need the "external"/"non-fat" Gradle plugin to not relocate KotlinPoet:

```
plugins {
  // Note: using the external plugin here to be able to reference KotlinPoet classes
  id("com.apollographql.apollo3.external")
}
```

**Comment by darvelo** [comment]
Not sure what I'm doing wrong. I have this in my project `build.gradle.kts`:

<img width="928" alt="Screenshot 2023-05-26 at 12 37 59 AM" src="https://github.com/apollographql/apollo-kotlin/assets/523169/5ca69c8c-4001-460c-97cf-09bc07b531a4">

And this in my shared multiplatform library `build.gradle.kts`:

<img width="434" alt="Screenshot 2023-05-26 at 12 38 16 AM" src="https://github.com/apollographql/apollo-kotlin/assets/523169/166e9691-d6be-4f36-8157-fe4a188c217f">

where in my `libs.versions.toml`, `apollo = "3.8.1"` and:

<img width="998" alt="Screenshot 2023-05-26 at 12 39 21 AM" src="https://github.com/apollographql/apollo-kotlin/assets/523169/b6cdd3f1-b6d4-451f-9d16-ac7a2e7ecba7">

But still `toBuilder()` is not imported.

**Comment by darvelo** [comment]
Oh, got it. I can't use `id("com.apollographql.apollo3")` at the same time. It's one or the other. :)

**Comment by darvelo** [comment]
OK, I believe I fixed it with this small change (below the commented original code), which seems to leave all classnames that are defined within a root class untouched:

<img width="738" alt="Screenshot 2023-05-26 at 2 32 25 AM" src="https://github.com/apollographql/apollo-kotlin/assets/523169/3c393f05-8760-4f8c-b29d-6ece795c8b82">


@martinbonnin Thank you for your swift reply, as always! It's always appreciated and super helpful 🙏🏽  Closing this issue for now unless something else comes up.

**Comment by martinbonnin** [comment]
> Seems like the only thing that's not working is renaming the Data type on queries and mutations

If I remember correctly `Data` classes are nested and referenced across multiple files making them harder to rename. Since they are nested, I would expect that they don't name clash with other symbols because the operation name would disambiguate that. But maybe there's something in Objective-C that creates a nameclash?
