### ISSUE TITLE
Un-minimized query in comment has parse errors

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-kotlin#5000]
### Version

3.8.2

### Summary

In generated query class, there's a very helpful comment with un-minimized query used by Apollo. However, it seems to be generated with superfluous escape characters, which unfortunately trigger parse errors when sending such query:

![image](https://github.com/apollographql/apollo-kotlin/assets/3951580/6e52fd14-c808-46ee-917b-43aef8270b4c)

### Steps to reproduce the behavior

The image is generated from the following part of a query:

```
query InitialJobs(
  $sortTarget: String
  $skills: [String!]
  $keywords: [String!]
```

it also happens for hardcoded array arguments

**Comment by BoD** [comment]
Thanks for filing! As you noticed, it looks like this is a [workaround](https://github.com/apollographql/apollo-kotlin/blob/a877fb6452e07c51147903df0ff954d6e272e8bc/libraries/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/kotlin/file/OperationBuilder.kt#L193) for https://youtrack.jetbrains.com/issue/KT-43906
