### ISSUE TITLE
Getting error "Schema(s) found: [...] But none of them contain type definitions."

### ISSUE THREAD

**Issue by aknghiem** [apollographql/apollo-kotlin#5009]
### Question

Hi.
I'm just trying to setup a very simple HelloWorld project.
I'm following the **Getting started** steps on your [README](https://github.com/apollographql/apollo-kotlin/blob/main/README.md), but I am getting the following error when running `./gradlew clean build`:
```
> Schema(s) found:
  /path/to/src/main/graphql/Schema.graphqls
  But none of them contain type definitions.
```

My `Schema.graphqls` is as follows:
```
type Book {
  title: String
}
```

Have I missed something here?

**Comment by BoD** [comment]
Hi!

This would happen if your schema doesn't specify a `Query` type - see for instance [this doc](https://www.apollographql.com/docs/apollo-server/schema/schema/#the-query-type).

**Comment by aknghiem** [comment]
Great. Thank you very much.

Changed to the following and it now works:
```
type Query {
  books: [Book]
  authors: [Author]
}

type Book {
  title: String
  author: Author
}

type Author {
  name: String
  books: [Book]
}
```
