### ISSUE TITLE
upgrade from Apollo 2.X.X to Apollo 3.X.X for java

### ISSUE THREAD

**Issue by miriro100** [apollographql/apollo-kotlin#5023]
### Question

related to the comment: "Apollo Kotlin 3 is focused at Kotlin and the changes to make it easier to consume in Kotlin had some unfortunate side effects for Java consumers." in #4283 , I want to know if now it is recommended to upgrade from Apollo 2.X.X to Apollo 3.X.X for java. 
if so, which version of: com.apollographql.apollo3:apollo-runtime dependency? apollo-client-maven-plugin?

**Comment by BoD** [comment]
Hi!

At the moment, Apollo Kotlin 3 is usable from Java by using RxJava adapters (more info [here](https://www.apollographql.com/docs/kotlin/advanced/java)). If you are not already using, or are not familiar with Rx, this may be a bit challenging. But it is considered stable in the library. 

Meanwhile, Apollo Kotlin 4 will contain a dedicated Java runtime which is optimized to be used from Java. From the consumer's point of view, it is similar to the Apollo Android v2 API. The first alpha of Apollo Kotlin 4 which contains this Java runtime was [released](https://github.com/apollographql/apollo-kotlin/releases/tag/v4.0.0-alpha.1) last month, so you can already try it out. However it is not yet documented (other than having a look at [tests](https://github.com/apollographql/apollo-kotlin/tree/main/tests/java-client/src/test/java/test)), and is considered experimental. We would love your feedback!

Ultimately the decision depends on factors specific to your project, like knowledge of Rx, ability to try out / use non-stable libraries, etc.

For a bit of context, can I also ask a bit more about your project? Are you on the server side?

**Comment by BoD** [comment]
You can have a look at the Java runtime in the beta of v4. Closing for now, don't hesitate to open other issues if needed.
