### ISSUE TITLE
🙏  Help Needed · Apollo not generating code for the commonMain target in a Kotlin/Native project

### ISSUE THREAD

**Issue by milosmns** [apollographql/apollo-kotlin#5032]
### A quick intro

I have to preface my question with a huge _"I'm a first-time Apollo user"_, so that you know what you're dealing with here. 🙂 

My project is a collector of git statistics with an insights engine for that git data. All of the data is pulled from GitHub via their API. It's stuff similar to what you'd see in the [Contributors](https://github.com/apollographql/apollo-kotlin/graphs/contributors) page, only executed locally and crunched differently for my own needs.

There is already a working script that's doing exactly what I want to accomplish, so I know it's possible. However, that script was hacked together in Python – and now I'd like to rewrite it to Kotlin, make it run natively on each platform, and be able to publish it somewhere. I am trying to make it work with Kotlin/Native.

### Where am I right now?

I have a Kotlin/Native project, currently targeting only Mac machines. I'll be able to open-source it soon, but for now I just want to share the information I have (as it might be enough to understand what's going on).

Minimal `build.gradle.kts`:

```kotlin

plugins {
  kotlin("multiplatform") version "1.8.+"
  id("com.apollographql.apollo3") version "4.+"
}

group = xyz.marinkovic.milos
version = 0.1.0

repositories {
  mavenCentral()
}

kotlin {
  System.getProperty("os.name").let { hostOs ->
    if (hostOs != "Mac OS X") {
      throw GradleException("Host OS is not supported in Kotlin/Native.")
    }
  }

  mutableListOf<KotlinNativeTargetWithHostTests>().apply {
    add(macosArm64())
    add(macosX64())
  }.forEach {
    it.binaries {
      executable(Output.artifact) {
        entryPoint = "main"
      }
    }
    it.binaries.all {
      binaryOptions["memoryModel"] = "experimental"
    }
  }

  sourceSets {
    val commonMain by getting {
      dependencies {
        implementation("com.apollographql.apollo3:apollo-api:4.+")
        implementation("com.apollographql.apollo3:apollo-runtime:4.+")
      }
    }
    val macosArm64Main by getting {
      dependsOn(commonMain)
    }
    val macosX64Main by getting {
      dependsOn(commonMain)
    }
  }
} // end of kotlin

apollo {
  service("commonMain") { // <- I suspect that this is wrong
    generateKotlinModels.set(true)
    packageName.set("com.github.graphql")
    schemaFiles.setFrom(fileTree("src/commonMain/resources/github") {
      include("schema.graphqls")
    })
  }
}
```

### Important to note

At the moment, I only use the `commonMain` source set. No other directories targeting specific operating systems are created.

I can run the program normally and output Hello World. It can also authenticate with GitHub and fetch data over the REST API using Ktor.

The GraphQL schema I keep in `src/commonMain/resources/github/schema.graphqls` is downloaded from [this page](https://docs.github.com/en/graphql/overview/public-schema) (at the very top). It's the public API schema shared officially by GitHub. If I introspect that API using Apollo, I get the same schema like the one they shared. In fact, I also tried replacing the official one with the introspected version, but I got the same results.

### The Problem

Whether I launch a new Gradle sync from IntelliJ IDEA, or manually execute the `generateApolloSources` Gradle command, the result is the same: 

##### My project generates only 6 small files from that enormous schema

This is what I get:

![image](https://github.com/apollographql/apollo-kotlin/assets/1771914/4f5ba5da-13d5-425c-9ce0-3a4c9fbe6314)

Note that it also looks like `build/generated/source/apollo/commonMain` is a "sources root" for some reason. I guess IDEA somehow reads that from Gradle… but not sure if this is normal or not.

I tried redirecting Apollo's output to another directory, cleaning the output directory, changing schema names and extensions to other variants – without any luck.

I can also see that Apollo configuration creates a new Gradle task called `generateCommonMainApolloSources`, which makes me think that my configuration is correct. I am probably mistaken about this.

-----

So I guess my question is… am I doing something wrong? Is what I'm trying to do even supported?

And thanks a bunch for looking into this with me! 🙏

**Comment by martinbonnin** [comment]
Hi again 👋 🐧 

I think what you're bumping into is that Apollo generates models based on queries, not the schema. If we were to generate models based on the schema, all the fields would have to be nullable (because there's no way to know whether you queried them or not). And that would defeat a lot of the typesafety of having a schema in the first place. This is something we ruled out very early in Apollo.

So the tldr; is that you should either change frameworks if you want something that's more generic and less typesafe of start writing your .graphql queries and generate code from them. By default, queries are read from `src/commonMain/graphql`. If you put your `.graphql` files there, you should see more generated files.

**Comment by martinbonnin** [comment]
You'll need to rename your schema from `schema.graphql` to `schema.graphqls`. In the current form, Apollo is trying to parse your schema as operations (and failing)

**Comment by milosmns** [comment]
You are correct, I didn't realize that these file extensions make a difference. Thanks a bunch. The request code is now generated accordingly!

In hindsight, it would have been helpful to see this in the docs (although I might have simply missed it)… either way, I'm closing this with my problem resolved.
