### ISSUE TITLE
[IJ plugin] "Go to declaration" doesn't offer graphql target when used on an import alias

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-kotlin#5033]
### Version

4.0.0-alpha1

### Summary

Pretty much the title, if I press `cmd + b` on a generated query class, I'm offered to open either the implementation or the graphql definition. However, if I do the same on an alias for the same query class, I instantly go to the implementation

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment]
Thanks for reporting! Reproducing it on my side.

**Comment by BoD** [comment]
Resolved in 4.0.0-alpha.2
