### ISSUE TITLE
Enabling test builders causing some tasks to run in incremental run when they should be UP-TO-DATE

### ISSUE THREAD

**Issue by mchauhan3-wooliesx** [apollographql/apollo-kotlin#5065]
### Version

3.8.2

### Summary

We are seeing a incremental build issue with tasks like `lintDebug` & `test` when the test builders are enabled.
So if we run a task `lintDebug` for a module which has test builders enabled, in its incremental run it also causes 
`lintAnalyzeDebug` and `lintReportDebug` tasks execution which ideally should be UP-TO-DATE. However, the subsequent incremental runs fine and these tasks are UP-TO-DATE.

<img width="1524" alt="Screenshot 2023-07-06 at 3 56 27 pm" src="https://github.com/apollographql/apollo-kotlin/assets/119823320/4efdbfcc-0a8a-4200-a240-26ecff500d1b">

Same behavior is observed for `./gradlew test` where it executed `compileDebugUnitTestKotlin` and `generateDebugUnitTestStubRFile` in its incremental run.

### Steps to reproduce the behavior

1. In your andorid library module, enable the test builders in `build.gradle.kts`
```
apollo {
    service("test") {
        packageNamesFromFilePaths()
        generateTestBuilders.set(true)
    }
}
```
2. Run `./gradlew clean lintDebug`
3. Then run `./gradlew lintDebug`
4. Observe logs for task execution and you will see `lintAnalyzeDebug`and `lintReportDebug` task executed.
5. Run `./gradlew lintDebug` again.
6. Observe logs for task execution and you will see `lintAnalyzeDebug`and `lintReportDebug` task are UP-TO-DATE.

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Hi 👋 

Thanks for sending this. I can't reproduce on the tutorial unfortunately ([branch](https://github.com/apollographql/apollo-kotlin-tutorial/compare/up-to-date)). Does it specifically need to be a library module?

I think the same behaviour should show with just `compileDebugUnitTestKotlin`? Then we can reduce the test to:

```
./gradlew clean compileDebugUnitTestKotlin
./gradlew compileDebugUnitTestKotlin -i
```

Can you see with `-i` the reason why the second invocation was not up-to-date?

Also, if you're comfortable with it, feel free to send me the build input comparisons at martin@apollographql.com

**Comment by mchauhan3-wooliesx** [comment]
Hi @martinbonnin thank you for looking into this. I tried the tutorial branch which you used and I can't reproduce on that. Let me see if I can try on a new sample repo.

**Comment by martinbonnin** [comment]
That'd be awesome, thanks a lot!

**Comment by mchauhan3-wooliesx** [comment]
In the meantime, I tried to run the `lintDebug` task with -i and that's the reason I am seeing:
```
Task ':<moduleName>:lintAnalyzeDebug' is not up-to-date because:
  Input property 'variantInputs.testArtifact' has been added for task ':<moduleName>:lintAnalyzeDebug'
  Input property 'variantInputs.testArtifact.artifactCollectionsInputs' has been added for task ':<moduleName>:lintAnalyzeDebug'
  Input property 'variantInputs.testArtifact.artifactCollectionsInputs.compileClasspath' has been added for task ':<moduleName>:lintAnalyzeDebug'
  ```

and exactly similar message for `lintReportDebug` task

**Comment by ychescale9** [comment]
We've done a bit more investigation and there's actually no issue with test.

Re . the `lintAnalyzeDebug` issue, it seems to only happen when:
- `generateTestBuilders` is enabled
- we use the variant API to disable unit test with the following snippet:

```kt
androidComponents {
    beforeVariants {
        it.enableUnitTest = extensions.findByType<org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension>()
            ?.sourceSets?.getByName("test")?.kotlin?.files?.isNotEmpty() == true
    }
}
```

I remember Xavier saying we shouldn't be looking at the source folder to decide whether to enable unit test (presumably because `enableUnitTest` is not a provider), but didn't expect things to break in this subtle way 😅 

When a module has tests, there's no issue at all.

So I think it's not a big deal for us right now as we should never need to enable test builder when we don't have any tests.  But I'm keen to understand exactly what's going on if you have insight 😃

**Comment by martinbonnin** [comment]
Thanks for the thorough investigation!

I think what's happening is that `sourceSets?.getByName("test")?.kotlin?.files` contains the Apollo Generated test builders but does not add a dependency on `generateApolloSources`. So your task graph now becomes stateful:

* first build, no `${Foo}_TestBuilder.kt` file is generated => `enableUnitTest` is `false`
* second build, `${Foo}_TestBuilder.kt` are present so `isNotEmpty()` is now `true` and in turns this marks other tasks not up-to-date

If you want to check for unit tests you wrote explicitely, I would just check `src/test` :

Something like so:
```kotlin
androidComponents {
    beforeVariants {
        it.enableUnitTest = file("src/test").exists() && file("src/test").listFiles()?.isNotEmpty() == true
    }
}```

**Comment by ychescale9** [comment]
Thanks @martinbonnin ! I totally missed that sourceset also contains generated code 🤦‍♂️ . Your explanation makes perfect sense, and thanks for the better snippet 😊
