### ISSUE TITLE
How to import ConnectionRecordMerger

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5074]
### Question

I'm currently trying to implement pagination and would like to realize cache merging. I've been implementing this based on the file below, but I can't find ConnectionRecordMerger.

https://github.com/apollographql/apollo-kotlin/blob/main/tests/pagination/src/commonTest/kotlin/CursorBasedPaginationTest.kt#L54

<img width="530" alt="スクリーンショット 2023-07-09 1 13 00" src="https://github.com/apollographql/apollo-kotlin/assets/1586910/58d6ceb3-8835-439c-b371-3ed258ae3e61">

Can't I import ApolloExperimental?

memo:
https://github.com/apollographql/apollo-kotlin/blob/7690bf5c06b6469228f899380c6fc9f7a3ee910f/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/RecordMerger.kt
https://github.com/apollographql/apollo-kotlin/blob/main/tests/pagination/src/commonTest/kotlin/CursorBasedPaginationTest.kt#L54
https://github.com/apollographql/apollo-kotlin/releases/tag/v3.4.0

**Comment by martinbonnin** [comment]
You probably need to import `apollo-normalized-cache-incubating` instead of `apollo-normalized-cache`

**Comment by sonatard** [comment]
Thanks!!

I solved it.

```gradle
    implementation "com.apollographql.apollo3:apollo-normalized-cache-incubating:$gradle.ext.apollo3"
    implementation "com.apollographql.apollo3:apollo-normalized-cache-sqlite-incubating:$gradle.ext.apollo3"
    // implementation "com.apollographql.apollo3:apollo-normalized-cache:$gradle.ext.apollo3"
    // implementation "com.apollographql.apollo3:apollo-normalized-cache-sqlite:$gradle.ext.apollo3"
```

**Comment by martinbonnin** [comment]
Heads up this is (as the name implies) pretty much incubating. I'm pretty sure the performance isn't great and I wouldn't use that in production (contrary to alphas 😄 ). It's mostly a test bed to gather feedback and iterate on API design. If you have any feedbacks abuot the ergonomics, please let us know!

**Comment by sonatard** [comment]
OK. I plan to only use 'incubating' for testing, not in a production environment. Currently, our pagination code is not clean, but  it's working, so there's no problem. First, I'll test it, and then I plan to refactor it again after the official release.

In our pagination code, we hold the values to paginate as a list in the Jetpack Compose state. However, we want to replace the state with a cache.
