### ISSUE TITLE
 data does not return and remains as a CacheMissException.

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5076]
### Version

v4 alpha2

### Summary

 data does not return and remains as a CacheMissException.

### Steps to reproduce the behavior

 I don't understand the specific conditions under which this occurs.

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Hi @sonatard 👋 We are going to need a bit more details. Is it something you saw specifically in the 4.0 alphas? Can you share you code ?

**Comment by sonatard** [comment]
I switched back to Apollo3 and investigated again, but the result did not change. After a more detailed investigation, I found that it was due to my implementation mistake. I apologize for hastily creating an issue.

**Comment by martinbonnin** [comment]
👍 thanks for the update

**Comment by sonatard** [comment]
This issue may indeed exist.

We had two problems. One was our implementation, which we have resolved. The next is likely a problem with Apollo v4. The issue was resolved when we reverted the almost identical code from Apollo v4 to v3. However, we don't have certainty, and we haven't had time for a detailed investigation.

Once we investigate again and understand the details, we would like to reopen this issue.

**Comment by martinbonnin** [comment]
Actually I'm not sure you can reopen this issue. Can you create a new one once you get the details? It'll be easier.

**Comment by oreillyjf** [comment]
Was there new issue opened for this?  Thinking we might be seeing something similar.

**Comment by martinbonnin** [comment]
@oreillyjf I don't think an issue was created, feel free to open one!
