### ISSUE TITLE
AS/Intellij Plugin - Allow Custom URLs for field latencies

### ISSUE THREAD

**Issue by agrosner** [apollographql/apollo-kotlin#5084]
### Use case

At my current company, we do not expose API keys to individual developers. Instead we wrap them up with special access privileges behind our VPN network. We'd like to use the [fetch field latencies](https://github.com/apollographql/apollo-kotlin/pull/5048) feature, but cannot due to it requiring all devs to use an API key. 

**Nice To Have**: A way to configure this in the apollo gradle plugin, then every dev at our company could benefit.

### Describe the solution you'd like

Allow us to specify a custom URL that returns the same data that the plugin expects so we can make use of it.

**Comment by BoD** [comment]
Hey @agrosner. Wondering if you can give us a bit more info about what is needed to make this work?

We could add a setting to set a custom url, that will be used instead of the default GraphOS one. But should the auth header still be sent? If it's sent, will it be overridden by your VPN layer?

**Comment by BoD** [comment]
I am going to close this one for now, please feel free to re-open if this is still relevant.
