### ISSUE TITLE
:app:generateStorefrontApolloSources Variables used in the query are warned as unused.

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5112]
### Version

3.8.2

### Summary

Variables used in the query are warned as unused.

### Steps to reproduce the behavior

The 'country' variable is used in the directive, but it is warned as an unused variable.

```
query Collection($id: ID!, $country: CountryCode) @inContext(country: $country) {
    collection(id: $id) {
        id
        title
        products(first: 100) {
            nodes {
                id
            }
        }
    }
}
```

### Logs

```
> Task :app:generateStorefrontApolloSources
w: collection.graphql: (1, 73): Apollo: Variable `country` is unused
```

**Comment by martinbonnin** [comment]
Many thanks for the reproducer query 🙏 . A fix is included [there](https://github.com/apollographql/apollo-kotlin/pull/5113).
