### ISSUE TITLE
Mutation doesn't notify watch queries

### ISSUE THREAD

**Issue by omidfaraji** [apollographql/apollo-kotlin#5129]
**Situation**

I have the following operations

```graphql
query Group($id: Id!) {
    groups(ids: [$id]) {
        id
        response {
            devices {
                ...device
            }
        }
    }
}


mutation RemoveDevice(
    $id: Id!
) {
    removeDevice(
        input: { deviceId: $id, }
    ){
        removedDeviceId
    }
}
```

Also, I have the following watch query and mutation function:

```kotlin
fun groupFlow(groupId: String): Flow<DeviceGroup> = apolloClient
       .query(GroupQuery(id = groupId))
       .fetchPolicy(FetchPolicy.CacheOnly)
       .watch()
       .map { it.dataAssertNoErrors.toModel() }
```

```kotlin
suspend fun removeDevice(deviceId: String) {
    apolloClient
        .mutation(
            RemoveDeviceMutation(
                id = deviceId
            )
        )
        .execute()
        .dataOrThrow()
}
```

When I call the removeDevice function, the watch query doesn't get notified.

WatcherInterceptor class:
<img width="1458" alt="Screenshot 2023-07-26 at 12 18 41" src="https://github.com/apollographql/apollo-kotlin/assets/7803544/2e4bb94f-bc8c-4975-be06-51f943aca76f">

The only clue I have is that inside the WatcherInterceptor the remove request doesn't contain a WatcherContext (line 22 of WatcherInterceptor) which causes the rest of the code in the WatcherInterceptor to not be run, and it proceeds to the next interceptor in the chain. 
`    val watchContext = request.watchContext ?: return chain.proceed(request)
`

Thus, the watchedKeys(line 31) doesn't get updated, which means once the remove request finishes and the cache gets updated, and changedKeys is published through "apolloStore.changedKeys" and the WatcherInterceptor gets notified(line 35), the changedKeys will not exist in the watchedKeys and this means that none of the watcher queries get notified.

The changedKeys contains the following values:
```
[
 "removeDevice({"input":{"removedDeviceId":"id:device:abcdefghijklmnopqrstuvwxyz"}}).deviceId",
 "QUERY_ROOT.removeDevice({"input":{"removedDeviceId":"id:device:abcdefghijklmnopqrstuvwxyz"}})"
]
```

**Question**
Having said the above things, what can be the actual reason that the watch queries don't get updated after a mutation in this case?
How should I fix it?
Can it be a bug?

**Comment by martinbonnin** [comment]
Thanks for the detailed issue ❤️ 

This is one of the limitation with normalized cache that the mutation has to return the modified data for the cache updates to work automatically. Else there's no way to map from the mutation result to the query.

In this specific case, it means you would need something like this:

```graphql
query Group($id: Id!) {
    groups(ids: [$id]) {
        id
        response {
            # note you need response to have an id
            id
            devices {
                ...device
            }
        }
    }
}
```

```
mutation RemoveDevice(
    $id: Id!
) {
    removeDevice(
        input: { deviceId: $id, }
    ){
        id 
        # query back the modified list
        devices {
           ...device
        }
    }
}
```

All that being said, if you don't own the backend, the easiest way is certainly to modify your cache manually. Something along the lines of the code below (disclaimer: I have not tested it at all so don't take this as gospel):

```kotlin
suspend fun removeDevice(deviceId: String) {
    val removedId = apolloClient
        .mutation(
            RemoveDeviceMutation(
                id = deviceId
            )
        )
        .execute()
        .dataOrThrow()
        .removeDevice
        .removedDeviceId

    val existingData = apolloClient.apolloStore.readOperation(GroupQuery(id = groupId))
    val newData = existingData.copy(
        groups = existingData.groups.map {
            it.copy(
                 response = it.response.copy(
                     devices = it.response.devices.filter { it.id != removedId }
                 )
            )
        }
    )

    
    apolloClient.apolloStore.writeOperation(GroupQuery(id = groupId), newData)
}
```

I know it's a lot of cumbersome code but I haven't found a better way so far when the backend doesn't support this.

**Comment by omidfaraji** [comment]
Thanks for the quick reply. Now I understand what the problem is.

I decided to modify the cache manually using readOperation/writeOperation, as you said but using writeOptimisticUpdates. The only issue now is that when I try to remove two devices in a row and a bit fast (I remove the second one ~1000 ms after the first one), readOperation fails for the second call, and I get an Exception.

This is the stack trace of the exception:
```
com.apollographql.apollo3.exception.CacheMissException: Object 'Devices:id:device:abcdefghijklmnopqrstuvwxyz' not found
at com.apollographql.apollo3.cache.normalized.api.internal.CacheBatchReader.toMap(CacheBatchReader.kt:104)
at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.readInternal(OperationCacheExtensions.kt:76)
at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.readDataFromCache(OperationCacheExtensions.kt:39)
at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$readOperation$2.invoke(DefaultApolloStore.kt:103)
at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$readOperation$2.invoke(DefaultApolloStore.kt:102)
at com.apollographql.apollo3.cache.normalized.internal.Lock.read(Lock.kt:12)
at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.readOperation(DefaultApolloStore.kt:102)
at com.apollographql.apollo3.cache.normalized.ApolloStore$DefaultImpls.readOperation$default(ApolloStore.kt:40)
at com.myapp.devicemanager.data.ConnectRepository.remove(ConnectRepository.kt:179)
```


And this is my new function:

```
suspend fun remove(deviceId: String, groupId: String) {
    Log.i("ConnectService", "removeDevice: folderArn=$groupId")
    val existingData = apolloClient.apolloStore.readOperation(
        operation = GroupQuery(id = groupId)
    )
    val uuid = Uuid.randomUUID()
    apolloClient.apolloStore.writeOptimisticUpdates(
        mutationId = uuid,
        operation = GroupQuery(arn = groupId),
        operationData = existingData.copy(
            groups = existingData.groups.map {
                it.copy(
                    response = it.response.copy(
                        devices = it.response.devices.filter { it.id != deviceId }
                    )
                )
            }
        )
    )
    try {
        apolloClient
            .mutation(
                RemoveDeviceMutation(
                    id = deviceId
                )
            )
            .execute()
            .dataAssertNoErrors
            .also {
                apolloClient.apolloStore.remove(
                    cacheKey = CacheKey(CACHE_TYPE_AXIS_CAMERA, deviceId),
                    cascade = true
                )
            }
    } finally {
        apolloClient.apolloStore.rollbackOptimisticUpdates(mutationId = uuid)
    }
}
```

I hope you can help me with this as well.

**Comment by martinbonnin** [comment]
Apologies for the delayed response. 

Can you try without optimistic updates first? 

Optimistic updates are linked to a mutation. They add journal entries based on the mutationId so doing things like `rollbackOptimisticUpdates(mutationId = uuid)` will be basically a no-op unless you pass a `mutationId`. Doing it without optimistic updates will help diagnosing the issue and then we can look at adding them again (probably you don't need the `writeOptimisticUpdates` API since you're doing everything manually but we can look into that later.

**Comment by martinbonnin** [comment]
@omidfaraji I'll close this one for now. Let me know if you want to resume this discussion and I'll happily reopen
