### ISSUE TITLE
Increase the maximum JSON nesting level, or make it customisable

### ISSUE THREAD

**Issue by Emplexx** [apollographql/apollo-kotlin#5159]
### Use case

I am querying a page of nested comments from a certain API, and getting an exception: `JsonDataException - Nesting too deep at [data, Page, threadComments, 0, childComments, 0, childComments, 0, childComments, 0, childComments, 0 ...`. Looking at past issues (#3308), I can see that the limited used to be 32 and was increased to 256. And the JSON response I am getting indeed has very deep nesting, however, it is a valid response and I want it to be parsed

### Describe the solution you'd like

I propose to either increase the nesting level limit further, or to make it possible to customize/change the limit (eg in the `ApolloClient.Builder`) so that it can be increased in cases like mine

**Comment by martinbonnin** [comment]
For the record, matching [Moshi discussion](https://github.com/square/moshi/pull/329). Most of the Json reading code of Apollo Kotlin originates from moshi so I'm a bit surprised this hasn't happened there.

Can you share your GraphQL query? 256 levels of nesting sounds like something that's very tedious to write. Or is it an automatically generated query?

**Comment by Emplexx** [comment]
It's not automatically generated, but rather recursive (I'm not sure what would it be called in GraphQL terminology)
Here is the query: 
```
query ($threadId: Int) {
    Page {
        threadComments(threadId: $threadId) { <- Array of ThreadComment
            id
            comment
            // Other fields omitted
            childComments // <- Another array of ThreadComment, each comment will also have the same fields specified above
        }
    }
}
```
So this means that if there's a chain of more than 256 comments, the JsonDataException will be thrown
[For reference, here is this same query with the specific comment chain that is causing this](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABMEQDp5lJFEAKAhgOYIAUADvg8%2BkQKwAMAShLlK1GkRQALPAnpgAwhDiJUAZxYUqEidNnyAkmB4A2fvwAsAdgA0o7TqJqIeFDwMARLeJrDS3x3sfCShlVRQgwKgpAEsAG0Uw5BQ1SIkAXzTM73SQdKA)

**Comment by martinbonnin** [comment]
GraphQL forces you to query sub-selection explicitely so I would have expected something like this:

```graphql
query ($threadId: Int) {
    Page {
        threadComments(threadId: $threadId) { <- Array of ThreadComment
            id
            comment
            // Other fields omitted
            childComments {
              childComments {
                childComments {
                  # ...
                          # ...
                                  # ...
                                          # ...
                                                  # 256 nesting levels later..
                                                  childComments {
                                                     id
                                                     text
                                                  }
                }
              }
            }
        }
    }
}
```

Can you check the type of the `childComments` field in your GraphQL schema? Could it be a custom scalar?

**Comment by martinbonnin** [comment]
> Can you check the type of the childComments field in your GraphQL schema? Could it be a custom scalar?

![Screenshot 2023-08-06 at 18 08 31](https://github.com/apollographql/apollo-kotlin/assets/3974977/f531e81c-9073-483a-af4a-a04f0cceef37)

Looks like it is, sorry I didn't see you added a link to the explorer (thanks a lot for providing that 👍 )

In that case I guess the only solution is to make the stack resize itself dynamically.

**Comment by Emplexx** [comment]
Yes, my bad, I made a mistake with the explanation above, `childComments` is actually a JSON field.

**Comment by martinbonnin** [comment]
Yep, realized that just a bit too late before hitting enter on my message 😄 . That's interesting. It's indeed the only practical way to get this. I was thinking along the lines of maybe providing an API on `JsonReader` that skips parsing so that custom scalar adapters can do the nesting they want but `JsonReader` probably needs to continue parsing anyways to resume operation after the custom scalar adapter is done. So probably dynamic resize is the way to go.

**Comment by martinbonnin** [comment]
@Emplexx is it possible to get the huge comment thread from the public API? Looks like the [query you linked](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABMEQDp5lJFEAKAhgOYIAUADvg8%2BkQKwAMAShLlK1GkRQALPAnpgAwhDiJUAZxYUqEidNnyAkmB4A2fvwAsAdgA0o7TqJqIeFDwMARLeJrDS3x3sfCShlVRQgwKgpAEsAG0Uw5BQ1SIkAXzTM73SQdKA) (`threadId = 60047`) is returning a relatively small result for me:

```json
{
  "data": {
    "Page": {
      "threadComments": [
        {
          "comment": "It is on apple music under VisualArt's / Key Sounds Label. Might be location specific.",
          "childComments": [
            {
              "comment": "I did find VisualArt's / Key Sounds Label on Apple Music along with the artist that made the OP, but I could not find any trace of Charlotte stuff, same thing when I used a VPN",
              "childComments": [
                {
                  "comment": "https://music.apple.com/us/album/tv%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-charlotte-op-ed-bravely-you-%E7%81%BC%E3%81%91%E8%90%BD%E3%81%A1%E3%81%AA%E3%81%84%E7%BF%BC-ep/1047176678",
                  "childComments": [
                    {
                      "comment": "Oh yea it's there, what a shame that it's displayed as unplayable on my phone and Windows 11 android subsystem and only as a purchasable album on web player.\n\nThanks still tho",
                      "childComments": null
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

I'd like to capture the case as a real life example that can happen if possible.

**Comment by Emplexx** [comment]
I'm so sorry I accidentally pasted the link from [this issue](https://github.com/apollographql/apollo-kotlin/issues/4460#issuecomment-1280635311) I opened last year (I was referencing how to copy a link to an operation)

The query I indended to link to is [**this**](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgraphql.anilist.co%2F&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABMEQDp5lJFEAKAhgOYIAUADvg8%2BkQKwAMAShLlK1GkRQALPAnpgAwhDiJUAZxYUqEidNnyAkmB4AmAMwAWfgBpR2nUTUQ8KHgYAiW8TWGkvDogBLMH8HKGVVFDtvCSgpQIAbRQjkFDVonQBfDKJsr0yQTKA) (nearly the same query but the threadId is 2340, that is the thread with a huge comment chain that exceeds the stack size and made me open this issue)

**Comment by martinbonnin** [comment]
That's an awesome test case, thank you for providing it.
