### ISSUE TITLE
Default enum types are not being recognized for certain schema formats

### ISSUE THREAD

**Issue by sforood** [apollographql/apollo-kotlin#5177]
### Version

v4.0.0-alpha.2

### Summary

Default enum types are not being recognized for multiple arg formats in our schema. One seems to be going through some validation that the other format is not. When I manually remove the escape chars in the breaking case, the issue goes away. Example below.

### Steps to reproduce the behavior

We have enum types populated in our schema (provided to us by our backend) in two ways. As far as I understand, these are both valid by Apollo's standards.

```
// Working case
{
  "name": "...",
  "description": "...",
  "args": [ 
   {
      "name": "sort",
      "description": null,
      "type": {
        "kind": "ENUM",
        "name": "NAME",
        "ofType": null
       },
      "defaultValue": "\"DEFAULTVALUE\""
    }
    ...
  ]
},
```
and 
```
// Non-working case
{ 
  "name": "...",
  "description": "...",
  "type": {
    "kind": "ENUM",
    "name": "Action",
    "ofType": null
  },
  "defaultValue": "\"SET\""
}
```
The non-working case fails with 
```
Execution failed for task ':graphql:generateRedditApolloSources'.
> e: null: (1, 1): Value `"SET"` cannot be used in position expecting `Action`
```

I believe this is failing because it's going through some kind of validation that the working case is not. Replacing  `defaultValue`'s `"\"SET\""` with `"SET"` works just fine.

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for reaching out!

 I _think_ this is an expected error. The GraphQL spec [says](https://spec.graphql.org/draft/):

```
defaultValue may return a String encoding (using the GraphQL language) of the default value used by this input value
in the condition a value is not provided at runtime. If this input value has no default value, returns null.
```

So `"\"SET\""` would be a [string value](https://spec.graphql.org/draft/#StringValue), not an [enum value](https://spec.graphql.org/draft/#EnumValue). 

That being said, the spec also [says](https://spec.graphql.org/draft/#sel-FAHfRDCAACCBomB):

```
GraphQL services must return one of the defined set of possible values. If a reasonable coercion is not possible they 
must raise a [field error](https://spec.graphql.org/draft/#field-error).
```

So it could be argued coercing from StringValue to EnumValue is _reasonable_ but I'd rather avoid servers relying on that behaviour too much if possible. 

May I ask what server you're using? Maybe a fix could be contributed there?

**Comment by carldunham** [comment]
It's an older version of Graphene. I'm sure there are other services in the wild that would exhibit this.

It makes sense based on what the spec says, but why the difference between arg defaults and input field defaults?

**Comment by martinbonnin** [comment]
> why the difference between arg defaults and input field defaults

Looks like a bug in Graphene if you ask me. [This GitHub issue](https://github.com/graphql-python/graphene/issues/940) looks similar.

graphql-js also [doesn't coerce StringValues to EnumValues](https://github.com/mjmahone/graphql-js/blob/8724e22f9e89224dd2669d6fc0c4b7fe34c2c8dd/src/type/definition.ts#L1344) so all in all, I'd say this works as intended. 

A short term solution is to edit your schema locally. You can convert to SDL using `./gradlew convertApolloSchema --from src/main/graphql/schema.json --to src/main/graphql/schema.graphqls` which makes editing easier. Longer term solution work with your backend team to fix this on the backend.

**Comment by carldunham** [comment]
> > why the difference between arg defaults and input field defaults

> Looks like a bug in Graphene if you ask me. 

Definitely a bug in Graphene, but was asking why don't we see the same issues in apollo-kotlin with args? Graphene generates the same incorrect format for enum defaults for both.

**Comment by sforood** [comment]
FYI changing to SDL has resolved the issue for the Android side
