### ISSUE TITLE
Add options to not generate data classes

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#5207]
### Description

Data classes have a runtime overhead in terms of bytecode size. Especially, `toString()`, `componentN()` and `copy()` are not always used. It would be nice to be able to skip them. 

There are compiler plugins to deal with this like [Poko](https://github.com/drewhamilton/Poko) and/or [DCG](https://github.com/facebookincubator/dataclassgenerate) but we could probably do this without a compiler plugin by generating the methods as needed.

Ideally this is configurable:

```kotlin
apollo {
  service("service") {
    // Generates equals/hashCode
    modelMethods.set(listOf("equalsHashCode"))
    // Also generates toString
    modelMethods.set(listOf("equalsHashCode", "toString"))
    // Only generates copy
    modelMethods.set(listOf("copy"))
    // Generates data classes
    modelMethods.set(listOf("data"))
  }
}
```

**Comment by BoD** [comment]
Available in [4.0.0-beta.1](https://github.com/apollographql/apollo-kotlin/releases/tag/v4.0.0-beta.1).
