### ISSUE TITLE
[IDE Plugin] Sandbox Button Does Not Carry Over Fragments from other Modules

### ISSUE THREAD

**Issue by agrosner** [apollographql/apollo-kotlin#5220]
### Version

4.0.0-alpha.4-SNAPSHOT.30

### Summary

Clicking on this button:
<img width="252" alt="Screenshot 2023-09-01 at 2 59 01 PM" src="https://github.com/apollographql/apollo-kotlin/assets/2117859/2f8b35d3-8a4b-488f-a4cb-f5282ebcd0c7">

Brings over the query, but not the fragments declared in other modules.

dependency like:
:query-module
 - :fragment-module

### Steps to reproduce the behavior

Create two graphql modules. One that has the fragment, and another with query that calls that fragment.

**Comment by BoD** [comment]
Thanks for reporting! 🙏  [A fix](https://github.com/apollographql/apollo-kotlin/pull/5236) has been merged, it will be visible in the next [weekly snapshot](https://github.com/apollographql/apollo-kotlin/tree/main/intellij-plugin#weekly-snapshots).
