### ISSUE TITLE
Implicit task dependency not working

### ISSUE THREAD

**Issue by dronda-t** [apollographql/apollo-kotlin#5221]
### Version

3.8.2

### Summary

My team has a library that among other things, stitches a bunch of separate schema files into one.

We then take this generated schema file and feed it into the apollo plugin via a Provider. Typically a provider will create a implicit dependency on the task. 

Depending on which task I run I get:
```
Execution failed for task ':generateTest-serviceApolloSources'.
> java.io.FileNotFoundException: /Users/me/repros/apollo-kotlin-implicit-dep/build/newSchema/test.graphql
```

and sometimes it will show:
```
A problem was found with the configuration of task
'generateTestApolloSources' (type
'ApolloGenerateSourcesTask').
    
    Reason: Task
':generateTestApolloSources' uses this
output of task ':internalTask'
without declaring an explicit or implicit dependency. This can lead to
incorrect results being produced, depending on what order the tasks are
executed.
 
    
    For more information, please refer to
https://docs.gradle.org/8.2/userguide/validation_problems.html#implicit_dependency
in the Gradle documentation.
```

I've excluded some text just to avoid leaking anything, but you probably get the idea.

I believe the apollo plugin should be able to handle providers properly so that we don't need to explicitly declare the dependency.

Currently we need to do (pseudo code)
```
generateTestApolloSources dependsOn internalTask
generateTestApolloSchema dependsOn internalTask
generateTestApolloUsedCoordinates dependsOn internalTask
```

Thank you for you time and please let me know what you think!

### Steps to reproduce the behavior

I created a repro to show how it works.

You can't do much without the apollo plugin immediately failing.

https://github.com/dronda-t/apollo-implicit-dep-repro

**Comment by martinbonnin** [comment]
Thanks for the detailed issue ❤️ . I can reproduce that behaviour. It's not easy to change because schemas can be configured from:

* schemaFile
* schemaFiles
* by default it looks in the source directories for a `.json|.graphqls|.sdl` file

Also it's used by the `downloadSchema` task as well as the IDE plugin model builder so it's a bit of a mess. But we'll get there! Thanks for the bug report!

**Comment by dronda-t** [comment]
Thanks @martinbonnin. I totally get it. It's a just a few extra lines for us to add right now, so it's not bad at all. It's just a minor annoyance. I appreciate you taking a look at this!
