### ISSUE TITLE
[IDE Plugin] Verify the name correspondence between Fragment and Component for Fragment Colocation

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5225]
### Use case

Using GraphQL, Fragment Colocation is very important, but many beginners make mistakes. A common thing is to use Fragment to make the Query DRY. However, this leads to using the same Fragment between different use cases (components), resulting in over fetching.

Therefore, I think it would be good to be able to check that Fragment and Component are correctly matched 1:1

```graphql
fragment ProductFragment on Product {
  id
  name
}
fragment ProductImageFragment on ProductImage {
  id
  url
}
```

```kotlin
// OK
fun Product(fragment: ProductFragment) {}

// NG
fun ProductImage(fragment: ProductFragment) {}

// OK
fun ProductImage(fragment: ProductImageFragment) {}
```

### Describe the solution you'd like

You can set a rule between the component name and the fragment name, and it will throw an error if there is a violation.

Fragment rule: `${Component}Fragment | ${Component}`

If you don't set a rule, this verification will not work.

If you don't want to merge this implementation into the Apollo Kotlin Plugin, I would like to implement a custom Lint rule myself. In that case, is there a way to implement custom Lint rules provided by the Apollo Kotlin Plugin?

**Comment by BoD** [comment]
Thanks for the suggestion! I think the rule is probably a bit too much tailored to your specific needs to be included in the Apollo plugin.

If you want to implement it, I don't think Lint can help, as it doesn't know anything about GraphQL. Your best guess is probably to implement a dedicated plugin that depends on the Kotlin and GraphQL plugins. This may look like a big task but actually bootstrapping a plugin can be quick with the help of [the template](https://github.com/JetBrains/intellij-platform-plugin-template) and you can look at the Apollo plugin for inspiration.

**Comment by BoD** [comment]
If that's OK I'm going to close this ticket for now. Please don't hesitate to open other tickets as needed.
