### ISSUE TITLE
[Multi-Modules] any sample for multi module  project ?

### ISSUE THREAD

**Issue by Abd-Elrahman-Essam** [apollographql/apollo-kotlin#5227]

**Comment by martinbonnin** [comment]
Good point. There's nothing like this but that would be quite useful indeed 👍 .

The closest you can find at the moment is integration tests, there are 3 multi-module projects there:

* [multi-module-1](https://github.com/apollographql/apollo-kotlin/tree/cedc6411338f5a9ebd24191c40191aa30683eabb/tests/multi-module-1)
* [multi-module-2](https://github.com/apollographql/apollo-kotlin/tree/cedc6411338f5a9ebd24191c40191aa30683eabb/tests/multi-module-2)
* [multi-module-3](https://github.com/apollographql/apollo-kotlin/tree/cedc6411338f5a9ebd24191c40191aa30683eabb/tests/multi-module-3)

**Comment by martinbonnin** [comment]
Hi all 👋 We started a collection of samples [here](https://github.com/apollographql/apollo-kotlin-samples). Right now it contains a single sample about multi-modules/multi-services setup. Hope it's helpful here, feedbacks welcome.

**Comment by martinbonnin** [comment]
Closing for now, let us know if you need more details.
