### ISSUE TITLE
How do I make query with Java?

### ISSUE THREAD

**Issue by josephearl** [apollographql/apollo-kotlin#5276]
### Question

v2 had documentation for using the library from Java. It looks like for later versions this is missing.
Am I supposed to implement a Kotlin `Continuation` somehow and pass that to `query.execute`?

Is plain Java really supported with newer versions? The v2 APIs seemed a lot nicer to use from Java.

**Comment by josephearl** [comment]
Noticed https://github.com/apollographql/apollo-kotlin/issues/5023 so will wait and try v4

**Comment by martinbonnin** [comment]
@josephearl note we just released `4.0.0-beta.1`. Documentation is [here](https://www.apollographql.com/docs/kotlin/v4/advanced/java). Feel free to try it out and let us know how that goes.
