### ISSUE TITLE
Consider discouraging the use of the Upload scalar

### ISSUE THREAD

**Issue by StylianosGakis** [apollographql/apollo-kotlin#5294]
### Description

As discussed in this issue https://github.com/apollographql/router/issues/842
In this blogpost https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/
And in this slack discussion https://slack-chats.kotlinlang.org/t/15976244/we-ve-been-historically-using-the-upload-scalar-to-upload-th#195b9d17-e627-4807-b63a-25dc9d305c73

Using the Upload scalar which tries to upload a multipart file through GraphQL is not supported at all from apollo-router, and seems to be generally discouraged.

As BOD mentions in the slack discussion, there are some docs about this in the iOS-only library discouraging its use here https://www.apollographql.com/docs/ios/fetching/mutations/#an-important-caveat-about-file-uploads. Maybe the same could be mentioned here to let new users know about it.

**Comment by BoD** [comment]
Thanks a lot for all the context 🙏

**Comment by BoD** [comment]
Doc update has been merged
