### ISSUE TITLE
SchemaFilePath in build.gradle

### ISSUE THREAD

**Issue by faizankhan48** [apollographql/apollo-kotlin#5304]
### Question

I am implementing it in a micro-service built in Kotlin. The micro-service has to make a GraphQL call to a server. The latest version was not able to built successfully but [3.8.2](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.8.2). I have set the plugin like this in `build.gradle`
```
plugins {
    // Other Plugins
    id 'com.apollographql.apollo3' version '3.8.2'
}

repositories {
    mavenCentral()
}

dependencies{
    // Other Dependencies
    implementation("com.apollographql.apollo3:apollo-runtime:3.8.2")
}

apollo {
    service('service') {
        packageName.set('com.faizan.service')
        // Specify the custom path to your GraphQL schema file
        schemaFilePath.set(file("src/main/graphql/application.graphql"))
        sourceFolder.set(file("${buildDir}/generated/source/graphql"))
    }
}
```

I also tried with 
`sourceFolder.set(file("src/main/graphql"))`

I have placed the schema file in
```
MyApplication
    src
        main
            graphql
                application.graphql
        kotlin
            com
                faizan
                    service
```

The error is 
`> Could not get unknown property 'schemaFilePath' for object of type com.apollographql.apollo3.gradle.internal.DefaultService.`

**Comment by BoD** [comment]
Hi!

The simplest configuration is just:

```
apollo {
    service('service') {
        packageName.set('com.faizan.service')
    }
}
```

and have your files like this:

```
MyApplication
    src
        main
            graphql
                schema.graphqls
                operations.graphql
        kotlin
            com
                faizan
                    service
```

Note that your schema should have the `.graphqls` extension while your operations should have `.graphql`.

**Comment by faizankhan48** [comment]
Thank you I got your point. With this structure when I try to download the schema using this command `./gradlew :app:downloadApolloSchema --endpoint='https://<some_domain>.com/graphql' --schema=app/src/main/graphql/schema.graphqls` it gives this error
```
* What went wrong:
Project 'app' not found in root project 'custom-integrations-service'.
```
As I am not working on Android app but a kotlin service which needs to call a graphQL client, how can this be fixed. settings.gradle has already `rootProject.name = 'custom-integrations-service'` So it tried adding this but nothing change
```
include ':app'
project(':app').name = 'custom-integrations-service'
```
and this is my project structure.
```
MyApplication
    src
        main
            graphql
                application.graphql
        kotlin
            com
                faizan
                    service
    build.gradle
    settings.gradle
```

**Comment by BoD** [comment]
You should execute `./gradlew :downloadApolloSchema` instead of `./gradlew :app:downloadApolloSchema` since you don't have an `app` module. You should also probably remove what you've put in `settings.gradle`.

**Comment by faizankhan48** [comment]
I ran this command `./gradlew :downloadApolloSchema --endpoint='https://countries.trevorblades.com/graphql' --schema=main/graphql/countryschema.graphqls` and it added the file righ inside `graphql` package and I created a query with `Countries.graphql` but I am unable to access this query in my class inside `service` package.
