### ISSUE TITLE
How to write unit test for code coverage?

### ISSUE THREAD

**Issue by faizankhan48** [apollographql/apollo-kotlin#5319]
### Question

I have a mutation query with name `RegisterGuest`
```
mutation RegisterGuest($firstName: String!, $lastName: String!, $email: String) {
    registerGuest( input:{
        firstName: $firstName
        lastName: $lastName
        email: $email
    })
    {
        ... on RegisterGuestSuccess {
            guest {
                id
                firstName
                lastName
                email
            }
            csrf
        }
    }
}
```
 and its corresponding class `RegisterGuestMutation` is generated in build. I am writing a unit test for code coverage so I created a mock apollo client
` val apolloClient = mockk<ApolloClient>()` and `private val apolloClientBuilder = ApolloClient.Builder()`. I have initialized the response like this
```
val expectedResponse = RegisterGuestMutation.Data(
            RegisterGuestMutation.RegisterGuest(
                "__typename",
                RegisterGuestMutation.OnRegisterGuestSuccess(
                    RegisterGuestMutation.Guest(
                        "guestId",
                        "firstName",
                        "lastName",
                        "email"
                    ),
                    "csrfToken"
                )
            )
        )
```
But I cannot mock its response via this

```
val registerGuestMutation = RegisterGuestMutation(firstName, lastName, Optional.present(email))
coEvery { apolloClient.mutation(registerGuestMutation).execute() } returns ApolloResponse(expectedResponse)
```
On `ApolloResponse(expectedResponse)` it says _Cannot access '<init>': it is private in 'ApolloResponse'_  The returned type required here is `ApolloResponse<RegisterGuestMutation.Data>` and response is following this also.
How can I fix this? Thanks.

**Comment by martinbonnin** [comment]
Hi 👋 

There is a build on `ApolloResponse`, you can use `ApolloResponse.Builder(operation, uuid, data)`. Would that work?

**Comment by faizankhan48** [comment]
It worked, Thanks.

**Comment by faizankhan48** [comment]
It worked, Thanks.
