### ISSUE TITLE
Can I set dummy variable inside dataclass and getting variable type is editable

### ISSUE THREAD

**Issue by muslimmuda15** [apollographql/apollo-kotlin#5442]
### Question

After I generate apollo graphql, I getting data class like this
![image](https://github.com/apollographql/apollo-kotlin/assets/26782958/fcddf158-2b96-44b9-b706-189b5a2e4578)

Can I add one variable again, like `public var isActive: Boolean?` and set some variable like `paid`  and `updated` using `var` instead `val`?
this is my query
![image](https://github.com/apollographql/apollo-kotlin/assets/26782958/16ea8f05-dabb-42ee-9d92-87dab15b5635)

Thank you.

**Comment by BoD** [comment]
Hi!
The models are generated as data classes with vals as you can see, and at the moment it is not possible to generate vars instead. It's likely you will want to convert these to your own (non generated) models, but maybe you can tell us a bit more about your use case?

**Comment by muslimmuda15** [comment]
in my flow, I want to update some item of order list `List<OrderField>` inside `RecyclerView`.
so I need some variables like `paid` and `updated` can be update programmatically and add extra variable outside query.
Maybe I can implementation like this:
```
data class MyCustomOrder(
    var isActive: Boolean,
    var paid: Boolean,
    var updated: Boolean,
    var myOrder: OrderField,
)
```
But this is not the clear code, because I set the item one by one again.

**Comment by BoD** [comment]
It looks like you could benefit from a way to have local only fields, which is a feature that [exists on the web client](https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/) but not yet on Apollo Kotlin. It's tracked in this issue: #2611.

For now you can wrap or convert the generated class into your own model with the additional fields.

**Comment by muslimmuda15** [comment]
Yeah, in `ReactJS`, `codegen` is pretty clear and easy to used it.
