### ISSUE TITLE
Build fails after schema file rename when Gradle configuration cache enabled

### ISSUE THREAD

**Issue by varahash** [apollographql/apollo-kotlin#5455]
### Version

3.8.2 and 4.0.0-beta.3

### Summary

Currently build fails if you rename schema file and configuration cache was enabled. Take a look at the steps to reproduce issue below.

**My current workaround**
I have little bit investigated this and it seems the problem in the following code (schema files searched in a non-compatible way with configuration cache)
https://github.com/apollographql/apollo-kotlin/blob/84f0f9253765ff4bfd8f223539fefd24e8da0488/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt#L965-L970

To workaround this, I set `Service.schemaFiles` directly instead of relying on default behavior.
https://github.com/apollographql/apollo-kotlin/blob/84f0f9253765ff4bfd8f223539fefd24e8da0488/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/api/Service.kt#L83

```
apollo {
    service("main") {
        srcDir("src/main/graphql")
        schemaFiles.setFrom(
            fileTree("src/main/graphql") {
                include("**/*.graphqls")
            }
        )
    }
}
```

PS: since in my project I have multiple schema files, I cannot use just `Service.schemaFile` for single file

### Steps to reproduce the behavior

**Steps**
1) Create simple `my_lib` module and use default configuration for Apollo plugin. Place GQL schema file into main sources: `/Users/user/projects/sample/my_lib/src/main/graphql/schema.graphqls`
2) Build module with configuration cache enabled `./gradlew :my_lib:assembleDebug --configuration-cache`
3) Rename `schema.graphqls` to `schema2.graphqls`
4) Build module again with configuration cache enabled `./gradlew :my_lib:assembleDebug --configuration-cache`

**Actual result**
The second build fails with error
```
> Task :my_lib:generateMainApolloSources FAILED
Execution failed for task ':my_lib:generateMainApolloSources'.
> java.io.FileNotFoundException: /Users/user/projects/sample/my_lib/src/main/graphql/schema.graphqls (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 307ms
122 actionable tasks: 6 executed, 116 up-to-date
Configuration cache entry reused.
```

**Expected result**
Build must success

**Comment by martinbonnin** [comment]
Thanks for opening this 🙏 

Linking https://github.com/apollographql/apollo-kotlin/issues/5221 as I think they share the same root cause.
