### ISSUE TITLE
Is com.apollographql.apollo3:apollo-mockserver multiplatform and supports js?

### ISSUE THREAD

**Issue by ar-g** [apollographql/apollo-kotlin#5456]
### Question

Is com.apollographql.apollo3:apollo-mockserver multiplatform and supports js?

**Comment by ar-g** [comment]
we'd rather prefer to keep running our tests on browser as we support few clients on this platform

**Comment by martinbonnin** [comment]
`apollo-mockserver` uses the [nodejs net API](https://nodejs.org/api/net.html) to create a "real" server listening to a "real" port. I don't see how it is possible on the browser today, there's just no API to do that.

If you want to keep your tests on the browser:
* Either run a server on your dev machine outside your tests (that server can be node, JVM, anything else)
* Or use [`TestNetworkTransport`](https://www.apollographql.com/docs/kotlin/testing/mocking-graphql-responses)

**Comment by ar-g** [comment]
thanks for your response @martinbonnin, I've tried TestNetworkTransport but it doesn't support CustomScalarAdapters, hence ended up with mockserver
