### ISSUE TITLE
How to debug Shopify introspection Bad Requests?

### ISSUE THREAD

**Issue by RenFraser** [apollographql/apollo-kotlin#5459]
### Question

Hi folks,

Thanks for the great repository! I have the following `build.gradle.kts` file and am looking for some guidance on how to debug failures when calling the `downloadServiceApolloSchemaFromIntrospection` task in my gradle build to get the schema file. I've followed [Downloading a schema](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration#downloading-a-schema) section of the docs but am getting `400 Bad Request`s from Shopify when attempting to hit the endpoint. Changing the API version from `unstable` also doesn't change anything.

My `build.gradle.kts` is as follows and I'm wondering if I'm missing some configuration? If it's not obvious, I'll pull the repository and step through it :)

```kotlin
plugins {
    kotlin("jvm") version "1.9.21"
    id("com.apollographql.apollo3") version "4.0.0-beta.3"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.apollographql.apollo3:apollo-runtime:4.0.0-beta.3")
}

apollo {
    service("service") {
        packageName.set("org.example")

        introspection {
            headers.set(
                mapOf(
                    "X-Shopify-Access-Token" to "myPAT", // looks like "shpat_something"
                    "Content-Type" to "application/json"
                )
            )
            endpointUrl.set("https://quickstart-86f8bb93.myshopify.com/admin/api/unstable/graphql.json")
            schemaFile.set(file("schema.graphqls"))
        }
    }

}

kotlin {
    jvmToolchain(17)
}
```

**Comment by martinbonnin** [comment]
Apologies about this, [this is a regression in `4.0.0-beta.3`](https://github.com/apollographql/apollo-kotlin/issues/5449). We've found the issue and it is merged in `main`. It's getting late here but we'll make a new release first thing tomorrow morning

**Comment by RenFraser** [comment]
Fantastic thank you Martin!
