### ISSUE TITLE
Infinite Loop on Apollo().client().query(query).execute() airplane mode

### ISSUE THREAD

**Issue by tristan-garaud** [apollographql/apollo-kotlin#5490]
### Version

3.8.1

### Summary

Hi,
I'm doing a test with airplane mode. And when I try to execute my simple query it never returns anything. Waiting 5 more minutes and still nothing. Do you know where the problem could come from ?
Thanks

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
It should throw. Can you double check if anything is catching your exceptions? If that doesn't work, a reproducer would help a ton to investigate this.

**Comment by martinbonnin** [comment]
@tristan-garaud did you get a chance to look into this? Any update?

**Comment by martinbonnin** [comment]
I'll close this one for now. Let us know if you want us to reopen
