### ISSUE TITLE
Apollo Migrating from V3 to V4

### ISSUE THREAD

**Issue by maliksaif070** [apollographql/apollo-kotlin#5504]
### Question

I have on going android project with Multi Module setup my structure is something like this :- 

Common > apollo > framework 
Features > sub_module_1 , sub_module_2 , sub_module_3 .... sub_module_47

Common > apollo > framework is where my schema.graphqls  is. 

now i am moving from using the default service of apollo and declaring my service in my shared module like following 
    
```kotlin
apollo { 
    service("apolloFrameworkService") {
        packageName.set('my_package_name_here')
        generateApolloMetadata.set(true)
        schemaFile.set(file("../framework/src/main/graphql/schema.graphqls"))
        alwaysGenerateTypesMatching.set(["TYPES_HERE"]) 
    }
        
    service("service2") {
        packageNamesFromFilePaths()
     } 
     service("service3") {
        packageNamesFromFilePaths()
     } ... // rest of the services
     
     service("service47") {
        packageNamesFromFilePaths()
     } 
}
```
       
    and i have declared service in my sub_modules_1 ... 47 something like this. 
    
```kotlin
    apollo {
        service("service2") {
            packageNamesFromFilePaths()
            schemaFile.set(project.file("${project.rootDir}/common/apollo/framework/src/main/graphql/schema.graphqls"))
        }
    }
```
    
    sub_module_1..47 dependencies have this 
    
```
dependencies {
    apolloMetadata project(':common:apollo:framework')
    implementation project(':common:apollo:framework') 
    }
```
    
    
While building project i have receive this error 
    
<img width="514" alt="Screenshot 2024-01-02 at 5 36 49 PM" src="https://github.com/apollographql/apollo-kotlin/assets/125885107/7a94b8c8-3f5c-4076-8618-41475ae8e72b">

e: file:///android/common/apollo/framework/build/generated/source/apollo/service2/type/GraphQLBoolean.kt:13:14 Redeclaration: GraphQLBoolean
  
What am i missing here so is there any un official work around.   
    
    
<img width="477" alt="Screenshot 2024-01-02 at 5 32 53 PM" src="https://github.com/apollographql/apollo-kotlin/assets/125885107/2c6486ed-1110-40c1-b008-e94136cba116">

**Comment by martinbonnin** [comment]
Hi and happy new year 🥳 

> `service("service47") {`

It's very unlikely that you have 47 services. Each schema has a service but I doubt you have 47 schemas?


Your setup should look like so:

framework/build.gradle.kts:

```kotlin
apollo { 
    service("api") {
        packageName.set('my_package_name_here')
        generateApolloMetadata.set(true)
        schemaFile.set(file("../framework/src/main/graphql/schema.graphqls"))
        alwaysGenerateTypesMatching.set(["TYPES_HERE"]) 
    }
}
```

moduleN/build.gradle.kts:

```kotlin
apollo { 
    service("api") {
        packageNamesFromFilePaths()
        dependsOn(project(":framework"))
    }
}
```

You can read more about `dependsOn()` in the [migration guide.](https://www.apollographql.com/docs/kotlin/v4/migration/4.0#multi-module-dependson)

**Comment by maliksaif070** [comment]
Hi @martinbonnin  Happy New Year. 
Yes you are correct, i do not have 47 service rather 47 modules so i associated a single service to single module. 

I guess i would use a single service and define in my ModuleN. 

and for dependsOn i also need to migrate the AGP. 

Thanks @martinbonnin 
Will let you how it goes .

**Comment by maliksaif070** [comment]
@martinbonnin Thanks previous issue has been resolved.
Everything works as expected with AGP 8.2.0 and apollo 3.8.2
as soon as i update the version to 
        apollo_version = '4.0.0-beta.4'
it throws error for apolloMetadata deprecated, so after fixing my moduleN gradle 

```
   apollo {
        service("apolloFrameworkService"){
            packageNamesFromFilePaths()
            dependsOn(project(':common:apollo:framework'))
        }
    }
```

that issue goes away once i try to rebuild the project 
i get following error 

**Cannot resolve SchemaTypeAdapter(GetTransactionsInput)**

**Execution failed for task ':features:notification-center:data:generateApolloFrameworkServiceApolloSourcesFromIr'.**

<img width="914" alt="Screenshot 2024-01-03 at 5 15 49 PM" src="https://github.com/apollographql/apollo-kotlin/assets/125885107/07bc85c8-6412-4970-be12-d79954f12287">

**Comment by martinbonnin** [comment]
You're probably missing the `CountUnreadNotificationRequest` in your `alwaysGenerateTypesMatching`:


framework/build.gradle.kts:

```kotlin
apollo { 
    service("api") {
        packageName.set('my_package_name_here')
        generateApolloMetadata.set(true)
        schemaFile.set(file("../framework/src/main/graphql/schema.graphqls"))
        alwaysGenerateTypesMatching.set(["CountUnreadNotificationRequest", ...]) 
        // or if you don't want to track every type, just use a wildcard
        alwaysGenerateTypesMatching.set(["*"]) 
    }
}
```

**Comment by martinbonnin** [comment]
@maliksaif070 any success here?

**Comment by maliksaif070** [comment]
@martinbonnin 
After this 
`alwaysGenerateTypesMatching.set([CountUnreadNotificationRequest]) 
`
the previous error is resolved how ever new errors for similar types appear for each and every Request & Response object.
for example before there were error for CountUnreadNotificationRequest , and nRequest Type 
now new errors suggest adding new types in 

`alwaysGenerateTypesMatching.set([NEW_TYPE])

it is a never ending cycle for now 

This is for .KTS i have groovy gradle
`alwaysGenerateTypesMatching.set(["*"]) 
`

**Comment by martinbonnin** [comment]
In `.kts`, you can do:

```kotlin
alwaysGenerateTypesMatching.set(listOf("*"))  
```

**Comment by maliksaif070** [comment]
@martinbonnin  
In your previous you mentioned this would be in **framework/build.gradle.kts:**

`alwaysGenerateTypesMatching.set(["CountUnreadNotificationRequest", ...]) 
`

Either way will try that shortly to see if it works for all the cases.

**Comment by martinbonnin** [comment]
You can choose whether you want to track used types manually (builds faster) or just include everything (easier):

```kotlin
apollo { 
    service("api") {
        // Track used types manually
        alwaysGenerateTypesMatching.set(["CountUnreadNotificationRequest", ...]) 
        // OR 
        // Just include everything
        alwaysGenerateTypesMatching.set(listOf("*")) 
    }
}
```

There is actually 3rd option which is to use Gradle to detect used types automatically (requires tracking all feature modules):

```kotlin
apollo { 
    service("api") {
      // Get the used types from the downstream module
      isADependencyOf(project(":feature1")) 
      // ...
      isADependencyOf(project(":feature47")) 
    }
}
```

You can read more about it in [the multi-modules docs](https://www.apollographql.com/docs/kotlin/v4/advanced/multi-modules#auto-detection-of-used-types]. 

All options work. It's all about the tradeoffs. If unsure, I recommend going with `alwaysGenerateTypesMatching.set(listOf("*"))` and you can optimize later if needed.

Let me know how that goes.

**Comment by maliksaif070** [comment]
@martinbonnin 

Project compiles and run no more errors. 
i ended up using following

```
apollo { 
    service("api") {
      // Get the used types from the downstream modules
      isADependencyOf(project(":feature1")) 
      // ...
      isADependencyOf(project(":feature47")) 
    }
}
```
Thank you for you support. Appreciate it.

**Comment by martinbonnin** [comment]
Awesome 🎉 Thanks for the follow up!
