### ISSUE TITLE
Can we use something like this in Android ../../common/GraphQL/schema.graphqls (instead of src/main/common/GraphQL)

### ISSUE THREAD

**Issue by codingworldp** [apollographql/apollo-kotlin#5505]
### Question

Can we use something like this in Android ../../common/GraphQL/schema.graphqls (instead of src/main/common/GraphQL)
This folder is root of the project, i want to use this schema file for both Android and iOS 

Project Structure will look like this 
android folder
common folder (where i will place graphQL queries and schema file)
iOS folder 

my gradle file looks like this 

```kotlin
apollo {
    service("graphql") {
        packageName.set("com.sample.app")
        generateApolloMetadata.set(true)
        schemaFile.set(file("../../common/GraphQL/schema.graphqls"))
    }
}
```

I'm getting these errors 
<img width="843" alt="Screenshot 2024-01-03 at 2 29 57 PM" src="https://github.com/apollographql/apollo-kotlin/assets/144183039/7a64934f-7248-4fae-89c1-b97188be61dc">

**Comment by martinbonnin** [comment]
Can you double check that you have the apollo runtime added to your dependencies?

```kotlin
dependencies {
  implementation("com.apollographql.apollo3:apollo-runtime")
}
```

**Comment by codingworldp** [comment]
adding implementation("com.apollographql.apollo3:apollo-runtime") fixed errors but it is not creating GraphQL queries @martinbonnin

**Comment by martinbonnin** [comment]
Dang, sorry to hear that. Can you ellaborate a bit more? What is your `build/generated/source/apollo` folder?

Maybe you need to configure where your operation files (`*.graphql`) are? This is done with `srcDir()`:

```kotlin
apollo {
  service("api") {
      packageName.set("com.sample.app")
      generateApolloMetadata.set(true)
      schemaFile.set(file("../../common/GraphQL/schema.graphqls"))
      srcDir(/*place where your *.graphql files are*/)
  }
}
```

**Comment by martinbonnin** [comment]
@codingworldp any news here?
