### ISSUE TITLE
Firing queries from Android Studio plugin with @nonull directive

### ISSUE THREAD

**Issue by damianpetla** [apollographql/apollo-kotlin#5506]
### Question

Hey, I am using Apollo plugin with Android Studio and I used to test my graphql files directly from IDE. Noticed that adding `@nonull` does not allow plugin to work and returns error message `"message": "directive 'nonnull' is not defined in the schema"`

The question is if that can be somehow workaround?

**Comment by martinbonnin** [comment]
Can you try enabling the "Apollo Kotlin" framework in the GraphQL plugin? 

<img width="1109" alt="Screenshot 2024-01-04 at 16 56 09" src="https://github.com/apollographql/apollo-kotlin/assets/3974977/bbf19780-d465-4d47-9a40-51959817e4c6">

**Comment by damianpetla** [comment]
Hey @martinbonnin I had this enabled
![image](https://github.com/apollographql/apollo-kotlin/assets/8932745/f79a9597-af4a-4b52-a820-2a98fbf77022)

**Comment by martinbonnin** [comment]
IDE support is still being worked on (see https://github.com/JetBrains/js-graphql-intellij-plugin/issues/697) so it'll come but the red underlines for `@semanticNonNull` are still expected at this stage.

I would still expect `@nonnull` to be detected though(see https://github.com/JetBrains/js-graphql-intellij-plugin/blob/21d5800921d07176992e3d006728a89a1c1eb242/resources/definitions/ApolloKotlin.graphql#L23)

**Comment by damianpetla** [comment]
`@nonnull` works just fine when editing graphql file, there is support for that. It just fails when executing graphql queries from IDE

**Comment by damianpetla** [comment]
Thanks. They work just fine from the app. Been using it for some time now on prod. It's just very convenient sometimes to verify something right from the IDE.

**Comment by martinbonnin** [comment]
I created https://github.com/apollographql/apollo-kotlin/issues/5507 as a follow up before I forget.
