### ISSUE TITLE
When attempting to migrate apollo 4.0 query/mutation are not geneated in own package

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-kotlin#5532]
### Version

4.0.0-beta.4

### Summary

I am trying to migrate our app from 3.7.5 to 4.0-beta-4

My apollo plugin usage looks like the one shown below.

What I am observing is that query, mutation files are now generated have package name com.mycompany.product.repo.network

However, when using 3.7.5 the generated mutation, query etc had their own package name example:
 
com.mycompany.product.repo.network.mutation , com.mycompany.product.repo.network.query etc.

What directive should I be using to make sure I get same behavior as 3.X? Without this I am looking at massive change from 3.7.5 to 4.X

I have also tried to specify package name explicitly that produces same generated code
```packageName.set("com.mycompany.product.repo.network")```

```


apollo {
    service("service") {
        packageNamesFromFilePaths("")
        codegenModels.set("operationBased")
        warnOnDeprecatedUsages.set(false) // true by default
        failOnWarnings.set(false) // true by default
        mapScalar("DateTime", "kotlin.String")
        mapScalar("ColorHex", "kotlin.String")
        mapScalar("URI", "kotlin.String")
        mapScalar("HTML", "kotlin.String")
        mapScalar("BigInt", "kotlin.Long")
        mapScalar("Locale", "kotlin.String")
    }
}
```

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Hi 👋 

When using `packageNamesFromFilePaths("")`, the package name is computed from the location of your GraphQL files. If you put them in directories like this, you should still have the `query` and `mutation` packages:


```
src/main/graphql/com/mycompany/product/repo/network/schema.graphqls
src/main/graphql/com/mycompany/product/repo/network/query/QueryStuff.graphql
src/main/graphql/com/mycompany/product/repo/network/mutation/MutateStuff.graphql
```

Can you share the layout of your `src/main/graphql` directory?

**Comment by snijsure** [comment]
Struture looks like this, note we are using schema.json file and not schema.graphqls is that the reason by any chance?

repo
└── network
    ├── fragment
    ├── mutation
    ├── query
    ├── schema.json

**Comment by martinbonnin** [comment]
> we are using schema.json file and not schema.graphqls is that the reason by any chance?

This shouldn't change much. I've uploaded a small reproducer [here](https://github.com/martinbonnin/test-package-name/blob/07ea017de75c6d171e0037d4926b324a32a7afc6/src/main/kotlin/MainTest.kt#L2). So far, it's working as expected: `Query` is in the `com.mycompany.product.repo.network.query` package. Any chance you can tweak it to reproduce your issue?

**Comment by snijsure** [comment]
I copied my network folder into your repo, and I was able to generate queries, mutation in individual directories, as expected.

However, I noticed that fragments are generated in fragment/fragment directory instead of just one top-level fragment directory.

Sorry basic question about running your MainTest.kt -- how do I run it?

One thing I didn't mention that my setup graphql is in its own package, does that make difference?

core-repo-network/src/main/graphql/com/mycompany/product/repo/network

And then queries, fragments, mutations are in these directories.

core-repo-network/src/main/graphql/com/mycompany/product/repo/network/fragment/
core-repo-network/src/main/graphql/com/mycompany/product/repo/network/query/
core-repo-network/src/main/graphql/com/mycompany/product/repo/network/mutation/
core-repo-network/src/main/graphql/com/mycompany/product/repo/network/schema.json

**Comment by snijsure** [comment]
One thing I noticed that in your project you have set 

```
service("api") {
        packageNamesFromFilePaths("")
}
```

but in my project I have

```
    service("service") {
        packageNamesFromFilePaths("")
    }
```

**Comment by martinbonnin** [comment]
>  I noticed that fragments are generated in fragment/fragment directory instead of just one top-level fragment directory

That's correct, fragments are generated in a `.fragment` subpackage. AFAIK, this was the case in 3.x too. 
If your issue is with fragments, 3.x had a `useSchemaPackageNameForFragments` option that is removed in v4. Could it be that you were using this?

> MainTest.kt -- how do I run it?

I just pushed a [commit](https://github.com/martinbonnin/test-package-name/commit/82bcc1f1114f63dc26e0a1afeca8b497ccfdf18f) to move that code under tests. If you pull latest changes, you should now be able to run the test from your IDE.

> my setup graphql is in its own package, does that make difference?

What do you mean by setup? Is it your schema? 

> `service("api")` vs `service("service")`

This doesn't change anything. This is for naming Gradle tasks mainly.

**Comment by snijsure** [comment]
I removed my gradle cache $HOME/.gradle/caches and the code is now getting generated , correctly! 

But now I am getting weird issues with error!
```
e: Could not load module <Error module>
```

Let me look at this project - https://github.com/apollographql/apollo-kotlin-tutorial  branch ```bump-4.0.0-beta.4``` to see i need to do something specific for Android project.

( 4.0 will build with [K2](https://blog.jetbrains.com/kotlin/2023/02/k2-kotlin-2-0/) so it'll require a stable version of K2 but overall the goal is early 2024. )

Yes we do use ```useSchemaPackageNameForFragments``` we will stop using that before migrating to 4.X
