### ISSUE TITLE
Java ApolloClient SocketTimeoutException, how to fix 

### ISSUE THREAD

**Issue by AerialSky93** [apollographql/apollo-kotlin#5602]
We are using ApolloClient in Java and receiving this error. How can it be fixed? What timeout config parameters should be added to request headers?

**Code:**

```

apolloClient
    .query(query)
    .toBuilder()
    .requestHeaders(headersData)
    .build()
    .enqueue(new ApolloCall.Callback<>() {

```
**Error:**

message=com.apollographql.apollo.exception.ApolloNetworkException: Caused by: java.net.SocketTimeoutException: timeout 

This stacklink is not Apollo specific rather OkHttp library, [java.net.SocketTimeoutException: timeout](https://stackoverflow.com/questions/36455656/java-net-sockettimeoutexception-timeout)

**Comment by martinbonnin** [comment]
It's the OkHttpClient default, which is [10 seconds](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html#connectTimeoutMillis--)

**Comment by AerialSky93** [comment]
> It's the OkHttpClient default, which is [10 seconds](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html#connectTimeoutMillis--)

Ok, @martinbonnin  so for my understanding my company wants a general timeout of 2 seconds, not 10 seconds, for both connectTimeout and readTimeout. If I take the code above, it may actually make my problem worse, is that correct? or would it help? appreciate it

I may have to explore other methods then

  ApolloClient apolloClient = new ApolloClient.Builder()
                .serverUrl("https://example.com")
                .okHttpClient(
                    new OkHttpClient.Builder()
                        .connectTimeout(2, TimeUnit.SECONDS)
                        .readTimeout(2, TimeUnit.SECONDS)
                        .build()
                )
                .build();

**Comment by martinbonnin** [comment]
You can use the timeout you want. For a 2s timeout use the below:

```java
        ApolloClient apolloClient = new ApolloClient.Builder()
                .serverUrl("https://example.com")
                .okHttpClient(
                    new OkHttpClient.Builder()
                        .connectTimeout(2, TimeUnit.SECONDS)
                        .readTimeout(2, TimeUnit.SECONDS)
                        .build()
                )
                .build();
```

**Comment by AerialSky93** [comment]
yep @martinbonnin so my question is , if I go from 10 seconds default to 2 seconds? Will it actually help alleviate the "SocketTimeoutException", or will it possible make it worse? since we are decreasing timeout seconds? thanks

**Comment by martinbonnin** [comment]
It depends what you want:

* If you want to fail fast then using `(2, TimeUnit.SECONDS)` will make the error appear faster.
* If you wan to give more time to your server to send a response, use a bigger value like `(20, TimeUnit.SECONDS)`.

**Comment by martinbonnin** [comment]
@AerialSky93 anything else we can help with here?

**Comment by AerialSky93** [comment]
it seems to work, thank you @martinbonnin
