### ISSUE TITLE
Kotlin cost

### ISSUE THREAD

**Issue by Truly93** [apollographql/apollo-kotlin#5607]
[plugins {
  id("com.apollographql.apollo3") version "3.8.2"
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("com.apollographql.apollo3:apollo-runtime:3.8.2")

  // optional: if you want to use the normalized cache
  implementation("com.apollographql.apollo3:apollo-normalized-cache-sqlite:3.8.2")
  // optional: if you just want the generated models and parsers and write your own HTTP code/cache code, you can remove apollo-runtime
  // and use apollo-api instead
  implementation("com.apollographql.apollo3:apollo-api:3.8.2")
}](apollo-api)

**Comment by martinbonnin** [comment]
Hi @Truly93, was there a question in this issue?

**Comment by Truly93** [comment]
> Hi @Truly93, was there a question in this issue?

I don't understand the sequence of installation

**Comment by martinbonnin** [comment]
Closing as non-actionable. Please leave a message if you want us to reopen
