### ISSUE TITLE
Rx2/3 Support artifact for beta.3 and beta.4 is missing

### ISSUE THREAD

**Issue by brian-plummer-okcupid** [apollographql/apollo-kotlin#5609]
### Question

I'm not seeing the artifacts for rx2/rx3 for beta.3 and beta.4. Am I being silly and missing something? Thanks in advance

[com.apollographql.apollo3:apollo-rx2-support](https://mvnrepository.com/artifact/com.apollographql.apollo3/apollo-rx2-support)
[com.apollographql.apollo3:apollo-rx3-support](https://mvnrepository.com/artifact/com.apollographql.apollo3/apollo-rx3-support)

**Comment by martinbonnin** [comment]
We decided to remove them as they really have little value, they were just wrappers around `kotlinx-coroutines-rx2`. 

There is some info in the (work in progress) [migration guide](https://www.apollographql.com/docs/kotlin/v4/migration/4.0#removed-rxjava-artifacts). We'll add more guidance there but the replacement should be quite straightforward. Mostly use `toFlow().asFlowable()`

**Comment by brian-plummer-okcupid** [comment]
thank you @martinbonnin ! :)

**Comment by martinbonnin** [comment]
The artifacts have been restored for 4.0.0 with `DeprecationLevel.ERROR`. They'll be removed in a future version.
