### ISSUE TITLE
Allow Custom Extensions in buildPostBody Method

### ISSUE THREAD

**Issue by morux2** [apollographql/apollo-kotlin#5627]
### Use case

We are trying to verify queries by passing signatures via extensions instead of using AutoPersistedQuery. As mentioned in https://github.com/apollographql/apollo-kotlin/issues/2922, we tried using the [ByteStringHttpBody](https://www.apollographql.com/docs/kotlin/kdoc/apollo-api/com.apollographql.apollo3.api.http/-byte-string-http-body/index.html) method. However, there is no way to serialize variables since FileUploadAwareJsonWriter is  internal. We would like to call the original implementation as much as possible to keep up with future updates of apollo-kotlin.

<img width="600" alt="スクリーンショット 2024-02-19 16 02 49" src="https://github.com/apollographql/apollo-kotlin/assets/19369161/6690d788-3e67-4234-b877-fedc753fa8e5">

apollo-kotlin: 3.8.2

### Describe the solution you'd like

add extensions argument to [buildPostBody](https://www.apollographql.com/docs/kotlin/kdoc/apollo-api/com.apollographql.apollo3.api.http/-default-http-request-composer/-companion/build-post-body.html) method.

<img width="437" alt="スクリーンショット 2024-02-19 16 09 51" src="https://github.com/apollographql/apollo-kotlin/assets/19369161/3e45582d-35f1-49e6-bc2b-01381fdddf80">

**Comment by martinbonnin** [comment]
Makes a lot of sense 👍 Thanks for the feature request.

An version of `buildPostBody` that allows writing extensions is available [here](https://github.com/apollographql/apollo-kotlin/pull/5630) (will backport in v3 in a bit).

If you are not doing [file uploads](https://www.apollographql.com/docs/kotlin), you can use the following for the time being:

```kotlin
class WithExtensionsHttpRequestComposer(private val serverUrl: String) : HttpRequestComposer {
  override fun <D : Operation.Data> compose(apolloRequest: ApolloRequest<D>): HttpRequest {

    val request = HttpRequest.Builder(HttpMethod.Post, serverUrl)
        .body(
            ByteStringHttpBody(
                "application/json",
                buildJsonByteString {
                  writeObject {
                    name("query")
                    value(apolloRequest.operation.document())
                    name("operationName")
                    value(apolloRequest.operation.name())
                    name("variables")
                    apolloRequest.operation.serializeVariables(this, apolloRequest.executionContext[CustomScalarAdapters]!!, false)
                    name("extensions")
                    writeObject {
                      name("key")
                      value("value")
                    }
                  }
                }
            )
        )
        .build()

    return request
  }
}
```

This is all using public API so it's not going anywhere any time soon. If you're using file uploads on the other hand, I'm afraid you'll have to copy/paste a lot of `FileUploadAwareJsonWriter` until the fix gets released.

**Comment by morux2** [comment]
Thanks for responding to our feature request and providing a temporary solution!
https://github.com/apollographql/apollo-kotlin/pull/5631 looks good to me. 

---
We are not doing the file uploads, therefore temporary solutions looks good.
It seems that the serializeVariables function does not have a third argument.

```kotlin
val operation = apolloRequest.operation
val customScalarAdapters = apolloRequest.executionContext[CustomScalarAdapters] ?: CustomScalarAdapters.Empty
```
```kotlin
name("variables")
writeObject {
    operation.serializeVariables(this, customScalarAdapters)
}
```

**Comment by morux2** [comment]
After https://github.com/apollographql/apollo-kotlin/pull/5631 released, our implementation looks like this.
It is almost copy of DefaultHttpRequestComposer. Is it possible to add buildRequestHeader() method to DefaultHttpRequestComposer for simplify our Composer?

```kotlin
class CustomHttpRequestComposer(
    private val serverUrl: String,
) : HttpRequestComposer {
    override fun <D : Operation.Data> compose(apolloRequest: ApolloRequest<D>): HttpRequest {
        val operation = apolloRequest.operation
        val customScalarAdapters = apolloRequest.executionContext[CustomScalarAdapters] ?: CustomScalarAdapters.Empty

        val requestHeaders = mutableListOf<HttpHeader>().apply {
            add(HttpHeader(DefaultHttpRequestComposer.HEADER_APOLLO_OPERATION_ID, operation.id()))
            add(HttpHeader(DefaultHttpRequestComposer.HEADER_APOLLO_OPERATION_NAME, operation.name()))
            if (apolloRequest.operation is Subscription<*>) {
                add(HttpHeader(HEADER_ACCEPT_NAME, HEADER_ACCEPT_VALUE_MULTIPART))
            } else {
                add(HttpHeader(HEADER_ACCEPT_NAME, HEADER_ACCEPT_VALUE_DEFER))
            }
            val headers = apolloRequest.httpHeaders
            if (headers != null) {
                addAll(headers)
            }
        }
        val sendDocument = apolloRequest.sendDocument ?: true
        val query = if (sendDocument) operation.document() else null
        return HttpRequest.Builder(
            method = HttpMethod.Post,
            url = serverUrl,
        ).addHeaders(requestHeaders)
            .body(buildPostBody(
                DefaultHttpRequestComposer.buildPostBody(
                    operation,
                    customScalarAdapters,
                    query,
                ) {
                    name("extensions")
                    writeObject {
                        name("key")
                        value("value")
                    }
                }
            ).build()
    }

    companion object {
        private const val HEADER_ACCEPT_NAME = "Accept"
        private const val HEADER_ACCEPT_VALUE_DEFER = "application/json"
        private const val HEADER_ACCEPT_VALUE_MULTIPART = "multipart/mixed; boundary=\"graphql\"; subscriptionSpec=1.0, application/json"
    }
}
```

**Comment by morux2** [comment]
This is another feature request.

Currently, we are copying DefaultHttpRequestComposer's requestHeaders implementations.
Would it be possible to add a `buildRequestHeader()` method to DefaultHttpRequestComposer for simplify custom composer implementaion?

```kotlin
    val requestHeaders = mutableListOf<HttpHeader>().apply {
      add(HttpHeader(HEADER_APOLLO_OPERATION_ID, operation.id()))
      add(HttpHeader(HEADER_APOLLO_OPERATION_NAME, operation.name()))
      if (apolloRequest.operation is Subscription<*>) {
        add(HttpHeader(HEADER_ACCEPT_NAME, HEADER_ACCEPT_VALUE_MULTIPART))
      } else {
        add(HttpHeader(HEADER_ACCEPT_NAME, HEADER_ACCEPT_VALUE_DEFER))
      }
      if (apolloRequest.httpHeaders != null) {
        addAll(apolloRequest.httpHeaders)
      }
    }

    companion object {
        private const val HEADER_ACCEPT_NAME = "Accept"
        private const val HEADER_ACCEPT_VALUE_DEFER = "application/json"
        private const val HEADER_ACCEPT_VALUE_MULTIPART = "multipart/mixed; boundary=\"graphql\"; subscriptionSpec=1.0, application/json"
    }
```

**Comment by martinbonnin** [comment]
> Would it be possible to add a buildRequestHeaders() method to DefaultHttpRequestComposer for simplify custom composer implementaion?

Woops, sorry that fell through! 

We could do something like so:

```kotlin
/*
 * Adds the default headers to this HttpRequest.Builder:
 * - Accept
 * - X-APOLLO-OPERATION-ID
 * - X-APOLLO-OPERATION-NAME
 */
fun HttpRequest.Builder.addDefaultHttpHeaders(): HttpRequest.Builder {}
```

That you could use like so:

```kotlin
      return HttpRequest.Builder(
            method = HttpMethod.Post,
            url = serverUrl,
        ).body(
                DefaultHttpRequestComposer.buildPostBody(
                    operation,
                    customScalarAdapters,
                    query,
                ) {
                    name("extensions")
                    writeObject {
                        name("key")
                        value("value")
                    }
                }
            )
            .addDefaultHttpHeaders()
            .build()
```
Heads up we are also changing the HTTP headers sent in v4. See https://github.com/apollographql/apollo-kotlin/pull/5533

I'm curious if you need those header specifically? Would anything break if we remove `X-APOLLO-OPERATION-ID` for an example?

**Comment by morux2** [comment]
@martinbonnin 

Sorry for the delayed response. Thank you for informing us about the latest changes to Apollo!
We've confirmed that there is no issue with the changing of HTTP headers.
And so, we decided to stop sending Headers to follow the update to Apollo.

It's okay to close this issue. Thank you for your warm support and response to the request 😄

**Comment by martinbonnin** [comment]
Thanks for the follow up! 

https://github.com/apollographql/apollo-kotlin/pull/5631 is now available in the [SNAPSHOTs](https://github.com/apollographql/apollo-kotlin/?tab=readme-ov-file#snapshots) and will be in next 3.8 and 4.0-beta versions. Thanks again for surfacing this!
