### ISSUE TITLE
Looking for equivalent of query.variables().marshal() for apollo3

### ISSUE THREAD

**Issue by ngallion** [apollographql/apollo-kotlin#5632]
### Question

We are migrating to apollo-api 3.8.2 and it looks like we can no longer call query.variables().marshal() to get a JSON string of our query variables. Is there an equivalent way to get a JSON string of the query variables?

**Comment by martinbonnin** [comment]
You can use [`variablesJson`](https://github.com/apollographql/apollo-kotlin/blob/d14bcb6d40db0cd3a9b91470e1084ff7b9f1129b/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/Executables.kt#L25):

```kotlin
val jsonString = operation.variablesJson(customScalarAdapters)
```

**Comment by ngallion** [comment]
That's it! Thank you so much!
