### ISSUE TITLE
How to handle key which is present in graphqls but not available on server side?

### ISSUE THREAD

**Issue by wishygupta** [apollographql/apollo-kotlin#5634]
### Question

In my mobile application on graphqls file I have few objects which will be added later on server side.
If my try to run the code the app crashes since the server doesn't respond with those keys. How can I make those optional or ignore them?

**Comment by martinbonnin** [comment]
Are trying to query fields that your server does not support? If yes, there's no silver bullet there. You'll either have to edit your queries to remove those fields or edit your server to support them.

I can think of possible alternative workarounds (mockserver, interceptor) but it's hard to tell without more context. Can you share your query/crash?

**Comment by martinbonnin** [comment]
@wishygupta anything else we can help with here?

**Comment by martinbonnin** [comment]
Closing. Let us know if anything comes up

**Comment by martinbonnin** [comment]
Woops, I should have closed this one as "not planned" to avoid the message bot. Sotty about this @wishygupta but yes, if you have any feedback please leave it here or in the survey!
