### ISSUE TITLE
Programmatic Caching Support For Relay Style Pagination

### ISSUE THREAD

**Issue by ArjanSM** [apollographql/apollo-kotlin#5666]
### Use case

Hi Team 👋 
Exciting to see the changes pertaining to merging of Relay Style Pagination Responses in the Incubating Normalized Cache.
In order to use the feature(s) that enabling merging of the Relay Style Pagination Response in Incubating Normalized Cache [requires setting a few parameter(s)](https://github.com/apollographql/apollo-kotlin/issues/4251), while defining custom directives `@fypePolicy` or `@fieldPolicy`.
However, is there any plan to enable this feature with the programmatic cache keys such as `CacheKeyGenerator` and `CacheKeyResolver`? 

### Describe the solution you'd like

 I'll leave it to the maintainers to decide.

**Comment by BoD** [comment]
Hi! You're right this is declarative only currently, and that it would probably makes sense to have a programmatic API as well. I'll keep this ticket open to track it.

To better understand the need, may I ask why you'd prefer it over the declarative way?

**Comment by ArjanSM** [comment]
Hi @BoD 
Thanks for the quick response.
Yes, so we have been utilising `CacheKeyGenerator` and `CacheKeyResolvers` to programmatically generate CacheKeys.
We preferred not to maintain an additional artifact in `extra.graphql` specifically because we didn't want multiple teams to step on top of each other's changes.

**Comment by BoD** [comment]
It is actually now possible to use the pagination mechanism with a programmatic configuration only, since #5772. An example is available [in `ConnectionProgrammaticPaginationTest`](https://github.com/apollographql/apollo-kotlin/blob/38af25fc4dee114d16087dd39063f2ec3265badc/tests/pagination/src/commonTest/kotlin/ConnectionProgrammaticPaginationTest.kt#L51).
