### ISSUE TITLE
Experimental @defer support does not work with AutoPersistedQueryInterceptor

### ISSUE THREAD

**Issue by rohandhruva** [apollographql/apollo-kotlin#5667]
### Version

4.0.0-beta.4

### Summary

When using `@defer`, a `response` will have multiple parts. However, `AutoPersistedQueryInterceptor` uses `var response = chain.proceed(request).single()`, which will lead to an immediate `IllegalArgumentException`, because: `Flow has more than one element`. 

### Steps to reproduce the behavior

Enable the `AutoPersistedQueryInterceptor` and use any operation that has `@defer`. The failure should reproduce even if you use `client.query().toFlow()`.

**Comment by BoD** [comment]
Thanks a lot for reporting! A fix will be in the next release and in the meantime it can be tried out with the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots).

**Comment by bwoodlt** [comment]
I'm having the same issue. I'm using `autoPersistedQueries`, despite seeing `gql` logs showing incremental payload, i couldnt access them in my logic.
