### ISSUE TITLE
[compiler] Add GraphQL AST to Apollo Compiler Plugins

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#5709]
### Description

Would be nice to expose the GraphQL AST to `Plugin` so that users could generate side data without having to parse the schema/operations twice

KotlinLang slack thread: https://slack-chats.kotlinlang.org/t/16651498/i-got-a-type-like-type-flow-id-id-currentstep-flowstep-progr#5519cac4-ca54-4d20-a7c4-16c52cd39871

**Comment by martinbonnin** [comment]
@StylianosGakis I gave a shot as generating visitors for all `Flow` fields here: https://github.com/martinbonnin/log-current-step


Call `./gradlew build`, which will run in order:

* `addGraphQLFields`: adds the `flowStep` fragment automatically to every field of `Flow` type
* `generateVisitors`: generate a `GeneratedVisitors.kt` file with code that can visit all the fields of `Flow` type for a given operation Name:

```kotlin
public fun interface Visitor {
  public fun visit(`data`: Any?, block: (FlowStep) -> Unit)
}

public val generatedVisitors: Map<String, Visitor> = mapOf(
      "getFlow" to Visitor { data, block ->
        data as GetFlowQuery.Data
        data.flowClaimBarNext.cast<FlowStep>().maybe(block)
      },
      "getNestedFlow" to Visitor { data, block ->
        data as GetNestedFlowQuery.Data
        data.nested?.flows?.forEach {
          it?.cast<FlowStep>().maybe(block)
        }
      },
    )
```

* `generateServiceApolloSources`: to also generate the Apollo sources

TBH, it's quite the setup to avoid a bunch of manual boilerplate (related [xkcd](https://xkcd.com/1319/)). Depending the size of your schema, it might or might not worth it. My guess is unless you have a huge schema and a large number of operations, it's not worth it.

**Comment by StylianosGakis** [comment]
Wow thanks a lot for taking the time to show me how this can be done.
I will just be honest with you and admit that this is definitely quite a lot of setup, and for the use case I had in mind this would definitely make it much harder to reason with not just for me but especially for my colleagues. They'd hate me for it I'm sure 😅

But this is a great thing to have at hand to look at if I happen to find some similar use case. Thanks a lot for putting it all together and sharing it with me!

**Comment by martinbonnin** [comment]
Ahah that's fair 👍 . I'll close this one for now. It's still there as reference.
