### ISSUE TITLE
[Intellij Plugin] Truncate "go to" data

### ISSUE THREAD

**Issue by demoritas** [apollographql/apollo-kotlin#5727]
### Version

4.0.0-beta.5

### Summary

(MacOs)

cmd-click on a fragment opens the "jump to" popup which contains a tad too much information using a lot of screen space

![Image](https://github.com/apollographql/apollo-kotlin/assets/7316033/21c54dfd-2a13-4aea-8de9-be6342bd7a22)

### Steps to reproduce the behavior

- have a non trivial fragment (becomes more visual with some layers of data in it)
- have a wide screen monitor
- command click on the usage of the fragment in GraphQl (...YourFragment)
- enjoy :)

**Comment by BoD** [comment]
Thanks for reporting! Let's see what we can do.

**Comment by BoD** [comment]
The fix is included in version 4.0.0-beta.6 of the plugin.
