### ISSUE TITLE
Pagination: merge `nodes` field in addition to `edges`

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#5735]
Currently it is possible to configure the (incubating) pagination system to handle Relay-style pagination by using `@TypePolicy(connectionFields: ...)` and `ConnectionFieldMerger`.

This will automatically merge the lists in `edges` into a single record, allowing the app code to watch it and update the UI.

In addition to the `edges` field, it is common for schemas to also have a `nodes` field (e.g. the GitHub and Shopify schemas), which simplifies a bit the usage of the API. `ConnectionFieldMerger` could handle this by merging `nodes` in addition to `edges`, if present.

Original question about this [here](https://github.com/apollographql/apollo-kotlin/issues/3593#issuecomment-2003872915).

**Comment by martinbonnin** [comment]
Is there? (Or can we add?) an existing pull request or proposal to add this to the [Relay specification](https://github.com/facebook/relay/blob/main/website/spec/Connections.md)? Would be rad to add this but having some proposal before doing the implementation would be even rad-er!

**Comment by sonatard** [comment]
I also hope that Nodes will be reflected in the Relay specification.

In the Relay specification, Edge cursors are not used, but even so, this is in the Note format and does not fundamentally address the issue.
https://github.com/facebook/relay/blob/main/website/spec/Connections.md?plain=1#L377-L381

Additionally, the terms "Relay Classic", "Relay Legacy", and "Relay Modern" appear in the Relay specification, but we do not understand what each of them refers to.

**Comment by martinbonnin** [comment]
@sonatard do you want to open an issue in the Relay repo and we can follow up with the Relay team to clarify the terms and explore the possible addition of `nodes`?

**Comment by sonatard** [comment]
Thank you for the suggestion. I plan to open two issues.

**Comment by sonatard** [comment]
Create a following issue
https://github.com/facebook/relay/issues/4653

And I had actually created an issue about nodes in the past. I had forgotten about it until today.
https://github.com/facebook/relay/issues/3850

**Comment by martinbonnin** [comment]
Good find! upvoted!

**Comment by BoD** [comment]
Closing now as this is available in the incubating caching artifact. Don't hesitate to open tickets for comments/issues with this.
