### ISSUE TITLE
QueueTestNetworkTransport `enqueueTestResponse` function not found in java project，Does it not support java?

### ISSUE THREAD

**Issue by WSSsssss33** [apollographql/apollo-kotlin#5742]
### Question

Q:enqueueTestResponse function not found in java project

Gradle: add testImplementation("com.apollographql.apollo3:apollo-testing-support:3.8.2")
My code: 
in testfile: 
ApolloClient apolloClient = new ApolloClient
			.Builder()
			.networkTransport(new QueueTestNetworkTransport())
			.build(); 
then, i want apolloClient to call enqueueTestResponse. But can't find any function here.
Does it not support java?

**Comment by martinbonnin** [comment]
`apollo-testing-support` hasn't been built with Java interop in mind. You can still use `enqueueTestResponse` as a static function though:

```java
TestNetworkTransportKt.enqueueTestResponse(apolloClient, response)
```

**Comment by WSSsssss33** [comment]
`TestNetworkTransportKt.enqueueTestResponse(apolloClient, response)`
the type of `response` should be the `ApolloResponse`? If so, how to create/new a `ApolloResponse` from a data, assume the data is Query.Data.  Ps: use Java

**Comment by martinbonnin** [comment]
Something like so:

```java
    MyQuery query = new MyQuery();
    ApolloResponse response = new ApolloResponse.Builder(query, null)
        .data(new MyQuery.Data(
            // your data here
        ))
        .build();
```

**Comment by WSSsssss33** [comment]
`@Test
    public void callWithQueryReturnsExpectedResult() {
		ApolloClient client = new ApolloClient.Builder()
			.networkTransport(new QueueTestNetworkTransport())
			.build();
		UUID uuid = UUID.randomUUID(); // Generate a random UUID

		Query<GetPipelineInfoQuery.Data> mockQuery = new GetPipelineInfoQuery(Optional.present("slug"),
			Optional.present(10));
		ApolloResponse response = new ApolloResponse.Builder(mockQuery, uuid, mockData())
			.build();
		TestNetworkTransportKt.enqueueTestResponse(client, response);
		client.query(mockQuery).execute(new Continuation<>() {
			@NotNull
			@Override
			public CoroutineContext getContext() {
				log.info("****getContext**");
				return EmptyCoroutineContext.INSTANCE;
			}

			@Override
            public void resumeWith(@NotNull Object responseObject) {
				log.info("****resumeWith**{}", responseObject);
				if (responseObject instanceof ApolloResponse) {
					log.info("****resumeWithApolloResponse**{}", responseObject);
				}
				if (responseObject instanceof Result.Failure) {
					log.info("****resumeWithFailure**", ((Result.Failure) responseObject).exception);
				}
			}
		});
	}`

I run this test, but it goes to `getContext` loop, so i can't get response. Did i am wrong here?

**Comment by martinbonnin** [comment]
Calling coroutines from Java is pretty complicated. 

I would recommend you update to version `4.0.0-beta.5`. There is a `apollo-runtime-java` artifact that you can use for your Java calls. You can read more about it in the dedicated [documentation page](https://www.apollographql.com/docs/kotlin/v4/advanced/java)

**Comment by WSSsssss33** [comment]
Thanks for your patience.
I hava update to `4.0.0-beta.5`
If i use `apollo-runtime-java` to replace previouse `ApolloClient`, when i want to add a `QueueTestNetworkTransport` via the [docmentation](https://www.apollographql.com/docs/kotlin/v4/testing/mocking-graphql-responses), some thing wrong here.
<img width="744" alt="image" src="https://github.com/apollographql/apollo-kotlin/assets/53244584/91fcfd2f-1588-4592-b269-2bd373cd2750">
and i can't use `TestNetworkTransportKt.enqueueTestResponse(client, apolloResponse);` because Type error for client.
How could i testing ?

**Comment by martinbonnin** [comment]
Good catch. The testing story for Java needs to be refined. 

My immediate recommendation would be to test using something like [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) and JSON responses. `MockWebServer` has really solid Java APIs.

**Comment by WSSsssss33** [comment]
Have try to use `MockWebServer` , but can't get response. Seem it do not enter to response callback loop. Can u try it?

`
		MockWebServer server = new MockWebServer();
		server.enqueue(new MockResponse()
			.setBody("yo dog")
			.setResponseCode(200)
		);
		server.start(9999);
		ApolloClient client = new ApolloClient.Builder()
			.serverUrl(server.url("/").toString())
			.build();

		Query<GetPipelineInfoQuery.Data> mockQuery = new GetPipelineInfoQuery(
			Optional.present("slug"),
			Optional.present(10));

		client.query(mockQuery).enqueue(response -> {
			log.info("****response:{}", response.data);
			if (response.data != null) {
				// No errors
				log.info("****data:{}", response.data);
			} else {
				// Errors
				if (response.exception instanceof ApolloGraphQLException) {
					// GraphQL errors
					log.info("****ApolloGraphQLException");
					System.out.println(((ApolloGraphQLException) response.exception).getErrors().get(0));
				} else {
					// Network error
					log.info("****ApolloGraphQLException");
					response.exception.printStackTrace();
				}
			}
		});
`

**Comment by martinbonnin** [comment]
If you're running this from a test, you'll have to wait until the callback is fired. If not your test is going to finish before the callback fires.

The quick & dirty way to do this is to just `Thread.sleep` (example [here](https://github.com/martinbonnin/apollo-java-test/tree/main/src/test/java/test)). More involved (and correct) solution would use synchronisation primitives like monitors and/or RxJava

**Comment by WSSsssss33** [comment]
Ok, it works. Thanks.
