### ISSUE TITLE
Multi Module & Multiple Schema support

### ISSUE THREAD

**Issue by sav621** [apollographql/apollo-kotlin#5744]
### Question

I'm currently having trouble supporting the following case in our multi module project:

- `graphql`  (schema module)
  - com/example
    - mainService
      - schema.sdl
    - subscriptionService 
      - schema.sdl

- `featureA` (feature module) 
  - graphql/queries: queries use `mainService` schema
  - graphql/subscriptions: subscriptions use `subscriptionService` schema

In order to have the queries and subscriptions live in the same module, I set the following in the schema module's service:

```
apollo {
  service("subscriptionService") {
    schemaFiles.setFrom("/com/example/mainService/schema.sdl", "/com/example/subscriptionService/schema.sdl")
    srcDir(File(graphql/com/example))
  }
}

```

This results in an error, though: `Multiple schemas found. Use different services for different schemas`. 

Am I missing something? Shouldn't this be allowed?

On Apollo Kotlin v3.7.2

**Comment by martinbonnin** [comment]
Hi 👋 

You'll need one service per schema. Something like so:

```kotlin
// schema/build.gradle.kts
apollo {
  service("queries") {
    schemaFiles.setFrom("com/example/mainService/schema.sdl")
    packageName.set("com.example")
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(listOf(".*"))
  }
  service("subscriptions") {
    schemaFiles.setFrom("com/example/subscriptionService/schema.sdl")
    packageName.set("com.example")
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(listOf(".*"))
  }
}
```

And then use that from your feature module:

```kotlin
// feature/build.gradle.kts
dependencies {
  apolloMetadata(project(":schema"))
}

apollo {
  service("queries") {
    srcDir("graphql/queries")
    packageName.set("com.example")
  }
  service("subscriptions") {
    srcDir("graphql/subscriptions")
    packageName.set("com.example")
  }
}
```

The name of the service have to match in both modules.

**Comment by sav621** [comment]
This was actually what I started with, but the feature module using multiple services seems to not generate those Apollo classes with this approach.

**Comment by martinbonnin** [comment]
Does it output an error? Or just nothing? I would double check your paths. `srcDir` needs to be from the root of the current module.

For reference, I uploaded a small reproducer there: https://github.com/martinbonnin/multi-multi
Hope this helps!

**Comment by sav621** [comment]
All Apollo classes are generated except for the ones that are needed in the module using both services. Shouldn't that suggest that the `srcDir` is set correctly? 

Here are the errors I get:
```
Caused by: com.apollographql.apollo3.ast.SourceAwareException: ... Cannot find a root type for operation type `subscription`
```

and

```
Caused by: com.apollographql.apollo3.ast.SourceAwareException: Cannot find type `X` for fragment `xFragment`
```
(In this ^ case, type X is from the main schema)

**Comment by sav621** [comment]
Should `srcDir("graphql")` also work, rather than `srcDir("graphql/queries")`? Will Apollo traverse the directory or does it need to be the full path? Asking because of a current limitation with our project. 

All Apollo classes are generated except for the ones that are needed in the module using both services. Shouldn't that suggest that the `srcDir` is set correctly? 

Here are the errors I get:
```
Caused by: com.apollographql.apollo3.ast.SourceAwareException: ... Cannot find a root type for operation type `subscription`
```

and

```
Caused by: com.apollographql.apollo3.ast.SourceAwareException: Cannot find type `X` for fragment `xFragment`
```
(In this ^ case, type X is from the main schema)

**Comment by martinbonnin** [comment]
`srcDir()` works like [Gradle `SourceDirectorySet.srcDir()`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#srcDir-java.lang.Object-). So it will recurse in sub-folders.

I do not recommend using `srcDir("graphql")` because as you found out, it's going to try to compile all operations under that directory, queries and subscriptions alike. If they do not use the same schema, compilation will fail with errors such as the ones you shared.

I'd recommend putting your `.graphql` files in separate directories:

```
schema
-- build.gradle.kts
-- src/main/graphql/queries
    -- schema.graphqls
-- src/main/graphql/subscriptions
    -- schema.graphqls
feature
-- build.gradle.kts
-- src/main/graphql/queries
    -- query1.graphql
-- src/main/graphql/subscriptions
    -- subscription1.graphql
```

And then 

```kotlin
// schema/build.gradle.kts
apollo {
  service("queries") {
    srcDir("src/main/graphql/queries")
    packageName.set("com.example")
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(listOf(".*"))
  }
  service("subscriptions") {
    srcDir("src/main/graphql/subscriptions")
    packageName.set("com.example")
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(listOf(".*"))
  }
}

// feature/build.gradle.kts
dependencies {
  apolloMetadata(project(":schema"))
}

apollo {
  service("queries") {
    srcDir("src/main/graphql/queries")
    packageName.set("com.example")
  }
  service("subscriptions") {
    srcDir("src/main/graphql/subscriptions")
    packageName.set("com.example")
  }
}
```

I haven't tested this so don't take it as gospel but it should give the general idea. Having different directories under `graphql` helps keeping things separate

**Comment by sav621** [comment]
Gotcha - they are in separate directories. It's more of a limitation with how we create services in our Gradle plugin. Sounds like it's an issue on our end though. Thanks for your time and examples! Will close this out
