### ISSUE TITLE
The tutorial API doesn't return errors when fed an unknown launch id.

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#5747]
### Description

Follow up from https://github.com/apollographql/apollo-kotlin/pull/5740

The tutorial API doesn't return errors anymore when fed an unknown launch id.

([sandbox example](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fapollo-fullstack-tutorial.herokuapp.com%2Fgraphql&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABABQAkANgIYxJQAWAkmOkYwCICEAlEcADpIiRarQYkAliyKUadJmF4ChwonAkBnDRIhDlq1YIMBfI0VNJjIY0A))

**Comment by BoD** [comment]
Resolved with https://github.com/apollographql/fullstack-tutorial/pull/352 (thanks @mabuyo!)
