### ISSUE TITLE
Feature to not emit cache misses?

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#5791]
### Question

I see that there used to be a `emitCacheMisses(Boolean)` but it was removed and I don't see why.

Usecase: I'm doing a query with the default `CacheFirst` fetch policy + `watch()` so I can get updates if there are any.  I'd like to have the flow emit when there's a valid value, or a network/server error.  I don't care about cache misses.  I can obviously filter the cache miss out myself with a `mapNotNull` or `filter` but I'm hoping there's a cleaner way to do that.

**Comment by edenman** [comment]
yeah, I guess I mean that I would like some way to do this globally (at the ApolloClient.Builder step?).  

Although I'm not sure how that would work if you did a query with `fetchPolicy(FetchPolicy.CacheOnly)`

**Comment by martinbonnin** [comment]
@edenman you can restore the global "ignore cache misses" using the below extension functions on `ApolloClient.Builder`:

```kotlin
fun ApolloClient.Builder.ignoreCacheMisses() = apply {
  addInterceptor(object : ApolloInterceptor {
    override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
      return chain.proceed(request).filter { it.exception !is CacheMissException }
    }
  })
}
```

It's not 100% clear given the `CacheOnly` case above if we want to provide that option by default. Maybe we need different cases for single-shot queries vs multiple-responses Flow or something like that.

As it's always easier to add than remove, I'd prefer not adding a new API at this point. If you end up using the extension function and it works well for you, feel free to leave a comment and we'll revisit.

**Comment by martinbonnin** [comment]
For the record, we [just bumped](https://github.com/apollographql/apollo-kotlin/issues/5799#issuecomment-2057978144) into a use case for always emitting cache misses. Having the initial cache result allows to skip displaying a loading indicator while fetching the cache result. 

I'm going to close this one for now. Anyone wanting a global `ignoreCacheMisses(true)` can use the extension function above:

```kotlin
fun ApolloClient.Builder.ignoreCacheMisses() = apply {
  addInterceptor(object : ApolloInterceptor {
    override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
      return chain.proceed(request).filter { it.exception !is CacheMissException }
    }
  })
}
``` 

If this is proven to work well, we could add it as a first party extension but I'd rather wait for a bit more feedback before doing so.
