### ISSUE TITLE
WasmJs support for apollo-adapters

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#5795]
### Description

`kotlinx.datetime` now supports WasmJs. We should publish a WasmJs version of `apollo-adapters`. 

But before doing that, we'll need a way to add BigDecimal support using `big.js` or something else.

**Comment by joreilly** [comment]
Is it case that Kotlin/JS is supported......thought similar hooks could be used when using WasmJs?

**Comment by joreilly** [comment]
Nvm, I see that it is....I tried enabling wasm for that module and following seems to work

```
findByName("wasmJsMain")?.apply {
      dependencies {
        implementation(npm("big.js", "5.2.2"))
      }
    }
```

I copied over `BigDecimal.kt` and it seems happy with `@JsModule("big.js")` but other errors then...

**Comment by joreilly** [comment]
asked about it here https://kotlinlang.slack.com/archives/CDFP59223/p1712856405783919

**Comment by martinbonnin** [comment]
Fixed with https://github.com/apollographql/apollo-kotlin/pull/5803 💙
