### ISSUE TITLE
Compiler plugin: add a GQLDocumentTransform API

### ISSUE THREAD

**Issue by rohandhruva** [apollographql/apollo-kotlin#5807]
### Use case

This feature request is to add a `GQLDocumentTransform` API to the [compiler plugins](https://www.apollographql.com/docs/kotlin/v4/advanced/compiler-plugins/).

We would like to transform the document at a higher level to try and apply some custom rules for our operations. For example, "whenever you see type `Foo` being used, always fetch field `bar`". This would be somewhat similar to how using `addTypename = always` adds `__typename` to every field fetched.

**Comment by martinbonnin** [comment]
@rohandhruva tentative API [here](https://github.com/apollographql/apollo-kotlin/pull/5809). After working on this, I'm having second thoughts though...

This is probably something that can be done in a separate Gradle task, outside of the Apollo compiler completely. How would you feel if instead of a `Plugin` API, we'd write a small doc page how to transform your operation before feeding the compiler? 

Bonus: you could transform your schema as well in there.

**Comment by rohandhruva** [comment]
>  How would you feel if instead of a `Plugin` API, we'd write a small doc page how to transform your operation before feeding the compiler?

Sure, if you feel like this is not a good fit for the compiler API and better suited as a different gradle task, I can definitely give it a shot!

Will this separate gradle task have a reference to the compiled schema so that we can "read" type info? So for example, I can say that for any usage of type `interface Video`, make sure `fooField` is always fetched. 

Somewhat related, I noticed that an issue with the `Plugin` API is that it's not possible (?) to pass build time parameters to it. For example, for registering the operation ids, we'd like to pass in some info available at build time from gradle properties. 

Does this limitation apply to `Plugin` in general, or am I missing something?

**Comment by martinbonnin** [comment]
> Will this separate gradle task have a reference to the compiled schema so that we can "read" type info?

Idea would be to grab the schema and operations. Parse and transform using apollo-ast and then feed that input the Apollo Gradle Plugin. I'll work on a sample project.

> for registering the operation ids, we'd like to pass in some info available at build time from gradle properties.

You can use [`buildConfiFields`](https://developer.android.com/build/gradle-tips). While it's some initial setup, it makes for a much better separation between your build logic and the apollo compiler. Also no need to recompile all your build when the apollo compiler changes, and vice versa.

**Comment by martinbonnin** [comment]
Sample project [here](https://github.com/martinbonnin/add-fields).

The interesting bits are:

* The [AddFields Gradle task](https://github.com/martinbonnin/add-fields/blob/main/build-logic/src/main/kotlin/AddGraphQLFields.kt)
* The [Gradle wiring](https://github.com/martinbonnin/add-fields/blob/main/build-logic/src/main/kotlin/main.kt)

**Comment by martinbonnin** [comment]
Thinking more about this, doing everything in a `generateApolloSources` dependency has one drawback: this task happens  before validation. So some assumptions that are usually safe to do (a field has always a matching field definition) may not always be safe in that case.
