### ISSUE TITLE
[Documentation] Defer docs "experimental" link results in a 404

### ISSUE THREAD

**Issue by StylianosGakis** [apollographql/apollo-kotlin#5830]
### Description

In https://www.apollographql.com/docs/kotlin/fetching/defer/ if you click on the "experimental" link at the top, which currently links to "https://www.apollographql.com/docs/resources/release-stages/" results in a 404
![image](https://github.com/apollographql/apollo-kotlin/assets/44558292/a0465323-a333-461e-a617-09652b93cf2d)

Interestingly, if you just enter that link to your browser it does properly redirect to "https://www.apollographql.com/docs/resources/product-launch-stages/".
So something may be wrong with the way that redirects are handled in the docs themselves?

**Comment by martinbonnin** [comment]
Good find 👀 , I'll dig

**Comment by martinbonnin** [comment]
Apologies for the delay. Turns out it's a disconnect between Gatsby (blog engine) and Netlify (hosting). The docs team is working on a fix but for now I just updated the links in #6031
