### ISSUE TITLE
Add @Generated annotation to Java code generated from the compiler

### ISSUE THREAD

**Issue by kasecato** [apollographql/apollo-kotlin#5855]
### Use case

As a NullAway user using Apollo Kotlin from Java, I want `@Generated` annotation added to the code generated by `apollo-compiler`. So that enables the NullAway option, which omits null checking of the generated Java code.

- NullAway, https://github.com/uber/NullAway
- `@Generated` 
  - https://docs.oracle.com/en/java/javase/21/docs/api/java.compiler/javax/annotation/processing/Generated.html
  - https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html
- `-XepDisableWarningsInGeneratedCode`: Disables warnings in classes annotated with `@Generated`
  - https://errorprone.info/docs/flags

### Describe the solution you'd like

We can add `@Generated` to class around [JavaCodegen.kt](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/java/JavaCodegen.kt)

**Comment by BoD** [comment]
Thanks for the feature request!

I didn't know about `@Generated` and it sounds reasonable to apply it, but I'm concerned that `javax.annotation.Generated` requires a specific dependency, whereas `javax.annotation.processing.Generated` is in the JDK starting from version 9 whereas Apollo Kotlin has a minimal version of 8.

Could you maybe use ErrorProne's `-XepExcludedPaths` flag instead?

**Comment by kasecato** [comment]
I have two suggestions, but no strong opinions and let me close this request

1. Use `jakarta.annotation.Generated`
    - https://github.com/jakartaee/common-annotations-api/blob/3.0.0-BRANCH/api/src/main/java/jakarta/annotation/Generated.java
    - 25KB library increase is not good
1.  Create a custom `@Generated` in `apollo-annotations`
    - Overkill
