### ISSUE TITLE
Crash when use policy 

### ISSUE THREAD

**Issue by enggazzar** [apollographql/apollo-kotlin#5891]
### Version

3.8.2

### Summary

![Capture](https://github.com/apollographql/apollo-kotlin/assets/3309531/0988de3d-45b3-4541-99d5-ee19d9d4c2fd)
 override suspend fun <T> getMerchantsByKeyWord(keyword:String): Flow<Response<T>> {
        return apolloClient.query(MerchantsByKeyWordQuery(keyword)).fetchPolicy(FetchPolicy.CacheAndNetwork)
            .toFlow()
            .map { response ->
                try {
                    //response.data.merchants
                    Response.Success(response.data?.toRestaurantsSearch() as T)
                } catch (e: Exception) {
                    Response.Failure( e.message ?: "unknown error")
                }
            }
    }

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment]
Hi! It looks like you're having a network issue. This can happen if your device has a connectivity issue, or e.g. if the backend is not responding.

**Comment by enggazzar** [comment]
I enabled working offline from cache policy

**Comment by BoD** [comment]
`CacheAndNetwork` will both go to the cache and the network, which will throw if the network fails.

**Comment by enggazzar** [comment]
I disable wifi to test app  working offline

**Comment by BoD** [comment]
In that case what you're seeing is definitely expected. You should probably add a `.catch {}` call to the Flow chain, to handle the exception.
