### ISSUE TITLE
Cache sharing between instances of ApolloStore

### ISSUE THREAD

**Issue by ankur2136** [apollographql/apollo-kotlin#5902]
### Version

3.8.3

### Summary

I have multiple implementations of ApolloClients where I want to share in-memory cache data with. However even after injecting the same `NormalizedCacheFactory` the entries are not same between the 2 instances.

### Steps to reproduce the behavior

A minimalist repro

        val cacheKey = CacheKey("TypeName", "CacheId")
        val reviewFragment = ReviewFragmentImpl()

        val cacheFactory = MemoryCacheFactory(expireAfterMillis = 100000)

        val client1 = ApolloClient.Builder().normalizedCache(cacheFactory)
            .serverUrl("test")
            .build()

        val client2 = ApolloClient.Builder().normalizedCache(cacheFactory)
            .serverUrl("test")
            .build()

        client1.apolloStore.writeFragment(
            reviewFragment,
            cacheKey,
            ReviewFragmentImpl.Data(
                id = "test",
                rating = 3,
                review = "test",
            )
        )

        println(client1.apolloStore.dump())
        println(client2.apolloStore.dump())

### Logs

```
{class com.apollographql.apollo3.cache.normalized.api.internal.OptimisticCache={}, class com.apollographql.apollo3.cache.normalized.api.MemoryCache={TypeName:CacheId=com.apollographql.apollo3.cache.normalized.api.Record@4e2ad3f2}}

{class com.apollographql.apollo3.cache.normalized.api.internal.OptimisticCache={}, class com.apollographql.apollo3.cache.normalized.api.MemoryCache={}}

```

I was expecting both dumps to be exact same.

**Comment by BoD** [comment]
Hi!

The reason is you are sharing a cache _factory_, which will be called to produce a cache instance twice - resulting in 2 separate instances. Instead you can share the `ApolloStore` which will have a reference to the cache, like so:

```kotlin
  val store = ApolloStore(cacheFactory)

  val client1 = ApolloClient.Builder().store(store)
    .serverUrl("test")
    .build()

  val client2 =ApolloClient.Builder().store(store)
    .serverUrl("test")
    .build()
```

**Comment by ankur2136** [comment]
Verified that the above works for me.
