### ISSUE TITLE
question: why are the auto-generated cache ids not optimized like in the JavaScript version

### ISSUE THREAD

**Issue by tafelnl** [apollographql/apollo-kotlin#5903]
### Question

I've used Apollo quite a lot in JavaScript. Always been very happy with it 👍

I was surprised to find out that the Kotlin variant of the library has a very different way of auto-generating cache ids than the JavaScript SDK. The cache ids that Kotlin auto-generates are undesirable for code generation. Which is mentioned in the docs. So that's fair enough. But I don't understand _why_ exactly. The JavaScript SDK makes manually declaring cache ids unnecessary in 99% of the cases. Why not go for the same approach here?

**Comment by BoD** [comment]
I think you are referring to the fact that the JavaScript client will default to use `id` and `_id` as keyfields, whereas Apollo Kotlin doesn’t do that, and instead will use the path to the field as the default when no key fields are configured - is that right?

I don’t have a full knowledge of the history of both projects but it looks like 2 different approaches were taken for the default indeed.

That being said, you can implement the same strategy in Apollo Kotlin by implementing a `CacheKeyGenerator`, like the first example [[here](https://www.apollographql.com/docs/kotlin/caching/programmatic-ids#cachekeygenerator)].

Please let me know if that works for you.

**Comment by tafelnl** [comment]
> That being said, you can implement the same strategy in Apollo Kotlin by implementing a CacheKeyGenerator, like the first example [[here](https://www.apollographql.com/docs/kotlin/caching/programmatic-ids#cachekeygenerator)].

Yeah, I figured indeed. That's very useful.

I was just curious if there was a specific reasoning for the difference between the two. But I guess it's nothing special. So I'll just have to keep my curiosity in check. No worries there. Thanks anyways
