### ISSUE TITLE
Apply com.apollographql.apollo3 plugin will break the dependencies in Kotlin Multiplatform according to IDEA

### ISSUE THREAD

**Issue by Hansanto** [apollographql/apollo-kotlin#5922]
### Version

4.0.0-beta.6

### Summary

 When the plugin is applied, all dependencies used  in `commonMain` are not available in `commonTest`is applied

### Steps to reproduce the behavior

I created a repository with the documentation linked to the problem https://github.com/Hansanto/apollo-issue

**Comment by martinbonnin** [comment]
Many thanks for the detailed bug report and reproducer ❤️ . Fix is [here](https://github.com/apollographql/apollo-kotlin/pull/5923)
