### ISSUE TITLE
`@loading` directive, similar to Houdini

### ISSUE THREAD

**Issue by kansson** [apollographql/apollo-kotlin#5925]
### Use case

Data loading can be simplified with loading states.

### Describe the solution you'd like

The idea comes from https://github.com/HoudiniGraphQL/houdini and can be used as a reference for implementation. See https://houdinigraphql.com/guides/loading-states#defining-the-shape for relevant docs.

**Comment by BoD** [comment]
Hi! Thanks for reaching out. 

This is an interesting idea. I could see this especially useful with `@defer` where different parts of the received model can have been received or not yet (currently modeled as `null`). Not 100% sure of the benefits in other cases, where (if I understand correctly) `@loading` fields will either be all loading, or all filled at the same time. Don't hesitate to add more context / examples to illustrate how this could be helpful in Kotlin/Compose.
