### ISSUE TITLE
Unnecessary AndroidX Multidex library included

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#5929]
### Version

4.0.0-beta.6

### Summary

Updating from beta 4 and noticed a new `androidx.multidex:multidex:2.0.1` dependency. Looks like it's added unconditionally in https://github.com/apollographql/apollo-kotlin/pull/5761

Could we make this optional?  AFAICT it's only necessary on pre-21 https://developer.android.com/build/multidex#mdex-pre-l

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
My bad, it should have been `testImplementation`. Thanks for catching this, will update in a bit 🙏

**Comment by BoD** [comment]
Removed in #5930, available in `4.0.0-beta7`
