### ISSUE TITLE
Sub-protocol not included when opening websocket [4.0.0-beta6]

### ISSUE THREAD

**Issue by isaacmanu** [apollographql/apollo-kotlin#5946]
### Version

4.0.0-beta6

### Summary

I'm trying to migrate our project to `4.0.0-beta6`.

I've replaced:
```
import com.apollographql.apollo3.network.ws.GraphQLWsProtocol
import com.apollographql.apollo3.network.ws.WebSocketNetworkTransport

.subscriptionNetworkTransport(
                WebSocketNetworkTransport.Builder()
                    .serverUrl(BASE_URL)
                    .protocol(GraphQLWsProtocol.Factory())
                    .build()
            )
```

With:
```
import com.apollographql.apollo3.network.websocket.GraphQLWsProtocol
import com.apollographql.apollo3.network.websocket.WebSocketNetworkTransport

.subscriptionNetworkTransport(
                WebSocketNetworkTransport.Builder()
                    .serverUrl(BASE_URL)
                    .wsProtocol(GraphQLWsProtocol())
                    .build()
            )
```

But whenever our app attempts to open a websocket now, it does so without the including any sub protocol:
<img width="1033" alt="Screenshot 2024-06-05 at 13 14 00" src="https://github.com/apollographql/apollo-kotlin/assets/67371753/4c8caab8-8cb6-419c-b7f1-88ca06ab69d7">

**Comment by martinbonnin** [comment]
Thanks for sending this, we'll dig into it. 
Just FYI, you can continue using the `com.apollographql.apollo3.network.ws` APIs if they worked well before, they are still around. But we'll definitely want to send that subprotocol for the new version.

**Comment by martinbonnin** [comment]
Fix is in https://github.com/apollographql/apollo-kotlin/pull/5948. Thanks for catching this!
