### ISSUE TITLE
Possible performance regression in v4.0.0-beta.7

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5947]
### Version

v4.0.0-beta.7

### Summary

Since version 4.0.0-beta.7, the round-trip time has become very long.
Additionally, the same issue occurs when we upgrade our app to Kotlin version 2 in version 4.0.0-beta.6.

### Steps to reproduce the behavior

I currently do not have time to conduct an investigation. Please let me know if there is any information you need. 

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Mmm indeed, there is quite a jump in the [json benchmarks](https://p.datadoghq.com/sb/d11002689-48ff7001681977d5a09c3a0775632cfa?fromUser=false&refresh_mode=sliding&from_ts=1715008613347&to_ts=1717600613347&live=true)

<img width="600" alt="Screenshot 2024-06-05 at 17 18 39" src="https://github.com/apollographql/apollo-kotlin/assets/3974977/486c2466-e22e-4e20-99ea-e74f98cbf35a">


We'll investigate, thanks for the heads up!

**Comment by martinbonnin** [comment]
We haven't been able to confirm locally yet. The benchmark give similar results:

beta.7
```
3 357 106   ns       12922 allocs    trace    JsonTests.jsonApollo
```
beta.6
```
3 330 695   ns       12922 allocs    trace    JsonTests.jsonApollo
```

We'll keep digging.

**Comment by martinbonnin** [comment]
I re-ran the benchmarks manually from `main` and it's back to normal times 🤔 

<img width="600" alt="Screenshot 2024-06-05 at 21 37 32" src="https://github.com/apollographql/apollo-kotlin/assets/3974977/9bb9a1aa-77ae-474a-9e8f-4a2f48bd6035">

I just tried [re-running the exact same commit](https://github.com/apollographql/apollo-kotlin/actions/runs/9377520538).

**Comment by sonatard** [comment]
I am using Jetpack Compose, and since Apollo4, there have been multiple recompositions, causing the same request to be sent to the server multiple times.

Both beta6 and beta7 are sending multiple requests, but for some reason, performance issues only occur in beta7. However, I would like to first solve the problem of sending multiple requests, and then recheck to see if the performance issues still occur.

**Comment by martinbonnin** [comment]
@sonatard apologies for the late response. Did you end up finding anything? This looks like a recomposition issue?

**Comment by sonatard** [comment]
@martinbonnin Yes, I found what causes recomposition. In Kotlin 2.0, if we pass a lambda function option as a key to remember, it is recognized as a different value each time, causing recomposition to occur.
If we remove the option from the key as shown below, recomposition will no longer occur.

```kt
--- a/app/src/main/java/com/appify/android/infra/network/apollo/ApolloClientExt.kt
+++ b/app/src/main/java/com/appify/android/infra/network/apollo/ApolloClientExt.kt
@@ -77,7 +77,7 @@ fun <D : Query.Data> ApolloClient.query(
     }

     var refetching by remember { mutableStateOf(false) }
-    val keys = arrayOf(q.hashCode(), option, refetching)
+    val keys = arrayOf(q.hashCode(), refetching)
     val apolloResponseFlow =
         remember(keys = keys) {
             when (watch) {
```

However, if the option cannot be included in the key, there remains the problem that if the option dynamically changes, it cannot be re-fetched.

**Comment by martinbonnin** [comment]
This is probably due to the fact that [lambdas are now using invokedynamic](https://kotlinlang.org/docs/whatsnew20.html#generation-of-lambda-functions-using-invokedynamic). It's hard to tell why your `option` is not equal against recomposition but I don't think we can do much in Apollo Kotlin?

**Comment by sonatard** [comment]
Thank you for your explanation. Currently, we pass options like fetchPolicy, and realistically, the options do not change depending on the state. For now, we plan to address this by removing the option from the key.

However, Apollo web does receive a fetchPolicy, and changes in this value trigger re-rendering. If we were to address this, we would solve it by accepting a FetchPolicy instead of a lambda and using it as the key.

Thank you for your cooperation.
