### ISSUE TITLE
Status Code 500 Not parsing error body

### ISSUE THREAD

**Issue by ds-griddynamics** [apollographql/apollo-kotlin#5958]
### Version

3.8.3

### Summary

Status Code - 500
```json 
{
  "errors": [
    {
      "message": "Not authorized to access the application.",
    }
  ]
}
```

Request throws above error check exception SS
<img width="1118" alt="Screenshot 2024-06-12 at 7 04 34 PM" src="https://github.com/apollographql/apollo-kotlin/assets/151758119/837c3fe2-7c7d-479c-9c4e-486f6f6ef4e5">

The error message should be `Not authorized to access the application.` but it throwing `Http request failed with status code 500`.

If you check in SS, the actual message is mapped to `errorMessage` but not to actual message. Can you verify

### Steps to reproduce the behavior

Simple BE is rejecting the call due to authorization failure

### Logs

```
HTTP: 500
Content-Length: 96
Content-Type: application/json; charset=utf-8
Date: Wed, 12 Jun 2024 13:41:34 GMT
Access-Control-Allow-Origin: *
ETag: W/"60-gJWZg86eFcw8mD1L1mOqWJaf9e0ddd234"
request-context: appId=cid-v1:
X-Powered-By: Express
[end of headers]
{"errors":[{"message":"Not authorized to access the application."}]}
```

**Comment by BoD** [comment]
Hi!

When receiving an HTTP status that is not in the 2xx range, the client considers that the response is not a GraphQL response and will throw an `ApolloHttpException` as you noticed. In that case, the body isn't read **by default**, but you can configure the client to read it:

```kotlin
val client = ApolloClient.Builder()
//...
.httpExposeErrorBody(true)
.build()
```

When doing this, you'll get a non null `ApolloHttpException.body`. Note that you should close it after reading (you can do something like `val body: String? = body?.use { it.readUtf8() }`.

**Comment by ds-griddynamics** [comment]
Worked! Thanks you fast reply

**Comment by BoD** [comment]
Glad it worked! Closing the issue, don't hesitate to reach out if you have other issues/questions.
