### ISSUE TITLE
writeOperation/writeFragment no longer publish updates by default

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#5971]
### Version

4.0.0-beta.7

### Summary

Recently updated from beta4.  `writeOperation` and `writeFragment` used to publish by default but now they don't (as a result of https://github.com/apollographql/apollo-kotlin/pull/5755)

**Comment by edenman** [comment]
(the signatures of the two methods look identical because `publish` is a default param)

**Comment by BoD** [comment]
Thanks for flagging! We made the write operations not suspending, but turned out publish needs to be suspend - so publishing is now removed by default, which is a behavior change. We should highlight that in the migration guide.

**Comment by edenman** [comment]
Yeah.  And probably deprecate the non-suspend version? Or at least rename it to something that indicates it doesn't publish updates?

**Comment by BoD** [comment]
@edenman After some thinking, we think the behavior change warrants an API change, which makes it harder to miss.

In #5976, we change the names of write functions and add extensions that have the same signature as in v3. Let us know what you think.

**Comment by edenman** [comment]
#5976 wfm

**Comment by BoD** [comment]
This has now been released in `4.0.0-rc.1`. 

Note: if you manually called `ApolloStore.publish()`, this is no longer needed with the RC onward, as the write methods now publish by default again (same behavior as 3.x). If you were explicitly passing `publish = true` then no change is needed.
