### ISSUE TITLE
doNotStoreOnDisk()

### ISSUE THREAD

**Issue by GeoffreyMetais** [apollographql/apollo-kotlin#5984]
### Use case

For features not needing disk persistency, but just a in-memroy caching mecanism and high performances 🚀 

It would be useful to have the equivalent of [doNotStore](https://www.apollographql.com/docs/kotlin/kdoc/apollo-normalized-cache-incubating/com.apollographql.apollo3.cache.normalized/do-not-store.html) operator, disabling I/O operations but not in-memory caching

### Describe the solution you'd like

doNotStoreOnDisk() operator :)

**Comment by martinbonnin** [comment]
Thanks for the feature request!

**Comment by BoD** [comment]
You can now do this with `.memoryCacheOnly(true)`, since `v4.0.0-rc.2`.
