### ISSUE TITLE
Apollo v2 to v3 refresh token mechanism

### ISSUE THREAD

**Issue by mserougi** [apollographql/apollo-kotlin#6029]
### Question

Any tips on how to quickly get an existing v2 retry mechanism migrated over to v3?

I can't wrap my head around the flow `intercept` version of v3, any way to keep using the v2 interceptor?

Here's the working v2 version:

```kotlin
class ApolloRequestInterceptor : ApolloInterceptor {
    private val maxRetryCount = 1

    private var retryCount = 0
    private var disposed = false

    override fun interceptAsync(request: ApolloInterceptor.InterceptorRequest, chain: ApolloInterceptorChain, dispatcher: Executor, callBack: ApolloInterceptor.CallBack) {
        chain.proceedAsync(request, dispatcher, object : ApolloInterceptor.CallBack {
            override fun onFailure(e: ApolloException) {
                callBack.onFailure(e)
            }

            override fun onResponse(response: ApolloInterceptor.InterceptorResponse) {
                if (disposed) {
                    return
                }

                if (isUnauthorized(response)) {
                    Logger.Internal.logInfo("⚠️ ApolloRequestInterceptor - User unauthorized")
                    synchronized(this) {
                        if (retryCount >= maxRetryCount) {
                            Logger.Internal.logInfo("⚠️ ApolloRequestInterceptor - Retry count reached limit")

                            retryCount = 0

                            callBack.onResponse(response)
                            callBack.onCompleted()
                        } else {
                            Logger.Internal.logInfo("⚠️ ApolloRequestInterceptor - Retrying...")

                            retryCount++

                            refreshToken { result ->
                                if (result) {
                                    chain.proceedAsync(request.toBuilder().fetchFromCache(false).build(), dispatcher, this)
                                } else {
                                    callBack.onResponse(response)
                                    callBack.onCompleted()
                                }
                            }
                        }
                    }
                } else {
                    retryCount = 0

                    callBack.onResponse(response)
                    callBack.onCompleted()
                }
            }

            override fun onFetch(sourceType: ApolloInterceptor.FetchSourceType?) {
                callBack.onFetch(sourceType)
            }

            override fun onCompleted() {}
        })
    }

    override fun dispose() {
        disposed = true
    }

    private fun isUnauthorized(response: ApolloInterceptor.InterceptorResponse): Boolean {
        return if (response.parsedResponse.isPresent) {
            @Suppress("UNCHECKED_CAST")
            val errors = response.parsedResponse.get().errors as List<com.apollographql.apollo.api.Error>?
            val error = errors?.firstOrNull()
            val extensions = error?.customAttributes?.get("extensions").toString()
            extensions.contains("AUTH_NOT_AUTHORIZED") || extensions.contains("AUTH_NOT_AUTHENTICATED")
        } else false
    }

    private fun refreshToken(completion: (Boolean) -> Unit) {
    }
}
```

**Comment by martinbonnin** [comment]
Hi 👋 

You can turn your `refreshToken()` function into a suspend one:

```kotlin
  suspend fun refreshTokenSuspend() = suspendCoroutine { continuation ->
    refreshToken {
      continuation.resume(it)
    }
  }
``` 

Then retry the flow using `.retryWhen {}`. Something like this:

```kotlin
class ApolloRequestInterceptor : ApolloInterceptor {
    private val maxRetryCount = 1

    private var retryCount = 0

    object Retry: Exception("Retry the flow")
  object RefreshFailed: Exception("Refresh the flow")

  val mutex = Mutex()


  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return chain.proceed(request).onEach { response ->
      if (!isAuthorized(response)) {
        val result = mutex.withLock {
          refreshTokenSuspend()
        }

        if (result) {
          throw Retry
        } else {
          throw RefreshFailed
        }
      }
    }.retryWhen { cause, attempt ->
      cause is Retry && attempt < maxRetryCount
    }
  }
}
```

This is all wildly untested and there is a surprising amount of detail in refreshing tokens so take this with a grain of salt.

If you're on Android, I'd recommend you use an OkHttp `Interceptor` instead. Authentication happens at the HTTP layer so it's a more natural place to add the interceptor. Plus there should be tons of example on the internet. You can for an example, take a look at the tutorial: https://github.com/apollographql/apollo-kotlin-tutorial/blob/5506c65076809f32a40ce0e0b01dfc285805fab2/compose/final/app/src/main/java/com/example/rocketreserver/Apollo.kt

**Comment by mserougi** [comment]
@martinbonnin Thanks for the code snippet, it's a starting point. I'm not worried about the actual token refresh logic as that's all done, I omitted it for brevity.

The problem with using an OkHttp interceptor, and from what I understand, is that you can't look at the response body, just the headers, which in my case won't work because the Graph server implementation responds with 200 even if the auth token is invalid, requiring my code to parse the response body and look for certain auth codes too.

**Comment by martinbonnin** [comment]
Oh right 👍  If your error is in the json then `ApolloInterceptor` will give you the parsed GraphQL error. Make sure to add your interceptor last so it runs just before the network one.

If you're looking at other examples, you can take a look at the [integration tests](https://github.com/apollographql/apollo-kotlin/blob/8d37c6119a43a620be175841050913c246ec1139/libraries/apollo-runtime/src/commonTest/kotlin/test/network/AuthorizationInterceptor.kt#L31) or at [Confetti](https://github.com/joreilly/Confetti/blob/832b1b3c92fe4040477a0012fe32be089b0dee9e/shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt#L45). Hope this helps, let me know how that goes!

**Comment by mserougi** [comment]
@martinbonnin I actually didn't need to change much from your code snippet at all, works like a charm, thank you!

**Comment by martinbonnin** [comment]
Nice, thanks for the follow up!
