### ISSUE TITLE
How to transform HTTP response status code for GraphQL response with errors

### ISSUE THREAD

**Issue by damianpetla** [apollographql/apollo-kotlin#6063]
### Question

By default my server returns errors in GraphQL response body e.g. `{"errors":[{"message":"Could not verify JWT: JWTExpired","extensions":{"path":"$","code":"invalid-jwt"}}]}` and status code is always 200. So it complicates how to deal with token expiration. 

I would like to ask if there is a known way that can transform response with such error to response with HTTP 401? If not, maybe someone could suggest other approach.

Note: I cannot change the server

**Comment by martinbonnin** [comment]
Hi 👋 

Usually, I recommend to use an `ApolloInterceptor` to retry at the GraphQL level instead of the HTTP level. You can take a look at [this issue comment](https://github.com/apollographql/apollo-kotlin/issues/3899#issuecomment-1051091305) for an example for how to do this.

**Comment by damianpetla** [comment]
@martinbonnin thanks, that is very useful. I actually managed to work out something on my own but I will try your suggestion too.
What I did is check on `ApolloInterceptor` if there is an error and throw custom `RetryException`. Then I have `retryWhen` and return `true` if it's `RetryException`. That restart the operation back to network transport and HttpInterceptor.

```kotlin
                .addInterceptor(object : HttpInterceptor {

                    @Volatile
                    private var cachedToken: String = //GET INITIAL TOKEN HERE

                    override suspend fun intercept(
                        request: HttpRequest,
                        chain: HttpInterceptorChain
                    ): HttpResponse {
                        val retryCount = request.headers.find { it.name == "Retry-Count" }?.value?.toInt() ?: 0
                        if (retryCount > 0) {
                            cachedToken = //UPDATE TOKEN
                        }
                        val response = chain.proceed(
                            request = request.newBuilder()
                                .addHeader("Authorization", cachedToken)
                                .addHeader("Retry-Count", (retryCount + 1).toString())
                                .build()
                        )
                        return response
                    }
                })
```

```kotlin
        .addInterceptor(object : ApolloInterceptor {
            override fun <D : Operation.Data> intercept(
                request: ApolloRequest<D>,
                chain: ApolloInterceptorChain
            ): Flow<ApolloResponse<D>> {
                val operation = request.operation
                return chain.proceed(request)
                    .onEach { response ->
                       //detect error here
                       if (errorDetected()) {
                          throw RetryException()
                       }
                    }
                    .retryWhen { cause, attempt ->
                        cause is RetryException && attempt < 3
                    }
            }
        })
```

I need to test also behaviour on web socket. Leaving my sample in case someone would need it.

**Comment by martinbonnin** [comment]
Love this idea of making the GraphQL and HTTP interceptors collaborate! Just curious about this line:

```kotlin
request.headers.find { it.name == "Retry-Count" }?.value?.toInt() ?: 0
```

Are there cases where this is not '0'?

```kotlin
                        val response = chain.proceed(
                            request = request.newBuilder()
                                .addHeader("Authorization", cachedToken)
                                .addHeader("Retry-Count", (retryCount + 1).toString())
                                .build()
                        )
```

This only affects the downstream chain so I fail to see how the retry count can increment. What am I missing?

**Comment by damianpetla** [comment]
@martinbonnin sry, looked like I fooled myself, spammed too many different logs to console and misread them thinking that http interceptor was hit as I planned 😢 
I have tried your solution too and it would have work but look like it fails on subscription handshake. That handshake is not respecting header set in ApolloInterceptor. But that probably I can workaround.

**Comment by martinbonnin** [comment]
Right, subscriptions use a different path. We could probably call the `HttpInterceptor`s for subscriptions as well but I don't think it would help because the GraphQL responses happen in individual subscriptions, not in the shared connection.   

>  That handshake is not respecting header set in ApolloInterceptor. 

Right. The WebSocket url and headers are currently owned by the `WebSocketNetworkTransport` and cannot be changed without creating a new `WebSocketNetworkTransport`. I'll think about how to change this.

> It would probably be a nice feature to handle this kind of thing out of the box since Graphql often return 200

Unfortunately (or fortunately, I'm not sure) authentication is not part of the GraphQL spec so there's no way to provide a "one-size-fits-all" solution.

**Comment by martinbonnin** [comment]
@damianpetla fix to honor `request.httpHeaders` in websockets is [here](https://github.com/apollographql/apollo-kotlin/pull/6072). If you get a chance to try with the SNAPSHOTs (when they're out in ~30min), it'd be cool to know if it works for your use case. (see also the [integration test](https://github.com/apollographql/apollo-kotlin/blob/66a1be07c7c394b0f55344c918d78bd370e3b1c6/libraries/apollo-runtime/src/commonTest/kotlin/test/network/WebSocketNetworkTransportTest.kt#L462))
