### ISSUE TITLE
Clarify the handling of HTTP status codes and Accept graphql-response+json

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#6079]
### Description

Currently, we return an error response if the status code is `!= 2xx`. I realized recently that the status codes in [the GraphQL over HTTP spec](https://graphql.github.io/graphql-over-http/draft/) are more for proxies and other links in the chain that do not speak GraphQL than for the client.

Investigate under what conditions we can parse the response and return it to the user (always? Or depending on the returned `Content-Type`?)

Also add `graphql-response+json` to the list of accepted content-types.

See https://graphql.github.io/graphql-over-http/draft/#sec-Processing-the-response

**Comment by BoD** [comment]
Done with #6170
