### ISSUE TITLE
iOS error on gradle sync "Could not resolve com.apollographql.apollo:apollo-compiler:4.0.0-rc.1"

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#6102]
### Version

4.0.0-rc.1

### Summary

Trying to convert our existing apollo module to KMP and getting this error in every iOS variant
<img width="704" alt="Screenshot 2024-08-06 at 11 20 24" src="https://github.com/user-attachments/assets/449897be-bb2b-45d5-ac1d-f8e3029b61ad">

tried 4.0.0, same issue.  
Kotlin 1.9.23
AS Koala 2024.1.2 Beta 2

```
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.myapp.base.plugin)
    alias(libs.plugins.apolloKotlin)
}

kotlin {
    jvm()
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain.dependencies {
            api(project(":libs:apollo:api"))
            api(libs.apollo.api)
            api(libs.apollo.runtime)
            api(libs.coroutines)

            implementation(project(":libs:apollo:schema"))
            implementation(project(":libs:logger"))
            implementation(libs.apollo.normalizedcache)
            implementation(libs.apollo.normalizedcache.api)
        }
    }
}

apollo {
    service("service") {
        packageName.set("apollo.impl")
        dependsOn(project(":libs:apollo:schema"))
    }
}
```

Definitely possible that I'm doing something wrong but I can't figure out what

**Comment by martinbonnin** [comment]
The compiler is not multiplatform (yet!), it's JVM only. You can't add it to a multiplatform project.

**Comment by edenman** [comment]
That would do it, thanks for the quick reply! Up to you if you want to leave this open or not

**Comment by martinbonnin** [comment]
I'll close it, KMP is not for any time soon. 
We'd need KMP javapoet and kotlinpoet before we start tackling this.
