### ISSUE TITLE
Is MapTestNetworkTransport inconsistent with error handling in version 4?

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin#6108]
### Question

We have some tests using `MapTestNetworkTransport`, and in some of these tests we are not registering test responses for all called operations. `MapTestNetworkTransport` throws an `IllegalStateException` in this case:
```
error("No response registered for operation ${request.operation}")
```

This was fine for us before migrating to version 4 as we'd fall into our catch statement:
```
} catch (e: ApolloException) {
  // Handle errors
}
```

however in version 4 we have migrated to handling `response.exception`:
```
if (response.exception != null) {
    // Handle errors
}
```
which means we have an uncaught exception.

Instead of throwing an exception when no response is registered, would it make sense for `MapTestNetworkTransport` to return a response with a non-null exception?

**Comment by BoD** [comment]
Hi! Thanks for reporting.

> Instead of throwing an exception when no response is registered, would it make sense for MapTestNetworkTransport to return a response with a non-null exception?

I think here it actually makes sense for it to throw because it's considered a programming mistake when no response can be found. Your test should provide all the expected responses, otherwise I think it's not testing a real scenario that can happen?

**Comment by jvanderwee** [comment]
Thanks @BoD, that's fair! Our use case is end-to-end tests in which previously we didn't need to register responses for all operations. You're right though, we should register all responses for completeness 👍
