### ISSUE TITLE
Using `NetworkMonitor` to monitor offline state

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin#6115]
### Use case

We'd love to use `NetworkMonitor` to monitor network state independently of GraphQL operations. Currently we are able to check the current state of the network and wait for the online state, but we are not able to wait for the offline state.

### Describe the solution you'd like

Would it be possible to add a `Flow<Boolean>` to the API? Or a `waitForOffline` suspending function?

**Comment by jvanderwee** [comment]
Our use case is that we display UI informing the user they are offline ![image](https://github.com/user-attachments/assets/f9b1de7b-601b-4a66-9a95-de7ffa3cc0ea)

**Comment by martinbonnin** [comment]
Yea, I hear you. It's also been requested in the past (see https://github.com/apollographql/apollo-kotlin/issues/4652).

Maybe `NetworkMonitor` is indeed a good place to do this as it's not too deep into `ApolloClient`. I'll dive more into this tomorrow.

**Comment by martinbonnin** [comment]
@jvanderwee this is now in the SNAPSHOTs. Any chance you can try it out before we cut a release?

**Comment by jvanderwee** [comment]
@martinbonnin works great, thank you!

**Comment by martinbonnin** [comment]
Thanks for confirming 💙

**Comment by jvanderwee** [comment]
Hey @martinbonnin, when do you plan on cutting the release?

**Comment by BoD** [comment]
Hey @jvanderwee the current plan was to make a release in early september
