### ISSUE TITLE
Is it possible to generate the query and data classes manually, without the Gradle plugin?

### ISSUE THREAD

**Issue by t3j3x6** [apollographql/apollo-kotlin#6123]
### Question

I would prefer it for the following reasons:

* I'm trying to integrate Apollo to an existing project that uses Maven instead of Gradle.
* I see there's a [third-party Maven plugin](https://github.com/aoudiamoncef/apollo-client-maven-plugin) for code generation, but I have trouble setting it up.
* I don't expect the schema to change and I would prefer to avoid complicating the build by introducing a plugin with a non-trivial configuration.
* The code generation increases the build time, which will be an issue on CI where every build is a clean build. As the schema in my case does not change, there's no upside to do code generation every time.

I can generate the code with the plugin in a separate project and copy the generated files over to my project, but that also seems like an over-complication to me. I would prefer to write the code that uses the Apollo compiler for code generation, commit both the generator and the generated code into the VCS, and then forget about it.

**Comment by BoD** [comment]
Hi! The Apollo Compiler is [published on Maven Central](https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-compiler/4.0.0/) so you can use it in your own project (that is how the 3rd party Maven plugin works). 

However, there is little documentation and guidance on how to use it, as this is an advanced use case. You can see an example on how to invoke it, in our tests, [here](https://github.com/apollographql/apollo-kotlin/blob/ea26b144cae3816b01304d8281fef18546d6a4bd/libraries/apollo-compiler/src/test/kotlin/com/apollographql/apollo/compiler/CodegenTest.kt#L453).

Before you go that route I would advise to persist a little more with the Maven plugin - this is probably the best way to do what you need.

**Comment by t3j3x6** [comment]
Thank you, I will take a look.
