### ISSUE TITLE
Migrating to Apollo 3: Usage of `SubscriptionManager.start/stop`

### ISSUE THREAD

**Issue by mformetal** [apollographql/apollo-kotlin#6153]
While migrating from Apollo 2 to Apollo 3, I can't find a trivial replacement for usage of `ApolloClient::enableSubscriptions/disableSubscriptions`. These APIs called down to `SubscriptionManager.start/stop` - `disable*` seems to have a corollary in:

```
client.subscriptionNetworkTransport.dispose()
```

This seems to close the underlying `Channel` - would I have to recreate the `subscriptionNetworkTransport` as a corollary for `enable*`?

Any clues/suggestions ? 🙏 Would be much appreciated!

**Comment by BoD** [comment]
Hi!

You are right that `dispose()` will stop any connection and the event loop, making the NetworkTransport not re-usable, so after calling that you'll need to instantiate a new one, and to use it you'll also need a new `ApolloClient` (you can call `ApolloClient.newBuilder()` to build upon an existing one).

That is probably the simplest way to do that, but if that's impractical there may be a way to use [`NetworkTransport.closeConnection(YourException)`](https://www.apollographql.com/docs/kotlin/v3/advanced/authentication#updating-your-websocket-token), and then wait for a signal to reconnect in `webSocketReopenWhen`, something like (untested!):

```kotlin
val reconnectSignalChannel = Channel<Unit>(0)

object MyDisconnectException : Exception

val apolloClient = ApolloClient.Builder()
    .(...)
    .webSocketReopenWhen { throwable, attempt ->
        if (throwable is MyDisconnectException) {
            reconnectSignalChannel.receive() // suspends until calling reconnectSignalChannel.offer(Unit)
        }
        true
    }
    .build()
```

**Comment by mformetal** [comment]
> Hi!
> 
> You are right that `dispose()` will stop any connection and the event loop, making the NetworkTransport not re-usable, so after calling that you'll need to instantiate a new one, and to use it you'll also need a new `ApolloClient` (you can call `ApolloClient.newBuilder()` to build upon an existing one).
> 
> That is probably the simplest way to do that, but if that's impractical there may be a way to use [`NetworkTransport.closeConnection(YourException)`](https://www.apollographql.com/docs/kotlin/v3/advanced/authentication#updating-your-websocket-token), and then wait for a signal to reconnect in `webSocketReopenWhen`, something like (untested!):
> 
> ```kotlin
> val reconnectSignalChannel = Channel<Unit>(0)
> 
> object MyDisconnectException : Exception
> 
> val apolloClient = ApolloClient.Builder()
>     .(...)
>     .webSocketReopenWhen { throwable, attempt ->
>         if (throwable is MyDisconnectException) {
>             reconnectSignalChannel.receive() // suspends until calling reconnectSignalChannel.offer(Unit)
>         }
>         true
>     }
>     .build()
> ```

Thanks for this migration path - I'm currently migrating a bunch of old Apollo2 code, I imagine this would break a lot of the wrapper logic we have. Wrote a ticket to investigate. Appreciate you! 

If you don't mind, can you keep this issue open for a minute so I can try and implement your suggestions?

**Comment by BoD** [comment]
Hey @mformetal, anything we can do in this issue, or is it ok to close it?

**Comment by mformetal** [comment]
> Hey @mformetal, anything we can do in this issue, or is it ok to close it?

Sorry for the late reply, tons of things on my plate - going to start work on this migration this week, mind keeping it open if I have any questions? Promise it'll be closed by Friday!

**Comment by martinbonnin** [comment]
Hi @mformetal , hope you're doing better. Let us know if there is anything we can do to help here.

**Comment by mformetal** [comment]
> Hi @mformetal , hope you're doing better. Let us know if there is anything we can do to help here.

So so so sorry! We're all good here, thanks 👍🏿
