### ISSUE TITLE
How can I do CacheMissException Test?

### ISSUE THREAD

**Issue by naoki601** [apollographql/apollo-kotlin#6161]
### Question

**Question**

**Version**
4.0.0

**Summary**
I have a function like below.
How can I test when it.exception is CacheMissException by using JUnit?
I can not find an example from the document.Thank you.

```kotlin
fun <D : Query.Data> watch(
        query: Query<D>,
        fetchPolicy: FetchPolicy,
    ): Flow<ApolloResponse<D>> {
        return apolloClient.query(query)
            .fetchPolicy(fetchPolicy)
            .watch()
            .filter { it.exception !is CacheMissException }
    }
```

**Comment by martinbonnin** [comment]
Hi 👋 

Can you ellaborate on what you're trying to test? If you want to simulate a `CacheMissException`, you can always configure your client with an empty cache, that will create a cache miss. We have a bunch of those in the integration tests. See [here](https://github.com/apollographql/apollo-kotlin/blob/8d37c6119a43a620be175841050913c246ec1139/tests/integration-tests/src/commonTest/kotlin/test/FetchPolicyTest.kt#L222) for an example.

**Comment by naoki601** [comment]
Hi 👋

Thank you for your reply.I want to  simulate a CacheMissException.
> import com.apollographql.mockserver.MockServer

How can I use this MockServer? Is it like below?
implementation("com.apollographql.mockserver:apollo-mockserver:4.0.0")

**Comment by martinbonnin** [comment]
> `implementation("com.apollographql.mockserver:apollo-mockserver:4.0.0")`

We've moved `MockServer` to a separate repo so we can iterate faster on it. You can read more about it [here](https://www.apollographql.com/docs/kotlin/migration/4.0/#moved-artifacts). The documentation is at https://apollographql.github.io/apollo-kotlin-mockserver/getting-started.html

To import it, you'll need

```
implementation("com.apollographql.mockserver:apollo-mockserver:0.0.3")
```
