### ISSUE TITLE
Support for Apollo GraphQL IntelliJ Plugin in K2 mode

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#6163]
### Use case
<img width="400" alt="スクリーンショット 2024-09-26 22 05 32" src="https://github.com/user-attachments/assets/532dde60-60d0-4276-953f-162fce3d806a">

<img width="971" alt="スクリーンショット 2024-09-26 22 07 28" src="https://github.com/user-attachments/assets/877ebf30-7ce0-4947-914e-926afb423cad">

https://plugins.jetbrains.com/plugin/20645-apollo-graphql

**Comment by BoD** [comment]
Thanks for reporting! The work [is done](https://github.com/apollographql/apollo-kotlin/pull/6150) but can't be merged just yet.

**Comment by BoD** [comment]
A version supporting K2 will be available in the [snapshots channel](https://www.apollographql.com/docs/kotlin/testing/android-studio-plugin/#weekly-snapshots) soon.
