### ISSUE TITLE
[v4] Calling toJson on an Operation.Data object throws ClassNotFoundException

### ISSUE THREAD

**Issue by adepto-io** [apollographql/apollo-kotlin#6174]
### Version

4.0.1

### Summary

Calling toJson or toJsonString on an Operation.Data object throws java.lang.ClassNotFoundException: z2.adapter.i0_ResponseAdapter$Data if R8 is enabled.

### Steps to reproduce the behavior

1. Execute a GraphQL query
2. Call toJson on the response's Data object
3. See the java.lang.ClassNotFoundException exception

This only happens when running a release build with R8 enabled

### Logs

```
java.lang.ClassNotFoundException: z2.adapter.i0_ResponseAdapter$Data
  at java.lang.Class.classForName(Native Method)
  at java.lang.Class.forName(Class.java:536)
  at java.lang.Class.forName(Class.java:467)
  at L2.I.d(Unknown Source:91)
  at L2.d.a(Unknown Source:1517)
  at D1.y.a(Unknown Source:111)
  at e9.U.m(Unknown Source:129)
  at e9.k.invokeSuspend(Unknown Source:11)
  at C7.a.resumeWith(Unknown Source:7)
  at b9.I.run(Unknown Source:112)
  at G2.o.run(Unknown Source:378)
  at i9.j.run(Unknown Source:2)
  at i9.a.run(Unknown Source:95)
  Suppressed: g9.g: [CoroutineName(applicationScope), E{Cancelling}@c48ac47, Dispatchers.Default]
```

**Comment by martinbonnin** [comment]
You're right. Although 99% of Apollo Kotlin is reflection-free, there's [a tiny bit of reflection](https://github.com/apollographql/apollo-kotlin/blob/7668a302eb5c62ca1d3e423ccfefa1142acee1f4/libraries/apollo-api/src/jvmMain/kotlin/com/apollographql/apollo/api/-Data.kt#L16) for that use case of serializing the data without an instance of the matching operation.  

You can try keeping the adapters. Something like so (wildly untested):


```
keep class **_ResponseAdapter$Data { *; }
```

Out of curiosity, what's the use case for doing this? `toJsonString()` is still experimental and we might design better APIs depending the use case.

**Comment by adepto-io** [comment]
I've been using the Apollo client since version 2 and developed my own caching solution. It uses room due to a requirement to have fine-grained control over what makes it into the cache. Cached data is also encrypted by a symmetric key from the Android Keystore. I didn't see another way to do this other than using toJson or toJsonString and reflection to dynamically map a Response.Data object to a Room entity. 

Thank you for the suggestion,  I've tried rule but it seems to have no effect because the app still crashes with the same exception.

**Comment by martinbonnin** [comment]
> I didn't see another way to do this other than using toJson or toJsonString and reflection to dynamically map a Response.Data object to a Room entity.

If you know what operation the `data` is from then you can lookup the adapter manually (but if it's a plain `Operation.Data` from possibly different operation, then it's not working).

> I've tried the rule but it seems to have no effect because the app still crashes with the same exception.

AFK right now but will dig a bit more into this tomorrow, there must be a way.

**Comment by martinbonnin** [comment]
This should do it:

```
-keep class ** implements com.apollographql.apollo.api.Operation$Data
-keep class **.*_ResponseAdapter* {
    public static ** INSTANCE;
}
```

I'll add a note to the KDoc

**Comment by martinbonnin** [comment]
> Unfortunately there are many different types of operations that need to be processed.

Gotcha 👍 

> The rule works

Nice 🎉 Thanks for confirming. I'll close this issue for now. We might be able to remove reflection at some point but probably not in the near future.
