### ISSUE TITLE
Does apollo support okhttp3 Authenticator?

### ISSUE THREAD

**Issue by igorwojda** [apollographql/apollo-kotlin#6191]
### Question

Apollo documentation mentions [support of OkHttp interceptors](https://www.apollographql.com/docs/kotlin/advanced/interceptors-http) as a way to easily add an "Authorization" header to HTTP requests. 

I wonder if Apollo also supports [okhttp Authenticator](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Authenticator.html) as a way to refresh auth token and retry the request? (after my initial trials I don't think this is the case but I want to double check)

**Comment by BoD** [comment]
This was answered on Slack - for the record, the issue was that this particular server replied with `200` in case of auth errors, thus OkHttp Authenticator doesn't work. A possible solution is to implement an ApolloInterceptor. Closing for now.

**Comment by martinbonnin** [comment]
> the issue was that this particular server replied with 200 in case of auth errors

FWIW, the "200 ok" days are counted and if a server supports `application/graphql-response+json`, it's now fine to use whatever HTTP status code makes sense. See https://github.com/apollographql/apollo-kotlin/pull/6170 and https://graphql.github.io/graphql-over-http/draft/#sec-Processing-the-response
