### ISSUE TITLE
Including header in cache key

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin#6202]
### Question

👋 we have a case where a query response can change based on the value of a header. is there a way we can include a header value in the cache key?

**Comment by martinbonnin** [comment]
Hi 👋 There's nothing like this at the moment. `CacheKeyGenerator` knows nothing about HTTP headers (which is a good thing in general). If we wanted something like this, we'd need to tunnel `ExecutionContext` all the way to `CacheKeyGenerator` (and `CacheResolver` too). Doable but would require some API changes + a bit more allocations/instructions in the request pipeline. 

May I ask what's the use case is? For relatively static data such as authorization and/or accept-language headers, I usually recommend changing the `ApolloClient` altogether. This is what we do in [Confetti](https://github.com/joreilly/Confetti/blob/504c216bb764ce5828f00aefdcbdd22916a7c11c/shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt#L85) for an example.

**Comment by jvanderwee** [comment]
Hey Martin! Our users are able to switch sub-accounts which updates an account id header. Switching Apollo client sounds like the best bet, thanks for sharing the Confetti example 👍
