### ISSUE TITLE
Use the SPDX URL for the MIT License

### ISSUE THREAD

**Issue by eygraber** [apollographql/apollo-kotlin#6240]
### Description

The current URL (`https://raw.githubusercontent.com/apollographql/apollo-kotlin/main/LICENSE`) doesn't work with [Licensee](https://github.com/cashapp/licensee) without explicitly allowing it, and it would be nice to use a standardized URL.

**Comment by BoD** [comment]
Thanks for reporting this! It appears that removing the URL from the POM and using the standard `MIT` spdx id will make Licesee happy

**Comment by BoD** [comment]
Fixed by #6247
