### ISSUE TITLE
Customizing your WebSocket protocol using GraphQLWsProtocol documentation 

### ISSUE THREAD

**Issue by mzubair-cars-commerce** [apollographql/apollo-kotlin#6253]
### Question

The documentation for [WebSocket protocol using GraphQLWsProtocol](https://www.apollographql.com/docs/kotlin/essentials/subscriptions#customizing-your-websocket-protocol) leads to the following exception:

`Caused by: java.lang.IllegalStateException: Apollo: 'webSocketEngine' has no effect if 'subscriptionNetworkTransport' is set.`

Is there additional documentation or guidance available that explains the correct setup for subscriptions using GraphQLWsProtocol? The exception does not provide clear guidance on how to resolve this issue.

**Comment by martinbonnin** [comment]
Hi 👋  Can you share your `ApolloClient` building code?

**Comment by mzubair-cars-commerce** [comment]
Hey @martinbonnin, here is what im using: 

`  ApolloClient.Builder()
            .serverUrl(environment.graphQL)
            .subscriptionNetworkTransport(
                WebSocketNetworkTransport.Builder()
                    .protocol(GraphQLWsProtocol.Factory())
                    .serverUrl(environment.subscription)
                    .build()
            )
            .okHttpClient(okHttpClient)
            .addInterceptor(SomeInterceptor())
            .build(),`

**Comment by martinbonnin** [comment]
Thanks for sending this 🙏 

The issue comes from `okHttpClient` that calls `webSocketEngine()` under the hood. I agree the error message is not helping, I'll look into this. In the meantime, you'll need to configure your client for both transports like so:

```kotlin
    val client = ApolloClient.Builder()
      .serverUrl(httpUrl)
      .subscriptionNetworkTransport(
        // subscriptions
        WebSocketNetworkTransport.Builder()
          .protocol(GraphQLWsProtocol.Factory())
          .serverUrl(websocketUrl)
          .okHttpClient(okHttpClient)
          .build()
      )
      .networkTransport(
        // queries/mutations
        HttpNetworkTransport.Builder()
          .okHttpClient(okHttpClient)
          .build()
      )
```

**Comment by mzubair-cars-commerce** [comment]
Thanks @martinbonnin that fixed it!
