### ISSUE TITLE
Apollo GraphQL Plugin - Download Schema tool does not work on Android Studio Ladybug

### ISSUE THREAD

**Issue by annaarroyo** [apollographql/apollo-kotlin#6258]
### Version

4.1.0

### Summary

On Android studio versions behind Ladybug, the "Tools -> Apollo -> download schema" task works and properly updates the schema.json file in the project. However, after updating to Android Studio Ladybug, the task successfully runs but nothing changes in the schema.json file. 

Android studio apollo graphql plugin version: 4.1.0
Apollo kotlin version: 3.8.5

**Comment by BoD** [comment]
I couldn't reproduce the issue so far. For a bit of context, this works by executing the `download<your service name>ApolloSchemaFromIntrospection` task from your project. 

Do you have an `introspection {}` block in your service? Can you check if running that task on the command line works?

**Comment by annaarroyo** [comment]
@BoD Correct, it's that task and I do not have any introspection block in my service. Running the task from the command line does say it was successful but it still doesn't update the schema.json file.

**Comment by BoD** [comment]
Thanks for following up! 

Something doesn't add up because that gradle task should only exist when the [introspection block](https://www.apollographql.com/docs/kotlin/advanced/plugin-recipes#downloading-a-schema) is there - otherwise there is no way to know where to download the schema from.

**Comment by annaarroyo** [comment]
@BoD  Apologies, yes there is an introspection block. Looks like this:
```
introspection {
            schemaFile.set(schemaJsonFile)
            endpointUrl.set("<the endpoint url>")
            headers.put("user-agent", "JS GraphQL")
        }
```

**Comment by BoD** [comment]
No worries!

If the Gradle task doesn't do anything - could it simply be that the schema you currently have locally is the same as the remote one, so there are no changes?

Also while we're talking about schemas, we recommend you name your schema `schema.graphqls` instead of `schema.json`: that way it will be written in the SDL format, which is much more readable than json.

**Comment by annaarroyo** [comment]
Hi @BoD Thanks for your help, I think the schema.json file is actually getting updated but it is super delayed for some reason and I didn't wait around to see it actually update (about a min after the task finishes). I assume this might have something to do with a custom formatting task that is run after so I will look into that with my team. Anyways, I'll close this for now and open up another ticket if I run into any more trouble. Thanks and I will definitely look into updating the schema.json to schema.graphqls.

**Comment by BoD** [comment]
Not 100% sure but it may be a case where the IDE doesn't get notified that the file has changed. Anyway thanks for the update, glad it works.
