### ISSUE TITLE
Add support for watchosX64

### ISSUE THREAD

**Issue by jeantuffier** [apollographql/apollo-kotlin#6261]
### Use case

I'm trying to share my logic with a Apple project targeting WatchOS. When adding `watchosX64()` to my project, the build fails because apollo only supports 
```
watchosArm32()
watchosArm64()
watchosSimulatorArm64()
```
I can make xcode build the Watch Os target only if I choose the stand alone emulator and not the one saying "via Iphone".
If I choose it, I get the following error: 
```
No matching variant of com.apollographql.apollo:apollo-runtime:4.0.0 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'watchos_x64', attribute 'org.jetbrains.kotlin.platform.type' with value 'native' but:
```
Are there any limitations to not supporting it? 
If I try to build the ios app target on the iPhone simulator, I get the same error.

### Describe the solution you'd like

Simply add `watchosX64()` to the supported targets

**Comment by BoD** [comment]
Hi! 

For the record, `watchosX64` is for the simulator on Intel Macs.

There is no particular reason why we don't include this target. Would you be interested in opening a pull request? Targets are handled in [this file](https://github.com/apollographql/apollo-kotlin/blob/main/build-logic/src/main/kotlin/Mpp.kt).

**Comment by jeantuffier** [comment]
Hi, that's strange then. I run my project on a MacBook Pro M1. Do you have any ideas why I would get this error?

**Comment by BoD** [comment]
In your initial message you said you explicitly added the `watchosX64` target to your project? If you actually don't need it you may omit it and this should solve the issue.

**Comment by jeantuffier** [comment]
I meant I had the issue if I try tu run my project from xcode on the "watch simulator via iPhone". If I use the stand-alone watch simulator, then it works all fine.

**Comment by BoD** [comment]
Thanks for following up! 

Hmm yes indeed this is surprising, I don't see why XCode is complaining about `x86_64` when you only have Arm64 targets in your project. And you're right that adding the target to Apollo Kotlin may not fix the issue. Are you able to make a simplified version of your project with the Apollo Kotlin dependency removed to compile and run?

**Comment by jeantuffier** [comment]
Turned out xcode has a `$(ARCHS_STANDARD)` property set in Build Settings > Architectures > Architectures. It has different values depending on the target. For the watch target, it has arm64, X86_64 and some others. By replacing the property with a simple "arm64" it all work smoothly.

Thanks for the help and sorry I used your time for something completely unrelated to Apollo!

**Comment by BoD** [comment]
TIL and no worries at all. Glad it works now.
