### ISSUE TITLE
Cache is not updated when child node has updated

### ISSUE THREAD

**Issue by ChlorUpload** [apollographql/apollo-kotlin#6317]
### Question

Hi, I want to ask you a simple dumb question

When I subscribe for a query like this:

```
query LessonViewerComponent_GetLesson($lessonId: ID!) {
    lesson(lessonId: $lessonId) {
        id
        __typename
        acquisition {
            id
            __typename
        }
    }
```

And create acquisition like this:

```
createLessonAcquisition(id: $id) {
        lesson {
            id
            __typename
            acquisition {
                id
                __typename
            }
        }
    }
```

The query result gets updated. However if I create acquisition like this:
```
createLessonAcquisition(id: $id) {
        lesson {
            id
            __typename
        }
        acquisition {
                id
                __typename
            }
    }
```
I expect that a new lesson with acquisition will be delivered to the query subscription since the acquisition id is the same with the acquisition inside the lesson. But, it doesn't.

My `extra.graphqls`:

```
extend type Lesson @typePolicy(keyFields: "id")
extend type LessonAcquisition @typePolicy(keyFields: "id")
```

What's wrong with my approach?

**Comment by martinbonnin** [comment]
The watchers are only notified if the contents changed. In your case, it's most likely that `id` and`__typename` are staying the same.

**Comment by martinbonnin** [comment]
@ChlorUpload anything else we can help with here?

**Comment by ChlorUpload** [comment]
Thank you. This was just my misunderstanding 🥲

**Comment by martinbonnin** [comment]
@ChlorUpload no worries at all, this is what issues are for :)
