### ISSUE TITLE
Infer keyFields for schema following Global Object Identification standard

### ISSUE THREAD

**Issue by x-sheep** [apollographql/apollo-kotlin#6318]
### Use case

The GraphQL site describes a best practice for uniquely identifying objects: https://graphql.org/learn/global-object-identification/

Specifically, all objects with an identifier that's unique across that GraphQL service should implement the following interface:

```graphql
# An object with a Globally Unique ID
interface Node {
  # The ID of the object.
  id: ID!
}
```

This is also part of the larger Relay Specification. This interface can be found in the GraphQL schema for GitHub, GitLab, WPGraphQL (WordPress plugin), and probably more.

### Describe the solution you'd like

If a schema has an interface that meets these requirements:

1. The name is `Node`
2. It has a non-nullable field called `id` of the `ID` scalar type
3. There are no other fields
4. It doesn't have a typePolicy directive yet

Apollo should be able to infer that the interface has the `@typePolicy(keyFIelds: "id")` directive. This would allow for smarter caching without needing users to extend a given schema with a directive.

**Comment by BoD** [comment]
Hi! Thanks for pointing to that page. 

While it is a common practice, the `Node` interface is not reserved in the GraphQL spec, and given that adding `@typePolicy` to the interface is fairly simple, we wouldn't be too keen on giving it a special treatment.

**Comment by x-sheep** [comment]
If no special behavior is to be added, it might be a good idea to describe it specifically in this article:

https://www.apollographql.com/docs/kotlin/caching/declarative-ids

It currently only mentions that types can be annotated one by one, but interfaces aren't mentioned. The `Node` interface seems like a good example to use.

**Comment by BoD** [comment]
Good idea! I've opened a PR to do that [here](https://github.com/apollographql/apollo-kotlin/pull/6319).

**Comment by BoD** [comment]
Doc updated in #6319
