### ISSUE TITLE
Create Android Studio Plugin

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-kotlin#650]
It would be nice to have syntax highlighting and query validation against a schema driven by an Intellij Plugin.  Any other requests?

**Comment by martinbonnin** [comment]
It would be pretty cool if 'refactoring'/'find usages' could work to change the name of the queries when needed/locate places where a given query is used.

**Comment by martijnwalraven** [comment]
Note that we have an existing [IntelliJ plugin](https://github.com/apollographql/intellij-graphql) that could use some love. Hyo (creator of GraphiQL) has an internal version that integrates the plugin with the [GraphQL Language Service](https://github.com/graphql/graphql-language-service) (see [this issue](https://github.com/apollographql/intellij-graphql/issues/2)). We've been having some trouble getting Facebook legal to accept the CLA, so I'll check to see if that has been resolved and ping Hyo so he can merge it.

**Comment by digitalbuddha** [comment]
Is the cla easier now with new licensing? @martijnwalraven

**Comment by martinbonnin** [comment]
I'd love it if somehow intellij could somehow "watch" the .graphql files and rebuild the classes whenever one of them changes. I believe DataBinding does something like this. I'm not sure if the functionality is accessible to other plugins.

**Comment by k-misztal** [comment]
Any update on AS plugin?

**Comment by jpvajda** [comment]
Hello everyone! The Apollo Kotlin Client team is starting to consider a project to build an Android Studio plugin for our Kotlin Client.  I wanted to re-engage the community on this thread to see if anyone had any ideas we can consider. Thank you!

**Comment by digitalbuddha** [comment]
Ha congrats! I am amazed what this project has become ♥️

**Comment by BoD** [comment]
Closing this now as the plugin (preview) [is available](https://www.apollographql.com/blog/mobile/kotlin/announcing-the-apollo-kotlin-plugin-for-android-studio-and-intellij-idea/). Please don't hesitate to open new issues for bugs or improvements!
